### ISSUE TITLE
图表的双重标题

### ISSUE THREAD

**Issue by zhibo-work** [tuna/thuthesis#26]
您好，我是大连海事大学的博士生，想把您的模板port成我们学校的模板。不知道可不可以，这里想征得您的允许。

如果您许可的话，我想问下一个问题。
因为看过模板之后，发现我们学校的要求和清华的非常相似，只是要求图表要有中英文标题，ccaption宏包可以解决，我想替换掉模板中原有的caption宏包，但是发现好像subfig等宏包和caption宏包直接有些关系，不知道直接替换可以吗？

非常感谢！

**Comment by sxdxyxy** [comment]
@zhibo-work Caption 包里面有 bicaption 命令，很好用的，你只需要如此设置（我用的是emacs org `,纯粹的latex你指需要删掉每行的#+latex_header: 就可以了）：
` #+latex_header: \usepackage{bicaption}
 #+latex_header: \captionsetup[figure][bi-second]{name=Fig.} 
 #+latex_header: \captionsetup[table][bi-second]{name=Tab.}
`
然后使用：
`\bicaption{中文标题}{英文标题}`
则会出现如下结果：
![image](https://user-images.githubusercontent.com/13362677/76512682-18102180-6490-11ea-8da2-e0609fa70272.png)
