### ISSUE TITLE
公式编号的括号是否应为中文括号？

### ISSUE THREAD

**Issue by liptonfred** [tuna/thuthesis#287]
研究生院网站提供的示例文件中编号是中文括号，如图。模板生成的pdf括号则是英文括号，是否可以考虑修改和示例相同呢？
![image](https://user-images.githubusercontent.com/20373498/34553528-ed238fb8-f162-11e7-94e6-5be5b0d399b8.png)

**Comment by zepinglee** [comment]
中午括号……我觉得这个可以忽略

**Comment by rrenjie** [comment]
我也发现了这个问题，不知道有没有办法修改

**Comment by xueruini** [comment]
修改 `\thu@maketag` 和 `\tagform@`。这个觉得没啥必要

**Comment by yaox12** [comment]
@zepinglee 既然为了和word版保持一致都改了那么多细节，这个要不要一起改了。这一波计算机系交博士论文，我们几个同学都手动改了，我觉得不如模板处理一下。

**Comment by zepinglee** [comment]
我去找研究生院的老师确认下。

**Comment by zepinglee** [comment]
确认了，改为中文括号。

**Comment by tianboh** [comment]
> 修改 `\thu@maketag` 和 `\tagform@`。这个觉得没啥必要

请问这两个指令在哪里改呀...

**Comment by xueruini** [comment]
> 确认了，改为中文括号。

是不是太难看了

**Comment by renjiefly** [comment]
本人最后毕业论文用的英文括号，正常毕业..

**Comment by Eric801** [comment]
> > 修改 `\thu@maketag` 和 `\tagform@`。这个觉得没啥必要
> 
> 请问这两个指令在哪里改呀...

同问如何修改为中文括号

**Comment by zepinglee** [comment]
我也觉得中文括号挺丑的，但是既然研究生院确认了就目前先改成这样吧。可以向研究生院反馈意见。

**Comment by anamewing** [comment]
是否可以添加一个选项来选择使用中文或英文括号？感觉中文括号是有点丑。

**Comment by zepinglee** [comment]
> 是否可以添加一个选项来选择使用中文或英文括号？感觉中文括号是有点丑。

有什么建议的选项名称？

**Comment by Harry-Chen** [comment]
> > 是否可以添加一个选项来选择使用中文或英文括号？感觉中文括号是有点丑。
> 
> 有什么建议的选项名称？

或许 `equ-paran-style = half / full` ?
