### ISSUE TITLE
支持Algorithm环境

### ISSUE THREAD

**Issue by netheril96** [tuna/thuthesis#325]
计算机相关的学位论文经常需要在文章中插入伪代码。我看到很多人现在用的是`algorithm2e`这个包。这个包和`thuthesis`没有冲突，但是其格式不是很一致。例如`thuthesis`中图表的标题都是“图1.1”“表2.3”这样，但是这些伪代码的标题是"Algorithm 1", "Algorithm 2"。如果`thuthesis`能内置伪代码的支持，并且统一格式（“算法1.3“，”算法2.4”等等）就最好了。

**Comment by zepinglee** [comment]
```
  \renewcommand{\listalgorithmcfname}{算法索引}
  \renewcommand{\algorithmcfname}{算法}
```

这两行翻译可以加到 thuthesis 里，但是我不建议把 algorithm2e 加进去，因为实现算法伪代码的包很多，如果默认加载了 algorithm2e 别人用其他包就会导致冲突。

**Comment by xueruini** [comment]
赞同 @zepinglee 的观点，算法包有点多，写 paper 各有偏好，固定一个反而不友好。各个包都提供修改 float name 的指令，是正解

**Comment by netheril96** [comment]
那个编号怎么改呢？从1改成1.1？

这个问题和thuthesis本身无关，但是我觉得你们最了解这个问题的答案了。

**Comment by xueruini** [comment]
本质上就是修改 algorithm counter 的 reset trigger 和 show style

- https://tex.stackexchange.com/questions/124902/algorithm-with-chapter-number
- https://tex.stackexchange.com/questions/65993/algorithm-numbering/66001
- https://tex.stackexchange.com/questions/110412/numbering-in-algorithmicx

**Comment by netheril96** [comment]
搞定👌

**Comment by Diyorazh** [comment]
> ```
>   \renewcommand{\listalgorithmcfname}{算法索引}
>   \renewcommand{\algorithmcfname}{算法}
> ```
> 
> 
> 这两行翻译可以加到 thuthesis 里，但是我不建议把 algorithm2e 加进去，因为实现算法伪代码的包很多，如果默认加载了 algorithm2e 别人用其他包就会导致冲突。

管理员大大们，请问这个加到哪里呀？我加到texsetup里面就悲剧了。我用的是overleaf直接引入的版本，伪代码包是
``\usepackage{algorithm} 
\usepackage{algpseudocode}``

**Comment by zepinglee** [comment]
> 管理员大大们，请问这个加到哪里呀？我加到texsetup里面就悲剧了。我用的是overleaf直接引入的版本，伪代码包是
> 
> `\usepackage{algorithm}  \usepackage{algpseudocode}`

这个还是在模板里处理一下

**Comment by Diyorazh** [comment]
我搞定了，代码如下：
``\usepackage{algorithm}
\usepackage{algorithmicx}
\usepackage{algpseudocode}
% \renewcommand{\listalgorithmcfname}{算法索引}
% \renewcommand{\algorithm}{算法}

\floatname{algorithm}{算法}
\renewcommand{\algorithmicrequire}{\textbf{输入:}}
\renewcommand{\algorithmicensure}{\textbf{输出:}}``

用`floatname`改的～

**Comment by zepinglee** [comment]
我待会改一下，这样用户只需要 `\usepackage` 就行了，不需要额外配置。当然写在 `thusetup.tex` 里的会覆盖默认配置。

**Comment by Harry-Chen** [comment]
FYI，这里有一些处理

https://github.com/xueruini/thuthesis/blob/1deac520e428199e02a35f8045cc41996fe38e20/thuthesis.dtx#L3915-L3926

**Comment by zepinglee** [comment]
我也同意不改 `REQUIRE` 和 `ENSURE`，但是还有别的问题：

1. 算法的 caption label 默认是粗体，最好改成跟图、表一致的 regular 字重，以及 11 pt 的字号。
2. `listofalgorithms` 需要修改以兼容 `titletoc`。
3. 宏包 `algorithm2e` 也需要配置下，还是由不少人用的。

**Comment by zepinglee** [comment]
e1bb0f8 和 0a88415 进行了一些额外的配置。

但是 `algorithm` 的 caption 格式是基于 `float` 宏包的，试图修改未能成功，暂时先这样吧。

**Comment by zepinglee** [comment]
> 请问一下我怎么在我自己的里面改一下呢？因为我已经personalize了之前从overleaf上引进的模板，论文也写了几十页了…… 谢谢！

这部分我也没改成功
