### ISSUE TITLE
外文系英语专业本科生论文

### ISSUE THREAD

**Issue by zepinglee** [tuna/thuthesis#435]
[英语专业论文写作指南.pdf](https://github.com/xueruini/thuthesis/files/2897740/default.pdf)
[sample_APA.docx](https://github.com/xueruini/thuthesis/files/2897741/sample_APA.docx)
[sample_MLA.docx](https://github.com/xueruini/thuthesis/files/2897742/sample_MLA.docx)

_Originally posted by @xavieryao in https://github.com/xueruini/thuthesis/issues/370#issuecomment-466751531_

**Comment by zepinglee** [comment]
感觉这个需求比较少，估计也只有 xavieryao 这样的修双学位的大神需要了，记录一下慢慢实现。

**Comment by xavieryao** [comment]
在实现完之前 其他人可以先用我的版本😂 https://github.com/xavieryao/thu-ell-bachelor-thesis

**Comment by zepinglee** [comment]
本科生外文专业要求参考文献：

> 文学和翻译学方向的论文使用 MLA 格式……语言学方向的论文使用 APA 格式

APA 格式的实现有 `apacite` 和 `biblatex-apa`，前者可以兼容 `natbib`，后者需要 `biblatex`。

MLA 格式只有 `biblatex-mla`，没有靠谱的 `natbib` 实现。

**Comment by zepinglee** [comment]
感觉可能 `thuthesis` 只能转换 `biblatex` 才能完美处理这个，以及本科生“外文资料的调研阅读报告”的独立参考文献。

**Comment by xueruini** [comment]
> 感觉可能 `thuthesis` 只能转换 `biblatex` 才能完美处理这个，以及本科生“外文资料的调研阅读报告”的独立参考文献。

是的，早就想试一下 `biber` 了

**Comment by zepinglee** [comment]
我提交了个初步的实验分支 https://github.com/xueruini/thuthesis/tree/biblatex

**Comment by xueruini** [comment]
那些 bst 有对应的 style 么

**Comment by zepinglee** [comment]
> 那些 bst 有对应的 style 么

啥意思？之前已经总结了一下 https://github.com/xueruini/thuthesis/issues/435#issuecomment-583748989

**Comment by xueruini** [comment]
参考文献列表格式的控制

**Comment by zepinglee** [comment]
> 参考文献列表格式的控制

我还是没太懂你在说啥……

APA 有 `apacite` 提供的 bst，但是需要魔改；

MLA 没有 bst，除非我自己写一个。

**Comment by zepinglee** [comment]
> 参考文献列表格式的控制

`biblatex` 不是用 bst 控制参考文献表格式的

**Comment by xueruini** [comment]
> `biblatex` 不是用 bst 控制参考文献表格式的

知道 bst 不能用。我的问题就是：得用 biblatex 调出来跟 bst 一样的效果，这个工作有现成的？我理解 bst 都是定制出来，这个恐怕是没有

**Comment by zepinglee** [comment]
现在的 bst 是在 https://github.com/CTeX-org/gbt7714-bibtex-style 基础上改的；现在 biblatex  用的是 https://github.com/hushidong/biblatex-gb7714-2015 ，也需要进行一定的改动，但应该不是很大工作量。

**Comment by zepinglee** [comment]
至 0eba564 已经基本完成啦。
