### ISSUE TITLE
replace gulp with l3build

### ISSUE THREAD

**Issue by xueruini** [tuna/thuthesis#444]

**Comment by zepinglee** [comment]
> `l3build ctan` 一直过不了，我想把 gulp 干掉

我之前写 `build.lua` 的时候没考虑发布的事，这个我来搞吧

**Comment by zepinglee** [comment]
我改了半天感觉 `l3build` 发布时太不够灵活了，主要是原来 `gulp` 生成的 `zip` 里有 `main.pdf` 和 `spine.pdf`，然而这俩算是 `demofiles` 但是需要单独编译。所以比较麻烦。

@xueruini 话说你看上 `l3build` 啥优点了；我感觉 `gulp` 挺方便的呀

**Comment by xueruini** [comment]
> @xueruini 话说你看上 `l3build` 啥优点了；我感觉 `gulp` 挺方便的呀

到没有必然的好坏，只是觉得少个依赖简单一点。node 也只有发布的时候用一下，没什么大问题。

**Comment by zepinglee** [comment]
在 5831775 中已经解决，`l3build` 的大致用法是：

1. 编译文档 `thuthesis.pdf` 和示例 `main.pdf`, `spine.pdf`；
```
l3build doc
```

1. 更新 `thuthesis.dtx` 和 `CHANGELOG.md` 的版本号和日期；
```
l3build tag 6.2.0
```

1. 生成 zip 压缩包（用来提交 CTAN）
```
l3build tag 6.2.0
```
这个有点坑的是，每次都会执行一遍 `l3build check` 和 `l3build doc`，所以比较耗时间。

**Comment by zepinglee** [comment]
00d042a 中设置 zip 压缩包再带个 TDS 结构的压缩包。

尽管 CTAN 不推荐结构简单的包提交时带 `.tds.zip`（https://ctan.org/file/help/ctan/CTAN-upload-addendum ），但是目前的 `thuthesis` 结构中 `tsinghua.pdf` 放在了 `doc` 分支下，这样用户安装 texlive 时如果设置不带文档（`tlpdbopt_install_docfiles 0`），编译封面时就可能缺失这个校名的图片。所以带 `.tds.zip` 可以避免这个问题。

**Comment by zepinglee** [comment]
67c6b09 中加了 `build-ctan.lua`，这样可以用 `l3build ctan --config build-ctan` 跳过 `l3build check` 的过程，这样的话是不是可以移除 `gulp` 那套东西了？

**Comment by Harry-Chen** [comment]
> [67c6b09](https://github.com/tuna/thuthesis/commit/67c6b09906ed64feb4d6730f246d59a4eac6f256) 中加了 `build-ctan.lua`，这样可以用 `l3build ctan --config build-ctan` 跳过 `l3build check` 的过程，这样的话是不是可以移除 `gulp` 那套东西了？

我觉得可以，毕竟有个 JS 在里面感觉有些神奇

**Comment by Harry-Chen** [comment]
> [67c6b09](https://github.com/tuna/thuthesis/commit/67c6b09906ed64feb4d6730f246d59a4eac6f256) 中加了 `build-ctan.lua`，这样可以用 `l3build ctan --config build-ctan` 跳过 `l3build check` 的过程，这样的话是不是可以移除 `gulp` 那套东西了？

但是目前有一个问题，不太方便同时生成用于 GitHub 发布的 zip 包了。确实可以再弄一个 `build-github.lua` 关掉 `packtdszip`，但是这样每次 `build` 都要跑好久（还是强制编译的锅）

**Comment by Harry-Chen** [comment]
我目前的想法是双管齐下，用 `l3build ctan` 打包一个带 `tds.zip` 的提交到 CTAN 的文件，用 `gulp` 打包另一个不带的文件，`make` 的时候依次调用。

**Comment by Harry-Chen** [comment]
> 我目前的想法是双管齐下，用 `l3build ctan` 打包一个带 `tds.zip` 的提交到 CTAN 的文件，用 `gulp` 打包另一个不带的文件，`make` 的时候依次调用。

在 427cbe925099759ed284e6d69b991241b180ac88 中实现了这个，可以看一下？

**Comment by zepinglee** [comment]
还有 GitHub 的 release，好麻烦……应该可以把 `l3build ctan --config build-ctan` 中编译文档的过程也跳过，我先试下。

（其实把 `.dtx` 拆成 `.cls` 和 `-doc.tex` 就没这些事了
