### ISSUE TITLE
外文文献翻译附录，有多篇翻译文献，请问如何每篇文献分别插入目录呢？

### ISSUE THREAD

**Issue by Leojc** [tuna/thuthesis#541]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2020
模板版本：dev
模板类型： bachelor

## 描述问题
外文文献翻译附录，有多篇翻译文献，请问如何分别插入目录呢？现在只要使用\tableofcontents，就会把多篇文献的目录全放在一起显示。可不可以实现每篇文章的目录分开呢？

**Comment by xueruini** [comment]
Dev支持了

**Comment by Harry-Chen** [comment]
> Dev支持了

dev 分支支持的是一个总的目录吧，还不是单独的目录

**Comment by zepinglee** [comment]
目前模板关于目录的部分是使用 `titletoc` 宏包的功能设置的，其中附录的独立目录用了 `titletoc` 的 Partial TOC’s 功能，参考其文档 6.3 节的内容。

如果每篇翻译文献有独立的目录，每个 section 都有独立目录。我个人不太推荐这样的样式，因为显得太杂乱了，所以暂时不统一改样式，你需要自行设置一下。

1. 在附录的每个 `\section` 后使用 `\startcontents[sections]`，最后的附录 A 结束时 `\stopcontents[sections]`；

2. 生成目录的命令使用 
```tex
\subsection*{\contentsname}
\printcontents[sections]{l}{2}[3]{}
```

3. 目录的格式还需要调整，参考
https://github.com/xueruini/thuthesis/blob/a55da62c2ab740191d62af889c90943d699acee1/thuthesis.dtx#L3575-L3582
主要是缩进的长度减少 `1\ccwd`。

**Comment by zepinglee** [comment]
> > Dev支持了
> 
> dev 分支支持的是一个总的目录吧，还不是单独的目录

蛤蜊橙有啥建议？

**Comment by Harry-Chen** [comment]
> > > Dev支持了
> > 
> > 
> > dev 分支支持的是一个总的目录吧，还不是单独的目录
> 
> 蛤蜊橙有啥建议？

我没有什么想法，每篇都有目录的话这翻译是得写了多长啊。。

是不是也可以开几个 translation 环境来做这个事情？

**Comment by Leojc** [comment]
我就是有点强迫症而已哈哈，也不是什么大问题。感觉分开挺麻烦的样子，那就算啦，谢谢各位~

**Comment by Leojc** [comment]
@zepinglee 好厉害，谢谢你

**Comment by zepinglee** [comment]
> 是不是也可以开几个 translation 环境来做这个事情？

每个 translation 是都是 chapter，所以编号是“附录 A”、“附录 B”、“附录 C”，而学校的要求是：

> 附录 A:为外文资料的调研阅读报告或书面翻译。附录 B:有些不宜放在正文中，但有参考价值的内容，如公式的推演、编写的算法 语言程序设计、图纸、数据表格等。

似乎不太符合要求。
