### ISSUE TITLE
关于 openright

### ISSUE THREAD

**Issue by zepinglee** [tuna/thuthesis#545]
由 @Harry-Chen 提出。

研究生《写作指南》要求：
> “中文封面”、“英文封面”、“关于学位论文使用授权的声明”三部分单面印刷，不加页码。从“中文摘要”开始各部分双面印刷，各部分之间不必留空白页。

本科生《写作指南》要求论文采用双面印刷，授权说明、中英文摘要、致谢、声明要单设一页。

这里的“单设一页”比较令人困惑，是指简单地 `\clearpage`，还是这部分要单面印刷（前后 `\cleardoublepage`）？有人反映打印店会在 PDF 添加空白页来进行调整。但是本科生的奇偶页左右边距是不一样的（也就是装订线 0.2 cm，在旧版的模板中似乎没有正确设置），手动插入空白页可能打乱奇偶页的边距。所以这个问题必须在 LaTeX 模板中解决。

另外，本科生和研究生的格式都存在这个问题，论文正文的起始页（`\mainmatter` 处）可能位于左侧，这样奇数页码位于左侧，偶数页码位于右侧，与传统的排版习惯不太符；

最好能够征求一下审查老师的意见，以及打印店实际处理的方案。

**Comment by zepinglee** [comment]
另：85bca68 中已经可以在 `\documentclass[]` 中使用 `openright` 设置全局右开。

**Comment by Harry-Chen** [comment]
我询问了一下大约六七个之前已经毕业的同学，来自不同系。大家印刷的时候都是把单设一页理解成“一张纸”的。基本上就是全局 openright，但是整个正文内部是连续的。当然图索引表索引之类的是否需要单面印刷也有不同的做法，但是这部分似乎审查老师并没有什么意见。

**Comment by zepinglee** [comment]
你说的“全局 openright”是指`\copyrightpage` 前、`\fontmatter` 处、`\mainmatter` 处进行 `\cleardoublepage`，其余按照默认的 `openany` 进行 `\clearpage`？图标索引我觉得没必要 openright，暂时不改吧。

另外我打算往研究生的 `\mainmatter` 处加 `\cleardoublepage`？

**Comment by zepinglee** [comment]
> 还有一些，比如目录和符号表之间

OK

**Comment by Harry-Chen** [comment]
> > 还有一些，比如目录和符号表之间
> 
> OK

想了想，最后的声明、致谢之类的也都是独立一页的。

其实我个人的做法是，打开 `openright` 选项，然后手工在 frontmatter 的每个 chapter 后面只做 `\clearpage`。

**Comment by Harry-Chen** [comment]
> > 其实我个人的做法是，打开 `openright` 选项，然后手工在 frontmatter 的每个 chapter 后面只做 `\clearpage`。
> 
> 啥？感觉会有问题吧？开了 `openright` 后，每个 `\chapter` 的开始前都会 `\cleardoublepage`，你在 chapter 后面 `\clearpage` 也会被下个 `\chapter` 的`\cleardoublepage` 给覆盖了。
> 
> 不过等 v6.1 就可以删掉这些了。

是的，做了一些非常 hacky 的事情把它们干掉了，相当于我自己控制了正文部分的这些行为

**Comment by xueruini** [comment]
> 是的，做了一些非常 hacky 的事情把它们干掉了，相当于我自己控制了正文部分的这些行为

感觉默认 `openany`，需要单独一页的部分加入 `\cleardoublepge` 更好理解

**Comment by zepinglee** [comment]
> 是的，做了一些非常 hacky 的事情把它们干掉了，相当于我自己控制了正文部分的这些行为

试下 3245f0f 的格式？
