### ISSUE TITLE
声明页的格式和 word 版不一致

### ISSUE THREAD

**Issue by zepinglee** [tuna/thuthesis#546]
由 Yichuan Gao 提出：

> thuthesis 的声明页似乎和 word 版不一致，声明页签名行与前文间只有20磅宽度的空行，`\vskip 2cm` 有点多了。

> 我们系格式审查也给了奇怪的建议

**Comment by Harry-Chen** [comment]
以及封面的“清华大学”，目前带的 `tsinghua.pdf` 是华文隶书，和 Windows 自带的隶书也有一点区别。冬小麦的文章里用的是后者，需要更新一下吗？

**Comment by zepinglee** [comment]
> 以及封面的“清华大学”，目前带的 `tsinghua.pdf` 是华文隶书，和 Windows 自带的隶书也有一点区别。冬小麦的文章里用的是后者，需要更新一下吗？

那还是改一下吧
