### ISSUE TITLE
关键词中不可以输入\LaTeX

### ISSUE THREAD

**Issue by thu-jw** [tuna/thuthesis#547]
## 编译环境
编译的系统：macOS 10.14 / Overleaf
TeX 发行版：TeX Live 2019 
模板版本：v5.5.2
模板类型：bachelor

## 描述问题

关键词中不可以输入 \LaTeX，编译后报错：

截图：
<img width="557" alt="image" src="https://user-images.githubusercontent.com/26575932/83240253-b6786d00-a1cb-11ea-8a62-e1df06ed14e8.png">

复现上述问题的代码：
```TeX
\documentclass{thuthesis}
\begin{document}
\begin{abstract}
\thusetup{
    keywords = {\LaTeX},
}
\end{abstract}
\end{document}
```

**Comment by thu-jw** [comment]
kvsetkeys 不支持将 \LaTeX 作为 key，可以将下面的代码

https://github.com/tuna/thuthesis/blob/a86b0824da527268645571cc5fe3096d65a665b3/thuthesis.dtx#L2937-L2948

改成

```LaTeX
\ExplSyntaxOn
\NewDocumentCommand{\thu@clist@use}{mm}
{
    \def\thu@@tmp{}%
    \clist_map_inline:nn {#1}{
        \ifx\thu@@tmp\@empty
            \def\thu@@tmp{#2}
        \else
            #2
        \fi
        ##1%
    }
}
\ExplSyntaxOff
```

**Comment by zepinglee** [comment]
3192ba2 和 97d055b 已经修复了这个问题，你可以试下 `dev` 版。

另外目前不打算入 LaTeX3 的坑。

**Comment by zepinglee** [comment]
另外这里 `\thu@clist@use` 本身就是模仿 `\clist_use:Nn` 的，可以直接
```tex
\ExplSyntaxOn
\let\thu@clist@use\clist_use:Nn
\ExplSyntaxOff
```

**Comment by thu-jw** [comment]
好的，谢谢
