### ISSUE TITLE
更新 repo 信息

### ISSUE THREAD

**Issue by Harry-Chen** [tuna/thuthesis#548]
RT，repo 发生迁移以后，有一些需要更新的：

* [x] dtx 文件里面的所有 `xueruini/thuthesis`
* [x] 文档和 metadata 中的 maintainer 信息由个人更改为清华大学 TUNA 协会（ @xueruini 的建议）
* [x] （接上条）在文档中加入项目的历史维护者信息
* [x] ctan links 更新
* [x] bump 版本号到 6.1.0

**Comment by jiegec** [comment]
push

**Comment by Harry-Chen** [comment]
d0240fb818b404c444ae5fe9af38b83d0aaef132 完成了大部分工作，等最后的一些修改就可以发版了

**Comment by Harry-Chen** [comment]
v6.1.0 已经发布了， @xueruini 求发布到 CTAN 然后更新一下相应信息

**Comment by xueruini** [comment]
应该都可以直接上传吧
make dist version=6. 1. 0 会生成打包zip

**Comment by Harry-Chen** [comment]
已经提交到 CTAN 了

**Comment by Harry-Chen** [comment]
CTAN 已经上架了
