### ISSUE TITLE
将书脊跟封面编译到一起

### ISSUE THREAD

**Issue by zepinglee** [tuna/thuthesis#551]
由 Yichuan Gao 在 tg 群反映，有的所秘要求把书脊插进论文里（本科生），也就是取代封面后的空白页。

研究生的话，在官网给出的 Word 版示例中，中文封面后都带有书脊页，也可以认为有这个需求。

我考虑到以下接口方案：
1. `\maketitle` 后使用 `\spine` 生成单独的书脊页；但是研究生的 `\maketitle` 会同时生成中英文封面，如果要将书脊插入到之间，就得把中英文封面拆分为两个命令，比如 `\maketitle`, `\maketitle*`（breaking change）；
2. 使用 `\thusetup{spine-in-title-page = true/false}` 控制 `\maketitle` 中是否含书脊。

**Comment by Harry-Chen** [comment]
我觉得目前的方案 2 可以，不过建议在示例的 `thusetup.tex` 里面加入这个选项（比如默认打开），不然大家一定找不到…

**Comment by zepinglee** [comment]
见 https://github.com/CTeX-org/forum/issues/127，应该是 Fandol 的问题。

**Comment by Harry-Chen** [comment]
> 见 [https://github.com/CTeX-org/forum/issues/127，应该是](https://github.com/CTeX-org/forum/issues/127%EF%BC%8C%E5%BA%94%E8%AF%A5%E6%98%AF) Fandol 的问题。

@qinglee 说可以 `\write18` 出去独立生成，我觉得也是一个办法

**Comment by zepinglee** [comment]
`spine-in-title-page` 有点太长，改成 `include-spine` 吧

**Comment by Harry-Chen** [comment]
目前的实现里面，在 fandol / noto 的配置下一定需要 `spine.tex` 存在，并且如果 PDF 存在就不重新编译，可能导致一些问题（比如修改了作者等配置之后，除非手工删掉 `spine.pdf` 否则不会更新）。

考虑是否在默认情况下不提供 `spine.tex`，而是由 `thuthesis` 每次生成并编译，但这也会引入一些额外的 overhead。或者产生编译警告，并在文档里进一步说明这个行为？

**Comment by zepinglee** [comment]
https://github.com/CTeX-org/forum/issues/127#issuecomment-1279715802 这里说 TeX Live 2022 已经修复了横排汉字旋转 90 度问题。我在 {mac, overleaf} * {fandol, noto} 均无法复现这个问题（将下面的 `\thu@input@spine` 改为 `\spine`）。

https://github.com/tuna/thuthesis/blob/e54a4ba852eaddfa711fb128c5a6d7db330fa860/thuthesis.dtx#L7086-L7096

似乎可以去掉 `\includepdf[pages=1]{spine.pdf}` 插入 PDF？

**Comment by Harry-Chen** [comment]
> [CTeX-org/forum#127 (comment)](https://github.com/CTeX-org/forum/issues/127#issuecomment-1279715802) 这里说 TeX Live 2022 已经修复了横排汉字旋转 90 度问题。我在 {mac, overleaf} * {fandol, noto} 均无法复现这个问题（将下面的 `\thu@input@spine` 改为 `\spine`）。
> 
> https://github.com/tuna/thuthesis/blob/e54a4ba852eaddfa711fb128c5a6d7db330fa860/thuthesis.dtx#L7086-L7096
> 
> 似乎可以去掉 `\includepdf[pages=1]{spine.pdf}` 插入 PDF？

我测试了一下也好用的，那就把 `input@spine` 都直接去掉吧
