### ISSUE TITLE
封面，授权，中英摘要之间有空白页，如何去除呢？

### ISSUE THREAD

**Issue by Leojc** [tuna/thuthesis#553]
## 编译环境
编译的系统：Windows 10 
TeX 发行版：TeX Live 2020
模板版本：v6.1.0
模板类型：bachelor

## 描述问题
封面，授权，中英摘要之间有空白页，这应该是openright的效果吧，请问如何去除？因为学校审核要求去掉全部空白页。我尝试着使用openany选项，无效。

学校的审核意见如下：
![批注 2020-06-10 201934](https://user-images.githubusercontent.com/33376945/84266926-dc9cf600-ab57-11ea-948e-40baf18782c4.png)

BTW：这里是上传电子版论文时的审核意见，不是印刷版，印刷版可能又要openright？不知道。

**Comment by Leojc** [comment]
@zepinglee @Harry-Chen 
联系上了电子版论文审核老师，我问了三个问题：
1.	之后要交的纸质版论文在格式上与上传的电子版有无区别？
2.	《本科生综合论文训练论文写作指南》中要求的授权、摘要等"单设一页"是一面还是一张纸？
3.	正文中每一章的开头是否需要控制在奇数页（即，若上一章在奇数页结束，则插入一个空白页以使得本章在奇数页开始）？

得到的答复为：
1 纸质版论文系里把关， 
2 电子版提交不要想到打印的事，
3 每章单起一页不要理会页码奇偶。

这么看的话，电子版才有统一格式，其他的是各个系不同的。电子版不需要有空白页。

**Comment by Harry-Chen** [comment]
> @zepinglee @Harry-Chen 
> 联系上了电子版论文审核老师，我问了三个问题：
> 1.	之后要交的纸质版论文在格式上与上传的电子版有无区别？
> 2.	《本科生综合论文训练论文写作指南》中要求的授权、摘要等"单设一页"是一面还是一张纸？
> 3.	正文中每一章的开头是否需要控制在奇数页（即，若上一章在奇数页结束，则插入一个空白页以使得本章在奇数页开始）？
> 
> 得到的答复为：
> 1 纸质版论文系里把关， 
> 2 电子版提交不要想到打印的事，
> 3 每章单起一页不要理会页码奇偶。
> 
> 这么看的话，电子版才有统一格式，其他的是各个系不同的。电子版不需要有空白页。

感谢！所以还是之前的方案，搞一个上传/打印的选项，前者统一成这样的格式，后者是插入空白页适合打印的格式。

这样的话，其实上传版本可以去掉页边距？
@zepinglee

**Comment by zepinglee** [comment]
“去掉页边距” 是啥意思？

**Comment by zepinglee** [comment]
```latex
\thusetup{
  output = print/electronic,
}
```
怎么样？

另外电子版是否需要书脊页？

**Comment by Leojc** [comment]
我之前提交时没有添加书脊页，审查意见里没有对此提出意见。

**Comment by Harry-Chen** [comment]
> “去掉页边距” 是啥意思？

哦，我没说清楚。就是本科生论文不是左右边距不一样吗，但是这个只是打印用的。建议电子版就改成一样的，否则会强迫症？

**Comment by Harry-Chen** [comment]
@Leojc 可以尝试一下 `dev` 分支的 `output = eletronic` 选项

**Comment by Harry-Chen** [comment]
发现了一个新问题，electronic 和 print 模式下，声明页面的页码也不一样了（捂脸）比较容易逼死强迫症

**Comment by zepinglee** [comment]
> 发现了一个新问题，electronic 和 print 模式下，声明页面的页码也不一样了（捂脸）比较容易逼死强迫症

对，是会有这个问题，但是要求“去掉全部空白页，又要页码连续”，没办法呀

**Comment by Leojc** [comment]
嗯嗯，现在可以了，应该满足要求了，十分感谢！

**Comment by zhoulvyylj** [comment]
还有一个比较土的方法，就是人力把没有空页的内容输出成单独的PDF文件，再把这些PDF文件合并成一个
