### ISSUE TITLE
工程硕士封面修改

### ISSUE THREAD

**Issue by eatingkong** [tuna/thuthesis#554]
如何显示“工程领域”而不是“学科”啊

**Comment by Harry-Chen** [comment]
请阅读文档，设置 `degree-type` 为 `professional` 即可

**Comment by eatingkong** [comment]
> 请阅读文档，设置 `degree-type` 为 `professional` 即可
插入  degree-type={professional} 会报错啊，没找到具体的文档说明，应该怎么设置啊。

**Comment by eatingkong** [comment]
> 请阅读文档，设置 `degree-type` 为 `professional` 即可

谢谢～我设置错地方了，原来是在\documentclass里。

**Comment by zepinglee** [comment]
我原本想让 `degree`、`degree-type` 允许在导言区中用 `\thusetup` 设置，但是需要改很多内容，所以目前只能在 `\documentclass` 中设置了
