### ISSUE TITLE
\copyrightpage 默认标题不能用于声明

### ISSUE THREAD

**Issue by gjz010** [tuna/thuthesis#556]
## 编译环境
编译的系统：Ubuntu 18.04 (WSL)
TeX 发行版：TeX Live 2019
模板版本：v5.5.2
模板类型：bachelor

## 描述问题
thuthesis-example使用\copyrightpage 用于将figure中的“关于学位论文使用授权的说明”和“声明”插入到论文中。但是二者在书签内的标题都被标成了“关于学位论文使用授权的说明”

复现上述问题的代码：
```TeX
\copyrightpage[scan-auth.pdf]
\copyrightpage[scan-statement.pdf] % 应当是声明，但是成了 关于学位论文使用授权的说明
```

**Comment by Harry-Chen** [comment]
因为 6.1.1 的文档错了，后者应该使用 `\statement`，6.1.2 就会修复。
