### ISSUE TITLE
不合适的 ff 连字

### ISSUE THREAD

**Issue by tanukihee** [tuna/thuthesis#559]
文档的插图索引的命令 `\listoffigures` 中，感觉两个 f 之间的连字并不合适。这是两个词之间而不是一个词之内的字母，连字会造成理解问题，若按德语的话，此处的连字可能还是「错误」的。
![image](https://user-images.githubusercontent.com/34062491/84679199-92ef4980-af63-11ea-9e5f-8cec093a0f47.png)
更合适的连字选择是 `figures` 中的 fi 连字。

**Comment by stone-zeng** [comment]
建议直接关闭所有 tt 字体的连字。

**Comment by tanukihee** [comment]
我以为是 feature 呢😂

**Comment by zepinglee** [comment]
TeX Gyre Cursor 居然默认开ligature……参考 https://tex.stackexchange.com/a/213019/82731

只能手动关掉了
