### ISSUE TITLE
在导言区设置 language=english 失效

### ISSUE THREAD

**Issue by zepinglee** [tuna/thuthesis#560]
From: 熊铮 <xiongz17@mails.tsinghua.edu.cn>

> 我最近正在使用 thuthesis 撰写硕士毕业论文，非常感谢你们分享的 tex 模板！
>
> 我在使用过程中遇到一个问题想请教一下怎么解决。我们的毕业论文要求用全英文撰写，所以我在 thusetup.tex 里设置了 language = english. 但是我发现编译出来的pdf里，每一章的标题依然是“第x章”而不是“Chapter x”，然后目录、参考文献、致谢等部分的标题也依然还是中文的。所以想请问下应该怎么解决这个问题呢？是我什么地方没有设置对吗？
>
> 我的编译环境是 Texlive2020 + TexStudio

**Comment by zepinglee** [comment]
找到原因了，原来逻辑写反了（捂脸

**Comment by zepinglee** [comment]
刚刚检查 CI 崩的原因，原来是示例中的 `diagbox` 依赖的 `pict2e` 更新了，增加了 `\Vector` 的定义，所以导致跟 `math_commands.tex` 定义的 `\Vector` 冲突。

1. 示例应该尽量提供符合学校格式要求的标准写法，一方面学校的写作指南推荐使用三线表，另一方面 `diagbox` 是个比较偏的需求。所以建议移除 `diagbox` 的示例。

2. 我原来搞 `math_commands.tex`，是为了鼓励在写变换字体的数学符号时使用表达语义的命令，而不是直接使用控制格式的命令，比如向量 x 应该写 `\Vector{x}` 或者定义新的命令 `\vx`，而不是直接写 `\mathbf{x}` 或者 `\symbf{x}`。所以按照 ICML 投稿模板提供的 `math_commands.tex` 改写了一份。另外还提供了一些命令的最佳写法，比如 `\argmax`。 @ Harry-Chen 现在我比较怀疑有没有保留这个文件的必要。

**Comment by Harry-Chen** [comment]
> 1. 示例应该尽量提供符合学校格式要求的标准写法，一方面学校的写作指南推荐使用三线表，另一方面 `diagbox` 是个比较偏的需求。所以建议移除 `diagbox` 的示例。

赞同

> 2. 我原来搞 `math_commands.tex`，是为了鼓励在写变换字体的数学符号时使用表达语义的命令，而不是直接使用控制格式的命令，比如向量 x 应该写 `\Vector{x}` 或者定义新的命令 `\vx`，而不是直接写 `\mathbf{x}` 或者 `\symbf{x}`。所以按照 ICML 投稿模板提供的 `math_commands.tex` 改写了一份。另外还提供了一些命令的最佳写法，比如 `\argmax`。 @ Harry-Chen 现在我比较怀疑有没有保留这个文件的必要。

（其实我挺怀疑有多少人会看）我觉得是不是可以用某种形式把它写进文档里

**Comment by zepinglee** [comment]
> 赞同

实例中很多其他内容也没有太多意义，不妨从你的论文中摘取一些合适的片段作为示例？@Harry-Chen

> （其实我挺怀疑有多少人会看）我觉得是不是可以用某种形式把它写进文档里

我也觉得，还是放到文档吧。

**Comment by Harry-Chen** [comment]
> 实例中很多其他内容也没有太多意义，不妨从你的论文中摘取一些合适的片段作为示例？@Harry-Chen

这个能具体一些吗，我的论文好像确实没有 example 那么丰富，基本上就是字、图、公式
