### ISSUE TITLE
关于在目录中显示摘要

### ISSUE THREAD

**Issue by weiguoguo** [tuna/thuthesis#561]
## 编译环境
编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
模板版本：v5.5.2
模板类型：doctor / master / bachelor

## 描述问题
尊敬的开发者，你好！
     我想向你请教，如何在目录中显示“摘要”
截图：
![image](https://user-images.githubusercontent.com/37107336/86357113-f2f22980-bc9f-11ea-9cfb-a9aede9b9838.png)

**Comment by zepinglee** [comment]
<img width="737" alt="Screen Shot 2020-07-02 at 20 48 37" src="https://user-images.githubusercontent.com/12290822/86360768-6e0a0e80-bca5-11ea-8d22-74a01e419f2e.png">
