### ISSUE TITLE
Suggestions: Using custom docker to speed up build

### ISSUE THREAD

**Issue by zhaofeng-shu33** [tuna/thuthesis#562]
Currently, for each commit the github action needs to install texlive environment from scratch.
The problem is that it needs to download many small files, which is a little bit slow (1min).
I suggest custom docker container can be built from `.github/worflows/install-texlive.sh` under someone's docker hub account. And the build environment is set up by pulling
a single large file (image). It can save some time I think.

I find a few months ago, some general purpose docker container is tried but abandoned.
I think general purpose texlive docker is not suitable since it is also quite large (several GBs).
> 已经修好，主要是因为最近 latex2e 更新频繁。
> 
> 1. xeCJK 的 bug 通过临时去掉 `Scale=MatchLowerCase`
> 2. https://hub.docker.com/r/danteev/texlive 的更新频率太慢，换成手动安装 CI 的 texlive。
> 
> _Originally posted by @zepinglee in https://github.com/tuna/thuthesis/pull/452#issuecomment-583737428_

**Comment by Harry-Chen** [comment]
TeX Live 里面的包会更新，我们每次都安装可以及时发现 regression。如果用 docker 镜像的话，就需要定期手工重新 build（不知道 DockerHub 能不能定期这么做）。

**Comment by zepinglee** [comment]
I suppose docker images can be automatically built with GitHub actions.

**Comment by Harry-Chen** [comment]
> I suppose docker images can be automatically built with GitHub actions.

我找到了，Docker Hub 可以做 auto build，这部分不需要写进 CI 脚本，用 WebHook 其实就可以

**Comment by zhaofeng-shu33** [comment]
> > I suppose docker images can be automatically built with GitHub actions.
> 
> 我找到了，Docker Hub 可以做 auto build，这部分不需要写进 CI 脚本，用 WebHook 其实就可以

You mean a separate repo for thuthesis-container?

**Comment by Harry-Chen** [comment]
切换到了 Docker，详见 4ecd16965。使用一个 Action 每天触发 build 来更新 DockerHub 上的镜像。

**Comment by zhaofeng-shu33** [comment]
The download time for docker image is about 20s, 3 times faster than before.
