### ISSUE TITLE
请问在overleaf中手动上传字体文件后如何设置调用？

### ISSUE THREAD

**Issue by lvhailong** [tuna/thuthesis#563]
![截屏2020-07-14下午6 09 32](https://user-images.githubusercontent.com/9078308/87414143-e05fe480-c5fd-11ea-9e8d-89507720c7ee.jpg)

我就遇到了模版说明文档里提到的这个问题，我使用overleaf在线编译的论文，应该用的是“Fandol黑体”，被格式审查老师说字体不对。能否手动将“中易黑体”字体文件上传到overleaf的目录中，通过修改某个位置实现对该字体的调用啊？

本人没有Windows电脑，已经尝试过在overleaf中添加如下命令强制按照windows字体但是会出现错误无法编译。
\documentclass[fontset=windows]{thuthesis}

**Comment by tanukihee** [comment]
需要上传宋黑仿楷四个字体，仅仅上传中易宋体是不够的

**Comment by lvhailong** [comment]
> 需要上传宋黑仿楷四个字体，仅仅上传中易黑体是不够的

那上传完这四个字体之后，需要在哪个位置修改设置使新字体生效呢？

**Comment by tanukihee** [comment]
保证根目录下有中易的四个字体后就可以使用 fontset=windows 了

**Comment by lvhailong** [comment]
> 保证根目录下有中易的四个字体后就可以使用 fontset=windows 了

这四个字体的确切命名是什么？放到根目录里把main.tex文档里加入一句\documentclass[fontset=windows]{thuthesis}就可以了吗？但我的还是编译错误，是不是字体文件名有误啊？
![截屏2020-07-14下午8 14 31](https://user-images.githubusercontent.com/9078308/87424932-70f2f080-c60f-11ea-8cf2-699ed378179a.jpg)
![截屏2020-07-14下午8 17 27](https://user-images.githubusercontent.com/9078308/87424938-751f0e00-c60f-11ea-8b29-ef3cb9a728e4.jpg)

**Comment by tanukihee** [comment]
你的仿宋字体有问题，应该是 simfang.ttc

**Comment by lvhailong** [comment]
> 你的仿宋字体有问题，应该是 simfang.ttc
> 以及 `\documentclass` 只要一个，
> 
> ```
> \documentclass[degree=master, fontset=windows]{thuthesis}
> ```

我这边从网上下载的字体可能不对，或者命名有问题。您能不能把这四个字体文件给我发一下，可以上传到我的云盘里，非常感谢！
https://cloud.tsinghua.edu.cn/u/d/7195775a001442669132/

**Comment by zepinglee** [comment]
你在 Overleaf 上就用默认的字体；编译终稿时在本地用 Windows 的字体。

**Comment by tanukihee** [comment]
传了（thu 还有私人云盘的，酸了

**Comment by lvhailong** [comment]
> 你在 Overleaf 上就用默认的字体；编译终稿时在本地用 Windows 的字，这样更尊重版权。

Overleaf不用安装配置太好用了 原来是版权的原因不支持这些字体啊，那好吧，我还是找台Windows电脑试试看吧

**Comment by lvhailong** [comment]
> 传了（thu 还有私人云盘的，酸了

我尝试上传了您发给我的simfang.ttf字体，但还是报错，可能我另外三个字体也有问题。先不折腾了 我还是找台windows电脑试试本地编译吧，谢谢您的帮助！

**Comment by tanukihee** [comment]
您至少需要给出报错信息才能让人猜是什么原因吧😁

不负责任地猜测一下，似乎 overleaf 只能通过字体名称来调用字体，所以在指定字体后会出现问题
![image](https://user-images.githubusercontent.com/34062491/87430594-05615100-c618-11ea-900f-6b99cfc3274e.png)

可以尝试不明确指定字体（即`\documentclass[degree=master]{thuthesis}`），然后在导言区中使用
```LaTeX
\setCJKmainfont[AutoFakeBold,ItalicFont=simkai.ttf]{simsun.ttc}
\setCJKfamilyfont{zhkai}[AutoFakeBold]{simkai.ttf}
\setCJKsansfont[AutoFakeBold]{simhei.ttf}
\setCJKfamilyfont{zhsong}[AutoFakeBold]{simsun.ttc}
\setCJKfamilyfont{zhhei}[AutoFakeBold]{simhei.ttf}
% 原来模板里并未使用到仿宋😂
```
即可。

![image](https://user-images.githubusercontent.com/34062491/87432365-773a9a00-c61a-11ea-861e-6e7559f2e141.png)

**Comment by lvhailong** [comment]
> 您至少需要给出报错信息才能让人猜是什么原因吧😁
> 
> 不负责任地猜测一下，似乎 overleaf 只能通过字体名称来调用字体，所以在指定字体后会出现问题
> ![image](https://user-images.githubusercontent.com/34062491/87430594-05615100-c618-11ea-900f-6b99cfc3274e.png)
> 
> 可以尝试不明确指定字体（即`\documentclass[degree=master]{thuthesis}`），然后在导言区中使用
> 
> ```
> \setCJKmainfont[AutoFakeBold,ItalicFont=simkai.ttf]{simsun.ttc}
> \setCJKfamilyfont{zhkai}[AutoFakeBold]{simkai.ttf}
> \setCJKsansfont[AutoFakeBold]{simhei.ttf}
> \setCJKfamilyfont{zhsong}[AutoFakeBold]{simsun.ttc}
> \setCJKfamilyfont{zhhei}[AutoFakeBold]{simhei.ttf}
> % overleaf 模板中并未使用到仿宋😂
> % 需要的话
> % \setCJKmonofont{simfang.ttc}
> % \setCJKfamilyfont{zhfs}{simfang.ttc}
> ```
> 
> 即可。
> ![image](https://user-images.githubusercontent.com/34062491/87432445-95a09580-c61a-11ea-860c-c24977d041b4.png)

太强了！！！我虽然不太懂您这几行代码是什么意思，但是我照做之后居然真的成功了，而且我发现这些字体文件名是不区分大小写的，只要拼写正确就不会报错。太感谢了！终于不用本地安装调试4GB的tex live了
