### ISSUE TITLE
2020 年 7 月新版《研究生学位论文写作指南》

### ISSUE THREAD

**Issue by zepinglee** [tuna/thuthesis#564]
[关于启用新版《清华大学研究生学位论文写作指南》及模板的通知](http://yjsy.cic.tsinghua.edu.cn/docinfo/board/boarddetail.jsp?columnId=0010106&parentColumnId=00101&itemSeq=45104)
[研究生学位论文写作指南](http://yjsy.cic.tsinghua.edu.cn/docinfo/board/boarddetail.jsp?columnId=001050603&parentColumnId=0010506&itemSeq=5365)

2020 年 7 月，研究生院修订了《清华大学研究生学位论文写作指南》及相应模板。新版《清华大学研究生学位论文写作指南》及模板从2021年1月毕业批次的研究生正式启用，各院系亦可结合实际情况提前启用。

- [x] 1. 新增了部分内容。
新增了“学位论文指导小组、公开评阅人和答辩委员会名单”、“插图清单”、“附表清单”、“指导教师（小组）学术评语”和“答辩委员会决议书”。
- [x] 2. 调整了学位论文组成和顺序。
将“主要符号对照表”更名为“符号与缩略语说明”。将“个人简历、在学期间发表的学术论文与研究成果”更名为“个人简历、在学期间完成的相关学术成果”。将“附录”调整至“致谢”和“声明”之前。将新增的“学位论文指导小组、公开评阅人和答辩委员会名单”放置在英文封面之后。将新增的“插图清单”、“附表清单”放置在“目录”之后。将新增的“指导教师（小组）学术评语”和“答辩委员会决议书”放置在“个人简历、在学期间完成的相关学术成果” 之后。
- [x] 3. 更新了参考文献著录规则。
- [x] 4. 更新了“目录”所列内容，目录从中文摘要开始。
- [x] 5. 新增和更新了部分附录。
新增了附录E交叉学科名称中英文对照表。
更新了附录C学科门类名称中英文对照表、附录D 一级学科名称中英文对照表、附录F二级学科名称中英文对照表、附录G部分专业学位名称中英文对照表、附录G工程博士、工程硕士及工程硕士领域名称中英文对照表。
- [x] 6. 新增和更新了部分模板。
新增了“学位论文指导小组、公开评阅人和答辩委员会名单”、“插图清单”、“附表清单”或“插图和附表清单”、“指导教师（小组）学术评语”、“答辩委员会决议书”示例模板。
更新了“目录”、“符号和缩略语说明”、“参考文献”、“个人简历、在学期间完成的相关学术成果”示例模板。
更新了“关于学位论文使用授权的说明”模板。
- [x] 7. 新增了“清华大学学位论文公开评阅人聘书及知情同意书”和“清华大学学位论文答辩委员会聘书及知情同意书”，以供参考。

**Comment by Harry-Chen** [comment]
相关文件：

[附件1《清华大学研究生学位论文写作指南》及模板修订说明(202007) .docx](https://github.com/tuna/thuthesis/files/4929043/1.202007.docx)

[关于启用新版清华大学研究生学位论文写作指南及模板的通知.docx](https://github.com/tuna/thuthesis/files/4929044/default.docx)

[清华大学研究生学位论文写作指南(202007）.pdf](https://github.com/tuna/thuthesis/files/4929046/202007.pdf)

[word模板.zip](https://github.com/tuna/thuthesis/files/4929050/word.zip)

[公开评阅人和答辩委员会聘书及知情同意书.zip](https://github.com/tuna/thuthesis/files/4929057/default.zip)

**Comment by zepinglee** [comment]
<img width="651" alt="Screen Shot 2020-07-16 at 13 09 02" src="https://user-images.githubusercontent.com/12290822/87629715-20da7200-c766-11ea-863b-849d53821ae8.png">

**Comment by zepinglee** [comment]
03-2关于学位论文使用授权的说明（硕士）.doc
<img width="637" alt="Screen Shot 2020-07-18 at 14 25 56" src="https://user-images.githubusercontent.com/12290822/87846467-a7c45180-c902-11ea-86fb-f2eb26007d61.png">
应该用分号。

**Comment by zepinglee** [comment]
研究生 2020 版的格式已经基本完成，@Harry-Chen 再来测试下？

**Comment by zepinglee** [comment]
@Harry-Chen 不妨先发布让大家用起来，有啥 bug 再慢慢修吧

**Comment by zepinglee** [comment]
2020 年 8 月研究生院悄悄更新了 Word 模板，主要修改了摘要中关键词的位置。
