### ISSUE TITLE
v7.0.0在Overleaf上编译错误，《2020年7月新版指南》的更改未体现

### ISSUE THREAD

**Issue by kr11** [tuna/thuthesis#567]
首先感谢作者的辛勤劳动成果！

## 编译环境
编译的系统：Overleaf
TeX 发行版：TeX Live 2019
模板版本：v7.0.0
模板类型：master

## 描述问题
1. 在Overleaf上编译出现报错，编译完整日志：
[overleaf-error-log.txt](https://github.com/tuna/thuthesis/files/5200096/overleaf-error-log.txt)

2. 编译得到的pdf存在一些编译错误或内容缺失。pdf：
[thuthesis.pdf](https://github.com/tuna/thuthesis/files/5200112/thuthesis.pdf)

如封面消失、摘要章节错乱（如下图）等：
![image](https://user-images.githubusercontent.com/5548915/92699587-5d020b80-f380-11ea-9763-748a97bd8706.png)

3. 《2020年7月新版指南》中的一些更改未体现在7.0.0编译好的pdf中：
* “主要符号对照表”并未更名为“符号与缩略语说明”
![image](https://user-images.githubusercontent.com/5548915/92699918-c1bd6600-f380-11ea-8ba0-beb3ddce5b7a.png)

* “个人简历、在学期间发表的学术论文与研究成果”并未更名为“个人简历、在学期间完成的相关学术成果”
![image](https://user-images.githubusercontent.com/5548915/92699961-ce41be80-f380-11ea-988b-dbc465a72503.png)

复现上述问题的代码：
master分支默认代码
#564

**Comment by zepinglee** [comment]
你是这里调用的 thuthesis.cls 是 TeX Live 中 2019/04/27 5.5.2 版本的，需要在本地 `xetex thuthesis.ins` 生成新版的 `thuthesis.cls` 在上传到 overleaf。

https://www.overleaf.com/latex/templates/thuthesis-tsinghua-university-thesis-latex-template/tjjttqzttsyv
这个模板是 xueruini 之前上传的，我稍后更新一下。

**Comment by kr11** [comment]
> 你是这里调用的 thuthesis.cls 是 TeX Live 中 2019/04/27 5.5.2 版本的，需要在本地 `xetex thuthesis.ins` 生成新版的 `thuthesis.cls` 在上传到 overleaf。
> 
> https://www.overleaf.com/latex/templates/thuthesis-tsinghua-university-thesis-latex-template/tjjttqzttsyv
> 这个模板是 xueruini 之前上传的，我稍后更新一下。

在mac上依次执行以下命令后编译成功，直接打包上传到Overleaf也成功了，编译出来新版本的论文格式了：
`xetex thuthesis.ins`
`make all`

还有个问题，请问是否有pdf格式的学校规定新版论文呢？我下载到的都是word格式，结果在mac上仿宋字体变成了雅黑，校对latex格式很困惑。谢谢！

**Comment by zepinglee** [comment]
没有 PDF 版。这是因为模板这里的字体是 FangSong_GB2312，但是 Mac 版 Word 以及 macOS 系统本地都不带这个字体，然后就 fallback 到（似乎是）苹方了，只能找盗版字体安装了。

**Comment by pyli0628** [comment]
> 你是这里调用的 thuthesis.cls 是 TeX Live 中 2019/04/27 5.5.2 版本的，需要在本地 `xetex thuthesis.ins` 生成新版的 `thuthesis.cls` 在上传到 overleaf。
> 
> https://www.overleaf.com/latex/templates/thuthesis-tsinghua-university-thesis-latex-template/tjjttqzttsyv
> 这个模板是 xueruini 之前上传的，我稍后更新一下。

请问，这版的overleaf是已经更新后的吗

**Comment by zepinglee** [comment]
> 请问，这版的overleaf是已经更新后的吗

对，已经是 v7.0.0 了
