### ISSUE TITLE
\listoffiguresandtables 命令不见了

### ISSUE THREAD

**Issue by wj-c** [tuna/thuthesis#570]
在最新版7.0.0中没有\listoffiguresandtables了

**Comment by zepinglee** [comment]
1. `\listoffiguresandtables` 是 v7.0.0 新加的；
2. https://github.com/tuna/thuthesis/blob/69d828ea9b9bb271e1a530742fb1aad321d73bf2/thuthesis.dtx#L4340 啥叫不见了？

**Comment by wj-c** [comment]
> 1. `\listoffiguresandtables` 是 v7.0.0 新加的；
> 2. https://github.com/tuna/thuthesis/blob/69d828ea9b9bb271e1a530742fb1aad321d73bf2/thuthesis.dtx#L4340
>     啥叫不见了？

v7.0.0中没有\listoffiguresandtables这条命令呢，\listoftables和\listoffigures都有的

**Comment by zepinglee** [comment]
https://github.com/tuna/thuthesis/blob/v7.0.0/thuthesis.dtx#L4340

https://github.com/tuna/thuthesis/blob/3428190a8db2f2ae581913914a46ccdc97a88247/thuthesis.dtx#L4340

**Comment by wj-c** [comment]
> https://github.com/tuna/thuthesis/blob/v7.0.0/thuthesis.dtx#L4340
> 
> https://github.com/tuna/thuthesis/blob/3428190a8db2f2ae581913914a46ccdc97a88247/thuthesis.dtx#L4340

我是从https://github.com/tuna/thuthesis/releases/download/v7.0.0/thuthesis-v7.0.0.zip这里下载的，然后其中的thuthesis.cls文件里真的找不到\listoffiguresandtables这个命令呢？然后使用这个thuthesis.cls作为模板的话，用\listoffiguresandtables这条命令也会提示undefined control sequence。

**Comment by zepinglee** [comment]
那个 zip 打包时没更新 cls 导致的，我重新上传了一份 [thuthesis-v7.0.0.zip](https://github.com/tuna/thuthesis/files/5287809/thuthesis-v7.0.0.zip) 。

**Comment by zepinglee** [comment]
另外强烈干掉 dtx，已经导致无数类似的问题了。

**Comment by wj-c** [comment]
> 那个 zip 打包时没更新 cls 导致的，我重新上传了一份 [thuthesis-v7.0.0.zip](https://github.com/tuna/thuthesis/files/5287809/thuthesis-v7.0.0.zip) 。

谢谢
