### ISSUE TITLE
字体问题导致编译失败

### ISSUE THREAD

**Issue by saprrow** [tuna/thuthesis#571]
## 编译环境
编译的系统：Ubuntu 18.04 (Mint 19.3)
TeX 发行版：TeX Live 2020 
模板版本：v7.0
模板类型：doctor / master / bachelor

## 描述问题
make thesis编译失败
注释掉thuthesis.cls中的相应字体即可编译成功，但不知道会不会有其他问题。

截图：
![Screenshot from 2020-10-01 21-30-51](https://user-images.githubusercontent.com/44662300/94815828-8ff26900-042d-11eb-8692-dfe7185eeb18.png)
![Screenshot from 2020-10-01 21-31-10](https://user-images.githubusercontent.com/44662300/94815835-91bc2c80-042d-11eb-82c1-889b355374cb.png)
![Screenshot from 2020-10-01 21-31-31](https://user-images.githubusercontent.com/44662300/94815839-9254c300-042d-11eb-88f6-a9cb085c08fe.png)

复现上述问题的代码：
$ make thesis

**Comment by zepinglee** [comment]
模板在 Ubuntu 下会根据系统是否有 Noto Serif CJK SC 选择 Noto CJK 或者 Fandol，你的问题主要是字重没有装全。

不建议修改 cls 文件，这可能会被 dtx  更新后覆盖；可以设置 fontset=fandol，当然更推荐把字重装全

**Comment by saprrow** [comment]
> 装一下字体包：
> 
> ```
> sudo apt install fonts-noto-cjk fonts-noto-cjk-extra
> ```
安装`fonts-noto-cjk-extra`包后解决问题，感谢~

**Comment by saprrow** [comment]
> 模板在 Ubuntu 下会根据系统是否有 Noto Serif CJK SC 选择 Noto CJK 或者 Fandol，你的问题主要是字重没有装全。
> 
> 不建议修改 cls 文件，这可能会被 dtx 更新后覆盖；可以设置 fontset=fandol，当然更推荐把字重装全

好的，谢谢解释~

**Comment by zepinglee** [comment]
后续可以改进：根据有无 Noto Sans CJK Light 来选择字体
