### ISSUE TITLE
中英文摘要的关键词位置没有靠页尾

### ISSUE THREAD

**Issue by kr11** [tuna/thuthesis#572]
首先感谢作者的辛勤劳动成果！

## 编译环境
编译的系统：mac / Overleaf
TeX 发行版：TeX Live 2017 / Tex Live 2929
模板版本：v7.1.0
模板类型：doctor

## 描述问题
学校的word模板中，中英文摘要的关键词都贴着每页的最下端。但7.1.0编译后，关键词紧挨摘要文字：
![image](https://user-images.githubusercontent.com/5548915/96158517-2e122300-0f46-11eb-9b97-994f954697f0.png)

复现上述问题的代码：
最新master分支代码：
commit 0c3fecc0970e0f7814ae0c423560522caa233f70 (tuna/master)
Author: Zeping Lee <zepinglee@gmail.com>
Date:   Wed Oct 14 21:19:51 2020 +0800
    Fix missing file from mwe package [zip]

**Comment by zepinglee** [comment]
研究生院 2020 年 8 月修改的版本已经将关键词的格式改为空一行。
