### ISSUE TITLE
博士后研究报告中 “清华大学人事部”单位错误

### ISSUE THREAD

**Issue by xchuwenbo** [tuna/thuthesis#573]
## 编译环境
编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
模板版本：v7.1.0
模板类型：postdoc

## 描述问题
题名页中单位是“清华大学人事部（北京）”。但是清华没有“人事部”

![image](https://user-images.githubusercontent.com/3981246/96356325-3bced080-111f-11eb-97b9-1fa1082ad3cd.png)

**Comment by zepinglee** [comment]
关于博后报告的讨论比较少，其中的格式应该还存在一些问题。

根据 http://postdoctor.tsinghua.edu.cn/info/czxz/1283 的 「编写《清华大学博士后研究报告》参考意见.doc」：
<img width="811" alt="Screen Shot 2020-10-18 at 12 32 49" src="https://user-images.githubusercontent.com/12290822/96358851-4ea4cd80-113e-11eb-8632-ae3939b09673.png">
我只是把“武汉大学”改成了“清华大学”，但是不太清楚是否准确。

**Comment by xchuwenbo** [comment]
谢谢回复。暂时还没有发现其他问题。
我把模板中的这一行改成了“清华大学”
然后下周去提交下试试，然后继续反馈在这里。

**Comment by xchuwenbo** [comment]
题名页还缺一行合作导师

**Comment by zepinglee** [comment]
「编写《清华大学博士后研究报告》参考意见.doc」并没有提到「合作导师」，这是提交后的反馈意见吗？

**Comment by McDifference** [comment]
> 关于博后报告的讨论比较少，其中的格式应该还存在一些问题。
> 
> 根据 http://postdoctor.tsinghua.edu.cn/info/czxz/1283 的 「编写《清华大学博士后研究报告》参考意见.doc」：
> <img alt="Screen Shot 2020-10-18 at 12 32 49" width="811" src="https://user-images.githubusercontent.com/12290822/96358851-4ea4cd80-113e-11eb-8632-ae3939b09673.png">
> 我只是把“武汉大学”改成了“清华大学”，但是不太清楚是否准确。

清华大学没有人事部，但有人事处。博士后管理办公室属于人事处。
