### ISSUE TITLE
研究生的声明部分的页眉和页码问题

### ISSUE THREAD

**Issue by zepinglee** [tuna/thuthesis#574]
模板目前的声明页的页眉设置主要是为了照顾本科生，因为他们的致谢和声明在打印时要“单设一页”，需要在前面添加一空白页，但是提交电子版时却不添加空白页，而且要将导师签字的声明页扫描后插入 PDF 中，这样声明页的页吗就可能会冲突。所以模板默认生成声明页时不添加页眉和页码，而导师签字后扫描的声明页插入 PDF 时才加上页码。

研究生的正文至结束都是连续的，中间不需要空白页，所以不存在页码冲突的问题，其实不需要上述麻烦的机制。

**Comment by yuantailing** [comment]
我遇到两个问题：

1. 目前（v7.2.0）研究生声明页在指定 pdf 文件时无法加页码，这意味着扫描件需要包含页码。这种方式是否不够灵活？希望能够在未确定页码时完成声明页的签字和扫描。
2. 声明页的排版细节（例如行间距、每行字数等）与 word 模板不完全不一致，因此我想用 word 删除页眉页脚后导出的 PDF。遇到同样的问题，即无法自动设置页码。

综上，能否将 page-style 交给用户设置：将 https://github.com/tuna/thuthesis/blob/fc43af2d1a726c6948c4b3b490c8ff127e17141d/thuthesis.dtx#L5049 改为 `\thispagestyle{\thu@statement@page@style}`。如需兼容以前版本，可在研究生 statement file 非空时将 page-style 默认值改为 empty。

**Comment by zepinglee** [comment]
嗯……去年 10 月份的时候是研究生院的老师，说示例文档的声明页没页码，所以我才取消的。

我觉得你说的有道理，我打算改成 `\statement` 的可选参数如果有 `pagestyle` 则由用户控制，默认还是跟现在一致。

> 声明页的排版细节（例如行间距、每行字数等）与 word 模板不完全一致……

每行字数是这样的，A4 纸宽 21.0 cm，减去左右两边的空白各 3.0 cm，文字宽度 16.0 mm 等于 453.54 pt，除以字号 12 pt 等于每行 37.8 个字。最后一个字是采用挤压还是挪到下一行就由排版软件控制了（一般来时这样的设计对中文不太好）。行距的话，Word 模板的设置有误，应该是 20 pt 不是 21 pt。
<img width="571" alt="Screen Shot 2021-03-14 at 17 50 42" src="https://user-images.githubusercontent.com/12290822/111064814-2fde1380-84f1-11eb-8865-56db697804cc.png">

**Comment by zepinglee** [comment]
@yuantailing 可以先用 09ec228 。
