### ISSUE TITLE
生成的文档无法查重！！！（在知网查重时报”检测失败,解析失败“的错）

### ISSUE THREAD

**Issue by LZGMatrix** [tuna/thuthesis#575]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2020
模板版本：v7.1.0
模板类型：doctor

## 描述问题
编辑生成的pdf文档在提交知网查重时，显示”检测失败,解析失败“

截图：
<img width="310" alt="Picture1" src="https://user-images.githubusercontent.com/56854605/97107513-fb64e900-1702-11eb-99ab-2f4027ce5c01.png">

**Comment by LZGMatrix** [comment]
大家有谁遇到这个问题找到解决方案的吗？

**Comment by LZGMatrix** [comment]
问题解决了

**Comment by zepinglee** [comment]
怎么解决的？给大家分享一下啊
