### ISSUE TITLE
Overleaf与word模板的字体不同

### ISSUE THREAD

**Issue by kr11** [tuna/thuthesis#577]
## 编译环境
编译的系统：Windows 7 / Overleaf
TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
模板版本：v5.5.2
模板类型：doctor

## 描述问题
Overleaf Template编译的封面标题字体与word模板不同

截图：
以下为Overleaf封面：
![image](https://user-images.githubusercontent.com/5548915/98620110-9aaef080-233f-11eb-8d1d-30837bcdd85c.png)

以下为word模板封面：
![image](https://user-images.githubusercontent.com/5548915/98620121-9f73a480-233f-11eb-900f-fcdb75f27c6d.png)

复现上述问题的代码：默认文件，标题为：单位根和协整及其结构突变的理论与应用研究

**Comment by zepinglee** [comment]
对，Word 中的中易黑体是版权字体，overleaf 上并不提供。所以建议在提交最终版前使用 Windows 平台的字体进行编译。
