### ISSUE TITLE
Mac 编译错误，以及新master分支的ref更改问题

### ISSUE THREAD

**Issue by kr11** [tuna/thuthesis#578]
## 编译环境
编译的系统：macOS 10.14 
TeX 发行版：TeX Live 2017
模板版本：v7.1.0
模板类型：doctor

## 描述问题
从github下载最新的master分支代码：
```
commit 3d644890bad628e8af771caa67356c806c51cb08 (HEAD -> master, origin/master, origin/dev, origin/HEAD)
Author: Zeping Lee <zepinglee@gmail.com>
Date:   Tue Nov 10 20:01:00 2020 +0800

    Fix bib format: remove space before pages
```

直接运行`xetex thuthesis.ins` 和 `make all`，编译报错，错误日志：
[thuthesis-example.log](https://github.com/tuna/thuthesis/files/5546745/thuthesis-example.log)

复现上述问题的代码：
master分支，无改动。

**Comment by kr11** [comment]
另外还想请教：master分支是更新了bib格式和指定文件位置吗？是否从`thuthesis-example.tex`移动到了`thusetup.tex`？

我注意到`thusetup.tex`文件中“参考文献使用 BibLaTeX 宏包“这部分的代码
有变动，以下两行被放出：
```
\usepackage[backend=biber,style=thuthesis-numeric]{biblatex}
\addbibresource{ref/refs.bib}
```
在`thuthesis-example.tex`文件中，`\bibliography{ref/refs}`被注释掉，`\printbibliography`被放出。

**Comment by zepinglee** [comment]
测试 biblatex 时忘记改回去了，不知道 CI 是咋过的。

bib 格式和制定文件位置的差异主要是 bibtex 和 biblatex 的差异
