### ISSUE TITLE
能不能在模板中加入选题报告？

### ISSUE THREAD

**Issue by qzxuhui** [tuna/thuthesis#579]
您好，希望在模板中加入选题报告的封面。

现在的航天航院固体力学系开题报告格式要求如下：

![Screenshot from 2020-12-05 13-15-20](https://user-images.githubusercontent.com/24250807/101234663-4c053400-36fc-11eb-922b-a3ff722b6971.png)

和博士论文相比，主要差别如下：
### 差别1：
* 博士论文：(申请清华大学工学博士学位论文)
* 选题报告：(清华大学博士学位论文选题报告)
### 差别2：
* 博士论文：没有学号
* 选题报告：有学号

**Comment by zepinglee** [comment]
可以，有没有官方文件的 URL？

**Comment by qzxuhui** [comment]
非常感谢，这个链接点开可以得到一个选题报告的模板

http://www.law.tsinghua.edu.cn/publish/law/7024/20111021165212974587726/3.doc

**Comment by qzxuhui** [comment]
对于有近期要开题要急用的同学，下面这个方式可以非常粗暴地做出封面：

直接修改realase版本的`thuthesis.cls`文件

### 修改1，大约在1637行
把
```
\newcommand\thu@titlepage@degree{%
  \begingroup
    \def\CJKglue{\hskip 1bp}%
    \CJKfamily+{}\xiaoer
    (申请清华大学\thu@degree@name\ifthu@degree@type@professional 专业\fi 学位论文)\par
  \endgroup
}
```
修改为
```
\newcommand\thu@titlepage@degree{%
  \begingroup
    \def\CJKglue{\hskip 1bp}%
    \CJKfamily+{}\xiaoer
    (清华大学博士学位论文选题报告)\par
  \endgroup
}
```
### 修改2，大约在1676行
对于学位类型是博士，即在开头使用`\documentclass[degree=doctor, fontset=windows]{thuthesis}`，
可以修改
```
\newcommand\thu@titlepage@info@doctor@academic{%
  \thu@titlepage@info@tabular{2.8cm}{2.8cm}{0.82cm}{%
    \thu@info@item{培养单位}{}{\thu@department}%
    \thu@info@item{学科}{}{\thu@discipline}%
    \thu@info@item{研究生}{\thu@name@title}{\thu@author}%
    \thu@info@item{指导教师}{\thu@name@title}{\thu@supervisor}%
    \thu@info@item{副指导教师}{\thu@name@title}{\thu@associate@supervisor}%
    \thu@info@item{联合导师}{\thu@name@title}{\thu@joint@supervisor}%
  }\par
}
```
为
```
\newcommand\thu@titlepage@info@doctor@academic{%
  \thu@titlepage@info@tabular{2.8cm}{2.8cm}{0.82cm}{%
    \thu@info@item{培养单位}{}{\thu@department}%
    \thu@info@item{学科}{}{\thu@discipline}%
    \thu@info@item{研究生}{\thu@name@title}{\thu@author}%
    \thu@info@item{学号}{\thu@name@title}{12345678}%
    \thu@info@item{指导教师}{\thu@name@title}{\thu@supervisor}%
    \thu@info@item{副指导教师}{\thu@name@title}{\thu@associate@supervisor}%
    \thu@info@item{联合导师}{\thu@name@title}{\thu@joint@supervisor}%
  }\par
}
```
硕士同理，修改1698行的对应的代码块即可。

这样就可以临时做出一个粗暴的做出一个封面出来。

感谢开发者未来可以把这个功能给加进去 ^-^。

**Comment by qzxuhui** [comment]
除了上述不同之外，选题报告封面应该不需要英文摘要和英文封面。英文封面不知道有没有办法不生成。英文摘要可以直接把`\begin{abstract*} ... \end{abstract*}`给注释了就不会生成。如果可以的话，可以建立一个开关来设置是否生成英文封面。谢谢。

**Comment by zepinglee** [comment]
研究生院的官方文件在 http://yjsy.cic.tsinghua.edu.cn/docinfo/board/boarddetail.jsp?columnId=0011505&parentColumnId=00115&itemSeq=322 ，不过仅限校内访问。

接口的话，`thesis-type = thesis/report` 怎么样？`type` 在旧版中用于设置 `type = doctore/master/bachelor`，最好避免冲突。另外 `student-id` 设置。

中英文的标题页是由 `\maketitle` 命令一起生成的，这是 LaTeX 的标准接口。所以我不建议拆开成两个命令分别用于中英文的封面。倒是可以考虑增加一个选项 `include-english-title-page = true / false` 用于手动控制，当然 `thesis-type = report` 自动改为 `false`。

**Comment by zepinglee** [comment]
> 对于有近期要开题要急用的同学，下面这个方式可以非常粗暴地做出封面：
> 
> 直接修改realase版本的`thuthesis.cls`文件

建议修改 `.dtx` 文件。

要注意，`.cls` 文件是从 `.dtx` 中 unpack 得到的。如果修改了 `.cls` 后再更新 `.dtx`，`make` 时会覆盖掉 `.cls` 的修改。

**Comment by qzxuhui** [comment]
哈哈哈哈哈，我不太会修改`.dtx`文件，就直接改了`.cls`。T^T。还得麻烦您这个专业的开发者来给一个解决方案啦。
出现两次`\maketitle`确实很奇怪。我觉得您的提议是一个好主意。辛苦啦。

**Comment by zepinglee** [comment]
@Harry-Chen 有啥建议？

**Comment by Harry-Chen** [comment]
> 研究生院的官方文件在 http://yjsy.cic.tsinghua.edu.cn/docinfo/board/boarddetail.jsp?columnId=0011505&parentColumnId=00115&itemSeq=322 ，不过仅限校内访问。
> 
> 接口的话，`thesis-type = thesis/report` 怎么样？`type` 在旧版中用于设置 `type = doctore/master/bachelor`，最好避免冲突。另外 `student-id` 设置。
> 
> 中英文的标题页是由 `\maketitle` 命令一起生成的，这是 LaTeX 的标准接口。所以我不建议拆开成两个命令分别用于中英文的封面。倒是可以考虑增加一个选项 `include-english-title-page = true/false` 用于手动控制，当然 `thesis-type = report` 自动改为 `false`。

是不是叫 `proposal` 更好一些？我同意用这样的选项，然后配合 `student-id`。

此外，这个事情是不是和研究生院联系一下，看看他们要不要跟着新的写作指南一起更新一下？

**Comment by zepinglee** [comment]
嗯，`proposal` 更好。我去联系下研究生院。

**Comment by zepinglee** [comment]
研究生院回复说就按照目前的格式，不打算更新。

**Comment by zepinglee** [comment]
@qzxuhui 目前 master 分支的版本可以设置选题报告格式了。
```
\documentclass[thesis-type=proposal, degree=doctor]{thuthesis}
\thusetup{student-id = 2000310000}
```
