### ISSUE TITLE
不好意思哈，不过《关于学位论文使用授权的说明》这里第三条是换了的，我该在什么地方修改，没有之前的cls文件了

### ISSUE THREAD

**Issue by liyuan-qiu** [tuna/thuthesis#581]
## 编译环境
编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
模板版本：v5.5.2
模板类型：doctor / master / bachelor

## 描述问题
《研究生学位论文写作指南》第 xx 页要求……而模板编译的结果是……

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{thuthesis}
\begin{document}
abc
\end{document}
```

**Comment by Harry-Chen** [comment]
请使用 **最新版** 的模板（<https://github.com/tuna/thuthesis/releases/tag/v7.1.0>），5.5.2 已经严重过时。

**Comment by zepinglee** [comment]
1. 看文档。
2. 描述清楚问题。
3. 上面两个没搞完不要新开 issue。
