### ISSUE TITLE
使用ATOM无法编译问题

### ISSUE THREAD

**Issue by GuangfuWang** [tuna/thuthesis#582]
## 编译环境
编译的系统： Windows 10
TeX 发行版：TeX Live 2020
模板版本：v5.5.2
模板类型：doctor / master / bachelor

## 描述问题
当尝试编译这个模板时，提示两个错误：
1：latexmk: Failure in some part of making file
2: Package kvsetkeys: Undefined key "output"

截图：

**Comment by zepinglee** [comment]
使用最新版的模板

**Comment by GuangfuWang** [comment]
> 使用最新版的模板

thanks
