### ISSUE TITLE
关于研究生学位论文英文版的Latex模板

### ISSUE THREAD

**Issue by JuneChen225** [tuna/thuthesis#585]
如题，学校在官网上提供了英文版的论文写作指南，不知latex的模板可否也跟进呢？我尝试了在latex里使用language = english，但是格式和今天给的通知的模板里不一样_(:з」∠)_  明年6月毕业的留鞋僧卑微求英文版本的，谢谢！

http://yjsy.cic.tsinghua.edu.cn/docinfo/board/boarddetail.jsp?columnId=0010106&parentColumnId=00101&itemSeq=48304

**Comment by zepinglee** [comment]
已经注意到了，正在修改中。

**Comment by JuneChen225** [comment]
> 已经注意到了，正在修改中。

感激！！

**Comment by zepinglee** [comment]
我简单改了个版本 push 到 dev 分支了，@JuneChen225 你来测试下？如果有问题再继续改。

**Comment by JuneChen225** [comment]
您好，我试了下，并对照了官网给出的word模板和指南，有以下地方需修改：
1. 中文封面：国际生要求有英文题目，在中文题目的下段，使用20号Arial，研究生的名字用16号的Times New Roman
2. 目录：一级标题应全大写，即TABLE OF CONTENTS, 目录中中文字体12号黑体，英文12号Times New Roman, 二级三级标题不是全大写
3. 正文：
3.1 目录中的一级标题对应的内容模板的标题也应全大写并加粗，即ABSTRACT, LIST OF FIGURES AND TABLES, REFERENCES, APPENDIX A, ACKNOWLEDGEMENTS, RESUME, COMMENTS, RESOLUTION
3.2 正文中的Chapter应全大写并加粗，即CHAPTER 1 XXX；二级、三级标题也应加粗
暂时就这些，麻烦您啦！感谢！新年快乐！

**Comment by zepinglee** [comment]
> 您好，我试了下，并对照了官网给出的word模板和指南，有以下地方需修改：
> 
> 1. 中文封面：国际生要求有英文题目，在中文题目的下一行，使用20号Arial，研究生的名字用16号的Times New Roman
> 2. 目录：一级标题应全大写，即TABLE OF CONTENTS, 目录中中文字体12号黑体，英文12号Times New Roman, 二级三级标题不是全大写
> 3. 正文：
>    3.1 目录中的一级标题对应的内容模板的标题也应全大写并加粗，即ABSTRACT, LIST OF FIGURES AND TABLES, REFERENCES, APPENDIX A, ACKNOWLEDGEMENTS, RESUME, COMMENTS, RESOLUTION
>    3.2 正文中的Chapter应全大写并加粗，即CHAPTER 1 XXX；二级、三级标题也应加粗
>    暂时就这些，麻烦您啦！感谢！新年快乐！

1. 中文标题页需要英文标题；
2. 这个应该是全大写的。PDF 书签为了可读性，还是保持原样。
<img width="1059" alt="Screen Shot 2021-01-07 at 22 37 16" src="https://user-images.githubusercontent.com/12290822/103905005-07284f00-5139-11eb-90f6-9601d1e7eb0a.png">

3. 这些也是大写加粗的，但是中文只用黑体不加粗。可能是需要重新生成 `cls` 文件。
<img width="692" alt="Screen Shot 2021-01-07 at 22 41 19" src="https://user-images.githubusercontent.com/12290822/103905359-7736d500-5139-11eb-9d11-80d3afe7bab0.png">

**Comment by JuneChen225** [comment]
emmm没懂 是说已经改了吗？

**Comment by zepinglee** [comment]
1 还没改了，2、3 已经改了。

**Comment by JuneChen225** [comment]
哎？可是为什么我刚刚重新下载了git文件还是一样

**Comment by zepinglee** [comment]
> 哎？可是为什么我刚刚重新下载了git文件还是一样的呢？我重新生成了cls文件了

需要下载 dev 分支：https://github.com/tuna/thuthesis/archive/dev.zip  。

**Comment by JuneChen225** [comment]
我确实是重新下载了dev分支，然后用xetex thuthesis.ins生成cls文件，还是没变
![image](https://user-images.githubusercontent.com/16095348/104268286-836eb980-54ce-11eb-8e54-68fa3d0ae465.png)
是哪里操作不对吗？我换了台电脑编译也是一样，我在thusetup里在output后面加了language = english，

**Comment by zepinglee** [comment]
我是用 `\documentclass[degree=master, language=english]{thuthesis}` 测试的。

中间的机制有些复杂，我稍后会改成允许两种设置方式。

**Comment by zepinglee** [comment]
英文模板的封面已经基本修正了。

还有两个细节需要找研究生院确认一下。
1. 「01-博-1-中文6学术型封面（有联合导师）.doc」和「01 Academic-Doctor-with co-supervisor.doc」的“联合指导教师”不一致。
<img width="386" alt="Screen Shot 2021-01-21 at 17 06 14" src="https://user-images.githubusercontent.com/12290822/105328416-fb458e00-5c0a-11eb-94be-081d1de3ab09.png">

2. 「01-硕-2-英文2-专业学位封面.doc」和「02 Professional-Master of Engineering-with associate supervisor.doc」的 engineering field 位置不一致。
<img width="447" alt="Screen Shot 2021-01-21 at 17 10 33" src="https://user-images.githubusercontent.com/12290822/105328972-976f9500-5c0b-11eb-96f3-9e7af1838247.png">

**Comment by lishyer** [comment]
thuset 设置成英文后，参考文献栏标题显示Bibliography不是References。。。

**Comment by zepinglee** [comment]
> thuset 设置成英文后，参考文献栏标题显示Bibliography不是References。。。

不会呀。
<img width="739" alt="Screen Shot 2021-01-23 at 17 40 07" src="https://user-images.githubusercontent.com/12290822/105574824-0da60000-5da2-11eb-85e3-14d0fecbc81e.png">

试一下最新的 `dev` 分支 d62076b ？

**Comment by lishyer** [comment]
> > thuset 设置成英文后，参考文献栏标题显示Bibliography不是References。。。
> 
> 不会呀。
> <img alt="Screen Shot 2021-01-23 at 17 40 07" width="739" src="https://user-images.githubusercontent.com/12290822/105574824-0da60000-5da2-11eb-85e3-14d0fecbc81e.png">
> 
> 试一下最新的 `dev` 分支 [d62076b](https://github.com/tuna/thuthesis/commit/d62076b1befdea026fdfd945a167dcf015a0f0f7) ？

![image](https://user-images.githubusercontent.com/16665337/105575147-56f74f00-5da4-11eb-8319-05993e277e3d.png)
好像只有本科生的是标题大写+REFERENCES。。。其他都是标题的首字母大写+Bibliography、、似乎是特意的改动。。。

**Comment by zepinglee** [comment]
> 好像只有本科生的是标题大写+REFERENCES。。。其他都是标题的首字母大写+Bibliography、、似乎是特意的改动。。。

`xetex thuthesis.ins` 生成新的 `cls`

**Comment by sisrfeng** [comment]
请问如何自动让这些标题名的大小写符合要求?
\chapter{my chapter name}  (这个现在确实能全部大写)
\section{my section name}
\subsection{my subsection name}

https://tex.stackexchange.com/a/129682/272703
失败:
        % \usepackage{sectsty}  % http://ctan.org/pkg/sectsty
        % \usepackage{titlecaps}  % http://ctan.org/pkg/titlecaps
            % 别用, 貌似和模板冲突

**Comment by lishyer** [comment]
ok，已收到！

**Comment by sisrfeng** [comment]
有简单粗暴但需要手工调整的方法吗? 今晚就得交了~

**Comment by sisrfeng** [comment]
vim里改论文本身:

```vim
    nno  <silent> <Leader>,  :call Tex_title_casE()<cr>
    nno  <silent> gc         viw:<C-u>call Title_casE()<CR>
    vno  <silent> gc         :<C-u>call Title_casE()<CR>

    fun! Tex_title_casE()
        norm k
        call search('\v\\(To_be_added_keep_it_HERE|%(sub)*section>\{)', 'e')
        "\ call search('\v\\((item)|%(sub)*section>\{)', 'e')
        norm vv
        exe "norm \<esc>"
        call Title_casE()
        exe "norm \<esc>"
        norm j
    endf


    fun! Title_casE()
    " Title Case -- 空格后的字母大写

        norm gv
        " Hack: fix Vim's gv proclivity to add a line when at line end
        if virtcol(".") == 1
            norm '>
            " line select
            norm gV
            " up one line
            norm k
            " back to char select
            norm gV
            """" back up one char
            """normal h
        en

        " yank
        norm "xy

        " lower case entire string
        let @x = tolower(@x)
        " capitalize first in series of word chars
        let @x = substitute(@x, '\w\+', '\u&', 'g')
        " lowercase a few words we always want lower
        let @x = substitute(@x, '\<A\>', 'a', 'g')
        let @x = substitute(@x, '\<An\>', 'an', 'g')
        let @x = substitute(@x, '\<And\>', 'and', 'g')
        let @x = substitute(@x, '\<In\>', 'in', 'g')
        let @x = substitute(@x, '\<The\>', 'the', 'g')
        " lowercase apostrophe s
        let @x = substitute(@x, "'S", "'s", 'g')

        " fix first word again
        let @x = substitute(@x, '^.', '\u&', 'g')
        " fix last word again
        let str = matchstr(@x, '[[:alnum:]]\+[^[:alnum:]]*$')
        let @x = substitute(@x, str . '$', '\u&', 'g')

        "\ "" optional lowercase...
                "\ let n = confirm(
                "\     \ "Lowercase additional conjunctions, adpositions, articles, and forms of \"to be\"?\n" .
                "\     \ "\n", "&Ok\n&Cancel", 2, "Info")
                let n = 1
                if n == 1
                    " lowercase conjunctions
                    let @x = substitute(@x , '\<After\>'    , 'after'    , 'g')
                    let @x = substitute(@x , '\<Although\>' , 'although' , 'g')
                    let @x = substitute(@x , '\<And\>'      , 'and'      , 'g')
                    let @x = substitute(@x , '\<Because\>'  , 'because'  , 'g')
                    let @x = substitute(@x , '\<Both\>'     , 'both'     , 'g')
                    let @x = substitute(@x , '\<But\>'      , 'but'      , 'g')
                    let @x = substitute(@x , '\<Either\>'   , 'either'   , 'g')
                    let @x = substitute(@x , '\<For\>'      , 'for'      , 'g')
                    let @x = substitute(@x , '\<If\>'       , 'if'       , 'g')
                    let @x = substitute(@x , '\<Neither\>'  , 'neither'  , 'g')
                    let @x = substitute(@x , '\<Nor\>'      , 'nor'      , 'g')
                    let @x = substitute(@x , '\<Or\>'       , 'or'       , 'g')
                    let @x = substitute(@x , '\<So\>'       , 'so'       , 'g')
                    let @x = substitute(@x , '\<Unless\>'   , 'unless'   , 'g')
                    let @x = substitute(@x , '\<When\>'     , 'when'     , 'g')
                    let @x = substitute(@x , '\<While\>'    , 'while'    , 'g')
                    let @x = substitute(@x , '\<Yet\>'      , 'yet'      , 'g')

                    " lowercase adpositions
                    let @x = substitute(@x , '\<As\>'   , 'as'   , 'g')
                    let @x = substitute(@x , '\<At\>'   , 'at'   , 'g')
                    let @x = substitute(@x , '\<By\>'   , 'by'   , 'g')
                    let @x = substitute(@x , '\<For\>'  , 'for'  , 'g')
                    let @x = substitute(@x , '\<From\>' , 'from' , 'g')
                    let @x = substitute(@x , '\<In\>'   , 'in'   , 'g')
                    let @x = substitute(@x , '\<Of\>'   , 'of'   , 'g')
                    let @x = substitute(@x , '\<On\>'   , 'on'   , 'g')
                    let @x = substitute(@x , '\<Over\>' , 'over' , 'g')
                    let @x = substitute(@x , '\<To\>'   , 'to'   , 'g')
                    let @x = substitute(@x , '\<With\>' , 'with' , 'g')

                    " lowercase articles
                    let @x = substitute(@x , '\<A\>'   , 'a'   , 'g')
                    let @x = substitute(@x , '\<An\>'  , 'an'  , 'g')
                    let @x = substitute(@x , '\<The\>' , 'the' , 'g')

                    " lowercase forms of to be
                    let @x = substitute(@x , '\<Be\>'      , 'be'    , 'g')
                    let @x = substitute(@x , '\<To\> \<Be\>' , 'to be' , 'g')
                    let @x = substitute(@x , '\<To\> \<Do\>' , 'to do' , 'g')
                    " lowercase prepositions
                    " lowercase conjunctions

                    let @x = substitute(@x , '\<Item\>'          , 'item'          , 'g')
                    let @x = substitute(@x , '\<Section\>'       , 'section'       , 'g')
                    let @x = substitute(@x , '\<Subsection\>'    , 'subsection'    , 'g')
                    let @x = substitute(@x , '\<Subsubsection\>' , 'subsubsection' , 'g')


                    let @x = substitute(@x, '\<Ab\>', 'aB', 'g')


                en

        " reselect
        norm gv


        " replacing selection
        norm "xP

        "
        norm gv
    endf

```

**Comment by zepinglee** [comment]
> 请问如何自动让这些标题名的大小写符合要求? \chapter{my chapter name} (这个现在确实能全部大写) \section{my section name} \subsection{my subsection name}
> 
> https://tex.stackexchange.com/a/129682/272703 失败: % \usepackage{sectsty} % http://ctan.org/pkg/sectsty % \usepackage{titlecaps} % http://ctan.org/pkg/titlecaps % 别用, 貌似和模板冲突

最新的模板应该符合要求。如果有问题的话新开 issue 把复现代码和截图贴一下。
