### ISSUE TITLE
报告Figure和表格的caption对齐和缩进问题

### ISSUE THREAD

**Issue by WangYJ2019** [tuna/thuthesis#589]
![caption error](https://user-images.githubusercontent.com/51941548/103631050-7d805200-4f7d-11eb-95fb-6b366e9d452c.jpg)
如上所示，当figure的caption内容比较短的情况下是居中对齐，但是caption大于1行的情况下，
（1）对齐方式发生了改变，从居中对齐变成了左对齐；
（2）图的编号（e.g. “图1.1”这几个字符）发生了悬挂缩进的现象。
与word排版出来的格式完全不一样。请问有办法处理么？
![word caption](https://user-images.githubusercontent.com/51941548/103631169-9db01100-4f7d-11eb-8cb8-5dfb6a705688.jpg)
【此为word排版出的结果】

**Comment by zepinglee** [comment]
《指南》第 12 页规定了「图序与图题置于图的下方，采用 11pt 字 居中书写」，但是这个规定显然没考虑多行的情况。我考察了一下我的领域的期刊，大部分的处理方式是，超过一行的 caption 像段落一样两端对齐，不悬挂缩进，尾行不居中，也就是 LaTeX 默认的样式。我觉得这样最合理。

如果简单粗暴地居中，各行都参差不齐，有些破坏排版的美感。
![103631169-9db01100-4f7d-11eb-8cb8-5dfb6a705688](https://user-images.githubusercontent.com/12290822/103642893-c5f43b80-4f8e-11eb-8385-cf8ba9931883.jpg)

另外没必要一定按照 Word 的样式。

**Comment by WangYJ2019** [comment]
@zepinglee ，谢谢您的回复。可以理解如果超过一行就应该两端对齐。
但是目前的模板好像是将“图1.1”这个标签悬挂，然后其他的caption内容两端对齐，这个排版感觉还是不好看。

一般杂志都是包括这个标签在内两端对齐的。请查看我上传的caption error图片，明显“图1.1
![caption error](https://user-images.githubusercontent.com/51941548/103644433-5764ad00-4f91-11eb-8d5f-7b7b32ac18a4.jpg)
”孤零零悬挂不好看，
个人认为最好还是去掉这个悬挂缩进更好一点。就像你说的“两端对齐，不悬挂缩进，尾行不居中”最好。

**Comment by zepinglee** [comment]
OK，我去掉了悬挂缩进。

**Comment by WangYJ2019** [comment]
谢谢您的回复，您真实THU latex模板的劳模~

**Comment by Liguobing00** [comment]
> 《指南》第 12 页规定了「图序与图题置于图的下方，采用 11pt 字 居中书写」，但是这个规定显然没考虑多行的情况。我考察了一下我的领域的期刊，大部分的处理方式是，超过一行的 caption 像段落一样两端对齐，不悬挂缩进，尾行不居中，也就是 LaTeX 默认的样式。我觉得这样最合理。
> 
> 如果简单粗暴地居中，各行都参差不齐，有些破坏排版的美感。
> ![103631169-9db01100-4f7d-11eb-8cb8-5dfb6a705688](https://user-images.githubusercontent.com/12290822/103642893-c5f43b80-4f8e-11eb-8385-cf8ba9931883.jpg)
> 
> 另外没必要一定按照 Word 的样式。

今天打印了论文去找系办老师审查格式，老师说《指南》中写的“居中书写”，意思就是多行的时候也应该居中。所以得改过来。

**Comment by zepinglee** [comment]
那就改成每行居中的样式吧。

这里的图表标题格式涉及两种不同的写作风格。一是国内常见的样式，插图下方使用使用简洁明确的标题作为图题，在必要时会配以图注。通常图注的文字也较为简洁，很多时候会对应图中的序号。下面是《科技书刊标准化 18 讲》的一张示例图。
<img width="618" alt="Screen Shot 2021-02-25 at 15 17 09" src="https://user-images.githubusercontent.com/12290822/113712583-e4e2a500-9718-11eb-979e-c6a6629f0aed.png">

第二种风格是国外的文章中常见的。在插图下方的 caption 中会有大段的文字，其中可能既包含插图的标题，也包含解释性的说明。正如 Chicago Maual of Style 3.21 节的描述述：

> A caption may consist of a word or two, an incomplete or a complete sentence, several sentences, or a combination.

这是 Chicago 的一张示例图（Figure 3.8）。
![chi-cms2017-fig-3-8](https://user-images.githubusercontent.com/12290822/113712645-f6c44800-9718-11eb-8d99-44d54c9e1332.png)
其中“Normalized peak vertical forelimb GREs versus gait” 这个短语对应于第一种样式的“图题”，后面的说明性文字跟图题组成整个 caption，然后像段落文字一样两端对齐。但是这样的解释行文字跟“图注”有些区别，在国内的文章中通常会写在正文里，并不跟图题写在一起。而国外的文章中 caption 经常会写得很长，比如下面是 Nature 的一篇文章的插图。
<img width="409" alt="Screen Shot 2021-02-25 at 15 31 40" src="https://user-images.githubusercontent.com/12290822/113712683-02177380-9719-11eb-940f-3df23e43bf2f.png">

**Comment by Liguobing00** [comment]
> 那就改成每行居中的样式吧。


太感谢 @zepinglee 这么快就有了回复，并且回复这么仔细，学习到了！我其实把你之前关于“多行题注左对齐比较美观”的回答给系办老师发了一下，系办老师就让我自己斟酌选择了，也没有再要求改。

我翻看了国内的教科书，基本上为子图都添加了子题注，所以基本上题注都是一行。比如：
![image](https://user-images.githubusercontent.com/14992913/113717571-52dd9b00-971e-11eb-97bb-f9dfb3459472.png)
![image](https://user-images.githubusercontent.com/14992913/113717761-8ae4de00-971e-11eb-8326-ed006a6978cd.png)


或者解释性的内容用括号括起来，在题注第二行（或者在上面用小一号字）列出，这样其实居中也好看。比如：
![image](https://user-images.githubusercontent.com/14992913/113717701-76084a80-971e-11eb-99d5-bc29b145acbe.png)
![image](https://user-images.githubusercontent.com/14992913/113717933-b5369b80-971e-11eb-8e3d-047d0e35c28b.png)


我自己的论文，因为其实基本上是把之前发表的英文论文翻译过来的，所以题注也非常的长。如果要按照国内的标准，那么需要重新作图，很是麻烦。

所以不**知道研究生院能不能给个准话**，按照国外的那种格式，是否可以？

**Comment by zepinglee** [comment]
我个人比较喜欢长段的 caption，主要是更方便阅读。caption 中一般要描述解释图中的细节，这样跟图放在一起阅读时就很方便。如果 caption 只有很短的标题，而描述、解释的文字在正文，读起来经常要来回翻页很麻烦。

模板中要不要改成每行居中呢？征求下 @Harry-Chen 的意见。

![IMAGE 2021-04-07 00:20:09](https://user-images.githubusercontent.com/12290822/113744139-03f02f80-9737-11eb-9671-0f90ef1a3d03.jpg)

**Comment by Harry-Chen** [comment]
> 我个人比较喜欢长段的 caption，主要是更方便阅读。caption 中一般要描述解释图中的细节，这样跟图放在一起阅读时就很方便。如果 caption 只有很短的标题，而描述、解释的文字在正文，读起来经常要来回翻页很麻烦。
> 
> 模板中要不要改成每行居中呢？征求下 @Harry-Chen 的意见。
> 
> ![IMAGE 2021-04-07 00:20:09](https://user-images.githubusercontent.com/12290822/113744139-03f02f80-9737-11eb-9671-0f90ef1a3d03.jpg)
> 

我个人倾向于现有的样子而不是每行居中。不知道研究生院的老师有没有什么想法？

**Comment by yaox12** [comment]
每行居中简直了。。。不能忍

**Comment by WangYJ2019** [comment]
我觉得，一个理想的处理方法是：对于上面几行满行的 ，用两端分散对齐；剩下未满行的那一部分，用居中对齐。不知道这样是否能够通过代码的方法完成？

**Comment by zepinglee** [comment]
> 我觉得，一个理想的处理方法是：对于上面几行满行的 ，用两端分散对齐；剩下未满行的那一部分，用居中对齐。不知道这样是否能够通过代码的方法完成？

嗯，`justification = centerlast` 可以实现。不过我先征求下研究生院老师的意见吧。

**Comment by zepinglee** [comment]
研究生院的意见是，带编号的 caption 只含标题，说明性文字以注释方式写在图表下方，两端对齐；或者写在正文中。也就是说，如果原来是按照国外的样式将标题和说明文字写成一段，需要改写。

**Comment by zepinglee** [comment]
在 LaTeX 中实现的方法：先用 `\caption*` 写说明文字，再 `\caption` 写标题。

**Comment by Harry-Chen** [comment]
> 研究生院的意见是，带编号的 caption 只含标题，说明性文字以注释方式写在图表下方，两端对齐；或者写在正文中。也就是说，如果原来是按照国外的样式将标题和说明文字写成一段，需要改写。

是不是加到文档里，以及让研究生院在写作指南中说明一下？

**Comment by WangYJ2019** [comment]
研究生院的格式好丑啊，我觉得我导师根本不会在这样的论文上面签字。除非研究生院给出具体的文件说明~
![研究生院要求图片格式](https://user-images.githubusercontent.com/51941548/114340590-7c694d00-9b8a-11eb-81c5-93163ee35d67.jpg)

**Comment by zepinglee** [comment]
我可以把邮件转给你。建议你先问下导师的意见，然后向研究生院培养办公室的姚飞老师（<yf@tsinghua.edu.cn>）反映。我感觉她也不是特别确定，应该还有讨论的空间。

**Comment by zepinglee** [comment]
我修改了图表的示例，提醒要改写成只含标题的 caption。
