### ISSUE TITLE
[Feature Request] 提供使用默认 Computer Modern 数学字体的选项

### ISSUE THREAD

**Issue by bryango** [tuna/thuthesis#590]
默认的字体遵循清华的规范，但是与 AMS 标准字体相去甚远且难以调整；尝试：

```tex
\setmathfont{Latin Modern Math}
```
可以解决部分问题，但仍存在一些毛病，包括但不限于：

- 部分字体依然错误，如 `\nabla` 符号
- 积分上下限不是正常的 `\nolimits` 形式

希望能提供一个开关，使用默认 Computer Modern 数学字体。参考 [`pkuthss`](https://github.com/CasperVector/pkuthss) 的 `nopkufont` 选项（`texdoc pkuthss` -> “pkuthss 文档类提供的选项”）。

**Comment by zepinglee** [comment]
你先试下 dev 分支，其中设置
```latex
\thusetup{
  math-style = TeX,
  math-font = lm,
}

直接使用 Type 1 的 Computer Modern 会有很多问题，尤其是在西文字体固定为 Times New Roman 的情况下。

**Comment by bryango** [comment]
初步测试似乎没有问题！感谢！希望能成为一个稳定的 documented option.

**Comment by zepinglee** [comment]
有个问题是，像 sin、cos 这类以字母拼成的函数依然会使用 Times New Roman 字体，夹杂在一起就很不协调。
<img width="704" alt="Screen Shot 2021-01-11 at 00 05 57" src="https://user-images.githubusercontent.com/12290822/104128139-cfbbdb80-53a0-11eb-9d19-b0a14a65e8d4.png">

尽管可以设置 `\setoperatorfont\symup` 有些改善，但是一些细节的 kerning 是不对的。所以强烈不建议搭配正文字体 Times New Roman 和数学字体 Latin Modern Math。

另外，12 月新版的研究生《撰写手册》第 13 页：
> 表达式采用 Cambria Math 或 Times New Roman 体……

SITX、XITS 和 Libertinus Math 都是 Times 风格的，所以推荐使用这几个。

**Comment by zepinglee** [comment]
关于积分上下限，这主要是几个数学符号标准（AMS, ISO, GB）的区别。其中的差异还包括 e、i、π 等几个数学常数的正斜体，省略号的位置等。我之前高估了 GB/T 3102.11—1993 以及它参照采纳的 ISO 标准，所以把一些数学符号设置得比较接近国标的样式。

另外，研究生《指南》第 12 页 2.3.18 节要求
> 要严格执行国家标准 GB 3100—1993、GB/T 3101—1993 和 GB/T 3102—1993 有关量和单位的规定。

其中似乎包括了 GB/T 3102.11，但是又好像不算是“量和单位”的范畴。我问过研究生院，也还没得到确切答复。

不过我前段时间考察了一下这几个标准的执行情况，ISO 的标准在国际上采用度不怎么高，而 GB/T 3102.11 在国内虽然大部分出版物会严格遵守，但是也有期刊不遵守的。所以我将数学符号的风格改得稍微折衷一些，同时也提供了 `math-style` 选项。

**Comment by AlexaraWu** [comment]
> 尽管可以设置 `\setoperatorfont\symup` 有些改善，但是一些细节的 kerning 是不对的。所以强烈不建议搭配正文字体 Times New Roman 和数学字体 Latin Modern Math。

直接设置 `\setoperatorfont\symup` 的话，operator 用的就的是 Latin Modern Math 了， kerning 肯定是不对的。正确的做法应该是使用 `\setmathrm` 设置 `\mathrm` 使用 Latin Modern 字体。
```latex
\setmathrm{lmroman10}[
  Extension      = .otf,
  UprightFont    = *-regular,
  BoldFont       = *-bold,
  ItalicFont     = *-italic,
  BoldItalicFont = *-bolditalic,
]
```

**Comment by zepinglee** [comment]
> 正确的做法应该是使用 `\setmathrm` 设置 `\mathrm` 使用 Latin Modern 字体。

感谢，我之前还没注意到文档中这个命令。

**Comment by AlexaraWu** [comment]
有个问题在这里问一下，国标文件虽然说「已定义的算子用正体字母表示」。但是它给的示例里偏微分符号 `\partial` 我怎么看都是斜体呀？正体总感觉怪怪的。

**Comment by zepinglee** [comment]
> 有个问题在这里问一下，国标文件虽然说「已定义的算子用正体字母表示」。但是它给的示例里偏微分符号 `\partial` 我怎么看都是斜体呀？正体总感觉怪怪的。

方正的字体问题。

**Comment by zepinglee** [comment]
> * 部分字体依然错误，如 `\nabla` 符号

@bryango XITS 的 `\nabla` 符号有啥问题？

**Comment by zepinglee** [comment]
我反对「与 AMS 标准字体相去甚远」的说法，一是 Computer Modern 本来就不是搭配 Times，二是 cm 也不是 AMS 的标准的或者唯一的字体，别的字体都不标准。实上 AMS 也参与了 STIX 项目（<https://www.stixfonts.org/pressrelease/>）。

**Comment by bryango** [comment]
> 我反对「与 AMS 标准字体相去甚远」的说法，一是 Computer Modern 本来就不是搭配 Times，二是 cm 也不是 AMS 的标准的或者唯一的字体，别的字体都不标准。实上 AMS 也参与了 STIX 项目（https://www.stixfonts.org/pressrelease/）。

Sure. 
<br/>

> > * 部分字体依然错误，如 `\nabla` 符号
> 
> @bryango XITS 的 `\nabla` 符号有啥问题？

这是说我之前自己尝试 `\setmathfont{Latin Modern Math}` 时，`\nabla` 仍保持粗体样式；采用您建议的
```tex
\thusetup{
  math-style = TeX,
  math-font = lm,
}
```
之后，此问题已经解决。感谢！

**Comment by zepinglee** [comment]
我稍后会把上面提到的 `\setmathrm` 加进去。

另外最近我还发现了 New Computer Modern 字体也还不错，比 lm 字形要多一些，还提供了不同风格（`\mathscr`）的手写体和正体的积分号字形，可以配置到 `math-font = newcm`。

**Comment by plong511** [comment]
请问积分上下限的问题是如何解决的？
我在thusetup部分直接加入了
math-style = TeX,
  math-font = lm,
后编译失败，是否还需要修改什么地方呢？

**Comment by zepinglee** [comment]
acb7f19 添加了选项 `math-font = newcm`，等待 #608 的 review。
