### ISSUE TITLE
本科生模板目录以及标题中“致 谢”和“声  明”空白的间距不一致

### ISSUE THREAD

**Issue by yoshiyone** [tuna/thuthesis#591]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2018
模板版本：v7.1.0
模板类型：bachelor

## 描述问题
使用本科生模板编译时，目录中的“致谢”中空了一个\quad的空白，而声明空的是\hspace{2em}，二者不统一导致目录中相应部分看着很别扭。

具体来说是在thuthesis.cls的第803行
```TeX
    \def\thu@acknowledgements@name{致\quad 谢}%
```
与第2265行附近的
```TeX
\newcommand\statement[1][]{%
  \@mainmatterfalse
  \ifthu@degree@bachelor
    \cleardoublepage
    \def\thu@statement@name{声\hspace{2em}明}%
  \else
    \def\thu@statement@name{声\hspace{1em}明}%
  \fi
```
不对应，应仿照2263-2268行修改第803行的代码，使得在使用本科生论文模板时，致谢二字之间空\hspace{2em}的间距。

备注：使用的cls文件为v7.1.0下载下来自带的，不知道如果编译thuthesis.dtx生成出来的有没有这个bug。

截图：
![image](https://user-images.githubusercontent.com/38660350/105444328-92145800-5ca8-11eb-8387-e8d614f879ee.png)

复现上述问题的代码：
```TeX
\documentclass[degree=bachelor]{thuthesis}
%略去其它代码，只要编译就会看出问题
```

**Comment by zepinglee** [comment]
确实不一致。

首先，《[本科生论文写作指南](https://lib.tsinghua.edu.cn/dra/news/annoucement/7963)》并没有规定「目录」、「致谢」和「声明」等标题中间空几字。在一些院系分发的 Word 版「声明」文档中，标题两字之间空两字宽。但是在一份综合论文训练论文样例《气候变化对冬小麦产量影响的数值模拟研究》中，「目录」、「致谢」和「声明」都是空一字宽。

LaTeX 模板在 v6.x 以前是统一空一字宽，从 v7.0.0 开始，应该是在校对本科生的 Word 版「声明」时修改的。

我觉得 Word 版「声明」文档似乎比论文样例更有权威性，建议改成统一空两字。另外 @yoshiyone 你们系发的相关文件是什么样的格式？

**Comment by yoshiyone** [comment]
> 确实不一致。
> 
> 首先，《[本科生论文写作指南](https://lib.tsinghua.edu.cn/dra/news/annoucement/7963)》并没有规定「目录」、「致谢」和「声明」等标题中间空几字。在一些院系分发的 Word 版「声明」文档中，标题两字之间空两字宽。但是在一份综合论文训练论文样例《气候变化对冬小麦产量影响的数值模拟研究》中，「目录」、「致谢」和「声明」都是空一字宽。
> 
> LaTeX 模板在 v6.x 以前是统一空一字宽，从 v7.0.0 开始，应该是在校对本科生的 Word 版「声明」时修改的。
> 
> 我觉得 Word 版「声明」文档似乎比论文样例更有权威性，建议改成统一空两字。另外 @yoshiyone 你们系发的相关文件是什么样的格式？

我们系目前下发的材料中，Word版声明文档的标题中间空了两个汉字的距离，写作指南中确实没有规定中间空几字。我们系目前没有发综合论文训练的样例，暂时无法参考。个人认为至少「致谢」和「声明」应当空相同的距离，否则在目录中看到二者不一致会非常明显。至于「目录」之间空几字，或许也顺便统一了会比较好？或许你们可以讨论一下按什么标准修改会比较合适，谢谢了！ @zepinglee

**Comment by zepinglee** [comment]
> 我们系目前下发的材料中，Word版声明文档的标题中间空了两个汉字的距离，写作指南中确实没有规定中间空几字。我们系目前没有发综合论文训练的样例，暂时无法参考。个人认为至少「致谢」和「声明」应当空相同的距离，否则在目录中看到二者不一致会非常明显。至于「目录」之间空几字，或许也顺便统一了会比较好？或许你们可以讨论一下按什么标准修改会比较合适，谢谢了！ @zepinglee

那我就统一空两字宽了。
