### ISSUE TITLE
title*使用\\换行， 提示Something's wrong--perhaps a missing \item. \makecover

### ISSUE THREAD

**Issue by XiaoZeLin** [tuna/thuthesis#592]
thusetup里的title*使用\\换行， 提示Something's wrong--perhaps a missing \item. \makecover。

我使用的是tex live2020和xelatex，想要标题换行如何解决这个问题？

**Comment by zepinglee** [comment]
无法复现你的问题。
```latex
\documentclass[degree=doctor]{thuthesis}
\thusetup{title* = Foo \\ Bar}
\begin{document}
\maketitle
\end{document}
```

建议按照模板报错模板的格式写。另外 `\makecover` 已经过时，建议确认一下版本。

**Comment by lkp520** [comment]
还是没看懂，怎么解决换行？

**Comment by zepinglee** [comment]
请给出复现问题的代码。

**Comment by lkp520** [comment]
`% !TeX encoding = UTF-8
% !TeX program = xelatex
% !TeX spellcheck = en_US

\documentclass[degree=master, degree-type=academic]{sysuthesis}
  % 学位 degree:
  %   doctor | master
  % 学位类型 degree-type
  %   academic(默认值) | professional

% 论文基本配置，加载宏包等全局配置
\input{sysusetup}


\begin{document}

\makecover
% 封面
\maketitle

% 声明
% % 声明页
\statementpage

\frontmatter
\input{data/abstract}

% 目录
\tableofcontents

% 插图和附表清单
% \listoffiguresandtables  % 插图和附表清单
% \listoffigures           % 插图清单
% \listoftables            % 附表清单

% 符号对照表
\input{data/denotation}

\cleardoublepage

% 正文部分
\mainmatter
\input{data/chap01}
\cleardoublepage
\input{data/chap02}
\cleardoublepage
\input{data/chap03}
\cleardoublepage
\input{data/chap04}
\cleardoublepage
\input{data/chap05}
\cleardoublepage
%\input{data/chap06}
%\cleardoublepage


% 其他部分
\backmatter

% 参考文献
\bibliography{ref}  % 参考文献使用 BibTeX 编译
% \printbibliography       % 参考文献使用 BibLaTeX 编译

% 附录
%\appendix
%\input{data/appendix}

% 在学期间完成的相关学术成果
\input{data/works}

% 致谢
\input{data/acknowledgements}

% % 指导教师/指导小组学术评语
% \input{data/comments}

% % 答辩委员会决议书
% \input{data/resolution}

\end{document}
`

`% !TeX root = ./main.tex

% 论文基本信息配置

\sysusetup{
  %******************************
  % 注意：
  %   1. 配置里面不要出现空行
  %   2. 不需要的配置信息可以删除
  %   3. 建议先阅读文档中所有关于选项的说明
  %******************************
  %
  output = print,
  %
  % 标题
  %   可使用“\\”命令手动控制换行 不行啊报错--------------------
  %
  title  = {基于深度学习的算法研究},
  title*  = {Research on algorithm \\
based on deep learning},
  %
  % 学位
  % 硕士 或 博士
  degree-name  = {硕士},
  %
  % 培养单位
  %   填写所属院系的全名
  %
  department = {1},
  %
  % 工程硕士的名称应为 "工程硕士 [专业名称]"
  discipline  = {1},
  %
  % 姓名
  author  = {1},
  %
  % 指导教师
  supervisor  = {1},
  supervisor-title  = {副教授},
  %
  % 答辩委员会成员
  committee-chair = {},
  committee-member1 = {},
  committee-member2 = {},
  committee-member3 = {},
  committee-member4 = {},
  committee-member5 = {},
  % 日期
  %   使用 ISO 格式；默认为当前时间
  %
  % date = {2020-12-01},
  %
  %
  % 密级: 公开
  secret-level = {公开},
  % secret-year  = {10},
  %
  % 
  series-id = {19213296},
}

% 载入所需的宏包
% 可以使用 nomencl 生成符号和缩略语说明
% \usepackage{nomencl}
% \makenomenclature

% 表格加脚注
\usepackage{threeparttable}

% 表格中支持跨行
\usepackage{multirow}

% 固定宽度的表格。放在 hyperref 之前的话，tabularx 里的 footnote 显示不出来。
% \usepackage{tabularx}

% 跨页表格
% \usepackage{longtable}

% 量和单位
\usepackage{siunitx}

% 定理类环境宏包
\usepackage{amsthm}
% 也可以使用 ntheorem
%\usepackage{amsmath} 
%\usepackage{amssymb}
%\usepackage[amsmath,thmmarks,hyperref]{ntheorem}


% 参考文献使用 BibTeX + natbib 宏包
% 顺序编码制
\usepackage[sort]{natbib}
\bibliographystyle{sysuthesis-numeric}

% 著者-出版年制
% \usepackage{natbib}
% \bibliographystyle{sysuthesis-author-year}

% 本科生参考文献的著录格式
% \usepackage[sort]{natbib}
% \bibliographystyle{sysuthesis-bachelor}

% 参考文献使用 BibLaTeX 宏包
% \usepackage[backend=biber,style=sysuthesis-numeric]{biblatex}
% \usepackage[backend=biber,style=sysuthesis-author-year]{biblatex}
% \usepackage[backend=biber,style=apa]{biblatex}
% \usepackage[backend=biber,style=mla-new]{biblatex}
% 声明 BibLaTeX 的数据库
% \addbibresource{ref/refs.bib}

% 定义所有的图片文件在 figures 子目录下
\graphicspath{{figures/}}

% 数学命令
\newcommand\dif{\mathop{}\!\mathrm{d}}  % 微分符号

% hyperref 宏包在最后调用
\usepackage{hyperref}
`

**Comment by lkp520** [comment]
`
! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.17 \makecover
               
? `

**Comment by zepinglee** [comment]
@lkp520 你发的是 `sysuthesis` 模板，应该更适合去该项目（似乎是 <https://github.com/DapengFeng/sysuthesis/commits/master>？）的 issues 中讨论。`thuthesis` 在 [v6.0.0](https://github.com/tuna/thuthesis/releases/tag/v6.0.0) 已经移除了 `\makecover` 命令。
