### ISSUE TITLE
建议文档中加入共同一作的标注方案

### ISSUE THREAD

**Issue by milkpku** [tuna/thuthesis#593]
作者您好，

由于现在经常出现共同一作的情形，需要在个人简历中注明，但thuthesis的样例和文档中没有给出推荐的解决方案，所以想请您在文档或者样例中添加一种推荐的解决方案。我个人尝试了如下的解决办法，但缺点是标注符号没有链接到脚注，实现也不是很优美。希望能有官方的解决方案，谢谢！

```latex
%% data/resume.tex
\begingroup\renewcommand{\thefootnote}{\fnsymbol{footnote}}
\begin{achievements}
  \item Author 1\footnotemark[1], Author 2\footnotemark[1]. Paper Title[J]. Jurnal, Year, Volume:Pages. 
\end{achievements}
\footnotetext[1]{贡献相同，共同第一作者}
\endgroup
```

**Comment by zepinglee** [comment]
你的这个写法一般在文章的标题页的作者姓名中经常使用，但是在个人简历（类似参考文献）中较少出现。写作指南中提到：

> 1. 学术论文
> 按照参考文献格式书写，尚未刊载但已经接到正式录用函的学术论文加括号注明已被××××期刊录用。

建议也在末尾加括号说明一下。

**Comment by milkpku** [comment]
> 你的这个写法一般在文章的标题页的作者姓名中经常使用，但是在个人简历（类似参考文献）中较少出现。写作指南中提到：
> 
> > 1. 学术论文
> >    按照参考文献格式书写，尚未刊载但已经接到正式录用函的学术论文加括号注明已被××××期刊录用。
> 
> 建议也在末尾加括号说明一下。

事实上很多计算机方向的论文经常出现共同一作，相应的就会出现在个人简历中。比如2020年CCF优秀博士论文中清华的三篇论文里都出现了个人简历中有共同一作的情况。而且其中一位还实现了标注符号到脚注的链接。所以我比较好奇他是如何实现的。

**Comment by yaox12** [comment]
@milkpku 根据我看到的往年的毕业论文，共同一作、导师一作学生二作都是在括号里说明的
