### ISSUE TITLE
\algorithm写伪代码，超过一页无法显示

### ISSUE THREAD

**Issue by ezb16** [tuna/thuthesis#595]
## 编译环境
编译的系统：Windows 10 
模板类型：doctor 

## 描述问题
利用\algorithm写伪代码时，超过了一页，就无法显示了，要怎么修改模板？急求！

**Comment by zepinglee** [comment]
给个代码测试下？

**Comment by ezb16** [comment]
鄂智博Zhibo E 
Beijing 100084, P.R. China
清华大学航天航空学院/School of Aerospace Engineering Of Tsinghua University
手机/mobile：18811763826
邮箱/E-mail：ezhibo@126.com



在2021年2月15日 22:23，Zeping Lee<notifications@github.com> 写道：

给个代码测试下？

**Comment by ezb16** [comment]
> 给个代码测试下？

怎么给代码呀，老师能留个邮箱吗

**Comment by tanukihee** [comment]
```
`﻿``LaTeX
把代码放在这里面
`﻿``
```

**Comment by ezb16** [comment]
\usepackage{float}
\usepackage{algorithm}
\usepackage{algorithmic}
\begin{algorithm}[h]
  \caption{基于二类离散变量的条带划分算法} \label{al11}%算法标题
  \begin{algorithmic}[1]%一行一个标行号
    \STATE \textbf{输入}:  $S= [s_1,s_2,...,s_{N_s}]$, $T=[t_1,t_2,...,t_{N_t}]$, $TW = [tw_{ijk}] $
    \STATE \textbf{初始化}: 集合 $OS = \phi $ , $OSTW = \phi $
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
  \end{algorithmic}
\end{algorithm}
这样不能跨页
![image](https://user-images.githubusercontent.com/79092091/107959848-df04f900-6fde-11eb-9d39-7612da7c2577.png)

**Comment by ezb16** [comment]
\makeatletter
\newenvironment{breakablealgorithm}
  {% \begin{breakablealgorithm}
   \begin{center}
     \refstepcounter{algorithm}% New algorithm
     \hrule height.8pt depth0pt \kern2pt% \@fs@pre for \@fs@ruled
     \renewcommand{\caption}[2][\relax]{% Make a new \caption
       {\raggedright\textbf{\ALG@name~\thealgorithm} ##2\par}%
       \ifx\relax##1\relax % #1 is \relax
         \addcontentsline{loa}{algorithm}{\protect\numberline{\thealgorithm}##2}%
       \else % #1 is not \relax
         \addcontentsline{loa}{algorithm}{\protect\numberline{\thealgorithm}##1}%
       \fi
       \kern2pt\hrule\kern2pt
     }
  }{% \end{breakablealgorithm}
     \kern2pt\hrule\relax% \@fs@post for \@fs@ruled
   \end{center}
  }
\makeatother

\begin{breakablealgorithm}[h]
  \caption{基于二类离散变量的条带划分算法} \label{al11}%算法标题
  \begin{algorithmic}[1]%一行一个标行号
    \STATE \textbf{输入}:  $S= [s_1,s_2,...,s_{N_s}]$, $T=[t_1,t_2,...,t_{N_t}]$, $TW = [tw_{ijk}] $
    \STATE \textbf{初始化}: 集合 $OS = \phi $ , $OSTW = \phi $
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
    \STATE 1
  \end{algorithmic}
\end{breakablealgorithm}

这样搞行距不对
![image](https://user-images.githubusercontent.com/79092091/107960326-736f5b80-6fdf-11eb-8748-a89d1cb1137b.png)

**Comment by ezb16** [comment]
文件如下
[thuthesis-test.zip](https://github.com/tuna/thuthesis/files/5982242/thuthesis-test.zip)

**Comment by zepinglee** [comment]
感觉写法有问题，我从来没见过文章的算法超过一页的。建议拆成几个子算法分别描述。
