### ISSUE TITLE
能否移除“目录”这一行 在目录中的显示

### ISSUE THREAD

**Issue by liziwl** [tuna/thuthesis#597]
![image](https://user-images.githubusercontent.com/23000702/109117780-67249480-777d-11eb-83fb-05aecda9286e.png)

**Comment by liziwl** [comment]
找到命令控制了，`\thu@chapter*[]{\contentsname}%`

**Comment by zepinglee** [comment]
注意看学校最新版的《指南》和 Word 模板，别乱改。
<img width="772" alt="Screen Shot 2021-02-25 at 16 21 53" src="https://user-images.githubusercontent.com/12290822/109124227-a22ac600-7785-11eb-8b62-f9810e338ea5.png">

**Comment by Gaviiin-W** [comment]
> ![image](https://user-images.githubusercontent.com/23000702/109117780-67249480-777d-11eb-83fb-05aecda9286e.png)

请问，你是在目录中怎么显示摘要的呢？

**Comment by zepinglee** [comment]
> 请问，你是在目录中怎么显示摘要的呢？

研究生版的摘要会自动加入目录。
https://github.com/tuna/thuthesis/blob/4344d676c6597da555820633ae6a3f76949c58a5/thuthesis.dtx#L5096

**Comment by Gaviiin-W** [comment]
> > 请问，你是在目录中怎么显示摘要的呢？
> 
> 研究生版的摘要会自动加入目录。
> 
> https://github.com/tuna/thuthesis/blob/4344d676c6597da555820633ae6a3f76949c58a5/thuthesis.dtx#L5096

感谢Zeping！我把这里的 [ ] 删除就可以在本科生的目录中显示摘要了
https://github.com/tuna/thuthesis/blob/4344d676c6597da555820633ae6a3f76949c58a5/thuthesis.dtx#L5099
