### ISSUE TITLE
编辑\left. \right.出现空白方框

### ISSUE THREAD

**Issue by xlc-THU** [tuna/thuthesis#598]
各位，最近在使用v7.1.0。
当公式中需要有单侧括号时，使用了\left.或\right.，但编译的文档中都出现一个白框，不太清楚是有宏包冲突还是什么原因。想请教各位。
之前用其他documentclass或期刊模板时，均没有遇到如下问题。

公式代码：
```latex
\begin{equation}
  \left\{ \begin{array}{ll}
    \xi = \xi \left(x,y\right) \\
    \eta = \eta \left(x,y\right) \\
  \end{array} \right.
  \left.\right.
\end{equation}
```

编译结果：（后两个方框是测试用）
![image](https://user-images.githubusercontent.com/79696582/109290129-294d6c00-7862-11eb-959d-a31739b74129.png)

**Comment by zepinglee** [comment]
直接用这个代码无法复现你的问题，可能跟 `equation` 外部的环境有关。建议贴下能复现问题的尽可能小的完整代码。
```latex
\documentclass[degree=master]{thuthesis}
\input{thusetup}
\begin{document}
\begin{equation}
  \left\{ \begin{array}{ll}
    \xi = \xi \left(x,y\right) \\
    \eta = \eta \left(x,y\right) \\
  \end{array} \right.
  \left.\right.
\end{equation}
\end{document}
```
<img width="462" alt="Screen Shot 2021-02-26 at 19 15 04" src="https://user-images.githubusercontent.com/12290822/109293571-f0fc5c80-7866-11eb-8212-4ed6a95b4267.png">

**Comment by xlc-THU** [comment]
经你提醒，重新检查了宏包，已经解决了，感谢！

由于试用了非Times类公式字体，之前指定公式中的数字（0~9，"30~"39）为Times New Roman，出现了bug，画蛇添足了。
现使用XITS或SIT2，没问题了。

**Comment by zepinglee** [comment]
你是咋设置的？是不是像 #590 打算用 Computer Modern Math？

**Comment by xlc-THU** [comment]
把公式字体设置为Latin Modern Math，把数字0至9单独设为Times类，目前暂时没有发现bug。

```
\setmathfont{Latin Modern Math} % 公式字体
\setmathfont[range={"30,"31,"32,"33,"34,"35,"36,"37,"38,"39}]{XITS Math} % 公式中数字用Times
```

**Comment by zepinglee** [comment]
你这样设置其实没啥效果：
<img width="864" alt="Screen Shot 2021-02-28 at 01 12 53" src="https://user-images.githubusercontent.com/12290822/109394469-1de16a00-7962-11eb-988b-a395b0c45e1c.png">

正确的方法是 `\setmathfont[range=up/num]{XITS Math}`。
<img width="845" alt="Screen Shot 2021-02-28 at 01 15 14" src="https://user-images.githubusercontent.com/12290822/109394522-6b5dd700-7962-11eb-8f28-91e265d4271d.png">

CM/LM 有这么大的吸引力嘛……另外我最近考虑把默认的数学字体换成 Type 1 的 `newtxmath`，有啥建议没？

**Comment by xueruini** [comment]
> CM/LM 有这么大的吸引力嘛……另外我最近考虑把默认的数学字体换成 Type 1 的 `newtxmath`，有啥建议没？

很久以前就用的 `newtx`，如果没记错的话

**Comment by zepinglee** [comment]
> > CM/LM 有这么大的吸引力嘛……另外我最近考虑把默认的数学字体换成 Type 1 的 `newtxmath`，有啥建议没？
> 
> 很久以前就用的 `newtx`，如果没记错的话

原来是用的 `newtxtext` + `newtxmath`，但是有人反映需要用 opentype  Time New Roman，跟 `newtxtext` 的 spacing 还是有些区别。当时考虑到混用 opentype 正文 + type1 newtxmath 容易产生问题，比如 https://github.com/sjtug/SJTUThesis/issues/439 ，所以当时选择了 `unicode-math`，而且对切换数学符号风格（AMS 和 GB）比较友好，

然而又有人不喜欢 stix 或 xits 的一些字形，总之众口难调。

**Comment by yaox12** [comment]
@zepinglee 顺便问一下，近期会release新版本吗？这学期毕业的博士论文DDL是4月1号

**Comment by yaox12** [comment]
@zepinglee 顺便问一下，近期会release新版本吗？这学期毕业的博士论文DDL是4月1号

**Comment by zepinglee** [comment]
> @zepinglee 顺便问一下，近期会release新版本吗？这学期毕业的博士论文DDL是4月1号

会有，应该在这周末。
