### ISSUE TITLE
模板中使用siunitx的数字与前文缺少空格

### ISSUE THREAD

**Issue by kly-510** [tuna/thuthesis#599]
请教！

模板中使用siunitx中\SI，出来的数字与前文文字间缺少空格，得要如example中把\SI另起一行才会有空格，如下图所示。

```
\documentclass[degree=doctor]{thuthesis}
\input{thusetup}
\begin{document}

\maketitle

温度达到
\SI{900}{\kelvin}。压力
\SI{10100}{\pascal}。高度
\SI{6.4e6}{\meter}。室温
\SIrange{10}{20}{\degreeCelsius}

温度达到\SI{900}{\kelvin}。压力\SI{10100}{\pascal}。高度\SI{6.4e6}{\meter}。室温\SIrange{10}{20}{\degreeCelsius}

\end{document}
```
![image](https://user-images.githubusercontent.com/79780305/109409032-21104080-79ca-11eb-9e93-132fe97b8d8e.png)

之前使用ctexart时，并不需要将\SI另起一行，自然与前文间有空格，不知是不是有宏包冲突之类的原因？

**Comment by tanukihee** [comment]
简单地说，在使用 xeCJK 时，请手动在中西文之间添加空格

**Comment by zepinglee** [comment]
> 之前使用ctexart时，并不需要将\SI另起一行，自然与前文间有空格，不知是不是有宏包冲突之类的原因？

xelatex 编译时一样的，包括空格或者换行。

<img width="600" alt="Screen Shot 2021-02-28 at 14 17 55" src="https://user-images.githubusercontent.com/12290822/109409685-c24dc580-79cf-11eb-92e7-b3d0a39b7381.png">

类似的问题在 https://github.com/CTeX-org/ctex-kit/issues 讨论过很多，比如 <https://github.com/CTeX-org/ctex-kit/issues/392>。总之建议养成手动加空格的习惯。

**Comment by kly-510** [comment]
好的，谢谢。

我是用xelatex编译的。不用\SI时，数字前面是会自动有空格的，但用了\SI就没有空格，所以觉得有些奇怪。

```
温度达到\SI{900}{\kelvin}。压力\SI{10100}{\pascal}。高度\SI{6.4e6}{\meter}。室温\SIrange{10}{20}{\degreeCelsius}
长度5米，高度10米
```

![image](https://user-images.githubusercontent.com/79780305/109410285-5883ea80-79d4-11eb-816d-c444b36ba6ff.png)

**Comment by zepinglee** [comment]
这种用宏生成的内容没法完美地处理每种情况，所以目前只能养成手动加空格的习惯。类似的还有 `图~\ref{fig:xxx}`。
