### ISSUE TITLE
更好的中文字体配置

### ISSUE THREAD

**Issue by alick** [tuna/thuthesis#6]
在 LaTeX 里，中文字体配置始终是一个纠结的问题。XeTeX 提供了方便的使用系统
字体的机制，但中文字体

即使这样，我们还是希望能给出不错的默认配置，以满足几类用户的需求：
1. 普通用户，不关心字体配置。目前默认用 Adobe 的四种字体。只要安装了它们，论文是可以正常用 xelatex 编译的。
2. 需要自定义字体，不想折腾 fc-list 等。最好提供个脚本，自动/半自动地生成字体配置文件。
3. 需要自定义字体，不介意折腾 fc-list。这个还是自己手写字体配置文件吧。

**Comment by zepinglee** [comment]
Doc 里面说
> 宏包中包含了 zhfonts.py 脚本,为 Linux/Mac 用户提供一种交互式的方式从系统中文字体 中选择合适的六种字体,最终生成对应的 ctex-fontset-thuthesis.def 文件。要使用它,只需 在命令行输入该脚本的完整路径即可。

不过 MacTeX 没有 fc-list 工具，所以在 Mac 下不能使用。

**Comment by xueruini** [comment]
> 不过 MacTeX 没有 fc-list 工具，所以在 Mac 下不能使用。

多谢指正！我把这个 issue 提出来。
