### ISSUE TITLE
longtable和hyperref不能同时使用

### ISSUE THREAD

**Issue by HaipengHan15** [tuna/thuthesis#604]
## 编译环境
编译的系统：Windows 10 
TeX 发行版：TeX Live 2019
模板版本：v7.1.0
模板类型：master

## 描述问题
在thusetup.tex中，longtable和hyperref好像不能同时使用，注释掉任何一个package都可以正常编译，同时调用就会报错。是我模板没用好吗？求助

截图：
![问题截图](https://user-images.githubusercontent.com/34022748/110195467-32e55e00-7e78-11eb-9b33-b582b0903a38.png)

复现上述问题的代码：
在thusetup.tex中同时使用longtable和hyperref即出现此问题

**Comment by zepinglee** [comment]
master 分支（ c29caa4 ）默认的示例是同时调用 `longtable` 和 `hyperref` 的，在 texlive 2020 上编译没有问题。另外我在 overleaf 的 texlive 2019 编译也没有问题。建议贴一下 `thusetup.tex` 的其他宏包调用情况。

**Comment by HaipengHan15** [comment]
> master 分支（ [c29caa4](https://github.com/tuna/thuthesis/commit/c29caa45e7384e29fdc523af98bd34a89f0f1f26) ）默认的示例是同时调用 `longtable` 和 `hyperref` 的，在 texlive 2020 上编译没有问题。另外我在 overleaf 的 texlive 2019 编译也没有问题。建议贴一下 `thusetup.tex` 的其他宏包调用情况。

thusetup.tex宏包调用如下所示
`
% 载入所需的宏包

% 可以使用 nomencl 生成符号和缩略语说明
% \usepackage{nomencl}
% \makenomenclature

% 表格加脚注
\usepackage{threeparttable}

% 表格中支持跨行
\usepackage{multirow}

% 固定宽度的表格。放在 hyperref 之前的话，tabularx 里的 footnote 显示不出来。
% \usepackage{tabularx}

% 跨页表格
\usepackage{longtable}

% 量和单位
\usepackage{siunitx}

% 定理类环境宏包
\usepackage{amsthm}
% 也可以使用 ntheorem
% \usepackage[amsmath,thmmarks,hyperref]{ntheorem}

% 参考文献使用 BibTeX + natbib 宏包
% 顺序编码制
% \usepackage[sort]{natbib}
% \bibliographystyle{thuthesis-numeric}

% 著者-出版年制
\usepackage{natbib}
\bibliographystyle{thuthesis-author-year}

% 本科生参考文献的著录格式
% \usepackage[sort]{natbib}
% \bibliographystyle{thuthesis-bachelor}

% 参考文献使用 BibLaTeX 宏包
% \usepackage[backend=biber,style=thuthesis-numeric]{biblatex}
% \usepackage[backend=biber,style=thuthesis-author-year]{biblatex}
% \usepackage[backend=biber,style=apa]{biblatex}
% \usepackage[backend=biber,style=mla-new]{biblatex}
% 声明 BibLaTeX 的数据库
% \addbibresource{ref/refs.bib}

% 定义所有的图片文件在 figures 子目录下
\graphicspath{{figures/}}

% 数学命令
\newcommand\dif{\mathop{}\!\mathrm{d}}  % 微分符号

% hyperref 宏包在最后调用
\usepackage{hyperref}
`
注释掉longtable那一行则不会报错。
谢谢！如果解决不了也没关系，表格无法跨页对我来说勉强能接受。

**Comment by zepinglee** [comment]
依然无法复现问题。你的版本是哪个 commit（比如 c29caa4 这样的 SHA-1 checksum）？

> 表格无法跨页对我来说勉强能接受。

多读些文章就完全接受了。（除非超过一页）

**Comment by HaipengHan15** [comment]
> 依然无法复现问题。你的版本是哪个 commit（比如 [c29caa4](https://github.com/tuna/thuthesis/commit/c29caa45e7384e29fdc523af98bd34a89f0f1f26) 这样的 SHA-1 checksum）？
> 
> > 表格无法跨页对我来说勉强能接受。
> 
> 多读些文章就完全接受了。（除非超过一页）

我直接用的是tuna镜像站中最新的那个版本v7.1.0.zip，不是很清楚属于哪个commit……

**Comment by zepinglee** [comment]
噢，v7.1.0 版本呀，我能复现这个问题。在 8bca6d2 中已经修复，见 #584 。

你可以先用 github 的 master 分支：<https://github.com/tuna/thuthesis/archive/master.zip>，需要编译 `xetex thuthesis.ins` 生成新版的 `.cls` 文件。

另外新的版本会在近期发布，也可以稍等待一下。

**Comment by HaipengHan15** [comment]
> 噢，v7.1.0 版本呀，我能复现这个问题。在 [8bca6d2](https://github.com/tuna/thuthesis/commit/8bca6d231a6085a1eb7f2408d85fecf86f97c093) 中已经修复，见 #584 。
> 
> 你可以先用 github 的 master 分支：https://github.com/tuna/thuthesis/archive/master.zip，需要编译 `xetex thuthesis.ins` 生成新版的 `.cls` 文件。
> 
> 另外新的版本会在近期发布，也可以稍等待一下。

好的，谢谢！

**Comment by feiyuxiaoThu** [comment]
> 噢，v7.1.0 版本呀，我能复现这个问题。在 [8bca6d2](https://github.com/tuna/thuthesis/commit/8bca6d231a6085a1eb7f2408d85fecf86f97c093) 中已经修复，见 #584 。
> 
> 你可以先用 github 的 master 分支：https://github.com/tuna/thuthesis/archive/master.zip，需要编译 `xetex thuthesis.ins` 生成新版的 `.cls` 文件。
> 
> 另外新的版本会在近期发布，也可以稍等待一下。

希望能尽快发表，我在使用的时候发现最新的 release 版本的格式和学校的格式要求还是有一些出入的。谢谢！

**Comment by zepinglee** [comment]
> 希望能尽快发表，我在使用的时候发现最新的 release 版本的格式和学校的格式要求还是有一些出入的。谢谢！

#608 under review.
