### ISSUE TITLE
积分上下限的显示问题

### ISSUE THREAD

**Issue by plong511** [tuna/thuthesis#607]
现在模板，积分号的上下限到了积分号的正上方和正下方，是否有办法改成正常的显示形式，与积分号的顶端和底端平行？

**Comment by zepinglee** [comment]
啥叫正常？积分号上下限的位置也属于不同数学风格的区别：ISO 和 GB 倾向于上下限在积分上端和下端，AMS 倾向于放在积分号的右侧。

`unicode-math` 可以用设置
```latex
\removenolimits{%
  \int\iint\iiint\iiiint\oint\oiint\oiiint
  \intclockwise\varointclockwise\ointctrclockwise\sumint
  \intbar\intBar\fint\cirfnint\awint\rppolint
  \scpolint\npolint\pointint\sqint\intlarhk\intx
  \intcap\intcup\upint\lowint
}%
```
```latex
\addnolimits{%
  \int\iint\iiint\iiiint\oint\oiint\oiiint
  \intclockwise\varointclockwise\ointctrclockwise\sumint
  \intbar\intBar\fint\cirfnint\awint\rppolint
  \scpolint\npolint\pointint\sqint\intlarhk\intx
  \intcap\intcup\upint\lowint
}%
```

我正在搞个选项允许用户选择 `integral-limits = true / false`。

另外你不是复旦的吗？

**Comment by plong511** [comment]
> 啥叫正常？积分号上下限的位置也属于不同数学风格的区别：ISO 和 GB 倾向于上下限在积分上端和下端，AMS 倾向于放在积分号的右侧。
> 
> `unicode-math` 可以用设置
> 
> ```
> \removenolimits{%
>   \int\iint\iiint\iiiint\oint\oiint\oiiint
>   \intclockwise\varointclockwise\ointctrclockwise\sumint
>   \intbar\intBar\fint\cirfnint\awint\rppolint
>   \scpolint\npolint\pointint\sqint\intlarhk\intx
>   \intcap\intcup\upint\lowint
> }%
> ```
> 
> ```
> \addnolimits{%
>   \int\iint\iiint\iiiint\oint\oiint\oiiint
>   \intclockwise\varointclockwise\ointctrclockwise\sumint
>   \intbar\intBar\fint\cirfnint\awint\rppolint
>   \scpolint\npolint\pointint\sqint\intlarhk\intx
>   \intcap\intcup\upint\lowint
> }%
> ```
> 
> 我正在搞个选项允许用户选择 `integral-limits = true / false`。
> 
> 另外你不是FDU的吗？



> 啥叫正常？积分号上下限的位置也属于不同数学风格的区别：ISO 和 GB 倾向于上下限在积分上端和下端，AMS 倾向于放在积分号的右侧。
> 
> `unicode-math` 可以用设置
> 
> ```
> \removenolimits{%
>   \int\iint\iiint\iiiint\oint\oiint\oiiint
>   \intclockwise\varointclockwise\ointctrclockwise\sumint
>   \intbar\intBar\fint\cirfnint\awint\rppolint
>   \scpolint\npolint\pointint\sqint\intlarhk\intx
>   \intcap\intcup\upint\lowint
> }%
> ```
> 
> ```
> \addnolimits{%
>   \int\iint\iiint\iiiint\oint\oiint\oiiint
>   \intclockwise\varointclockwise\ointctrclockwise\sumint
>   \intbar\intBar\fint\cirfnint\awint\rppolint
>   \scpolint\npolint\pointint\sqint\intlarhk\intx
>   \intcap\intcup\upint\lowint
> }%
> ```
> 
> 我正在搞个选项允许用户选择 `integral-limits = true / false`。
> 
> 另外你不是FDU的吗？

好的多谢！上下限在积分号右侧比较顺眼一些。
其实我是THU的。。。在FDU的模板上问那么多问题，就是一些大家能想到的原因...嗯...操心两份毕业论文有些心累

**Comment by Liam0205** [comment]
> > 啥叫正常？积分号上下限的位置也属于不同数学风格的区别：ISO 和 GB 倾向于上下限在积分上端和下端，AMS 倾向于放在积分号的右侧。
> > `unicode-math` 可以用设置
> > ```
> > \removenolimits{%
> >   \int\iint\iiint\iiiint\oint\oiint\oiiint
> >   \intclockwise\varointclockwise\ointctrclockwise\sumint
> >   \intbar\intBar\fint\cirfnint\awint\rppolint
> >   \scpolint\npolint\pointint\sqint\intlarhk\intx
> >   \intcap\intcup\upint\lowint
> > }%
> > ```
> > 
> > 
> > ```
> > \addnolimits{%
> >   \int\iint\iiint\iiiint\oint\oiint\oiiint
> >   \intclockwise\varointclockwise\ointctrclockwise\sumint
> >   \intbar\intBar\fint\cirfnint\awint\rppolint
> >   \scpolint\npolint\pointint\sqint\intlarhk\intx
> >   \intcap\intcup\upint\lowint
> > }%
> > ```
> > 
> > 
> > 我正在搞个选项允许用户选择 `integral-limits = true / false`。
> > 另外你不是FDU的吗？
> 
> 好的多谢！上下限在积分号右侧比较顺眼一些。
> 其实我是THU的。。。在FDU的模板上问那么多问题，就是一些大家能想到的原因...嗯...操心两份毕业论文有些心累

狗粮撒得好~

**Comment by zepinglee** [comment]
> 其实我是THU的。。。在FDU的模板上问那么多问题，就是一些大家能想到的原因...嗯...操心两份毕业论文有些心累

今日最佳狗粮。

**Comment by zepinglee** [comment]
#608 under review.

**Comment by zepinglee** [comment]
@plong511 话说你可以比较下两份模板的差异，帮助改进 thuthesis。

**Comment by plong511** [comment]
> @plong511 话说你可以比较下两份模板的差异，帮助改进 thuthesis。

大清的模板已经做得很好很省心了，之前一直看不太顺眼的公式显示问题也解决了。
