### ISSUE TITLE
macOS无法编译v7.2.0版的示例文件

### ISSUE THREAD

**Issue by yaox12** [tuna/thuthesis#611]
## 编译环境
编译的系统：macOS 11.2.3
TeX 发行版：MacTeX 2020
模板版本：v7.2.0
模板类型：master（即示例文件）

## 描述问题

macOS下无法编译v7.2.0版的示例文件

复现上述问题的代码：

v7.2.0 示例项目。

报错信息：
```
/Users/.../Downloads/thuthesis-v7.2.0/thuthesis.cls:937: Package fontspec Error: The font "KaiTi" cannot be found.
```
```

**Comment by yaox12** [comment]
补充，手动指定
```tex
\thusetup{
  system = mac,
  fontset = mac,
}
```
仍然报错

**Comment by zepinglee** [comment]
你的系统中有 SimSun，就默认按照 Windows 的字体配置了。

**Comment by zepinglee** [comment]
研究生院建议提交终稿时使用 Windows 的字体。
