### ISSUE TITLE
图题与正文的间距过大，尤其是浮动为 h 的图片

### ISSUE THREAD

**Issue by yuantailing** [tuna/thuthesis#617]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2020
模板版本：v7.2.1
模板类型：master

## 描述问题
《研究生学位论文写作指南》第 12 页要求 图题“段前空 6 磅，段后空 12 磅” 而模板编译的结果是

浮动为 [h] 的图片，图题与正文的间距明显大于 12 磅；浮动为 [t] 的图片，图题与正文的间距略微大于 12 磅。

截图：
<img width="702" alt="figure-h" src="https://user-images.githubusercontent.com/8487114/111942395-29155900-8b0e-11eb-8095-cd5ae787dadc.png">

复现上述问题的代码：
```TeX
% !TeX root = ../thuthesis-example.tex

\chapter{图表示例}

\section{插图}

图片通常在 \env{figure} 环境中使用 \cs{includegraphics} 插入，如图~\ref{fig:example} 的源代码。
建议矢量图片使用 PDF 格式，比如数据可视化的绘图；
照片应使用 JPG 格式；
其他的栅格图应使用无损的 PNG 格式。
注意，LaTeX 不支持 TIFF 格式；EPS 格式已经过时。

若图或表中有附注，采用英文小写字母顺序编号，附注写在图或表的下方。
% LaTeX 传统上一般将附注的内容同图表的标题写在一起，形成很长的一段文字。

图片通常在 \env{figure} 环境中使用 \cs{includegraphics} 插入，如图~\ref{fig:example} 的源代码。
建议矢量图片使用 PDF 格式，比如数据可视化的绘图；
照片应使用 JPG 格式；
其他的栅格图应使用无损的 PNG 格式。
注意，LaTeX 不支持 TIFF 格式；EPS 格式已经过时。

图片通常在 \env{figure} 环境中使用 \cs{includegraphics} 插入，如图~\ref{fig:example} 的源代码。
建议矢量图片使用 PDF 格式，比如数据可视化的绘图；
照片应使用 JPG 格式；
其他的栅格图应使用无损的 PNG 格式。
注意，LaTeX 不支持 TIFF 格式；EPS 格式已经过时。
填充文字。填充文字。填充文字。填充文字。填充文字。

\begin{figure}[h]
  \centering
  \includegraphics[width=0.6\linewidth]{example-image-a.pdf}
  \caption{示例图片}
  \label{fig:example1}
\end{figure}

\begin{figure}[t]
  \centering
  \includegraphics[width=0.6\linewidth]{example-image-a.pdf}
  \caption{示例图片}
  \label{fig:example}
\end{figure}

图片通常在 \env{figure} 环境中使用 \cs{includegraphics} 插入，如图~\ref{fig:example} 的源代码。
建议矢量图片使用 PDF 格式，比如数据可视化的绘图；
照片应使用 JPG 格式；
其他的栅格图应使用无损的 PNG 格式。
注意，LaTeX 不支持 TIFF 格式；EPS 格式已经过时。

图片通常在 \env{figure} 环境中使用 \cs{includegraphics} 插入，如图~\ref{fig:example} 的源代码。
建议矢量图片使用 PDF 格式，比如数据可视化的绘图；
照片应使用 JPG 格式；
其他的栅格图应使用无损的 PNG 格式。
注意，LaTeX 不支持 TIFF 格式；EPS 格式已经过时。
```

**Comment by yuantailing** [comment]
这有一种没什么道理但确实奏效（目测误差 2 磅以内）的改法，仅供参考：

https://github.com/yuantailing/thuthesis/commit/420eecc1c66f3470cc490ac5e4fee5484f844712

<img width="699" alt="figure-h" src="https://user-images.githubusercontent.com/8487114/111952009-68987100-8b1f-11eb-8067-b967cde78831.png">

**Comment by shyoshyo** [comment]
横向排版单个图片的时候疑似还会因为间距问题出现左右不对称的情况
```latex
\begin{sidewaysfigure}[p]
  \centering
  \includegraphics[width=\linewidth]{data/fig/vis.png}
  \caption{颜色主题的可视化}
  \label{fig:vis}
\end{sidewaysfigure}
```
![Screenshot from 2021-03-26 16-54-54](https://user-images.githubusercontent.com/5780122/112607333-0e1b4f80-8e54-11eb-9dae-1e964f4eb384.png)

**Comment by zepinglee** [comment]
@shyoshyo 新开个 issue 讨论

**Comment by zepinglee** [comment]
参考 https://github.com/tuna/thuthesis/issues/614#issuecomment-810973591 。

我在 https://github.com/tuna/thuthesis/commit/4e80821519c1cba75c0386bf707f614c763c29cb 中修复了这个问题，效果如下。
<img width="596" alt="Screen Shot 2021-03-31 at 18 44 40" src="https://user-images.githubusercontent.com/12290822/113134490-6f2b9480-9253-11eb-842f-c124bd0e6ba8.png">
