### ISSUE TITLE
Algorithm环境中的行距过大

### ISSUE THREAD

**Issue by yaox12** [tuna/thuthesis#619]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2020
模板版本：v7.2.1
模板类型：doctor

## 描述问题

Algorithm环境中的行距过大，比v7.1.0编译出来的大很多。

截图：

v7.1.0编译的结果：
![image](https://user-images.githubusercontent.com/3831900/111945409-a5129f80-8b14-11eb-980a-d602b62a13b9.png)

v7.2.1编译的结果：
![image](https://user-images.githubusercontent.com/3831900/111945475-c1aed780-8b14-11eb-9e03-2b22745c87d8.png)

**Comment by zepinglee** [comment]
我感觉 v7.2.1 的设置才是正确的。

正文的字号是 12 pt，行距 20 pt，是字号的 5/3 倍。算法环境中使用 `\small` 字号，行距也应该跟正文保持相同的比例，尤其是其中同样有这么多中的情况下。当然，如果是纯西文，我觉得可以用 `\linespread{0.72}\selectfont` 局部调整下行距。

**Comment by zepinglee** [comment]
我测试了以下，算法环境 `algorithm` 和 `algorithmic` 从版本 v7.2.0 到 v7.2.1 不应该有行距的变化，见 [algorithms](https://github.com/tuna/thuthesis/tree/algorithms) 分支。在 v7.2.0 添加测试文件 [testfiles/package-algorithms.tex](https://github.com/tuna/thuthesis/commit/62f8b12d5d5ba1ad3f148692ac427100bc1aecc5#diff-835ab7bef4f087ed4f9142f1097f54845a7710d05f6a610f01f8bad59b0c8e97)，merge v7.2.1 后的变化在 https://github.com/tuna/thuthesis/commit/3691a1c16066433b9a040965fdeda7f0c8c363a0 ，其中只有浮动体前后距离的变化，行距并未改变。

另外纠正下算法环境使用的字号跟表格一样是 11 pt。

**Comment by yaox12** [comment]
v7.2.0开始就变大了，上面那个很密的是v7.1.0。我现在用16pt行距，观感比较好。。。

**Comment by zepinglee** [comment]
看错了……

**Comment by zepinglee** [comment]
算法环境的字号默认同表格一致，而表格中要求：

> 表单元格中的文字采用 11pt 字书 写，汉字用宋体，英文和数字用 Times New Roman 体，单倍行距，段前空 3 磅， 段后空 3 磅。

我之前设置表格的行距时把段前段后共 6 pt 一起加到行距里了，所以导致算法的行距也偏大。正确方法是设置 14.3 pt 行距，然后表格中使用 `\arraystretch` 调整段前段后的距离。
