### ISSUE TITLE
Latex中有类"try...catch..."的语法吗

### ISSUE THREAD

**Issue by llk2why** [tuna/thuthesis#623]
目前有个需求，本地的texlive2020的**nicematrix**包是v3.14的，overleaf的**nicematrix**版本是大于v5.0的。这个差异导致了本地latex能编译过的格式化参数字母只能是**大写**的，而overleaf只能接受**小写**的格式化参数。overleaf有个变通的方法是使用如下导入包的命令，则可以大小写都接受：
```
\usepackage[define-L-C-R]{nicematrix}
```
但v3.14版本不支持这样的选项（我尝试过直接升级nicematrix，但是直接给我升级成了v5.12，出bug了，网上查了需要用最新的latex，尚不清楚如何合理升级），我想问问是否有"try...catch..."的语法，如：
```
try:
    \usepackage[define-L-C-R]{nicematrix}
catch:
    \usepackage{nicematrix}
```
从而实现本地和overleaf的兼容，求知道的大佬指点一下。

**Comment by Harry-Chen** [comment]
建议卸载本地的 TeX Live 重装最新版，或者可以直接把新版的 sty 文件放在工作目录中编译，会比 texmf 中的优先被使用。

**Comment by llk2why** [comment]
> 建议卸载本地的 TeX Live 重装最新版，或者可以直接把新版的 sty 文件放在工作目录中编译，会比 texmf 中的优先被使用。

最新版的Tex Live是TUNA上的[这个发行版](https://mirrors.tuna.tsinghua.edu.cn/ctan/systems/texlive/Images/texlive2020.iso)吗？我已经重装过了，其版本就是
```
➜  ~ tex -v
TeX 3.14159265 (TeX Live 2020)
kpathsea version 6.3.2
Copyright 2020 D.E. Knuth.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the TeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the TeX source.
Primary author of TeX: D.E. Knuth.
```
默认的**nicematrix**就是2020/03/23 v3.14，重装后更新也会出现对应的bug，还是说TUNA镜像的Tex Live不够新？

用sty文件直接编译我试试，顺便问一下，一般老一点的包去哪能找到啊？我看CTAN的网站都只放着最新的包（我就是最新的包有bug），没找到有legacy或者older的字样，对CTAN的风格也不是很懂😂

**Comment by llk2why** [comment]
也就是因为这比较乱的关系比较难搞，就像问问有没有类似"try...catch..."的语法，不过只要最后有个解决方案即可😂

**Comment by stone-zeng** [comment]
显然没有 try catch 啊你在想什么……

就事论事，可以这样搞：

```tex
\usepackage{nicematrix}

\ExplSyntaxOn
\bool_set_true:N \c__nicematrix_define_L_C_R_bool
\ExplSyntaxOff
```

**Comment by llk2why** [comment]
> 显然没有 try catch 啊你在想什么……
> 
> 就事论事，可以这样搞：
> 
> ```
> \usepackage{nicematrix}
> 
> \ExplSyntaxOn
> \bool_set_true:N \c__nicematrix_define_L_C_R_bool
> \ExplSyntaxOff
> ```

当然是心存侥幸😂....好嘞，我试试

**Comment by Harry-Chen** [comment]
> > 建议卸载本地的 TeX Live 重装最新版，或者可以直接把新版的 sty 文件放在工作目录中编译，会比 texmf 中的优先被使用。
> 
> 最新版的Tex Live是TUNA上的[这个发行版](https://mirrors.tuna.tsinghua.edu.cn/ctan/systems/texlive/Images/texlive2020.iso)吗？我已经重装过了，其版本就是
> ```
> ➜  ~ tex -v
> TeX 3.14159265 (TeX Live 2020)
> kpathsea version 6.3.2
> Copyright 2020 D.E. Knuth.
> There is NO warranty.  Redistribution of this software is
> covered by the terms of both the TeX copyright and
> the Lesser GNU General Public License.
> For more information about these matters, see the file
> named COPYING and the TeX source.
> Primary author of TeX: D.E. Knuth.
> ```
> 默认的**nicematrix**就是2020/03/23 v3.14，重装后更新也会出现对应的bug，还是说TUNA镜像的Tex Live不够新？
> 
> 用sty文件直接编译我试试，顺便问一下，一般老一点的包去哪能找到啊？我看CTAN的网站都只放着最新的包（我就是最新的包有bug），没找到有legacy或者older的字样，对CTAN的风格也不是很懂😂

TeX Live 的镜像是不会更新的，要么使用在线安装，要么装完之后使用 tlmgr 全部更新一下

**Comment by llk2why** [comment]
> 显然没有 try catch 啊你在想什么……
> 
> 就事论事，可以这样搞：
> 
> ```
> \usepackage{nicematrix}
> 
> \ExplSyntaxOn
> \bool_set_true:N \c__nicematrix_define_L_C_R_bool
> \ExplSyntaxOff
> ```



> > > 建议卸载本地的 TeX Live 重装最新版，或者可以直接把新版的 sty 文件放在工作目录中编译，会比 texmf 中的优先被使用。
> > 
> > 
> > 最新版的Tex Live是TUNA上的[这个发行版](https://mirrors.tuna.tsinghua.edu.cn/ctan/systems/texlive/Images/texlive2020.iso)吗？我已经重装过了，其版本就是
> > ```
> > ➜  ~ tex -v
> > TeX 3.14159265 (TeX Live 2020)
> > kpathsea version 6.3.2
> > Copyright 2020 D.E. Knuth.
> > There is NO warranty.  Redistribution of this software is
> > covered by the terms of both the TeX copyright and
> > the Lesser GNU General Public License.
> > For more information about these matters, see the file
> > named COPYING and the TeX source.
> > Primary author of TeX: D.E. Knuth.
> > ```
> > 
> > 
> > 默认的**nicematrix**就是2020/03/23 v3.14，重装后更新也会出现对应的bug，还是说TUNA镜像的Tex Live不够新？
> > 用sty文件直接编译我试试，顺便问一下，一般老一点的包去哪能找到啊？我看CTAN的网站都只放着最新的包（我就是最新的包有bug），没找到有legacy或者older的字样，对CTAN的风格也不是很懂😂
> 
> TeX Live 的镜像是不会更新的，要么使用在线安装，要么装完之后使用 tlmgr 全部更新一下

之前tlmgr --all 也试过了，可能是我本地的问题😂总之解决了，多谢sq大佬
