### ISSUE TITLE
上标引用后面有多余的空格

### ISSUE THREAD

**Issue by yuantailing** [tuna/thuthesis#624]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2020
模板版本：v7.2.1
模板类型：master

## 描述问题
根据《研究生学位论文写作指南》附件《09正文 第3章（示例）》的示例，上标引用的中括号与两侧中文之间没有空格，而模板编译的结果是有空格。

截图：
![image](https://user-images.githubusercontent.com/8487114/112467725-60039d00-8da2-11eb-9120-36963020d509.png)

复现上述问题的代码：
```TeX
\documentclass[degree=master]{thuthesis}
\input{thusetup}
\begin{document}
引用\cite{bixon1996dynamics}测试。
引用\citet{bixon1996dynamics}测试。
\bibliography{ref/refs}  % 参考文献使用 BibTeX 编译
\end{document}

```

**Comment by zepinglee** [comment]
确实是个 bug。

这个需要深入 `natbib` 底层处理，而且可能是 `xeCJK` 自动添加的，需要费些时间。

**Comment by zepinglee** [comment]
@hushidong 我发现 `biblatex` 也有类似的问题。你觉得左右两边的空隙一致的设计是不是更好些？

**Comment by hushidong** [comment]
你的意思是特意在前面加一个空格么？我看一般文档中是不加的吧，正常的英文是没有的，中文后面多出来的空主要是xecjk加入的。

如果一定要加那么弄个短的空格（半空格），做个选项给它。分三种情况：1默认的，前面无，后面有，2前面有，后面有，3前面无，后面无。

**Comment by zepinglee** [comment]
> 你的意思是特意在前面加一个空格么？我看一般文档中是不加的吧，正常的英文是没有的，中文后面多出来的空主要是xecjk加入的。
> 
> 如果一定要加那么弄个短的空格（半空格），做个选项给它。分三种情况：1默认的，前面无，后面有，2前面有，后面有，3前面无，后面无。

我的意思是去掉上标式引用后面的空白。

一般写英文会在后面手动输入空格，比如 `Citation\cite{foo} test`，这样没有太大问题。但是中文的话是连续的，`xeCJK` 自动添加的空白就有些多余。所以我建议把你说的第 3 种情况设为默认的。

**Comment by hushidong** [comment]
嗯，去掉也是好的。去掉的话，biblatex这边需要对所有的引用命令加点点东西，用patch的手段似乎还不好使，稍微麻烦点，也能实现。

不过有没有可能从xecjk入手去解决呢？判断一下然后不加，这估计也麻烦。

其实最简单的方式还是写作者手动加点东西将空格去掉好了，毕竟这种情况不是很多的，只有偶尔的情况需要在句中引用的，大多数情况都是在句尾。

**Comment by hushidong** [comment]
我试了一下，目前biblatex这边还不知道怎么解决，加东西无效，不知道是展开层次不对还是怎么回事？
我想要解决这个问题，可能要了解xecjk加空格的机制？
你对它了解么？从时间看在正文中cite命令后面加mbox可以消除空格，但在cite命令的宏里面加mbox无法消除

**Comment by zepinglee** [comment]
我不太赞成手写 `引用\cite{key}\mbox{}测试`，主要是背离了格式与内容分离的原则。

另外我觉得用 xeCJK 来判断不太靠谱。对于上标式引用使用两侧紧凑的样式更合理，比如
<img width="137" alt="Screen Shot 2021-03-30 at 19 00 37" src="https://user-images.githubusercontent.com/12290822/112978804-599e6800-918a-11eb-8888-19651929308e.png">
但是像 inline numeric 或者 author-year 的情况，
<img width="135" alt="Screen Shot 2021-03-30 at 19 02 35" src="https://user-images.githubusercontent.com/12290822/112979026-a124f400-918a-11eb-9923-700b63050eb1.png">
<img width="251" alt="Screen Shot 2021-03-30 at 19 03 24" src="https://user-images.githubusercontent.com/12290822/112979033-a3874e00-918a-11eb-9be0-66181b6d06b7.png">
在两边加上一定的空白显得更为美观。如果只靠 xeCJK 来判断，它只如果找到前面上标的页码，就不知道是否应该加空白。

还有从 Nature 的文章来看，上标式引用在句中和句尾两种情况都有相当的比例，所以不宜忽略其中一种情况。
<img width="404" alt="Screen Shot 2021-03-30 at 19 07 34" src="https://user-images.githubusercontent.com/12290822/112979589-5e175080-918b-11eb-8ccd-9324e9e604ff.png">

**Comment by zepinglee** [comment]
我找了一下 natbib 中的代码，在生成上标的引用时，`\textsuperscript` 前有 `\unskip\kern\p@`。这句的效果是，即便 `\cite` 有空格或者 `\quad` 这样的命令，它也会吞掉，只空 1 pt。我试了下在 `\textsuperscipt{}` 后也加上 `\kern\p@` 能够满足要求。

biblatex 相关的代码中我没找到相关的实现部分。

感觉这个 issue 转移到 xeCJK 那边问一下更合适。

**Comment by hushidong** [comment]
你提供了一个好的思路，在`\textsuperscipt{}`加上`\kern\z@`可以解决，我之前都是在\textsuperscipt{}里面加的它，所以失效了。

限制biblatex这边可以这么处理：

重定义如下宏基本就ok了。
```
\renewrobustcmd{\mkbibsuperscript}[1]{%
  \unspace\allowhyphens\textsuperscript{%
    \begingroup
    \protected\long\def\mkbibsuperscript##1{%
      \blx@warning{Nested superscript}%
      \mkbibbrackets{##1}}%
    #1\endgroup}\kern\z@}
```

**Comment by zepinglee** [comment]
@hushidong 另外请教下 biblatex 的 `.cbx` 和 `.bbx` 内容能改到 `.cls` 模板中吗？（除了用 `filecontents`）

**Comment by hushidong** [comment]
能吧，放到biblatex之后，导言区结束之前。
