### ISSUE TITLE
《关于学位论文使用授权的说明》内容错误与格式差异

### ISSUE THREAD

**Issue by yuantailing** [tuna/thuthesis#625]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2020
模板版本：v7.2.1
模板类型：master

## 描述问题
根据《研究生学位论文写作指南》附件《03-2关于学位论文使用授权的说明（硕士）》，（1）没有“保密的论文在解密后遵守此规定”这句话，（2）数字是宋体，（3）其它排版细节差异。而模板编译的结果是 见截图

截图：
![image](https://user-images.githubusercontent.com/8487114/112468511-4dd62e80-8da3-11eb-8d65-ac186fff6874.png)

复现上述问题的代码：
```TeX
\documentclass[degree=master]{thuthesis}
\begin{document}
\copyrightpage
\end{document}
```

**Comment by zepinglee** [comment]
> （1）没有“保密的论文在解密后遵守此规定”这句话，

2020 年 10 月版时还有这句话，这个是 2020 年 12 月版去掉的。

> （2）数字是宋体，

这其实是 Word 模板不严谨，全文的正文部分都是中文部分用宋体，西文和数字用 Times New Roman。

> （3）其它排版细节差异

《指南》要求的格式中，版心宽度不是正文字号的整数倍，所以不同排版软件处理起来有所差异是正常的。

**Comment by yuantailing** [comment]
指南左右边距是 3cm，latex模板左右边距 3.2cm。每行文字数量不同可能还与这有关。

**Comment by yuantailing** [comment]
1. 边距参考：
```tex
\newcommand\thu@copyright@page@graduate{%
  \newgeometry{
    vmargin = 3.0cm,
    hmargin = 3.0cm,
  }%
  \begingroup
    \ctexset{
      chapter = {
        format     = {\centering\sffamily\erhao},
        beforeskip = 40bp,
        afterskip  = 6bp,
      },
    }%
    \thu@chapter*[]{关于学位论文使用授权的说明}%
    \thispagestyle{empty}%
  \endgroup
  \vskip 43bp%
```

2. 宋体数字宽度比 Times New Roman 宽度大，这造成有数字的行多排了一个字。所以猜测排版细节差异可能字体导致的。

**Comment by zepinglee** [comment]
> 指南左右边距是 3cm。

感谢指出！

这个是 2020 年 10 月版 Word 模板中修改的（8 月版的还是上下 3.8 cm 左右 3.2 cm）。

**Comment by zepinglee** [comment]
> 指南左右边距是 3cm，latex模板左右边距 3.2cm。每行文字数量不同可能还与这有关。

这个是在 2020 年 10 月版中修改的。8 月以以前版本的 Word 模板中左右边距 3.2 cm。

**Comment by zepinglee** [comment]
你给的参数没啥问题，我又调了下其他地方的 layout 参数，跟 Word 模板基本一致了。

<img width="713" alt="Screen Shot 2021-03-26 at 11 59 15" src="https://user-images.githubusercontent.com/12290822/112575143-b4eaf600-8e2a-11eb-80dd-4945bd6b4c1d.png">

其中红色的是 Word 模板的，青色的是 LaTeX 模板生成的，重叠在一起时就是黑色的。

[diff.pdf](https://github.com/tuna/thuthesis/files/6209288/diff.pdf)

看来 Word 不会处理左边的标点悬挂。

**Comment by zepinglee** [comment]
原来的排版的差异主要是 `xeCJK` 处理全宽括号的断行导致。默认情况下会倾向于在右括号右边断行，避免在左括号左边断行，但是用在这里就比较尴尬。我手动添加了 `\allowbreak` 和 `\nobreak` 后就一样了。

**Comment by yuantailing** [comment]
Sorry, close 错了，没等合进主分支就误 close 了。
