### ISSUE TITLE
横向排版单个图片的时候疑似还会因为间距问题出现左右不对称的情况

### ISSUE THREAD

**Issue by zepinglee** [tuna/thuthesis#627]
横向排版单个图片的时候疑似还会因为间距问题出现左右不对称的情况
```latex
\begin{sidewaysfigure}[p]
  \centering
  \includegraphics[width=\linewidth]{data/fig/vis.png}
  \caption{颜色主题的可视化}
  \label{fig:vis}
\end{sidewaysfigure}
```
![Screenshot from 2021-03-26 16-54-54](https://user-images.githubusercontent.com/5780122/112607333-0e1b4f80-8e54-11eb-9dae-1e964f4eb384.png)

_Originally posted by @shyoshyo in https://github.com/tuna/thuthesis/issues/617#issuecomment-808049684_

**Comment by zepinglee** [comment]
@shyoshyo 在 `sidewaysfigure` 环境中 `\textwidth`、`\textheight`、`\linewidth` 都会变成实际的版心上下高度（参考 <https://tex.stackexchange.com/q/272486/82731>），你在设置 `[width=\linewidth]` 时会让图片实际的上下高度跟版心对齐，但是实际的左右宽度按比例超出了版心。建议调着图片的尺寸。

至于为何左右不对称，可能需要深入研究 `rotating` 的实现。

**Comment by shyoshyo** [comment]
调整尺寸不能解决左右不对称的问题

![image](https://user-images.githubusercontent.com/5780122/113538128-035b7a00-960d-11eb-9a91-d8df9672c471.png)

```
\begin{sidewaysfigure}[p]
  \centering
  \begin{tikzpicture}
        \draw (0,0) rectangle (0.99\linewidth, 0.1in);
  \end{tikzpicture}
  \caption{颜色主题的可视化颜色主题的可视化颜色主题的可视化颜色主题的可视化颜色主题的可视化颜色主题的可视化颜色主题的可视化颜}
  \label{fig:vis}
\end{sidewaysfigure}
```

**Comment by shyoshyo** [comment]
@zepinglee 

![image](https://user-images.githubusercontent.com/5780122/113538239-4c133300-960d-11eb-8c54-6001d07763e5.png)

\begin{sidewaysfigure}[p]
  \centering
  \begin{tikzpicture}
        \draw (0,0) rectangle (0.99\linewidth, 5.2in);
  \end{tikzpicture}
  \caption{颜色主题的可视化颜色主题的可视化颜色主题的可视化颜色主题的可视化颜色主题的可视化颜色主题的可视化颜色主题的可视化颜}
  \label{fig:vis}
\end{sidewaysfigure}

当图片稍微高一点（但是不超过左右的页边距）的时候，不对称的问题更加明显，可能需要研究 rotating 是怎么处理的

**Comment by shyoshyo** [comment]
![image](https://user-images.githubusercontent.com/5780122/113538450-d65b9700-960d-11eb-85f8-77a514ecd8c3.png)

```
\begin{sidewaysfigure}[p]
  1234512345
\end{sidewaysfigure}
```

这个问题应该跟 caption 的前后间距没任何关系

**Comment by shyoshyo** [comment]
![image](https://user-images.githubusercontent.com/5780122/113539443-6995cc00-9610-11eb-86f4-3e69c2510bc2.png)

无脑 fuzz 出一种 hack 的方案

```
\begin{sidewaysfigure}[p]
  \tikz{}
  \vskip0bp
  颜色主题的可视化
\end{sidewaysfigure}
```

**Comment by shyoshyo** [comment]
![image](https://user-images.githubusercontent.com/5780122/113540281-600d6380-9612-11eb-8a28-23a4b6f805c9.png)

```
\begin{sidewaysfigure}[p]
  \tikz{}
  \vskip4bp
    \begin{tikzpicture}
        \draw (0,0) rectangle (0.99\linewidth, 5.5in);
    \end{tikzpicture}
\end{sidewaysfigure}
```

感觉还是行间距处理的问题，对于图片会多出来 4 bp，\vksip 放最下面最上面还不行，必须得放到两个东西中间

**Comment by shyoshyo** [comment]
肮脏的解决方案ggg

![image](https://user-images.githubusercontent.com/5780122/113540710-46205080-9613-11eb-8347-2dc45c7f00b1.png)


```
\begin{sidewaysfigure}[p]
  \tikz{}
  \vskip4bp
  \begin{minipage}{\linewidth}
    \centering
      \begin{tikzpicture}
            \draw (0,0) rectangle (0.99\linewidth, 5.2in);
      \end{tikzpicture}
      \caption{颜色主题的可视化颜色主题的可视化颜色主题的可视化颜色主题的可视化颜色主题的可视化颜色主题的可视化颜色主题的可视化 \label{fig:vis}}
  \end{minipage}
\end{sidewaysfigure}

```

**Comment by zepinglee** [comment]
即便用标准文档类两边也不是很对称

```latex
\documentclass{article}

\usepackage[showframe]{geometry}
\usepackage{mwe}
\usepackage{graphicx}
\usepackage{rotating}
\usepackage{tikz}


\begin{document}

\lipsum

\begin{sidewaysfigure}[p]
  \centering
  % \includegraphics[width=0.99\linewidth,height=400pt]{example-image.pdf}
  \begin{tikzpicture}
    \draw (0,0) rectangle (0.99\linewidth, 400pt);
  \end{tikzpicture}
\end{sidewaysfigure}

\lipsum

\end{document}
```

<img width="750" alt="Screen Shot 2021-04-05 at 13 44 05" src="https://user-images.githubusercontent.com/12290822/113541526-fe9ac400-9614-11eb-9b3e-f31d3b9b7359.png">

**Comment by shyoshyo** [comment]
> 即便用标准文档类两边也不是很对称
> 
> ```
> \documentclass{article}
> 
> \usepackage[showframe]{geometry}
> \usepackage{mwe}
> \usepackage{graphicx}
> \usepackage{rotating}
> \usepackage{tikz}
> 
> 
> \begin{document}
> 
> \lipsum
> 
> \begin{sidewaysfigure}[p]
>   \centering
>   % \includegraphics[width=0.99\linewidth,height=400pt]{example-image.pdf}
>   \begin{tikzpicture}
>     \draw (0,0) rectangle (0.99\linewidth, 400pt);
>   \end{tikzpicture}
> \end{sidewaysfigure}
> 
> \lipsum
> 
> \end{document}
> ```
> 
> <img alt="Screen Shot 2021-04-05 at 13 44 05" width="750" src="https://user-images.githubusercontent.com/12290822/113541526-fe9ac400-9614-11eb-9b3e-f31d3b9b7359.png">


哎，强迫症浑身难受gggg

学习了，谢谢 @zepinglee QwQ
