### ISSUE TITLE
最新模板把参考文献中页码与之前冒号间的空格去掉了？

### ISSUE THREAD

**Issue by guyonggu** [tuna/thuthesis#629]
研究生院的写作指南官网上的最新修改是：

2021年3月：
参考文献规范：在页码前的冒号和页码之间增加一个英文空格

但好像从 7.2.0 版本中把之前有的空格给去掉了，这是怎么回事？

**Comment by tuogy** [comment]
附议，新版写作指南又加了个空格。

**Comment by zepinglee** [comment]
早些版本的《指南》和 Word 模板是不带空格的，所以 v7.2.0 才去掉。刚刚发布的 2021 年 3 月版改为加空格。我今天已经收到研究生院老师的邮件通知，正在处理。
