### ISSUE TITLE
natbib后端无法正确排版online类型文献

### ISSUE THREAD

**Issue by gaotongsh** [tuna/thuthesis#630]
## 编译环境
编译的系统：Windows 10
TeX 发行版：MiKTeX
模板版本：v7.2.1
模板类型：master

## 描述问题
《研究生学位论文写作指南》第19页要求引用电子资源必须标注引用日期。而在BibTeX文件中按要求加入`urldate`项后，正文中文献编号错误，参考文献中排版也有错误（在最前面出现多余字符）。如不添加`urldate`项，排版结果正确，但不符合要求。

报错为：
>Package natbib Warning: Citation `info' on page 1 undefined on input line 5.
>(d:/Downloads\test\test.bbl [1])
>Package natbib Warning: There were undefined citations.

正文截图：
![image](https://user-images.githubusercontent.com/12027397/112997869-118a4000-91a0-11eb-9822-d5910803ec15.png)

参考文献截图：
![image](https://user-images.githubusercontent.com/12027397/112997898-1949e480-91a0-11eb-8441-8b6b40e8112d.png)

复现上述问题的代码：
```TeX
\documentclass[degree=master]{thuthesis}
\usepackage[sort]{natbib}
\bibliographystyle{thuthesis-numeric}

\begin{filecontents}{ref.bib}
@online{info,
  author = {清华大学},
  title = {清华大学信息门户},
  url = {http://info.tsinghua.edu.cn/},
  urldate = {2021-03-30}
}
\end{filecontents}

\begin{document}
abc\cite{info}
\bibliography{ref}
\end{document}
```

**Comment by gaotongsh** [comment]
经测试，改用BibLaTeX后端后可以排版成功。
解决问题的代码：
```TeX
\documentclass[degree=master]{thuthesis}
\usepackage[backend=biber,style=thuthesis-numeric]{biblatex}
\addbibresource{ref.bib}
\begin{document}
Test\cite{info}
\printbibliography
\end{document}
```
正文截图：
![image](https://user-images.githubusercontent.com/12027397/112999640-b3f6f300-91a1-11eb-8e0e-88bfff71306f.png)

参考文献截图：
![image](https://user-images.githubusercontent.com/12027397/112999662-b9ecd400-91a1-11eb-9e1c-d2aff8c35769.png)

不过我另外发现，BibLaTeX和NatBib排版参考文献的斜杠（EB/OL）居然不太一样。但这是另一个问题了。

**Comment by gaotongsh** [comment]
但是据我测试，改用BibLaTeX后端后，在Overleaf上编译论文会超时，而原有的natbib后端没问题……所以还是希望尽快修复。

**Comment by yaox12** [comment]
@gaotongsh 原因是你的bib条目里没有写`year`字段，所以会报错。加上之后就可以正常编译了。另外，按照规范，应该还需要`date`字段。

**Comment by zepinglee** [comment]
我能复现你的问题。

这主要是你的 `.bib` 中缺了 `year` 或者 `date`，但是 `natbib` 要求必须提供年份，所以我在 bst 中就根据 `urldate` 估计一个年份，所以 `.bbl` 中会有 `\bibitem[{清华大学([2021])}]{info}`。
<img width="724" alt="Screen Shot 2021-03-30 at 23 28 42" src="https://user-images.githubusercontent.com/12290822/113015028-b6604980-91af-11eb-92ae-29b1f2e0a1da.png">

不过这样写导致 LaTeX 中处理有误，应该改成 `\bibitem[清华大学({[2021]})]{info}`。稍后我修改一下 `.bst`。

**Comment by zepinglee** [comment]
> @gaotongsh 原因是你的bib条目里没有写`year`字段，所以会报错。加上之后就可以正常编译了。另外，按照规范，应该还需要`date`字段。

加 `year` 或者 `date` 都可以避免这个问题。不过国标和《指南》中的这个例子既没有 `date` 也没有 `year`。
<img width="683" alt="Screen Shot 2021-03-30 at 23 33 19" src="https://user-images.githubusercontent.com/12290822/113015845-81a0c200-91b0-11eb-930f-a47ecc0007b4.png">

许多网站也不太适合给出合适的年份和公告日期，我认为是可以省略的。

**Comment by gaotongsh** [comment]
> 许多网站也不太适合给出合适的年份和公告日期，我认为是可以省略的。

对，我也这么觉得，所以我看BibLaTeX排出来结果还挺符合要求的。

**Comment by zepinglee** [comment]
这个问题主要是跟 `bibunits`（本科生必需）同时使用时导致的，我修改了 `bst` 可以规避这个问题。

**Comment by zepinglee** [comment]
> 对，我也这么觉得，所以我看BibLaTeX排出来结果还挺符合要求的。

BibLaTeX 的方案已经经过配置，也是符合学校要求的。两种方法都可以用但略有区别，具体参考 thuthesis 的文档和 [biblatex-gb7714-2015 的文档](http://mirrors.ctan.org/macros/latex/contrib/biblatex-contrib/biblatex-gb7714-2015/biblatex-gb7714-2015.pdf)。

**Comment by zepinglee** [comment]
> 但是据我测试，改用BibLaTeX后端后，在Overleaf上编译论文会超时，而原有的natbib后端没问题……所以还是希望尽快修复。

居然能超时……我在本地用 biblatex 的时候有时也能卡个十几秒。
