### ISSUE TITLE
使用授权的说明和声明无法用扫描文件替换

### ISSUE THREAD

**Issue by zgl12** [tuna/thuthesis#633]
## 编译环境
编译的系统：Windows 10
TeX 发行版：MiKTeX 2.9.6753
模板版本：v7.2.2
模板类型：doctor

## 描述问题

在使用授权的说明和声明中，如果将签字扫描后的pdf文件替换原始页面，会出现bug，无法生成pdf文件。即使采用thuthesis7.2.2版本，仅改变如下代码的两处注释位置，依然会出现bug。

截图：
![微信图片_20210404211429](https://user-images.githubusercontent.com/43402896/113509992-001faa00-958b-11eb-884a-f548af0eb5d4.png)

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{thuthesis}
\begin{document}

% 使用授权的说明
% \copyrightpage
% 将签字扫描后授权文件 scan-copyright.pdf 替换原始页面
\copyrightpage[file=scan-copyright.pdf]

% 声明
% \statement
% 生成的声明页是否要插入页眉和页脚（默认 empty）
% 仅在需要进行电子签名时，才需要打开这一选项
% 插入的扫描声明页总是会生成页眉（研究生）和页脚，不受这一选项影响
% \statement[page-style=plain]
% 将签字扫描后的声明文件 scan-statement.pdf 替换原始页面
\statement[file=scan-statement.pdf]

\end{document}
```

**Comment by zepinglee** [comment]
需要用 `xetex thuthesis.ins` 生成新版的 `.cls` 文件。

**Comment by zgl12** [comment]
> 需要用 `xetex thuthesis.ins` 生成新版的 `.cls` 文件。

非常感谢您的回复，我一直在WIndows10系统下采用WinEdt10.3软件进行编译，以为是自动生成新版的.cls，导致没有进行编译，编译之后现在该问题已解决。
另外，我将7.2.2新版的thuthesis.dtx，thuthesis.ins，tsinghua-name-bachelor.pdf 和thuthesis-*.bst拷贝至7.1.0版本工作目录覆盖相应的文件，然后生成新的模板后，依然出现类似的问题。可能由于模板进行了重要的修改，不兼容已写好的正文内容，我将按照新模板进行调整编写。
再次感谢您的回复，感谢您对thuthesis的贡献，祝好！

**Comment by zepinglee** [comment]
> 然后生成新的模板后，依然出现类似的问题。

如果有疑问的话把报错和相关代码贴一下，从 v7.1.0 到 v7.2.2 在使用方法上应该没有太大的变化，见 <https://github.com/tuna/thuthesis/blob/master/CHANGELOG.md>。

**Comment by zgl12** [comment]
> 如果有疑问的话把报错和相关代码贴一下，从 v7.1.0 到 v7.2.2 在使用方法上应该没有太大的变化，见 https://github.com/tuna/thuthesis/blob/master/CHANGELOG.md。

您好，我发现了问题的所在，当我采用v7.2.2自带的scan-copyright.pdf和scan-statement.pdf时，可以生成文件，但是采用扫描后的pdf文件时，会出现bug。我扫描得到的pdf如附件，是一整张图片，请问对扫描得到的pdf有格式要求吗？非常抱歉给您添麻烦了！
[scan-copyright.pdf](https://github.com/tuna/thuthesis/files/6256329/scan-copyright.pdf)
[scan-statement.pdf](https://github.com/tuna/thuthesis/files/6256330/scan-statement.pdf)

**Comment by zepinglee** [comment]
我在 macOS 的 TeX Live 2021 也能复现你的问题。使用 xelatex 编译时报错是：
```
[1] [2] [3] (./data/committee.tex [4]) [5] [6]
invalid 2 0 R offset 9

invalid 3 0 R offset 991901

invalid 4 0 R offset 991998

invalid 5 0 R offset 992185

invalid 6 0 R offset 992243

invalid 7 0 R offset 992294
[1]    53992 segmentation fault  xelatex thuthesis-example.tex
```
感觉是 PDF 文件有问题。你是用什么扫描仪/软件生成的 PDF？

**Comment by zgl12** [comment]
> 感觉是 PDF 文件有问题。你是用什么扫描仪/软件生成的 PDF？

您好，我是用的惠普打印机的scanning生成的pdf，好像是因为PDF的像素太高了，我用Adobe Acrobat Pro DC将扫描文件保存为缩小大小的pdf后，即可正常运行，不会报错

**Comment by zepinglee** [comment]
> > 感觉是 PDF 文件有问题。你是用什么扫描仪/软件生成的 PDF？
> 
> 您好，我是用的惠普打印机的scanning生成的pdf，好像是因为PDF的像素太高了，我用Adobe Acrobat Pro DC将扫描文件保存为缩小大小的pdf后，即可正常运行，不会报错

你原来是用的多少 DPI？后来改成了多少？我记录一下以帮助其他有类似问题的同学

**Comment by Harry-Chen** [comment]
> > > 感觉是 PDF 文件有问题。你是用什么扫描仪/软件生成的 PDF？
> > 
> > 
> > 您好，我是用的惠普打印机的scanning生成的pdf，好像是因为PDF的像素太高了，我用Adobe Acrobat Pro DC将扫描文件保存为缩小大小的pdf后，即可正常运行，不会报错
> 
> 你原来是用的多少 DPI？后来改成了多少？我记录一下以帮助其他有类似问题的同学

测试了一下，HP m521dw 使用 HP Scan 生成的 300, 600, 1200 DPI 的 PDF 都能正常使用，怀疑不是 DPI 而是工具问题，只是因为 Acrobat 重新生成了 PDF 就好了

**Comment by zgl12** [comment]
> 你原来是用的多少 DPI？后来改成了多少？我记录一下以帮助其他有类似问题的同学

您好，原来PDF的DPI是600，后来我改成了300。另外，我测试了一下，当扫描PDF的分辨率低于或等于300时，程序都可以正常运行。非常感谢您的帮助，祝好！

**Comment by zgl12** [comment]
> 测试了一下，HP m521dw 使用 HP Scan 生成的 300, 600, 1200 DPI 的 PDF 都能正常使用，怀疑不是 DPI 而是工具问题，只是因为 Acrobat 重新生成了 PDF 就好了

您好，我用Adobe Acrobat Pro DC和Photoshop将PDF降低分辨率之后都可以正常运行。另外，插入扫描页不会自动添加页眉和页脚，使用如下代码才能正常添加页眉和页脚
% 声明
% \statement
% 生成的声明页是否要插入页眉和页脚（默认 empty）
% 仅在需要进行电子签名时，才需要打开这一选项
% 插入的扫描声明页总是会生成页眉（研究生）和页脚，不受这一选项影响
% \statement[page-style=plain]
% 将签字扫描后的声明文件 scan-statement.pdf 替换原始页面
\statement[file=scan-statement.pdf, page-style=plain]

**Comment by zepinglee** [comment]
你的用法没问题，但这里的注释忘记改了。

原来（v7.2.0 前）是本科生和研究生都默认生成时页眉页脚 empty，插入扫描页时再添回。你的声明页应该是使用这个版本生成的。

然后研究生院老师说「编译生成的声明没页眉页脚，格式不对」，我就在 v7.2.0 改成了研究生在编译生成声明时加页眉页脚，而插入扫描页时不加。省的有人不看使用说明就批判一番。

后来有人反馈这样不够灵活（<https://github.com/tuna/thuthesis/issues/574#issuecomment-798833514>），所以又改为允许研究生使用 `pagestyle` 控制页眉页脚。

**Comment by zepinglee** [comment]
> 测试了一下，HP m521dw 使用 HP Scan 生成的 300, 600, 1200 DPI 的 PDF 都能正常使用，怀疑不是 DPI 而是工具问题，只是因为 Acrobat 重新生成了 PDF 就好了

HP m521dw……

**Comment by zgl12** [comment]
> 你的用法没问题，但这里的注释忘记改了。
> 
> 原来（v7.2.0 前）是本科生和研究生都默认生成时页眉页脚 empty，插入扫描页时再添回。你的声明页应该是使用这个版本生成的。
> 
> 然后研究生院老师说「编译生成的声明没页眉页脚，格式不对」，我就在 v7.2.0 改成了研究生在编译生成声明时加页眉页脚，而插入扫描页时不加。省的有人不看使用说明就批判一番。
> 
> 后来有人反馈这样不够灵活（[#574 (comment)](https://github.com/tuna/thuthesis/issues/574#issuecomment-798833514)），所以又改为允许研究生使用 `pagestyle` 控制页眉页脚。

噢噢，原来如此，谢谢您的回复，非常感谢您对LaTex模板的贡献。祝好！
