### ISSUE TITLE
#629问题依旧没有修复

### ISSUE THREAD

**Issue by zgl12** [tuna/thuthesis#634]
## 描述问题
您好，v7.2.2版本Changelog中提到的#629问题好像依旧没有修复，参考文献的页码前和冒号之间的空格未去掉。在v7.2.2提供的thuthesis-example.pdf示例文件中也是如此，如下面截图所示。

截图：
![无标题](https://user-images.githubusercontent.com/43402896/113578262-1c881900-9655-11eb-83c1-7233eb3f014c.png)

**Comment by zepinglee** [comment]
写错了，这个空格是要加回来的。

**Comment by zepinglee** [comment]
Fixed in b4e5e7f.

**Comment by zgl12** [comment]
> 写错了，这个空格是要加回来的。

好的，非常感谢您的回复，祝好！
