### ISSUE TITLE
macOS上使用`fontset=windows`并不能正确替换所有字体

### ISSUE THREAD

**Issue by yaox12** [tuna/thuthesis#637]
## 编译环境
编译的系统：macOS 11.2.3
TeX 发行版：MacTeX 2021
模板版本：v7.2.2
模板类型：doctor

## 描述问题

我手动在macOS上安装了`SimSun`、`SimHei`、`Kaiti`、`Fangsong`、`Courier New`等字体，但由于下面这行代码

https://github.com/tuna/thuthesis/blob/614ff2caaff9e2b63b298eec306488dbcca25a26/thuthesis.dtx#L2244-L2248

在macOS上使用`fontset=windows`并不能正确替换所有字体，即`Menlo`没有被替换成`Courier`，要设置成`system=windows`才行。我觉得是不是应该改成
```tex
\ifthu@fontset@mac
```
以保证字体是由`fontset`完全控制的。

**Comment by zepinglee** [comment]
《指南》没有规定西文的等宽字体，可以使用任何字体。`fontset` 的设置主要是为了修复 `ctex` 某版本检测系统的问题，在你说的情况下确实不太符合原汁原味的 Window 字体风格。但是我很不喜欢 Courier New 的字形，所以这个不妨留作 feature。

实在有需要的话可以在导言区设置 \setmonofont{Courier New}[Scale = MatchLowercase]
