### ISSUE TITLE
关于著者-出版年制参考文献表的著者姓名与年份之间改为逗号的疑问

### ISSUE THREAD

**Issue by HaipengHan15** [tuna/thuthesis#638]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2019
模板版本：v7.2.2
模板类型：master

## 描述问题
想问下为什么7.2.2的著者-出版年制参考文献表的著者姓名与年份之间改为逗号了呢？在《学位论文写作指南》上没看到对应的要求……

**Comment by zepinglee** [comment]
1. GB/T 7714—2015 使用了逗号。
<img width="729" alt="Screen Shot 2021-04-09 at 00 12 23" src="https://user-images.githubusercontent.com/12290822/114060892-6c224b00-98c8-11eb-9791-01dd0315c676.png">

2. 2021 年 3 月版 Word 模板「10-1参考文献-著者出版年制（示例）.doc」中使用的是逗号。
<img width="677" alt="Screen Shot 2021-04-09 at 00 14 51" src="https://user-images.githubusercontent.com/12290822/114061103-a1c73400-98c8-11eb-959e-b54bc0f3a5ed.png">

3. 《指南》第 3.4.2 节有两个示例，使用的是句点。这是沿用了 GB/T 7714—2005 的样式。我注意到 Word 模板跟《指南》的差异后询问了研究生院的姚飞老师，确认了统一用逗号。《指南》的相关部分会在后续版本中修改。

**Comment by HaipengHan15** [comment]
> 1. GB/T 7714—2015 使用了逗号。
> 
> <img alt="Screen Shot 2021-04-09 at 00 12 23" width="729" src="https://user-images.githubusercontent.com/12290822/114060892-6c224b00-98c8-11eb-9791-01dd0315c676.png">
> 
> 1. 2021 年 3 月版 Word 模板「10-1参考文献-著者出版年制（示例）.doc」中使用的是逗号。
> 
> <img alt="Screen Shot 2021-04-09 at 00 14 51" width="677" src="https://user-images.githubusercontent.com/12290822/114061103-a1c73400-98c8-11eb-959e-b54bc0f3a5ed.png">
> 
> 1. 《指南》第 3.4.2 节有两个示例，使用的是句点。这是沿用了 GB/T 7714—2005 的样式。我注意到 Word 模板跟《指南》的差异后询问了研究生院的姚飞老师，确认了统一用逗号。《指南》的相关部分会在后续版本中修改。

好的明白，太厉害了谢谢您！
