### ISSUE TITLE
章级标题的间距偏小

### ISSUE THREAD

**Issue by yuantailing** [tuna/thuthesis#641]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2020
模板版本：v7.2.2
模板类型：master

## 描述问题
《研究生学位论文写作指南》第 xx 页要求 大部分章级标题段前空 24 磅，段后空 18 磅；而模板编译的结果是 段前段后间距偏小

| 页码 | 项目 | 要求 | LaTeX 模板 |
| -- | -- | -- | -- |
| 6 | 学位论文指导小组、公开评阅人和答辩委员会名单 | 段前空 24 磅，段后空 18 磅 | 间距偏小 |
| 7 | 中、英文摘要 | 同上 | 同上 |
| 7 | 目录 | 同上 | 同上 |
| 7 | 插图和附表清单 | 同上 | 同上 |
| 8 | 符号和缩略语说明 | 同上 | 同上 |
| 8 | 各章标题 | 同上 | 同上 |

声明，个人简历、在学期间完成的相关学术成果，指导教师学术评语等标题虽然在指南里没有规定间距，但是 word 模板实际采用了与上述章节相同的间距。

截图：
见 thuthesis-example.pdf

复现上述问题的代码：
```TeX
\input{thuthesis-example}
```

**Comment by yuantailing** [comment]
这导致 word 模板跟 LaTeX 模板排摘要能排的字数不一样多，可能隐式地违反了摘要长度限制。

**Comment by zepinglee** [comment]
Word 模板的设置有问题。

以「09正文 第3章（示例）.doc」为例，这主要是因为 Word 的文档设置了网格，而标题的段落属性选择单倍行距且「对齐到网格」，所以实际是按照网格排的。红色的是 Word 模板，青色的是 LaTeX 模板。

<img width="717" alt="Screen Shot 2021-04-09 at 12 49 43" src="https://user-images.githubusercontent.com/12290822/114129898-108ca780-9932-11eb-9843-5b76edede9d6.png">

但是如果去掉 Word 模板中文档属性的网格，效果是这样的。

<img width="691" alt="Screen Shot 2021-04-09 at 12 50 19" src="https://user-images.githubusercontent.com/12290822/114129947-269a6800-9932-11eb-90eb-9b8223423dc2.png">

而且 Word 模板中不同文档的网格设置还不一致。比如「09正文 第3章（示例）.doc」有网格，但「02-1-1学位论文指导小组、公开评阅人和答辩委员会名单（有指导小组，全部或部分公开评阅）.doc」无网格。实际上这两个文档的标题是没有对齐的。

<img width="697" alt="Screen Shot 2021-04-09 at 13 04 21" src="https://user-images.githubusercontent.com/12290822/114130888-1be0d280-9934-11eb-8c58-8af142b4a47a.png">

文档的网格也会影响表格的行距。

[main-grid-diff.pdf](https://github.com/tuna/thuthesis/files/6283278/main-grid-diff.pdf)
[main-no-grid-diff.pdf](https://github.com/tuna/thuthesis/files/6283280/main-no-grid-diff.pdf)
[02-09.pdf](https://github.com/tuna/thuthesis/files/6283281/02-09.pdf)
