### ISSUE TITLE
英文版格式的行间距和图表下文字字体不对

### ISSUE THREAD

**Issue by ivanloyui** [tuna/thuthesis#644]
参照了v7.2.1的英文版格式被指出
1. 段前间距、一二三级标题行间距、标题下的行间距不符
2. 图、表标题字体与正文字体(12pt)相符。按理应该小一号(11pt)
如果遇到这种问题，是否请问是否通过cls修改字体、段前段后空和固定值。

**Comment by ivanloyui** [comment]
以上问题由审查老师提出。

**Comment by zepinglee** [comment]
分别给个图例说明一下？

**Comment by ivanloyui** [comment]
> 分别给个图例说明一下？

@zepinglee 
<img width="170" alt="3" src="https://user-images.githubusercontent.com/22440907/114871374-cde43700-9e2b-11eb-848a-bbc329ad4bb9.png">

上图为表格的线粗磅问题

<img width="282" alt="2" src="https://user-images.githubusercontent.com/22440907/114871384-d0469100-9e2b-11eb-8f36-691dc37113b7.png">

上图为表格标题行间距问题



<img width="89" alt="微信截图_20210415204455" src="https://user-images.githubusercontent.com/22440907/114871378-cf156400-9e2b-11eb-99d6-1b4e4296c3bb.png">

上图为图caption字体（Scr)与正文lats字体大小一致的问题

<img width="221" alt="问题1" src="https://user-images.githubusercontent.com/22440907/114871383-cfadfa80-9e2b-11eb-8b04-d69e2702d84d.png">

上图为序号与标题间距问题

**Comment by ivanloyui** [comment]
以上均为使用英文模板写的latex文档编译的

**Comment by zepinglee** [comment]
> 以上均为使用英文模板写的latex文档编译的

1. 三线表的三条线分别用 `\toprule`、`\midrule` 和 `\bottomrule`。
2. 页面顶部的“段前”不会生成空白，可以用 Word 模板试一下加到段前 100 pt。
3. 用 Acrobat 查看一下对应的字号是多少，图表 caption 11 pt 应该没问题。
4. 这个跟研究生院提过，图序跟图题空一个 em space 就跟中文“空一字宽”一致了。看来他们没改，还是只有一个空格。我稍后修改一下模板。

**Comment by ivanloyui** [comment]
> > 以上均为使用英文模板写的latex文档编译的
> 
> 1. 三线表的三条线分别用 `\toprule`、`\midrule` 和 `\bottomrule`。
> 2. 页面顶部的“段前”不会生成空白，可以用 Word 模板试一下加到段前 100 pt。
> 3. 用 Acrobat 查看一下对应的字号是多少，图表 caption 11 pt 应该没问题。
> 4. 这个跟研究生院提过，图序跟图题空一个 em space 就跟中文“空一字宽”一致了。看来他们没改，还是只有一个空格。我稍后修改一下模板。

好的 谢谢前辈。第2.指的是我的图、表都会有段前的问题，您的意思是结合Word加到段前100pt吗。只是刚好举例的是在页面顶部，有些在正文之间的图与表貌似也存在相同的问题。

**Comment by zepinglee** [comment]
> 好的 谢谢前辈。第2.指的是我的图、表都会有段前的问题，您的意思是结合Word加到段前100pt吗。只是刚好举例的是在页面顶部，有些在正文之间的图与表貌似也存在相同的问题。

我想起来了，v7.2.2 修复了这个间距的问题，见 #614 和 #617 。

**Comment by ivanloyui** [comment]
感谢李前辈，那我先转换成7.2.2看看 非常感谢！

**Comment by zepinglee** [comment]
> 参照了v7.2.1的英文版格式被指出
> 
> 1. 段前间距、一二三级标题行间距、标题下的行间距不符
> 2. 图、表标题字体与正文字体(12pt)相符。按理应该小一号(11pt)
>    如果遇到这种问题，是否请问是否通过cls修改字体、段前段后空和固定值。

段前间距、一二三级标题行间距分别给个示例？
