### ISSUE TITLE
公式索引无法生成

### ISSUE THREAD

**Issue by philipsweng** [tuna/thuthesis#645]
## 编译环境
编译的系统：Overleaf
TeX 发行版：TeX Live 2020
模板版本：v7.2.1
模板类型：bachelor

## 描述问题
插图索引和附表索引可以正常生成，但公式索引无法生成。

截图：
![image](https://user-images.githubusercontent.com/22523444/115144055-13e40980-a07d-11eb-943d-94fb47e48f9a.png)
![image](https://user-images.githubusercontent.com/22523444/115144060-1a728100-a07d-11eb-8d8d-206d93810606.png)
![image](https://user-images.githubusercontent.com/22523444/115144064-1e9e9e80-a07d-11eb-90c6-17d97d12f385.png)
复现上述问题的代码：
```TeX
\listoffigures           % 插图清单
\listoftables            % 附表清单
\listofequations
```

**Comment by zepinglee** [comment]
本科生没有公式索引的要求。而且公式没有名称，做个索引里也没有意义。

**Comment by philipsweng** [comment]
> 本科生没有公式索引的要求。而且公式没有名称，做个索引里也没有意义。

好的，谢谢！
