### ISSUE TITLE
学术硕士封面字体问题

### ISSUE THREAD

**Issue by XuZikang** [tuna/thuthesis#647]
如题，在使用thuthesis-example.tex编译学术硕士毕业论文时，第一页和书脊页的字体与2020年的word模板字体不同。

第一页的培养单位、学科、研究生、指导教师、联合指导教师这几行和书脊页的字体均为仿宋_GB2312，而模板编译得到的字体为仿宋。

附图如下，第一张为latex编译的结果，第二张为word模板的效果：

![QQ截图20210425153343](https://user-images.githubusercontent.com/34147158/115984831-a33c7000-a5db-11eb-8798-1d3121fb0322.png)

![QQ截图20210425153403](https://user-images.githubusercontent.com/34147158/115984839-af283200-a5db-11eb-9396-f5c0068d01fb.png)

**Comment by zepinglee** [comment]
仿宋_GB2312 只覆盖了 GB 2312 字符集，如果名字带个不常见的字就会缺字形。新一些的 Windows 以及 macOS 中不提供「仿宋_GB2312」，比如你自己的系统，所以图 2 的 Word 模板效果中字体会 fallback 到等线体（黑体），并不是仿宋体。而且，「仿宋_GB2312」和（中易）仿宋的差异相当小，一般不会察觉到。所以，模板才会这样设置。

**Comment by XuZikang** [comment]
谢谢您的回复！我在自己的Windows10上安装了仿宋_GB2312后打开Word模板，确实模板字体和编译生成的pdf文档保持了一致。另外想向您确认一下书脊的字号大小是否为3号（格式审查的老师对此有些疑问），以及书脊右侧的虚线是否会影响最终效果。

**Comment by zepinglee** [comment]
> 另外想向您确认一下书脊的字号大小是否为3号（格式审查的老师对此有些疑问），以及书脊右侧的虚线是否会影响最终效果。

如果你没设置 `spine-font` 的话，默认为三号。

右侧的虚线应该没有用，所以 LaTeX 模板不会生成。

**Comment by XuZikang** [comment]
好的，谢谢您！

**Comment by XuZikang** [comment]
> > 另外想向您确认一下书脊的字号大小是否为3号（格式审查的老师对此有些疑问），以及书脊右侧的虚线是否会影响最终效果。
> 
> 如果你没设置 `spine-font` 的话，默认为三号。
> 
> 右侧的虚线应该没有用，所以 LaTeX 模板不会生成。

格式审查老师说模板的字号为小三号，与模板不符。

维护的同学可以在模板内修改一下~

我现在是在thusetup.tex文件里加上了一行，可以实现修改。

`spine-font = {\zihao{-3}},`

**Comment by zepinglee** [comment]
我刚发现博士的是三号，硕士的是小三号。我稍后在模板里改一下默认值吧。

`spine-font = {\zihao{-3}}` 是正确的设置。
