### ISSUE TITLE
appendix-survey 中修改 cite-style=inline

### ISSUE THREAD

**Issue by silentsaber** [tuna/thuthesis#648]
我在使用最新overleaf模板，写文献调研data/appendix-survey中，希望让文中的引用与文字齐平（引用角标不显示在右上角）.

我尝试用:
```
\thusetup{
  cite-style = inline,
}
```
然后通过\cite{}引用在ref/appendix.bib中的文献，发现显示为问号(?)。
但如果我将`cite-style=inline`这一句注释掉，就能够正常显示。
如图:
![image](https://user-images.githubusercontent.com/32814213/116198188-3f937d80-a768-11eb-8257-a091a348a6ff.png)
![image](https://user-images.githubusercontent.com/32814213/116198225-47532200-a768-11eb-84ee-7acacf3e9d2b.png)
其中能正常显示的文献为ref/refs中的zhangkun1994, 不能正常显示的8353828是ref/appendix中的，而该文件内只有`\bibliography{ref/appendix}`。

在latex方面我是一个新手，查阅了网上的资料，都没有找到解决办法。希望得到您们的帮助。万分感激。

**Comment by silentsaber** [comment]
设置`cite-style=inline`的方法是我根据chap04.tex中的示例实现的。
事实上用\nocite{}和单独的数字[1]、[2]，也能满足我目前的需求，但是单击数字不会跳转到参考文献处。
我想要知道是否有更好的解决方案。

**Comment by silentsaber** [comment]
似乎问了一个愚蠢的问题。
似乎可以通过修改thuthesis.cls里面的thusetup{cite-style=inline}实现

**Comment by zepinglee** [comment]
奇怪，不应该呀。你是咋改的？

**Comment by silentsaber** [comment]
> 奇怪，不应该呀。你是咋改的？

就是写附录A参考文献的时候，在appendix-survey中\maketitle之下，加的
```
\thusetup{
  cite-style = inline,
}
```
这会导致\cite{}引用ref/appendix.bib中文献时，变成问号。
删掉`cite-style=inline`就是正常的
