### ISSUE TITLE
如何同时生成中文目录和英文目录？

### ISSUE THREAD

**Issue by chenshen03** [tuna/thuthesis#650]
您好，很感谢您们的开源维护。想请问下如何同时生成中文目录和英文目录？如下所示：
![image](https://user-images.githubusercontent.com/20432947/117649001-8bf7a800-b1c1-11eb-8f93-473d5a558e48.png)
![image](https://user-images.githubusercontent.com/20432947/117648988-8732f400-b1c1-11eb-9810-0bab4f11177c.png)

**Comment by zepinglee** [comment]
比较麻烦，通常 `\chapter`、`\section` 这些命令无法填入中英文两份信息。
