### ISSUE TITLE
关于参考文献引用序号间逗号后的空格缺失问题

### ISSUE THREAD

**Issue by Zhiwen-Xiao** [tuna/thuthesis#652]
![image](https://user-images.githubusercontent.com/38645413/118134822-ec425000-b434-11eb-98b0-c0f48f480f5e.png)

学校说明文档中明显参考文献序号间逗号后有空格，而模板生成的参考文献序号间仅有逗号。

**Comment by Zhiwen-Xiao** [comment]
很感谢您们的维护，请问这个问题应当如何修改呢？

**Comment by zepinglee** [comment]
1. GB/T 7714—2015 中是没有逗号的。
<img width="726" alt="Screen Shot 2021-05-13 at 22 07 47" src="https://user-images.githubusercontent.com/12290822/118137599-f74aaf80-b437-11eb-80cc-217ab51224fc.png">

2. 国外的期刊方面，像 Nature 也是不加逗号的。
<img width="569" alt="Screen Shot 2021-05-13 at 22 10 54" src="https://user-images.githubusercontent.com/12290822/118137695-177a6e80-b438-11eb-8380-83a793a5852a.png">

我再找研究生院确认下。

**Comment by Zhiwen-Xiao** [comment]
非常感谢~

**Comment by Jiang-Cui** [comment]
请问这个问题解决了么？

**Comment by zepinglee** [comment]
研究生院的姚老师回复：引用序号的逗号与正文平排时加空格，作为上标时不加空格。
