### ISSUE TITLE
使用授权的说明无法用扫描文件替换

### ISSUE THREAD

**Issue by BlakeXiaochu** [tuna/thuthesis#653]
# 编译环境

编译的系统：Windows 10
TeX 发行版：TeX Live 2020
模板版本：v7.1.0
模板类型：master

# 描述问题
与 [issue 633](https://github.com/tuna/thuthesis/issues/633) 类似，已使用 xetex thuthesis.ins 生成新版的 .cls 文件。
在使用模板自带的scan-copyright.pdf和自己扫描得到的scan-copyright.pdf都会出现编译错误

![image](https://user-images.githubusercontent.com/14849079/118220904-45e76080-b4af-11eb-9f73-2fb9342bc425.png)

但使用模板自带的scan-statement.pdf和自己扫描得到的scan-statement.pdf则可正常编译

![image](https://user-images.githubusercontent.com/14849079/118221031-6d3e2d80-b4af-11eb-9071-36e770067915.png)

**Comment by zepinglee** [comment]
似乎是 v7.1.0 的一个 bug，建议升级到最新版。

**Comment by BlakeXiaochu** [comment]
更新至7.22版本，问题依然存在

**Comment by zepinglee** [comment]
`xetex thuthesis.ins`

v7.2.2 压根就没有 `\thu@authorization@title`

**Comment by BlakeXiaochu** [comment]
抱歉，更新时部分文件忘记替换了，问题已解决，十分感谢~
