### ISSUE TITLE
书面翻译附录原文索引无法生成（已使用Latexmk编译）

### ISSUE THREAD

**Issue by thuwzh** [tuna/thuthesis#656]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2019
模板版本：v7.2.2
模板类型：bachelor

## 描述问题
使用英文版本，附录的外文资料书面翻译部分无法生成原文索引，也无法生成附录这部分的参考文献。已使用Latexmk编译。

截图：
![图片](https://user-images.githubusercontent.com/73944210/118812813-1be3d300-b8e1-11eb-926d-b3cb026985bc.png)
![图片](https://user-images.githubusercontent.com/73944210/118812864-2736fe80-b8e1-11eb-9134-0fe5ff823d56.png)

复现上述问题的代码：
```latex
文献引用示例\cite{chen2000limit}。


% 书面翻译的参考文献
\bibliographystyle{unsrtnat}
\bibliography{ref/appendix}

% 书面翻译对应的原文索引
\begin{translation-index}
  \nocite{chen2000limit}
  \bibliographystyle{unsrtnat}
  \bibliography{ref/appendix}
\end{translation-index}
```

**Comment by zepinglee** [comment]
检查一下报错。

**Comment by thuwzh** [comment]
您好，报错显示 No file thuthesis-example-translation.bbl.和No file thuthesis-example-index.bbl.

**Comment by zepinglee** [comment]
BibTeX 的报错？

**Comment by Vopaaz** [comment]
我似乎也碰到了同样的问题，是 xelatex 的报错：

```
l.827 \begin{translation-index}

? No file main-translation.aux.

Package natbib Warning: Citation `Johnson2019' undefined
on input line 828.

No file main-translation.bbl.

! LaTeX Error: \begin{bibunit} on input line 1 ended by \end{translation-index}
.
```

**Comment by thuwzh** [comment]
> 
> 
> BibTeX 的报错？

是的

**Comment by zepinglee** [comment]
> > BibTeX 的报错？
> 
> 是的

你去找下 bibtex 的报错，这不是 bibtex 的。

另外 `chen2000limit` 是在 `ref/appendix.bib` 中吗？

**Comment by zepinglee** [comment]
> 我刚才发现前面还有另一条错误信息漏了，
> 
> ```
> ! LaTeX Error: Environment translation-index undefined.
> ```

版本问题。

**Comment by thuwzh** [comment]
还是没有解决这个问题，翻译部分我就不引用了吧，感谢作者！
