### ISSUE TITLE
newtx数学字体支持失效

### ISSUE THREAD

**Issue by expiron** [tuna/thuthesis#658]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2019
模板版本：v7.2.2
模板类型：master

## 描述问题
使用`newtxmath`数学字体编译公式出错。`newtx` 宏包版本`revision:    59238`。

截图：
```log
(c:/TeXLive/2021/texmf-dist/tex/latex/pdflscape/pdflscape.sty (c:/TeXLive/2021/texmf-dist/tex/latex/graphics/lscape.sty) (c:/TeXLive/2021/texmf-dist/tex/latex/base/atbegshi-ltx.sty)) (c:/TeXLive/2021/texmf-dist/tex/latex/newtx/ot1ntxtlf.fd
c:/TeXLive/2021/texmf-dist/tex/latex/newtx/ot1ntxtlf.fd:28: Undefined control sequence.
l.28 \ifntx@sl
               % point to real slanted fonts
No pages of output.
```

复现上述问题的代码：
```TeX
\documentclass[degree=master]{thuthesis}
% 首先加载 amsthm 以使用 newtx 字体
\usepackage{amsthm}
\thusetup{
  math-font = newtx,
}
\newcommand\dif{\mathop{}\!\mathrm{d}}  % 微分符号
\begin{document}
\mainmatter
\begin{equation}
  T_e = J \frac{\dif \omega}{\dif t} + B \omega + T
\end{equation}
\end{document}
```

**Comment by zepinglee** [comment]
似乎是刚更新的 `newtx` 导致的。

`\ifntx@sl` 的定义在 `newtxtext` 中，所以目前只能设置正文的西文字体为 `newtx`：
```latex
\thusetup{
  font = newtx,
  math-font = newtx,
}
```

**Comment by expiron** [comment]
> 
> 
> 似乎是刚更新的 `newtx` 导致的。
> 
> `\ifntx@sl` 的定义在 `newtxtext` 中，所以目前只能设置正文的西文字体为 `newtx`：
> 
> ```
> \thusetup{
>   font = newtx,
>   math-font = newtx,
> }
> ```

可是将`font`改成`newtx`后英文封面的标题和英文摘要的标题字体都不对了呀

**Comment by zepinglee** [comment]
确实，混用 Type 1 字体和 OpenType 字体很麻烦。

我晚上再研究一下。

**Comment by zepinglee** [comment]
https://github.com/sjtug/SJTUThesis/pull/570#issuecomment-845678587 指出，1.651 版已经改过来了。
