### ISSUE TITLE
本科附录外文资料书面翻译 目录部分出现未知引用编号

### ISSUE THREAD

**Issue by nhy17-thu** [tuna/thuthesis#659]
## 编译环境
编译的系统：macOS 10.14
TeX 发行版：TeX Live 2018
模板版本：v7.2.2
模板类型：bachelor

## 描述问题
使用本科毕业设计论文模版中的书面翻译模版`appendix-translation.tex`，在生成目录时出现未知编号[2]包裹整个目录部分。将`\tableofcontents`命令注释掉可使该未知编号[2]消失。

截图：
<img width="612" alt="image" src="https://user-images.githubusercontent.com/37825824/118937632-4fc20580-b980-11eb-8556-a8ab3c94decb.png">
下图是将附录中所有标题注释掉后的展示效果：
<img width="489" alt="image" src="https://user-images.githubusercontent.com/37825824/118938961-c6133780-b981-11eb-860f-a6f185b2a2d9.png">
<img width="401" alt="image" src="https://user-images.githubusercontent.com/37825824/118937999-b5ae8d00-b980-11eb-8cce-dc97541ef80f.png">

复现上述问题的代码：
```TeX
\begin{translation}
\label{cha:translation}

\title{Pixel2Mesh：从单帧RGB图片生成3D网格模型}
\maketitle

\tableofcontents

测试。
```

**Comment by zepinglee** [comment]
我在 TeX Live 2017 中可以复现，但是在 2021 中不会出现这个 bug。

具体原因我晚上再研究下。

**Comment by nhy17-thu** [comment]
> 我在 TeX Live 2017 中可以复现，但是在 2021 中不会出现这个 bug。
> 
> 具体原因我晚上再研究下。

Hi Zeping,

感谢回复！升级到Tex Live 2021以后这个问题在我的电脑上也消失了。或许可以作为一种解决方案？

**Comment by zepinglee** [comment]
这主要是因为 `titletoc` 在 `2019/07/14 v2.11.1702` 中修改了 `\printcontents` 的接口（<https://github.com/jbezos/titlesec/commit/281e238d756e0dd6751d8f87edaca3625a0b5f9d>）。

如果你的 TeX Live 2018 还在请帮我测试一下 d6f13eb 。

**Comment by nhy17-thu** [comment]
> 这主要是因为 `titletoc` 在 `2019/07/14 v2.11.1702` 中修改了 `\printcontents` 的接口（[jbezos/titlesec@281e238](https://github.com/jbezos/titlesec/commit/281e238d756e0dd6751d8f87edaca3625a0b5f9d)）。
> 
> 如果你的 TeX Live 2018 还在请帮我测试一下 [d6f13eb](https://github.com/tuna/thuthesis/commit/d6f13eb05f75278763acbba1038b3c1c3f456dd9) 。

不好意思，我之前升级到2021的时候已经把2018版删掉了😂抱歉抱歉
