### ISSUE TITLE
本科生模板 主要符号表（denotation.tex）文件的默认名称问题？

### ISSUE THREAD

**Issue by msj17thu** [tuna/thuthesis#661]
目前提供的本科生毕业论文最新模板（v7.2.2）中`denotation.tex`默认题目是**主要符号对照表**，而论文写作指南要求是**主要符号表**，请问除了直接更改`*.cls`文件，可以在`thusetup.tex`通过命令修改吗？

希望下一版更新的时候可以考虑到这个问题:grin:。

**Comment by zepinglee** [comment]
我发下这是个上古时代（v5.0 前）遗留下来的 bug。

**Comment by Harry-Chen** [comment]
六月前计划发布新版本
