### ISSUE TITLE
图片caption中添加footnote不能正常显示

### ISSUE THREAD

**Issue by QQQQQH** [tuna/thuthesis#670]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2021
模板版本：v7.2.2
模板类型：bachelor

## 描述问题
在`figure`环境中通过`\footnote`为`\caption`添加脚注，脚注没有显示在当前页的下方，而是显示在了最后插图索引页的下方，并且标号不是①而是②。
若使用`\footnotemark`与`\footnotetext`则不存在这样的问题。

截图：
![image](https://user-images.githubusercontent.com/48670154/119604938-7f5e8b00-be22-11eb-803c-3c9f426d2ce8.png)
![image](https://user-images.githubusercontent.com/48670154/119604975-900f0100-be22-11eb-8857-eed60bf51e26.png)

复现上述问题的代码：
```TeX
\begin{figure}
  \centering
  \includegraphics[width=0.6\linewidth]{sigmoid.pdf}
  \caption{Sigmoid函数图像\protect\footnote{图片摘自\url{https://en.wikipedia.org/wiki/Sigmoid_functionl}}}
  \label{fig:sigmoid}
\end{figure}
```

```TeX
\begin{figure}
  \centering
  \includegraphics[width=0.6\linewidth]{sigmoid.pdf}
  \caption{Sigmoid函数图像\protect\footnotemark[1]}
  \label{fig:sigmoid}
\end{figure}
\footnotetext[1]{图片摘自\url{https://en.wikipedia.org/wiki/Sigmoid_functionl}}
```

**Comment by Harry-Chen** [comment]
浮动环境中不能直接使用 footenote。如有需要，可以考虑使用 `threeparttable`。

**Comment by QQQQQH** [comment]
> 浮动环境中不能直接使用 footenote。如有需要，可以考虑使用 `threeparttable`。

`threeparttable`是用来处理表格的吧，请问图片的情况应该怎么处理？

**Comment by xk-huang** [comment]
使用 footnotetext footnotemark:

```
\begin{figure}[t]
    \centering
    \includegraphics[width=0.8\linewidth]{xxxx}
    \caption{Laro \protect\footnotemark}
    \label{fig:go}
\end{figure}

\footnotetext{\url{https://medium.com/}}
```
