### ISSUE TITLE
本科附录外文资料书面翻译引用呈现问号，但编译并不报错

### ISSUE THREAD

**Issue by xx-zhou16** [tuna/thuthesis#676]
## 编译环境
编译的系统： Windows 10
TeX 发行版：TeX Live 2021
模板版本：v7.2.2
模板类型：bachelor

## 描述问题
类似 #656 中的问题，但在我的环境下没有报任何error，但引用也是显示`[?]`。（而在正文的引用是可以正常显示的）
appendix-translation.tex 中的引用无法正常显示。
截图：

![image](https://user-images.githubusercontent.com/26536908/120077505-4867ce00-c0dd-11eb-9e46-66aba1081650.png)

appendix-translation.tex 中：
![image](https://user-images.githubusercontent.com/26536908/120077523-5c133480-c0dd-11eb-91c8-43185149c9fc.png)

appendix.bib中：
![image](https://user-images.githubusercontent.com/26536908/120077527-5fa6bb80-c0dd-11eb-80b0-5c240f23b3a8.png)

复现上述问题的代码：
```TeX
\section{文献引用}
 
文献引用示例\cite{abrahams99tex}。.
\cite{testzhou}。。

% 书面翻译的参考文献
\bibliographystyle{unsrtnat}
\bibliography{ref/appendix}

% 书面翻译对应的原文索引
\begin{translation-index}
  \nocite{salomon1995advanced}
  \bibliographystyle{unsrtnat}
  \bibliography{ref/appendix}
\end{translation-index}
```

**Comment by xx-zhou16** [comment]
编译用的是 `xelatex->bibtex->xelatex->xelatex`.

**Comment by zepinglee** [comment]
<img width="697" alt="Screen Shot 2021-05-30 at 00 35 45" src="https://user-images.githubusercontent.com/12290822/120077851-02ac0500-c0df-11eb-8189-63326243ee9b.png">

使用纯 `xelatex` 编译需要调用 `bibtex` 编译对应的内容，或者使用 `latexmk`。

**Comment by xx-zhou16** [comment]
> <img alt="Screen Shot 2021-05-30 at 00 35 45" width="697" src="https://user-images.githubusercontent.com/12290822/120077851-02ac0500-c0df-11eb-8189-63326243ee9b.png">
> 
> 使用纯 `xelatex` 编译需要调用 `bibtex` 编译对应的内容，或者使用 `latexmk`。

我使用的是前者，见https://github.com/tuna/thuthesis/issues/676#issuecomment-850861669。

**Comment by xx-zhou16** [comment]
我用的版本如下，正文部分的引用是可以正常显示的。
```
C:\Users\Administrator>xelatex -v
XeTeX 3.141592653-2.6-0.999993 (TeX Live 2021/W32TeX)
kpathsea version 6.3.3
Copyright 2021 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 68.2; using 68.2
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.10.4; using 2.10.4
Compiled with Graphite2 version 1.3.14; using 1.3.14
Compiled with HarfBuzz version 2.7.4; using 2.7.4
Compiled with libpng version 1.6.37; using 1.6.37
Compiled with pplib version v2.05 less toxic i hope
Compiled with fontconfig version 2.13.93; using 2.13.93

C:\Users\Administrator>bibtex -v
BibTeX 0.99d (TeX Live 2021/W32TeX)
kpathsea version 6.3.3
Copyright 2021 Oren Patashnik.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the BibTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the BibTeX source.
Primary author of BibTeX: Oren Patashnik.
```

**Comment by zepinglee** [comment]
> 我使用的是前者 `xelatex->bibtex->xelatex->xelatex`。

那你需要用 bibtex 编译 `bibtex thuthesis-example-translation.aux` 和 `thuthesis-example-index.aux`。这才是完整的编译流程：
<img width="654" alt="Screen Shot 2021-05-30 at 00 44 48" src="https://user-images.githubusercontent.com/12290822/120078083-46ebd500-c0e0-11eb-8908-448e2ca9b25e.png">

当然，最推荐使用 `latexmk`。

**Comment by zepinglee** [comment]
具体地说，这几部分独立的参考文献是用了 `bibunits` 的功能，所以必须用 bibtex 单独编译。

**Comment by xx-zhou16** [comment]
> 具体地说，这几部分独立的参考文献是用了 `bibunits` 的功能，所以必须用 bibtex 单独编译。

感谢，尝试手动编译 所有相关 `*.aux` 之后，是可以的。   
此外，还想请教一下：
我之前使用的是 VSCode 的 latex workshop 插件，
我的相关setting是
```
    "latex-workshop.latex.tools": [
        {
            "name": "xelatex",
            "command": "xelatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdf",
                "%DOCFILE%"
            ]
        },
        {
            "name": "pdflatex",
            "command": "pdflatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOCFILE%"
            ]
        },
        {
            "name": "bibtex",
            "command": "bibtex",
            "args": [
                "%DOCFILE%"
            ]
        },
        {
            "name": "latexmk",
            "command": "latexmk",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdf",
                "%DOCFILE%"
            ]
        }
    ],
    "latex-workshop.latex.recipes": [
        {
            "name": "xe->bib->xe->xe",
            "tools": [
                "xelatex",
                "bibtex",
                "xelatex",
                "xelatex"
            ]
        },
        {
            "name": "xelatex",
            "tools": [
                "xelatex"
            ],
        },
        {
            "name": "pdflatex",
            "tools": [
                "pdflatex"
            ]
        },
        {
            "name": "pdf->bib->pdf->pdf",
            "tools": [
                "pdflatex",
                "bibtex",
                "pdflatex",
                "pdflatex"
            ]
        },
        {
            "name": "LaTeXmk",
            "tools": [
                "latexmk"
            ]
        }
    ],
```
我这样的设置下存在两个问题：
- 使用配置里的`xe->bib->xe->xe` 在无`appendix-translation.tex`时，是完全正常的，但这样应该是没有执行`bibtex thutesis-example-translation.aux`，所以会导致我上面的问题，所以，有什么办法修改一下setting，让插件可以自动 `bibtex *.aux`吗？ 
- 我试了`latexmk`，如果按照插件setting里的配置，我自动编译，有一堆error，这个该怎么解决呢？

**Comment by xx-zhou16** [comment]
接 https://github.com/tuna/thuthesis/issues/676#issuecomment-850864639
然而我直接命令行执行 `latexmk thuthesis-example.tex` 之后一切正常，但是用插件就不可。

**Comment by zepinglee** [comment]
> * 使用配置里的`xe->bib->xe->xe` 在无`appendix-translation.tex`时，是完全正常的，但这样应该是没有执行`bibtex thutesis-example-translation.aux`，所以会导致我上面的问题，所以，有什么办法修改一下setting，让插件可以自动 `bibtex *.aux`吗？

我还没试过配置这样的，主要是因为不能根据是否调用 `translation` 环境自动选择是否进行 bibtex 的编译。比如没有用 `translation` 环境的情况，这样配置必须要过一遍 `bibtex thuthesis-example-translation.aux` 就会报错。目前 https://github.com/tuna/thuthesis/blob/master/.vscode/settings.json 中是基于 `latexmk` 配置的。

> * 我试了`latexmk`，如果按照插件setting里的配置，我自动编译，有一堆error，这个该怎么解决呢？

你试下 `f412e57`？我这边用 `latex-workshop` 和 `latexmk for thuthesis`  的 recipe 并没有报错，

**Comment by xx-zhou16** [comment]
@zepinglee  
sorry, 我一开始用的是released zip， 没有用git，那个里面没有official的 vscode latex-workshop setting，我才看到。
我刚刚试了一下official setting，是没问题的。感谢！

**Comment by zepinglee** [comment]
@Harry-Chen 要不要把 `.vscode` 加进 release 版本？这样会不会给人一种钦定的感觉？
