### ISSUE TITLE
外文资料的书面翻译 中  摘要部分 如何取消显示“关键词”

### ISSUE THREAD

**Issue by xx-zhou16** [tuna/thuthesis#677]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2021
模板版本：v7.7.2
模板类型：bachelor

## 描述问题

在本科生论文 附录中的
外文资料的书面翻译 
中 的 摘要部分，会有“关键词”显示，
但有些情况在这里并不需要 “关键词” （一些原文本身没有keywords）

截图：
![image](https://user-images.githubusercontent.com/26536908/120109058-61828480-c19a-11eb-94cb-9cc305f6442c.png)

复现上述问题的代码：
```TeX
\title{一个题目}
\maketitle

\tableofcontents

\begin{abstract}
    一些摘要内容。
\end{abstract}
```

**Comment by zepinglee** [comment]
摘要有必要翻译吗？

我没设计 `survey`/`translation` 环境的 `abstract`，所以还是正文的中文摘要格式。

**Comment by xx-zhou16** [comment]
😅 我也不知道需不需要翻译……
有没有简便的方法可以去掉这个关键词这行的

**Comment by zepinglee** [comment]
我稍后在模板中修改一下吧。

这里 `abstract` 的标题也需要改为 section 标题。
