### ISSUE TITLE
本科生论文数学公式编号格式

### ISSUE THREAD

**Issue by xx-zhou16** [tuna/thuthesis#683]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2021
模板版本：v7.7.2
模板类型：bachelor

## 描述问题
根据《本科综合论文训练论文写作指南》中第4页
> 公式：公式的编号写在括号内，置于公式行末，其间不加虚线。如：（1-2）。

导师说要严格按照这个指南，公式必须要有 **编号**，且要写成 `(1-2)` 而不是 `(1.2)`。
紧急求助 😢 。请问怎么改一下比较快。

截图
![image](https://user-images.githubusercontent.com/26536908/121059877-8b6c2480-c7f4-11eb-9a0e-12d4aea57168.png)

复现上述问题的代码：
```TeX
\begin{align}
a & = b + c + d + e \\
& = f + g
\end{align}
```

**Comment by zepinglee** [comment]
`\begin{document}` 处：
```latex
\thusetup{
  equation-number-separator = {-},
}
```

`\appendix` 处：
```latex
\thusetup{
  figure-number-separator = {-},
  table-number-separator = {-},
}
```

**Comment by zepinglee** [comment]
我提议把本科生的默认改成这样，虽然很蠢但不会有问题。

**Comment by xx-zhou16** [comment]
感谢!

**Comment by zepinglee** [comment]
@Harry-Chen 的意见？

**Comment by Harry-Chen** [comment]
> @Harry-Chen 的意见？

在有更多报告前，我持反对意见，因为文档里告知了修改方法。

**Comment by zepinglee** [comment]
那就再收集一些反馈信息。如果有审查老师提出再考虑更改默认的 number-separator。
