### ISSUE TITLE
打印版和电子版排版有略微差别

### ISSUE THREAD

**Issue by Zhikaiiii** [tuna/thuthesis#684]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2020
模板版本：v7.2.3
模板类型：bachelor

## 描述问题
打印版和电子版排版有略微差别

截图：
电子版：
[
![1](https://user-images.githubusercontent.com/55917203/121630009-eaf55900-caae-11eb-90e6-70db1608d2ae.PNG)
](url)

打印版：
![2](https://user-images.githubusercontent.com/55917203/121630023-f3e62a80-caae-11eb-9beb-50c14deb9c59.PNG)

此外，打印版里面空白页是会占页码的嘛？

**Comment by Harry-Chen** [comment]
本科生要求打印时引入装订距离。此外打印版本所有章节应该右起。

**Comment by zepinglee** [comment]
<img width="622" alt="Screen Shot 2021-06-11 at 14 38 09" src="https://user-images.githubusercontent.com/12290822/121642100-a5428b80-cac2-11eb-84c6-b4d8f34a6463.png">
本科生要求左侧给装订线多留 0.2 cm，但是电子版本质上是单面的，应去掉装订线的距离，所以跟打印版相比版心宽度不一样。见 #553 的讨论。

空白页会占页码，这是排版习惯。

**Comment by Zhikaiiii** [comment]
谢谢解答: )
