### ISSUE TITLE
是否能够更改章节标题（chapter）与页眉之间的距离

### ISSUE THREAD

**Issue by lrq99** [tuna/thuthesis#687]
章节标题和页眉之间的距离较大，我试过编辑.cls文件中chapter属性的beforeskip，但是好像并没有效果。

**Comment by zepinglee** [comment]
> 章节标题和页眉之间的距离较大

那里较大？给个示例？

**Comment by Gaviiin-W** [comment]
> > 章节标题和页眉之间的距离较大
> 
> 哪里较大？给个示例？

**lrq1999**应该指的是每一章chapter与页眉的距离，如下：
![image](https://user-images.githubusercontent.com/80686289/167263666-cd6b031b-3ea8-4cbe-8001-01d5434fa05e.png)
次标题的距离就是正常的，如下：
![image](https://user-images.githubusercontent.com/80686289/167263700-2bb1af97-b677-40d7-bf41-aa4f3a3d49c2.png)
这是我的相关边距设置：
      top            = 2.5cm,
      headheight = 1.9cm,
      headsep    = 0.5cm,

**Comment by Gaviiin-W** [comment]
有一种方法：将
https://github.com/tuna/thuthesis/blob/4344d676c6597da555820633ae6a3f76949c58a5/thuthesis.dtx#L3686
改成：
        format     = \vskip -0.9cm \centering\sffamily\fontsize{15bp}{20bp}\selectfont,
效果如下：
![image](https://user-images.githubusercontent.com/80686289/167264348-7dc99c1b-1605-40e7-bf88-fe40623164db.png)
不知道有没有其他方法，也不清楚我这样改会不会有某些蝴蝶效应😅
