### ISSUE TITLE
设置 copyrightpage 以后 tikz external 的 pdf 中会带有 copyrightpage 的背景

### ISSUE THREAD

**Issue by jiegec** [tuna/thuthesis#693]
## 编译环境
编译的系统：macOS 10.14
TeX 发行版：MiKTeX 21.2
模板版本：v7.2.2
模板类型：bachelor

## 描述问题

设置了 \copyrightpage 为 授权文件后，tikz external 生成的 thesis-figure%d.pdf 中可以看到授权文件作为背景，tikz 画图内容作为前景。

复现上述问题的代码：

```TeX
\copyrightpage[file=scan-copyright.pdf]
\usepackage{tikz}
\usetikzlibrary{external}
\tikzexternalize
```

**Comment by zepinglee** [comment]
给个完整的示例？我没用过 `tikz`。

**Comment by jiegec** [comment]
见 https://github.com/jiegec/thuthesis/blob/master/thuthesis-example-figure0.pdf

**Comment by zepinglee** [comment]
我可以复现了。

```latex
\documentclass[degree=bachelor]{thuthesis}

\usepackage{tikz}
\usetikzlibrary{external}
\tikzexternalize

\begin{document}

\copyrightpage[file=figures/scan-copyright.pdf]

\begin{figure}[htbp]
  \centering
  \begin{tikzpicture}
      \draw[step=1cm,gray,very thin] (0,0) grid (10,10);
  \end{tikzpicture}
\end{figure}

\end{document}
```

**Comment by zepinglee** [comment]
感觉是 `tikz`/`pdfpages` 的 bug，因为用标准文档类也能复现。
```latex
\documentclass{article}

\usepackage{pdfpages}
\usepackage{tikz}
\usetikzlibrary{external}
\tikzexternalize

\begin{document}

\includepdf{example-image-a4.pdf}

\begin{figure}[htbp]
  \centering
  \begin{tikzpicture}
      \draw[step=1cm,gray,very thin] (0,0) grid (10,10);
  \end{tikzpicture}
\end{figure}

\end{document}
```

不用 `pdfpages`：
<img width="485" alt="Screen Shot 2021-07-10 at 19 09 27" src="https://user-images.githubusercontent.com/12290822/125161052-a266b380-e1b2-11eb-83f0-4f999b1529fd.png">

使用 `pdfpages`：
<img width="482" alt="Screen Shot 2021-07-10 at 19 09 53" src="https://user-images.githubusercontent.com/12290822/125161062-adb9df00-e1b2-11eb-907e-c5e387babd41.png">

**Comment by zepinglee** [comment]
这个是 `tikz` 的兼容性问题，见文档「52.8.2 Compatibility With Other Libraries or Packages」：
<img width="732" alt="Screen Shot 2021-07-11 at 11 04 09" src="https://user-images.githubusercontent.com/12290822/125181478-b99bb480-e237-11eb-91f8-6569faa8c623.png">
这里给的解决方案有些奇怪，可以修改为：
```latex
\tikzifexternalizing{%
  \renewcommand*\includepdf[2][]{}
}{}%
```
我打算把这部分添加到模板中（ 1e26b19 ），目前可以修复 f1b0286 的示例（ 688c8d2 ），需要再测试下有没有别的问题。

另外一种解决办法参考 <https://github.com/pgf-tikz/pgf/issues/78> 或 <https://tex.stackexchange.com/a/160670/82731> 设置 `external/optimize command away`：
```latex
\tikzexternalize[optimize command away=\includepdf]
```
