### ISSUE TITLE
外文书的中文译本

### ISSUE THREAD

**Issue by jwen15** [tuna/thuthesis#695]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2021
模板版本：v7.2.3
模板类型：doctor

## 描述问题
请问，外文书的中文译本，如果想放到参考文献中，在 .bib 里该怎么写啊？

**Comment by zepinglee** [comment]
https://github.com/tuna/thuthesis/blob/1288c42a77c6d66e99c6e965948e38eeeeb531e5/ref/refs.bib#L158-L168

**Comment by jwen15** [comment]
对不起，瞎了，竟然没看到……
非常感谢！
