### ISSUE TITLE
问题：\item编号如何重新从1开始？

### ISSUE THREAD

**Issue by hotjunfeng** [tuna/thuthesis#698]
## 编译环境
编译的系统：Windows 10 
TeX 发行版：MiKTeX 20.12
模板版本：v7.2.3
模板类型：doctor

## 描述问题
在《个人简历、在学期间完成的相关学术成果》章节中，我想在原有的两个section后面添加一个名为“参与项目”的新section，我发现在这个新section中使用\item生成的编号仍然延续了上个section中\item的编号，而我想让这个新section中的\item重新从1开始编号，请问如何实现？感谢！

**Comment by zepinglee** [comment]
研究生院的示例是连续啊编号的，建议不要改。

**Comment by hotjunfeng** [comment]
@zepinglee  没错，示例中的编号都在“在学期间完成的相关学术成果”这同一个section，连续编号很合理。而我想添加一个新的自定义section，用来列一些我在读研期间参与的项目，我觉得还是重新编号比较合适，毕竟在里面罗列的内容和学术成果不是一类，如果连续编号感觉不太对。请问可以实现重新从1开始编号吗？感谢！

**Comment by dawnlh** [comment]
@hotjunfeng 请问你最后解决了吗？面临同样的问题~
