### ISSUE TITLE
请问musiq的代码什么时候开源

### ISSUE THREAD

**Issue by upupbo** [tuna/thuthesis#699]
## 编译环境
编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
模板版本：v5.5.2
模板类型：doctor / master / bachelor

## 描述问题
《研究生学位论文写作指南》第 xx 页要求……而模板编译的结果是……

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{thuthesis}
\begin{document}
abc
\end{document}
```

**Comment by Harry-Chen** [comment]
您所述的问题与本模板没有关系。

**Comment by upupbo** [comment]
请问musiq什么时候开源，谢谢前辈



---原始邮件---
发件人: "Shengqi ***@***.***&gt;
发送时间: 2021年9月14日(周二) 上午10:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tuna/thuthesis] 请问musiq的代码什么时候开源 (#699)




 
您所述的问题与本模板没有关系。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
