### ISSUE TITLE
博士开题报告-目录页

### ISSUE THREAD

**Issue by tenplus15** [tuna/thuthesis#700]
## 编译环境
编译的系统：Windows 10
TeX 发行版：VS code
模板版本：v7.2.3
模板类型：doctor  开题报告

## 描述问题
目录页：除了第1章，第2章外，还会生成单独的一条“目录......I”（图中红框处）。
请问这一条能否手动配置取消？

截图：

![目录](https://user-images.githubusercontent.com/81611501/134796174-e203a74f-2608-4f56-a015-28c0fcf4845b.png)

**Comment by Harry-Chen** [comment]
这是博士论文的写作指南中要求的。

**Comment by zepinglee** [comment]
这是研究生院的《研究生学位论文写作指南》要求的格式，建议开题报告跟学位论文格式保持一致。
