### ISSUE TITLE
使用docker 编译文档会报错

### ISSUE THREAD

**Issue by liziwl** [tuna/thuthesis#705]
## 编译环境
编译的系统：Docker
TeX 发行版：TeX Live 2021
模板版本：最新
模板类型：样例

复现步骤
```bash
docker pull texlive/texlive:latest
docker run -it texlive/texlive:latest /bin/bash
git clone https://github.com/tuna/thuthesis.git --depth=4
cd thuthesis
make doc
```

错误信息
```
/usr/local/texlive/2021/texmf-dist/tex/latex/amsfonts/amssymb.sty:240: LaTeX Er
ror: Command `\eth' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.240 ...ol{\eth}            {\mathord}{AMSb}{"67}

No pages of output.
Transcript written on thuthesis.log.
Latexmk: Examining 'thuthesis.log'
```

另 make thesis 正常，不报错。

**Comment by liziwl** [comment]
刚又测试了下 latest 也就是2021不可以编译doc，2020的docker镜像可以。

**Comment by zepinglee** [comment]
大概是 markdown 调用了 amssymb 跟 unicode-math 冲突

**Comment by liziwl** [comment]
plain这个参数如果使用老版本的markdown包会出未定义的错误，需要提示更新。

另外使用plain，无序列表每个项前面的圆点会丢失。

**Comment by liziwl** [comment]
致谢后，丢失了名为“changelog”的章节标题。

![image](https://user-images.githubusercontent.com/23000702/142005105-6c394173-54d1-45f1-a0c4-33a115be8769.png)

**Comment by zepinglee** [comment]
感谢指出！我再想想办法。

这个 `markdown` 包真的坑。

**Comment by liziwl** [comment]
> 感谢指出！我再想想办法。
> 
> 这个 `markdown` 包真的坑。

感觉 `markdown` 更新好勤快，不知道能不能提 issue 要他们改兼容性。

**Comment by liziwl** [comment]
只有下面这3个变量冲突，一个不太好的解决方案直接取消定义，但是不知道会不会引入其他问题。

```latex
\let\eth\undefined
\let\digamma\undefined
\let\backepsilon\undefined
\RequirePackage[tightLists=false]{markdown}
```

**Comment by zepinglee** [comment]
> 感觉 `markdown` 更新好勤快，不知道能不能提 issue 要他们改兼容性。先发了一个issue [Witiko/markdown#110](https://github.com/Witiko/markdown/issues/110) 看看他们有没有解决方案。

@liziwl 感谢！


> 只有下面这3个变量冲突，一个不太好的解决方案直接取消定义，但是不知道会不会引入其他问题。

另一种方法是，假装已经载入 `amssymb`。

```latex
\expandafter\def\csname ver@amssymb.sty\endcsname{0000/00/00}
\RequirePackage[tightLists=false]{markdown}
\expandafter\let\csname ver@amssymb.sty\endcsname\relax
```

**Comment by liziwl** [comment]
要是采用开发者的建议用 plain 就更麻烦了。设定为 `\RequirePackage[plain]{markdown} `，然后自己定义 renderer（或者从宏包里抄默认 renderer 定义出来）粗看至少有 tightLists，headings，bullet List，emphasis 需要重新定义。

**Comment by zepinglee** [comment]
> 要是采用开发者的建议用 plain 就更麻烦了。设定为 `\RequirePackage[plain]{markdown}`，然后自己定义 renderer（或者从宏包里抄默认 renderer 定义出来）粗看至少有 tightLists，headings，bullet List，emphasis 需要重新定义。

@liziwl 那个 issue 已经添加到 2.13.0 的 milestone，静待更新就好了。

**Comment by zepinglee** [comment]
估计 `markdown` v2.13.0 要更好久，先改成这样了。

https://github.com/tuna/thuthesis/blob/62bcc9409ae221d10d420e293e057aa177321edc/thuthesis.dtx#L6576-L6580
