### ISSUE TITLE
使用autonum与algorithm中的align环境时无法编译

### ISSUE THREAD

**Issue by jiaqi61** [tuna/thuthesis#707]
## 编译环境
编译的系统：Windows 10 / Overleaf
TeX 发行版：MiKTeX 2.9.6753 / TexLive 2019
模板版本：v7.2.3
模板类型：doctor

## 描述问题
autonum包可自动让只被引用过的公式有编号。使用autonum包和algorithm包时，如果在algorithm环境中加入多行公式环境，则无法编译。

以上现象在其它模板中不存在，如IEEE论文模板。

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{thuthesis}

\usepackage{algorithm}
\usepackage{autonum}

\begin{document}

\chapter{1}\label{ch3}
\section{a}\label{sec1}

\begin{algorithm}
\caption{这是一个算法}\label{alg}
\begin{align}
    1=2\\
    2=a
\end{align}
\end{algorithm}

\section{b}
\label{sec2}

\end{document}
```
上述代码无法编译通过，但注释掉
\usepackage{autonum}
或者
\label{sec2}
或者
\begin{align}
    1=2\\
    2=a
\end{align}
后便可正常编译

**Comment by zepinglee** [comment]
应该是 `autonum` 跟 `caption` 冲突。我是了一下 <https://tex.stackexchange.com/q/158579/82731> 的方法，但还是不 work。感觉有点复杂。

**Comment by jiaqi61** [comment]
> 应该是 `autonum` 跟 `caption` 冲突。我是了一下 https://tex.stackexchange.com/q/158579/82731 的方法，但还是不 work。感觉有点复杂。

感觉挺复杂的，不知道为啥注释其中之一就行了。有啥解决办法吗，自动编号还挺实用的。

**Comment by zepinglee** [comment]
`caption` 包是用来设置图表标题格式的，不太方便去掉。你可以去问问 `caption` 的作者 <https://gitlab.com/axelsommerfeldt/caption/-/issues>。否则就只能去掉 `autonum` 了。
