### ISSUE TITLE
Mac下采用MacTeX 2021编译出问题

### ISSUE THREAD

**Issue by hiyyg** [tuna/thuthesis#709]
## 编译环境
编译的系统：macOS 11.6
TeX 发行版：MacTeX 2021
模板版本：v7.2.3
模板类型：doctor

## 描述问题
编译完成后出现以下error
```
Missing { inserted. \chapter{引言}
Missing } inserted. \chapter{引言}
Missing { inserted. \statement[file=data/statement-scan.pdf]
Missing number, treated as zero. \statement[file=data/statement-scan.pdf]
Illegal unit of measure (pt inserted). \statement[file=data/statement-scan.pdf]
Missing } inserted. \statement[file=data/statement-scan.pdf]
Missing { inserted. \chapter{指导教师学术评语}
Missing } inserted. \chapter{指导教师学术评语}
```
导致结果第一章上面多了一行章的标题文本
截图：
![image](https://user-images.githubusercontent.com/62354758/141675003-d4918032-c705-4f12-8988-0f462fd0e9f5.png)

在overleaf中编译没有问题。

**Comment by hiyyg** [comment]
重新安装MacTeX 2019再编译就没问题了，可能目前对2021的支持还有bug

**Comment by xueruini** [comment]
我这里正常

```
❯ brew info mactex
mactex: 2021.0328
https://www.tug.org/mactex/
/usr/local/Caskroom/mactex/2021.0328 (4.4GB)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/mactex.rb
==> Name
MacTeX
==> Description
Full TeX Live distribution with GUI applications
==> Artifacts
mactex-20210328.pkg (Pkg)
==> Caveats
You must restart your terminal window for the installation of MacTex CLI tools to take effect.
Alternatively, Bash and Zsh users can run the command:

  eval "$(/usr/libexec/path_helper)"
```

<img width="532" alt="截屏2021-11-15 15 49 04" src="https://user-images.githubusercontent.com/1863/141742376-318c3f65-c131-414c-a184-4c6d5adce82c.png">

**Comment by hiyyg** [comment]
@xueruini 我这里测试了github的样例也确实能编译，但是我自己的就有bug（mac和ubuntu的2021都有，overleaf没有）。
mac和ubuntu现在都降到2019了，编译正常。
可能是我用的包跟哪里有冲突。

**Comment by hiyyg** [comment]
通过一行行注释，发现是导入了这个`extramarks`包，去掉就可以了。
但是很奇怪overleaf上是没问题的。

**Comment by zepinglee** [comment]
应该是额外引入的宏包的问题。Overleaf 上可使用最新发型版是 TeX Live 2020。

**Comment by hiyyg** [comment]
@zepinglee 看了下overleaf的设置，确实用的是2020, 2021可能也是有这问题
