### ISSUE TITLE
使用fontset=windows的时候Overleaf compilation timedout

### ISSUE THREAD

**Issue by DarkestNumb** [tuna/thuthesis#715]
## 编译环境
编译的系统：Overleaf
TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
模板版本：v5.5.2
模板类型：master 

## 描述问题
使用fontset=windows的时候Overleaf compilation timedout. 不使用的时候没事。 

截图：
![image](https://user-images.githubusercontent.com/46142965/144913314-8048e9e5-d7e8-4f29-80bc-28050a2a3e38.png)

\documentclass[degree=master,language = english,  thesis-type = proposal, **fontset=windows**]{thuthesis}
  % 学位 degree:
  %   doctor | master | bachelor | postdoc
  % 学位类型 degree-type:
  %   academic（默认）| professional
  % 语言 language
  %  chinese（默认）| english
  % 字体库 fontset
  %   windows | mac | fandol | ubuntu
  % 建议终版使用 Windows 平台的字体编译

**Comment by zepinglee** [comment]
Overleaf 上没有 Windows 平台的字库

**Comment by Harry-Chen** [comment]
如不方便在本地安装，可以使用 <https://overleaf.tsinghua.edu.cn/>
