### ISSUE TITLE
使用note的时候在参考文献里不出现

### ISSUE THREAD

**Issue by DarkestNumb** [tuna/thuthesis#719]
## 编译环境
编译的系统：Overleaf
模板版本：v5.5.2
模板类型：master
## 描述问题
《研究生学位论文写作指南》第 xx 页要求……而模板编译的结果是……

截图：
![image](https://user-images.githubusercontent.com/46142965/147628990-28996d96-1cd5-42d5-bc00-1009596720cd.png)

复现上述问题的代码：
@article{zhangkun1994,
  author     = {张昆 and 冯立群 and 余昌钰 and others},
  title      = {机器人柔性手腕的球面齿轮设计研究},
  journal    = {清华大学学报: 自然科学版},
  volume     = {34},
  number     = {2},
  pages      = {1--7},
  year       = {1994},
  key        = {zhang1 kun1},
  **note       = {Problem Here!}**
}

**Comment by zepinglee** [comment]
使用最新的模板？
