### ISSUE TITLE
请问在清华的这个模板下怎么从tex和pdf转成word呢

### ISSUE THREAD

**Issue by August0424** [tuna/thuthesis#720]
使用清华的模板把tex和pdf都弄好了，包括相关的图表、公式等。请问怎么无损转化为word呢？请大佬指教！

**Comment by Harry-Chen** [comment]
很抱歉，thuthesis 不提供此类支持，通常 PDF 也不能 **无损** 转化为 Word。

**Comment by August0424** [comment]
> 很抱歉，thuthesis 不提供此类支持，通常 PDF 也不能 **无损** 转化为 Word。

请问有推荐的方法吗？清华这边毕业论文最后不需要用到word吗

**Comment by Harry-Chen** [comment]
不需要，在官方的任何系统中都仅需提交 PDF 即可。

**Comment by August0424** [comment]
> 不需要，在官方的任何系统中都仅需提交 PDF 即可。

好的，感谢您的解答！

**Comment by zepinglee** [comment]
> 使用清华的模板把tex和pdf都弄好了，包括相关的图表、公式等。请问怎么无损转化为word呢？请大佬指教！

Adobe Acrobat 和 Microsoft Word 都可以将 .pdf 转为 .docx，不过对于 latex 编译的 pdf 或多或少都会有些问题，尤其是表格部分。

> 请问有推荐的方法吗？清华这边毕业论文最后不需要用到word吗

不需要，只有少数老板要求学生转成 Word 文档发给他们修改。

**Comment by August0424** [comment]
> 

非常感谢！

**Comment by August0424** [comment]
> > 使用清华的模板把tex和pdf都弄好了，包括相关的图表、公式等。请问怎么无损转化为word呢？请大佬指教！
> 
> Adobe Acrobat 和 Microsoft Word 都可以将 .pdf 转为 .docx，不过对于 latex 编译的 pdf 或多或少都会有些问题，尤其是表格部分。
> 
> > 请问有推荐的方法吗？清华这边毕业论文最后不需要用到word吗
> 
> 不需要，只有少数老板要求学生转成 Word 文档发给他们修改。

非常感谢！
