### ISSUE TITLE
amsmath中的 \underbrace 显示错误

### ISSUE THREAD

**Issue by hdchieh** [tuna/thuthesis#722]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2021
模板版本：v7.2.3
模板类型：master

## 描述问题
\underbrace 显示错误

截图：
![image](https://user-images.githubusercontent.com/33096672/149857486-b128cd05-f445-45d0-939a-16d03e86dd10.png)
期望结果：
![image](https://user-images.githubusercontent.com/33096672/149857675-749247ec-c0a2-4e15-a996-750d7af792eb.png)

复现上述问题的代码：
```TeX
\begin{align}
    {a}_{i, j}^{\mathrm{rel}} &=\underbrace{{E}_{x_{i}}^{\top} {W}_{q}^{\top} {W}_{k, E} {E}_{x_{j}}}_{(a)}+\underbrace{{E}_{x_{i}}^{\top} {W}_{q}^{\top} {W}_{k, R} {R}_{i-j}}_{(b)} \nonumber\\
    &+\underbrace{u^{\top} {W}_{k, E} {E}_{x_{j}}}_{(c)}+\underbrace{v^{\top} {W}_{k, R} {R}_{i-j}}_{(d)}\text{,} 
\end{align}
```

**Comment by hdchieh** [comment]
Using \overbracket and \underbracket from  `mathtools' package. 显示正常，但形态为下中括号。
```Latex
\begin{align}
    \underbracket{a+b}_{c}
\end{align}
```

![image](https://user-images.githubusercontent.com/33096672/149859440-1e6c1774-e611-4956-8380-85c04eab83ef.png)

**Comment by zepinglee** [comment]
我无法复现这个问题，建议把导言区相关的配置贴一下。
```latex
\documentclass{thuthesis}
\begin{document}
\begin{align}
  {a}_{i, j}^{\mathrm{rel}} &=\underbrace{{E}_{x_{i}}^{\top} {W}_{q}^{\top} {W}_{k, E} {E}_{x_{j}}}_{(a)}+\underbrace{{E}_{x_{i}}^{\top} {W}_{q}^{\top} {W}_{k, R} {R}_{i-j}}_{(b)} \nonumber\\
  &+\underbrace{u^{\top} {W}_{k, E} {E}_{x_{j}}}_{(c)}+\underbrace{v^{\top} {W}_{k, R} {R}_{i-j}}_{(d)}\text{,}
\end{align}
\end{document}
```
<img width="353" alt="Screen Shot 2022-01-18 at 16 34 21" src="https://user-images.githubusercontent.com/12290822/149900183-313e5d73-97f4-4ce2-b3c5-430aee418266.png">

**Comment by hdchieh** [comment]
> 我无法复现这个问题，建议把导言区相关的配置贴一下。
> 
> ```
> \documentclass{thuthesis}
> \begin{document}
> \begin{align}
>   {a}_{i, j}^{\mathrm{rel}} &=\underbrace{{E}_{x_{i}}^{\top} {W}_{q}^{\top} {W}_{k, E} {E}_{x_{j}}}_{(a)}+\underbrace{{E}_{x_{i}}^{\top} {W}_{q}^{\top} {W}_{k, R} {R}_{i-j}}_{(b)} \nonumber\\
>   &+\underbrace{u^{\top} {W}_{k, E} {E}_{x_{j}}}_{(c)}+\underbrace{v^{\top} {W}_{k, R} {R}_{i-j}}_{(d)}\text{,}
> \end{align}
> \end{document}
> ```
> 
> <img alt="Screen Shot 2022-01-18 at 16 34 21" width="353" src="https://user-images.githubusercontent.com/12290822/149900183-313e5d73-97f4-4ce2-b3c5-430aee418266.png">

不好意思 提问错误版本了。
