### ISSUE TITLE
积分符号不好看

### ISSUE THREAD

**Issue by lkp520** [tuna/thuthesis#723]
是直立的，怎么修改为斜体？
![image](https://user-images.githubusercontent.com/55350193/150446059-fb26cf40-9410-4c80-aaa9-fbc0c55dd485.png)

**Comment by zepinglee** [comment]
`math-style = TeX`

**Comment by lkp520** [comment]
Undefined key math-style.

**Comment by zepinglee** [comment]
`math-style` 是 [v7.2.0](https://github.com/tuna/thuthesis/releases/tag/v7.2.0) 引入的。如果你使用的是 sysuthesis 模板，应该去对应的项目中讨论。
