### ISSUE TITLE
2022年6月毕业流程中要求使用没有指导小组的版本

### ISSUE THREAD

**Issue by ZhikunWei** [tuna/thuthesis#734]
根据《二〇二二年六月计算机系研究生毕业工作流程说明》，提交论文的说明处用红字标识 “ 注意：使用新版论文模板（用没有指导小组的模板）。”
但注意到当前版本仍为带指导小组的版本，是否自行删除指导小组部分即可？
另外，不知道除了指导小组的修改，最新论文模板还有没有其他更新。
[二〇二二年六月计算机系研究生毕业工作流程说明.docx](https://github.com/tuna/thuthesis/files/8182866/default.docx)

**Comment by zepinglee** [comment]
那只是个示例，应该不难修改吧？
