### ISSUE TITLE
页眉与正文重合的问题

### ISSUE THREAD

**Issue by zepinglee** [tuna/thuthesis#735]
## 编译环境

编译的系统：macOS 12.2.1
TeX 发行版：TeX Live 2021
模板版本：v7.2.3
模板类型：doctor / master / bachelor

## 描述问题

#733 指出，章标题过长时，页眉内容与页眉线会向下挤甚至与正文内容重叠。

根据研究生院的姚飞老师建议，应改为页眉线位置不变，多行页眉的文字内容向上移动。

截图：
<img width="822" alt="Screen Shot 2022-03-04 at 18 43 01" src="https://user-images.githubusercontent.com/12290822/156748953-a9c165c1-3188-4c19-9375-4ced758bd65e.png">

<img width="829" alt="Screen Shot 2022-03-04 at 18 43 28" src="https://user-images.githubusercontent.com/12290822/156749002-730e57e8-5c3e-4d53-869f-5c373cadf727.png">

复现上述问题的代码：
```TeX
\documentclass[degree=master,language=english]{thuthesis}
\usepackage{lipsum}
\begin{document}
\chapter{Short heading}
\chapter{%
  Long \\
  long \\
  long \\
  heading%
}
\lipsum
\chapter{Short heading}
\end{document}
```

**Comment by zepinglee** [comment]
其实这个是 `fancyhdr` 的问题：
```tex
```

**Comment by zepinglee** [comment]
@moSODOPE 试一下 [`issue#735`](https://github.com/tuna/thuthesis/tree/issue%23735) 分支的 e6c4a70 有没有解决问题。

**Comment by moSODOPE** [comment]
> 

好的。非常感谢🙏
是用开发版生成最新.cls文件覆盖旧的吗？这样试了，没有用。
删了.cls文件之后，仍然可以编译，并且还是之前的样子。这是系统缓存了之前的.cls文件导致的吗

**Comment by zepinglee** [comment]
> 是用开发版生成最新.cls文件覆盖旧的吗？这样试了，没有用。 

对，用 [`issue#735`](https://github.com/tuna/thuthesis/tree/issue%23735) 分支的 `.dtx` 和 `.ins` 文件覆盖掉原来的，然后用 `xetex` 编译 `thuthesis.ins` 生成新的 `.cls`。

下面代码在 [`issue#735`](https://github.com/tuna/thuthesis/tree/issue%23735) 分支的效果是：
<img width="816" alt="Screen Shot 2022-03-09 at 10 59 33" src="https://user-images.githubusercontent.com/12290822/157364243-41413146-540f-4c25-bafc-6e1704911498.png">
<img width="786" alt="Screen Shot 2022-03-09 at 10 59 58" src="https://user-images.githubusercontent.com/12290822/157364284-92c54545-36dd-4876-9d39-83f672864458.png">

```tex
\documentclass[degree=master,language=english]{thuthesis}
\usepackage{lipsum}
\begin{document}
\chapter{Short heading}
\clearpage
\chapter{%
  Long \\
  long \\
  long \\
  heading%
}
\lipsum
\clearpage
\chapter{Short heading}
\end{document}
```

**Comment by moSODOPE** [comment]
> 
牛的，重合问题解决了，非常感谢！
