### ISSUE TITLE
页眉下的横线与文字距离非常近甚至重叠

### ISSUE THREAD

**Issue by feima0969thu** [tuna/thuthesis#741]
## 编译环境
编译的系统：macOS 10.15
TeX 发行版：TeXstudio 2.12.14  
模板版本：v7.2.3
模板类型：doctor

## 描述问题
由于某一章节的名字比较长，页眉会变成两行，页眉下的横线与页面的第一行文字距离非常近。当有上标引用时候，引用文章上标数字会与横线重叠。

截图：
![1647516982131](https://user-images.githubusercontent.com/25701789/158800534-6aed5f4a-8821-4279-83e9-c93e42c12cb4.jpg)

**Comment by zepinglee** [comment]
参考 #735。
