### ISSUE TITLE
本科生使用biblatex的话外文资料的附录环境会报错

### ISSUE THREAD

**Issue by Swetres** [tuna/thuthesis#746]
## 编译环境
编译的系统：macOS 12.3
TeX 发行版：MacTeX及各种宏包几天前全部更新过
模板版本：v7.2.4
模板类型：bachelor

## 描述问题
想试着用biblatex进行参考文献的引用，发现如果不加入外文资料（翻译/调研）的话可以正常编译，但是加入了之后就编译失败。
（心理系习惯使用apa格式进行引用，虽然没有明文规定）

截图：
<img width="766" alt="image" src="https://user-images.githubusercontent.com/47295767/159703652-131a00fa-b9d4-4e7d-ac44-9542f6ec0dc4.png">

复现上述问题的代码：
在thusetup.tex中使用

\usepackage[style=apa]{biblatex}
\addbibresource{ref/refs.bib}
\addbibresource{ref/appendix.bib}

并且删除了正文中的引用（保留的话\citet,\citep没有定义会报错）
编译报错如图

即便删除了appendix-translation中其他所有代码只留下

% !TeX root = ../thuthesis-example.tex
\begin{translation}
\label{cha:translation}
\end{translation}

仍然会有类似图中的报错

想确认一下有可行的解决方案嘛

**Comment by zepinglee** [comment]
biblatex 无法在正文和附录（调研/翻译）分别使用不同样式，所以调研和翻译部分只能使用基于 bibtex 的 `bibunits`。

**Comment by Swetres** [comment]
好的谢谢，但是如果想在正文中用apa格式的引用该如何操纵呢？
在说明文档里提到使用

\usepackage[natbibapa]{apacite}
\bibliographystyle{apacite}

但是单独使用仍然会有Command \@bibunitname undefined. \begin{translation}的报错，
也不能与原来的共有
\usepackage[sort]{natbib}
\bibliographystyle{thuthesis-bachelor}

**Comment by zepinglee** [comment]
> 好的谢谢，但是如果想在正文中用apa格式的引用该如何操纵呢？ 

据我了解，除了外文系的本科生都要求正文使用 GB/T 7714。建议你先找老师确认是否允许正文使用 APA 样式。

不过外文系本科生的论文没有调研/翻译部分，所以模板目前还没有处理 apacite 与 bibunits 的兼容性。如果正文和附录都使用  APA 格式的话，可能 biblatex 的 `refsection` 或者 `refsegment` 功能进行配置更方便一些。不过我对这部分还不太熟，需要研究一下。

**Comment by Swetres** [comment]
往届公开的优秀论文用的APA样式所以应该是可以的。（不过毕竟系里大多数人还是用word写的）

自己试着在cls文件中把`bibunit`环境注释掉后在正文中在`refsection`环境中写可以解决调研或是翻译的问题，
剩下的问题大概目前apa包并没有对中文的本土化，尝试用

	\makeatletter
	\newcommand\ifintextcite{\ifdefstring{\blx@delimcontext}{textcite}}`
	\makeatother

	\DefineBibliographyStrings{English}{
		and = {\addcomma},
		andothers = {\ifintextcite{\unspace 等人}{et\addabbrvspace al\adddot}},
		mathesis         = {硕士学位论文},
		phdthesis        = {博士学位论文}
	}

	\defbibheading{bibliography}[\bibname]{%
	#1}

能做到将文中引用换成“等人”，
但是括号中引用的et al. 以及中文参考文献部分的排序自己暂时是解决不了，如果最后审核严格又很难解决的话还是用回word好了

**Comment by zepinglee** [comment]
确实比较麻烦。
