### ISSUE TITLE
请问下怎么修改摘要的字体

### ISSUE THREAD

**Issue by ChaoJiang52** [tuna/thuthesis#750]
请问下怎么修改摘要的字体：
例如标题我想换成4号黑体字，摘要内容为小4号宋体字

**Comment by zepinglee** [comment]
https://github.com/tuna/thuthesis/blob/19d9edcfe10ed29416956e69f43200410f1ff9c0/thuthesis.dtx#L5019-L5042

标题需要设置 `\ctexset{chapter/format`，内容直接设置字号就行。

**Comment by ChaoJiang52** [comment]
我修改了dtx文件里面的字号：
比如变成 chapter/format = \centering\sffamily\fontsize{5bp}{7.5bp}\selectfont, 
并且保存好dtx文件后，然后重新编译tex文件，字号没有发生改变，请问下是什么原因

**Comment by zepinglee** [comment]
> 我修改了dtx文件里面的字号： 比如变成 chapter/format = \centering\sffamily\fontsize{5bp}{7.5bp}\selectfont, 并且保存好dtx文件后，然后重新编译tex文件，字号没有发生改变，请问下是什么原因

1. 注意 `\ifthu@degree@graduate` 和 `\ifthu@main@language@english` 条件；
2. 需要编译 `.ins` 编译生成新的 `.cls` 文件。

**Comment by ChaoJiang52** [comment]
改为 chapter/format = \centering\sffamily\fontsize{14bp}{21bp}\selectfont,
使用tex thuthesis.ins命令 编译.ins生成新的.cls后 
编译tex生成pdf，摘要标题变成乱码了，然后字体改回去重新编译，还是乱码。。

**Comment by zepinglee** [comment]
> 改为 chapter/format = \centering\sffamily\fontsize{14bp}{21bp}\selectfont, 使用tex thuthesis.ins命令 编译.ins生成新的.cls后 编译tex生成pdf，摘要标题变成乱码了，然后字体改回去重新编译，还是乱码。。

`xetex thuthesis.ins`

**Comment by ChaoJiang52** [comment]
改了条件和用了你给的命令，可以啦。谢谢！

**Comment by ChaoJiang52** [comment]
还有一个问题，页眉的内容在哪里修改呢，我的需求是奇数页和偶数页分别有各自的页眉内容，而不是第x章xx。

**Comment by zepinglee** [comment]
> 还有一个问题，页眉的内容在哪里修改呢，我的需求是奇数页和偶数页分别有各自的页眉内容，而不是第x章xx。

https://github.com/tuna/thuthesis/blob/19d9edcfe10ed29416956e69f43200410f1ff9c0/thuthesis.dtx#L3131-L3172

**Comment by ChaoJiang52** [comment]
修改好了，感谢。

**Comment by wj-c** [comment]
> 修改好了，感谢。

求问你是怎么修改的呀
