### ISSUE TITLE
英文版 resume 格式可能不对

### ISSUE THREAD

**Issue by siahuat0727** [tuna/thuthesis#755]
## 编译环境
编译的系统：Overleaf
TeX 发行版：
模板版本：v7.2.3
模板类型：master

## 描述问题
Thesis Templates (EN) - 15 Resume (with academic achievements) 要求……

<img width="806" alt="image" src="https://user-images.githubusercontent.com/17688111/160801255-678b0eed-389e-490f-ae85-f539389232b9.png">

而模板编译的结果是……

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/17688111/160801783-9d0c7ce9-337f-4e52-a9c2-5fff62f21f24.png">

不知是否需要其他设定，感谢！

**Comment by siahuat0727** [comment]
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/17688111/160806878-d8004951-e07b-4380-afa3-f33df2760b24.png">

手动改成这样是否合适？谢谢！

ref: https://tex.stackexchange.com/questions/51410/left-aligning-all-text-in-itemized-list-beamer

**Comment by zepinglee** [comment]
目前模板并没有配置英文版的格式，算是一个 bug。

你的设置没什么问题，我稍后将英文版的格式加到模板中，尽量保持同中文版一致的接口。

**Comment by zepinglee** [comment]
<img width="1528" alt="Screen Shot 2022-04-08 at 23 00 12" src="https://user-images.githubusercontent.com/12290822/162468395-5590a4c6-5eb7-4390-916b-2635cf60c4d2.png">

这个英文版格式和中文版完全不一样。

**Comment by zepinglee** [comment]
@siahuat0727 请试一下 [issue#755](https://github.com/tuna/thuthesis/tree/issue%23755) 分支的英文版格式有没有问题。

**Comment by siahuat0727** [comment]
Hi, 我已经按手动改的先定稿了，感谢你对这个模版的维护！
