### ISSUE TITLE
生僻汉字可能无法显示的问题

### ISSUE THREAD

**Issue by Hu-Hanyang** [tuna/thuthesis#758]
## 编译环境
编译的系统：Overleaf
TeX 发行版：
模板版本：v7.2.3
模板类型：master

## 描述问题
生僻汉字“旸”无法显示

截图：
![image](https://user-images.githubusercontent.com/37182404/161679480-4b2b389b-4913-463f-930b-668435f0b42a.png)

**Comment by Hu-Hanyang** [comment]
忘记说明是封面（thusetup.tex）的生僻字“旸”无法打出，在resume.tex中“旸”是可以显示的。

**Comment by Harry-Chen** [comment]
请使用 Windows 字体编译

**Comment by Hu-Hanyang** [comment]
> 

您好，我在thuthesis-example.tex文件中使用了 \documentclass[degree=master,fontset=windows]{thuthesis}  命令，但是编译后显示 Timed out (Sorry, your compile took too long to run and timed out. This may be due to a LaTeX error, or a large number of high-res images or complicated diagrams)

**Comment by Hu-Hanyang** [comment]
补充：也换到了windows系统的电脑上进行编译，同样的Timed out

**Comment by zepinglee** [comment]
需要在 Windows 本地编译，或者将 Windows 的字体传到 overleaf。

**Comment by eedalong** [comment]
> 请使用 Windows 字体编译

@Harry-Chen 能不能给一个Windows字体传到Overleaf上的并进行编译配置的说明呢，比如需要改哪些配置等

**Comment by Harry-Chen** [comment]
请见 #747，检测到 SimSun 后会自动切换到 Windows 字体，不需要进行配置。

**Comment by eedalong** [comment]
wow，赞的，只不过我试了一下，把字体包传到根目录下，就是与模板中的thusetup.tex, thuexample.tex等文件相同的目录下，重新编译，似乎仍然无法显示生僻字。字体包里有如下几个ttf
![截屏2022-04-08 上午11 53 33](https://user-images.githubusercontent.com/39682259/162359385-3a273d41-e683-46f3-bf80-ca63e057d0fa.png)

**Comment by eedalong** [comment]
相同字，正文里显示没问题，就是thusetup里面设置显示会出问题

**Comment by zepinglee** [comment]
> 相同字，正文里显示没问题，就是thusetup里面设置显示会出问题。指定fontset=windows后确实会出现编译失败的问题。

具体什么问题贴出来，或者截个图。

**Comment by eedalong** [comment]
> > 相同字，正文里显示没问题，就是thusetup里面设置显示会出问题。指定fontset=windows后确实会出现编译失败的问题。
> 
> 具体什么问题贴出来，或者截个图。

最终在thusetup.tex中加了一段设置解决了

 \usepackage{xeCJK}
 \xeCJKsetup{AutoFallBack}
