### ISSUE TITLE
overleaf下载pdf后中文封面部分内容消失（包括申请人、工程领域/学科、导师等）

### ISSUE THREAD

**Issue by zhangxj19** [tuna/thuthesis#760]
## 编译环境
overleaf 最新模板

## 描述问题
overleaf下载pdf后中文封面部分内容消失（包括申请人、工程领域/学科、导师等）

截图：
如下是编译好的pdf预览
![image](https://user-images.githubusercontent.com/32873170/163313199-c578bd8c-fdd8-4080-abac-884507148945.png)
下载后中间部分消失
![image](https://user-images.githubusercontent.com/32873170/163313290-f667bb42-0bc6-415f-83d4-43020c4e336f.png)

**Comment by Harry-Chen** [comment]
是否尝试更换阅读器打开？

**Comment by zhangxj19** [comment]
换adobe打开正常了。
用edge浏览器打开不正常。
谢谢解答!
