### ISSUE TITLE
关于siunitx宏包中百分号和平面角度符号的表示

### ISSUE THREAD

**Issue by zxl19** [tuna/thuthesis#761]
您好，感谢维护thuthesis模板，最近在对照学院论文格式要求修改论文时对于百分号和平面角度符号的显示有一些疑问，想请教一下。

第一个问题是使用siunitx宏包表示百分号和平面角度符号时是否需要添加空格，在issue#599 中提到需要手动在手动在中西文之间添加空格，但是与Word对比发现Word中百分号和平面角度符号左右无论是中西文都没有添加空格，请问这里是否需要与Word保持一致。

![微信截图_20220414205420](https://user-images.githubusercontent.com/59674656/163394631-82ef64f9-62a4-4ff9-a064-47d260a2b8e9.png)

第二个问题是关于平面角度符号的显示，学院论文格式要求平面角度符号不与数字相连，单独出现时需要加英文括号`\left(\si{\degree}\right)`，我在表格中有一个单位为度的量，我在表头中使用中文括号括英文括号表示`（\left(\si{\degree}\right)）`，但是在显示是似乎中英文括号没有对齐，请问有没有更好的解决方案，谢谢！

![微信图片_20220414204222](https://user-images.githubusercontent.com/59674656/163392664-84333125-d844-4163-bb6f-58dfa2913ef0.jpg)

补充信息：
thuthesis版本：v7.2.4
texlive版本：2020

**Comment by zepinglee** [comment]
1. 关于百分号，建议不必参考 Word 中的格式。其实在 LaTeX 中百分号两侧的空格影响不大：
```tex
相对误差达到2\%左右\par
相对误差达到 2\% 左右\par
相对误差达到\qty{2}{\percent}左右\par
相对误差达到 \qty{2}{\percent} 左右\par
```
<img width="204" alt="Screen Shot 2022-04-14 at 21 48 26" src="https://user-images.githubusercontent.com/12290822/163404481-b7e44338-332e-479b-a2d2-8ffd78d0e3cc.png">

2. 我对这个不太熟悉，建议问一下导师等专业人士。

**Comment by tanukihee** [comment]
1. 理论来说，word 的度与百分号中文之间没有默认插空是有问题的，我建议即使在 word 里，也手动在度和百分号与中文间插空

2. 西文括号与西文对齐，中文括号与中文对齐。要使中西文之间也对齐的话，似乎除了 raisebox 之外想不到什么好方法

**Comment by zxl19** [comment]
我明白了，感谢二位的解答，祝好！ @zepinglee @tanukihee
