### ISSUE TITLE
mac下论文字体问题可能的解决方案

### ISSUE THREAD

**Issue by MonusW** [tuna/thuthesis#762]
## 问题描述
原模版中mac系统下编译使用的字体和windows不一样，即和学校所给word模版的字体不一样。

### 1. 总体思路
mac系统下Microsoft Word应用自带的字体包含了论文编译所需的**全部字体**，可以通过判断当前机器是否安装了Word，来决定是否使用里面的字体进行编译。

### 2. 判断是否安装Word应用的方法
通过是否存在SimSun字体文件判断是否安装了Word应用
```tex
\IfFileExists{/Applications/Microsoft Word.app/Contents/Resources/DFonts/SimSun.ttf}{%
% Word 已安装
}{%
% Word 未安装
}
```

### 3. 设置使用Word下字体进行编译的方法（测试可用）：
```tex
%% 设置字体目录
\newcommand{\wordfontpath}{/Applications/Microsoft Word.app/Contents/Resources/DFonts/}
%% 系统已经自带这些英文字体，不需要指定目录
\setmainfont{Times New Roman}
\setsansfont{Arial}
\setmonofont{Courier New}[Scale=MatchLowercase]

\xeCJKsetup{EmboldenFactor=3}
%% 指定使用Word目录下的中文字体
\setCJKmainfont{SimSun}[Path=\wordfontpath, AutoFakeBold=true, ItalicFont=KaiTi]
\setCJKsansfont{SimHei}[Path=\wordfontpath, AutoFakeBold=true]
\setCJKmonofont{FangSong}[Path=\wordfontpath]

\setCJKfamilyfont{zhsong}{SimSun}[Path=\wordfontpath, AutoFakeBold=true]
\setCJKfamilyfont{zhhei}{SimHei}[Path=\wordfontpath, AutoFakeBold=true]
\setCJKfamilyfont{zhkai}{KaiTi}[Path=\wordfontpath]
\setCJKfamilyfont{zhfs}{FangSong}[Path=\wordfontpath]
```

### 4. 可能的问题
- 不确定老版本的mac系统是否自带上述三种英文字体（`Times New Roman`, `Arial`, `Courier New`）。
- 上面这些字体设置命令是我从模版cls文件里找到的，不确定是否有遗漏。
- 不确定WPS是否自带上述中文字体。

**Comment by zepinglee** [comment]
> 不确定老版本的mac系统是否自带上述三种英文字体（`Times New Roman`, `Arial`, `Courier New`）。

OS X 10.8 的时代就已经有这些字体了（<https://support.apple.com/en-us/HT201344>）。

唯一的问题是这样调用其他软件的字体严格来说是违反授权协议的，我不太确定在模板中这样明显的配置是否合适，想征求一下 @Harry-Chen 的意见。

**Comment by Harry-Chen** [comment]
> 唯一的问题是这样调用其他软件的字体严格来说是违反授权协议的，我不太确定在模板中这样明显的配置是否合适，想征求一下 @Harry-Chen 的意见。

根据[微软的说法](https://docs.microsoft.com/en-us/typography/fonts/font-faq)，随 Windows 附带的字体可以使用，但我没找到关于 Office 的部分

**Comment by MonusW** [comment]
> > 唯一的问题是这样调用其他软件的字体严格来说是违反授权协议的，我不太确定在模板中这样明显的配置是否合适，想征求一下 @Harry-Chen 的意见。
> 
> 根据[微软的说法](https://docs.microsoft.com/en-us/typography/fonts/font-faq)，随 Windows 附带的字体可以使用，但我没找到关于 Office 的部分

或者是否可以考虑加一个可选的cjk-font-path参？这样在模版里就不用显式配置使用office字体了，也更灵活一点

**Comment by zepinglee** [comment]
> 或者是否可以考虑加一个可选的cjk-font-path参数？这样在模版里就不用显式配置使用office字体了，也更灵活一点

感觉这样不如直接双击安装到系统字体……

**Comment by zepinglee** [comment]
我觉得还是用为用户方便吧，那我就把 2b59988 合并到 master 了？

**Comment by MonusW** [comment]
> 我觉得还是用为用户方便吧，那我就把 [2b59988](https://github.com/tuna/thuthesis/commit/2b599884d54bbf4301169a0577ce184e4206c8e6) 合并到 master 了？

我觉得可以，感谢！
