### ISSUE TITLE
使用nomencl包带导数的符号顺序会提前

### ISSUE THREAD

**Issue by Hu-Hanyang** [tuna/thuthesis#763]
## 编译环境
编译的系统： Windows 10 
TeX 发行版：TeX Live 2022
模板版本：v7.2.3
模板类型： master 

## 描述问题
新版《论文格式审查表》要求 符号和缩略语说明 需要按照字母顺序排列。使用了 nomencl包，最终有导数存在的符号的顺序会提前。

截图：
![image](https://user-images.githubusercontent.com/37182404/163581167-d7482c0f-2634-40e9-af83-68daa70292cf.png)

本地编译使用TeXworks editor，编译流程：
1. XeLaTex;
2. BibTex;
3. 命令行：makeindex thuthesis-example.nlo -s nomencl.ist -o thuthesis-example.nls ;
4. XeLaTex;
5. XeLaTex.

**Comment by zepinglee** [comment]
参考 `nomencl` 的文档。

<img width="548" alt="Screen Shot 2022-04-16 at 09 46 39" src="https://user-images.githubusercontent.com/12290822/163657061-6dd451de-710e-4e01-82cc-123e822ecd07.png">
