### ISSUE TITLE
ntheorem 证明环境缺少冒号

### ISSUE THREAD

**Issue by liziwl** [tuna/thuthesis#764]
https://github.com/tuna/thuthesis/blob/dd4ae257c46720e7a772f6571889a979cd8cedae/thuthesis.dtx#L6431-L6437

`\newtheorem*{proof}{\thu@proof@name}% ` 应该移动到 `\theoremseparator{\thu@theorem@separator}% `设定后，theoremsymbol 设定前，不然证明环境缺少冒号。这样就同 `amsthm` 定义的带冒号的证明环境不一致了。

由于默认是 `amsthm` 不太容易发现这个不一致。

**Comment by zepinglee** [comment]
《写作指南》中没有要求定理、证明等环境的格式，其实可以由用户自由配置。早期版本的模板是直接调用 `ntheorem` 并配置的，比如 2017-03-26 v5.3.2 的 `proof` 就是不带冒号的。
https://github.com/tuna/thuthesis/blob/8e4ede6e33074a1ec6c2ebb1594238413f1d5c56/thuthesis.dtx#L1749-L1757

后来由于 `ntheorem` 的兼容性问题，模板改成了允许用户在导言区调用 `amsthm` 或 `ntheorem`。
https://github.com/tuna/thuthesis/blob/dd4ae257c46720e7a772f6571889a979cd8cedae/thuthesis.dtx#L6406-L6418

我倾向于将 `amsthm` 的 `proof` 环境的冒号删掉，跟 `ntheorem` 的一致。

**Comment by liziwl** [comment]
贵校的情况删掉是比较好的选择，因为中文模式下中文冒号后还有 `\quad` 看起来间距相当大，不然还最好针对中文特别设定一下。

此外还想了解一下 `ntheorem` 是有什么兼容性问题？

**Comment by zepinglee** [comment]
我印象中 `ntheorem` 的 bug 更多一些，而且有的包跟 `ntheorem` 同时调用时需要额外处理。简单搜了一下，#288 的情况是 `empheq` 需要 `ntheorem` 参数提供兼容性。另外还有 <https://tex.stackexchange.com/q/5599/82731> 的分析。
