### ISSUE TITLE
longtable 续表格式

### ISSUE THREAD

**Issue by jas0n1ee** [tuna/thuthesis#766]
#584 中按照2020-12 版指南修改了续表的格式，但研究生学位论文写作指南（二○二一年六月）中将续表格式改为

> 如某个表需要转页接排，可以“续表”的形式另页打印，格式同前，只需在每页表序前加“续”字即可，例如“续表3.1 第四次全国经济普查数据（北京）”。续表均应重复表头。

因此当前模板中longtable续表的表序与表题需要做对应修改。

提供一个dirty hack，将长表格进行label`\label{tab:xxxx}`，而后通过如下实现

> \caption*{续表~\ref{tab:xxxx} \quad 跨页长表格的表题}\\

来插入续表的表序与标题

**Comment by zepinglee** [comment]
嗯？又改回去了？

可以给我发一份最新的《指南》和 Word 模板吗？

**Comment by zepinglee** [comment]
2021-06 版确实修改了续表的格式。模板本身没有设置 `longtable` 标题的格式，只需修改示例文件。我找到的最简单的方法是
```tex
\caption*{续表~\thetable\quad 跨页长表格的表题}
```
