### ISSUE TITLE
\songti\heiti等宏命令是

### ISSUE THREAD

**Issue by shenghuxu** [tuna/thuthesis#769]
Undefined control sequence.
<recently read> \songti 
                        
l.11 \songti

这是报错信息，但是\CJKfamily{zhsong}这种宏命令不会报错。为什么，是ctex宏包损坏还是版本过低

**Comment by zepinglee** [comment]
https://github.com/tuna/thuthesis/blob/366b9413482584f3684346c0fc351d46cfbaaff9/thuthesis.dtx#L2683-L2688
