### ISSUE TITLE
是否考虑增加 LuaLaTeX 支持

### ISSUE THREAD

**Issue by Berrysoft** [tuna/thuthesis#771]
CTeX 在 LuaLaTeX 使用 luatexja 提供相关支持，不清楚 xeCJK 的相关代码能不能比较容易地 port 过去？看起来不是很多？

**Comment by Berrysoft** [comment]
LuaLaTeX 的优点在于，可以很方便地使用 tikz-feynman 画费曼图

**Comment by zepinglee** [comment]
> CTeX 在 LuaLaTeX 使用 luatexja 提供相关支持，不清楚 xeCJK 的相关代码能不能比较容易地 port 过去？看起来不是很多？

主要困难在于本科生和博后报告的封面需要下划线，其中使用了 `xeCJKfntef` 的 `\CJKunderline`，依赖 `xeCJK` 和 `xetex`。其他的就是字体的配置了，应该不算太难。不过 luatex-ja 比 xecjk 要慢很多。粗略估计前者的时间是后者的 3～5 倍（排除刷新字体缓存）。你可以试一下 <https://github.com/ustctug/ustcthesis> 这个项目比较两者的速度。

**Comment by zepinglee** [comment]
另外插图最好还是编译成 pdf 再插入论文中，每次都用 Lua 编译就太慢了。

**Comment by Berrysoft** [comment]
性能不是问题，把插图另外编译这种操作实在是太麻烦了，希望能有 LuaLaTeX 这个可能性。

**Comment by zepinglee** [comment]
那我试一下吧。

@Berrysoft 另外你是本科生还是研究生？后者的论文不需要下划线，改起来应该相对简单一些。

**Comment by Berrysoft** [comment]
我已经是研究生啦，不过这个模板肯定还是要为本科生服务的吧，莫非只给研究生加 Lua 支持？

**Comment by zepinglee** [comment]
ed67031 初步实现了 LuaTeX 的支持，不过还有几个地方不够理想。

1. 本科生的带下划线的标题无法自动换行，只能手动换行。这是因为 `xeCJKfntef` patch 了 `ulem` 的 `\uline` 才能对中文自动换行，而换成 LuaTeX 则没有了相关的 patch。后续考虑尝试 `luatex-ja` + `lua-ul` 的方式。
2. Word 模板中有些位置的西文字符需要强制使用中文字体，如本科生封面的日期，目前找不到实现的方法。

目前效果：
<img width="797" alt="Screen Shot 2022-05-02 at 09 16 24" src="https://user-images.githubusercontent.com/12290822/166173471-86e66fce-07c2-4293-b601-d31c35a4d1dc.png">

Word 版：
<img width="646" alt="Screen Shot 2022-05-02 at 09 25 00" src="https://user-images.githubusercontent.com/12290822/166173911-32a93519-f0af-494c-945f-8f06c2f6cfb8.png">

**Comment by tanukihee** [comment]
> Word 模板中有些位置的西文字符需要强制使用中文字体，如本科生封面的日期，目前找不到实现的方法。

用 `\ltjjachar`

**Comment by zepinglee** [comment]
> > Word 模板中有些位置的西文字符需要强制使用中文字体，如本科生封面的日期，目前找不到实现的方法。
> 
> 用 `\ltjjachar`

模板中有部分需要使用中文字体的内容是用户录入的日期，保存在 `\thu@date` 里，好像还不能直接使用 `\ltjjachar`。

https://github.com/tuna/thuthesis/blob/d1cc25d09a0041d27487a5ff075b4911931829e4/thuthesis.dtx#L4801

**Comment by tanukihee** [comment]
```latex
\documentclass[]{ctexart}
\usepackage{lua-visual-debug}
\begin{document}
\ltjjachar`2\kern-.5\zw\ltjjachar`0\kern-.5\zw\ltjjachar`*\kern-.5\zw\ltjjachar`*\kern-.5\zw 年\ltjjachar`*\kern-.5\zw\ltjjachar`*\kern-.5\zw 月\ltjjachar`*\kern-.5\zw\ltjjachar`*\kern-.5\zw 日

20**年**月**日
\end{document}
```

用到了一些肮脏的 workaround，因为 `\ltjjachar` 是把下个字符当成「汉字字符」看，所以会调用中文字形，但是在 JFM 里定义的汉字字宽是 `1\zw`（ctex 下等于 1em），这个数字又没办法改，只能用肮脏的办法了

**Comment by tanukihee** [comment]
> > > Word 模板中有些位置的西文字符需要强制使用中文字体，如本科生封面的日期，目前找不到实现的方法。
> > 
> > 
> > 用 `\ltjjachar`
> 
> @tanukihee 模板中有部分需要使用中文字体的是用户录入的日期，保存在 `\thu@date` 里，好像还不能直接使用 `\ltjjachar`。
> 
> https://github.com/tuna/thuthesis/blob/d1cc25d09a0041d27487a5ff075b4911931829e4/thuthesis.dtx#L4801

啊这……

**Comment by tanukihee** [comment]
```LaTeX
\documentclass[]{ctexart}
\usepackage{lua-visual-debug}
\begin{document}
{\fontspec{simsun}\ltjsetparameter{autoxspacing=false} 2022年5月2日}

2022年5月2日
\end{document}
```
那就最 dirty 的，直接上 fontspec（逃

**Comment by zepinglee** [comment]
> ```
> \documentclass[]{ctexart}
> \usepackage{lua-visual-debug}
> \begin{document}
> {\fontspec{simsun}\ltjsetparameter{autoxspacing=false} 2022年5月2日}
> 
> 2022年5月2日
> \end{document}
> ```
> 
> 那就最 dirty 的，直接上 fontspec（逃
> 
> ![image](https://user-images.githubusercontent.com/34062491/166180278-16b7e108-9652-43dd-8716-b1eb776ed468.png)

确实是个可行的办法，不过模板中配置了多种字体，直接用字体名就不太方便了。我试试能不能用 `\CJK@family` 之类的。

**Comment by zepinglee** [comment]
e01e54a 基本解决了上面的问题。

**Comment by Explorer-cc** [comment]
> 把插图另外编译这种操作实在是太麻烦了

其实不然，有一些人把「单开一个`figure`文件夹之后在其中用`standalone`画完图(例如需要`lualatex`的`tikz-feynman`和`luadraw`)，再用`\includegraphics`插入」的方式称为「**two-approach method**」。

我个人觉得这并不麻烦，事实上有如下的优点：
- 主文件`main.tex`的行文逻辑更清晰：在码字的时候只关注文本内容；而在`standalone`中画图的时候更关注画图的细节，避免在正文中插入大段画图代码影响正文逻辑，如果需要修改图，也不用在长篇大论的`main.tex`中寻找究竟是哪个图
- 从项目结构来看，分离「画图」和「正文」，能更好地体现类似于「低耦合高内聚」的观点，只要给图片合适的有意义的文件名，会一定程度上提高代码的可读性 
- 不是所有基于`xeCJK`模板都能轻松(无痛)地从`xelatex`转到`lualatex`，可以看到上面实际上用到了一些trick才实现...
- 避免在主文件多次编译`tikzpicture`，正如"每次都用 Lua 编译就太费时间"相比于"直接插入画好的`.pdf`图片"会拖慢项目编译的速度，最好还是避免反复编译画图部分的代码
