### ISSUE TITLE
如何跨文件引用图/表？

### ISSUE THREAD

**Issue by Saltsmart** [tuna/thuthesis#773]
您好！Thuthesis给我的latex项目带来了不少启发，在此感谢！

有一个比较棘手的问题：Thuthesis的正文是由`data/`中的很多个tex文件共同编译的，如何实现引用不同文件中的章节、图、表等内容呢（如在论文第2章重新提及第1章的表1.1）？

目前我了解到的方案是使用`xr`宏包，但是它要求被引用的文件要能生成单个的`.aux`文件，而这就进一步要求被引用文件有单独的`\begin{document}`。我尝试过Overleaf提供的这种[方案](https://www.overleaf.com/learn/how-to/Cross_referencing_with_the_xr_package_in_Overleaf)，它的实例项目很正常，但按步骤在我自己的项目里实现始终`XR Package Warning: NOT IMPORTED`，提示找不到`.aux`文件。

**Comment by Saltsmart** [comment]
我发现Thuthesis v7.2.4没有使用`xr`包，也没有给每个chapter单独开document环境，这个问题该如何解决呢？

**Comment by tanukihee** [comment]
正常引用就可以了呀？

**Comment by Harry-Chen** [comment]
这些文件都是 `thuthesis-example.tex` 里面 `\input` 进来的，不是独立编译单元

**Comment by Saltsmart** [comment]
> 正常引用就可以了呀？ [test.zip](https://github.com/tuna/thuthesis/files/8618620/test.zip)

试了一下，确实可以！是我昨天想复杂了，`xr`包在**同一个项目里（我的理解是只有一个文档有\begin{document}）**是不需要用的，overleaf也说明了：

> The xr package is used for cross-referencing across **multiple independent documents**
