### ISSUE TITLE
去除空白页后，页码从2开始的问题

### ISSUE THREAD

**Issue by Gaviiin-W** [tuna/thuthesis#777]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2022
模板版本：v7.2.4
模板类型：bachelor

## 描述问题
为了去除空白页（学校要求），手动删除了.dtx中的\cleardoublepage（宏定义没有删除）。空白页确实可以删除，但是第一章页码变成了2，前一张变成了1。请问，这可以通过定义页码开始位置来解决吗？

截图：
![image](https://user-images.githubusercontent.com/80686289/167180451-31655006-e4b4-43b5-af81-e70a15b20f8e.png)
![image](https://user-images.githubusercontent.com/80686289/167180498-3c28b99d-bd84-4976-ac8f-207b33dd81d7.png)

复现上述问题的代码：
手动删除了.dtx中的\cleardoublepage（宏定义没有删除），如：
![image](https://user-images.githubusercontent.com/80686289/167180773-3ab1b9e7-ac66-4eb8-9653-d257b284f91b.png)

**Comment by zepinglee** [comment]
如果去除空白页是为了提交电子版，应该先阅读文档。
<img width="758" alt="Screen Shot 2022-05-07 at 08 23 07" src="https://user-images.githubusercontent.com/12290822/167230319-4d55b84e-de21-4a8d-8d5a-d82df5e608f3.png">

**Comment by Gaviiin-W** [comment]
感谢！

**Comment by Gaviiin-W** [comment]
> 如果去除空白页是为了提交电子版，应该先阅读文档。 <img alt="Screen Shot 2022-05-07 at 08 23 07" width="758" src="https://user-images.githubusercontent.com/12290822/167230319-4d55b84e-de21-4a8d-8d5a-d82df5e608f3.png">
改了之后发现有个问题，每一章都是另起一页开始，如图：
![image](https://user-images.githubusercontent.com/80686289/167243372-a9ee337c-cea0-46dd-be65-3f0a47919f87.png)
如何接着上一章开始呢？
还有就是电子版如何设置左右页边距不同呢？如左边距2.5，右边距2

**Comment by zepinglee** [comment]
根据往年经验，提交电子版只是去掉空白页，并不取消需要章标题另起一页，参考 #553 。

页面布局的相关代码在 https://github.com/tuna/thuthesis/blob/d1cc25d09a0041d27487a5ff075b4911931829e4/thuthesis.dtx#L1889-L1898 。

注意本科生的的“装订线”是 0.2 cm。而且 https://github.com/tuna/thuthesis/issues/553#issuecomment-642408924 者出于避免强迫症考虑电子版中去掉了“装订线”距离。

**Comment by zepinglee** [comment]
> 如果去除空白页是为了提交电子版，应该先阅读文档。 <img alt="Screen Shot 2022-05-07 at 08 23 07" width="758" src="https://user-images.githubusercontent.com/12290822/167230319-4d55b84e-de21-4a8d-8d5a-d82df5e608f3.png">

感觉这里的文档没说清楚，我再改一下。

**Comment by Gaviiin-W** [comment]
还想请问 **目录中章节缩进** 相关代码在哪儿修改呢？我们学校要求section缩进两个字符。

**Comment by zepinglee** [comment]
> 还想请问 **目录中章节缩进** 相关代码在哪儿修改呢？我们学校要求section缩进两个字符。

原来你是在项目基础上新开发模板呀？你应该说明目的，我误以为是乱改格式的同学呢。

目录中的章节标题格式在

https://github.com/tuna/thuthesis/blob/d1cc25d09a0041d27487a5ff075b4911931829e4/thuthesis.dtx#L3939-L3956

`[1em]` 和 `[1.5em]` 就是左侧缩进，参考 `titletoc` 文档。

**Comment by Gaviiin-W** [comment]
> > 还想请问 **目录中章节缩进** 相关代码在哪儿修改呢？我们学校要求section缩进两个字符。
> 
> 原来你是在项目基础上新开发模板呀？你应该说明目的，我误以为是乱改格式的同学呢。
> 
> 目录中的章节标题格式在
> 
> https://github.com/tuna/thuthesis/blob/d1cc25d09a0041d27487a5ff075b4911931829e4/thuthesis.dtx#L3939-L3956
> 
> `[1em]` 和 `[1.5em]` 就是左侧缩进，参考 `titletoc` 文档。

哈哈，是的，我没有说清楚。🤣非常感谢你的答疑,都是一些小改动,暂时没有其他问题啦.那我就先close啦,以后有问题还得再来麻烦各位大佬🤗🤗

**Comment by Gaviiin-W** [comment]
@zepinglee 又有一个新开发模板的问题，因为我们学校要求所有英文字体均为Times new roman，所以我把这里https://github.com/tuna/thuthesis/blob/d1cc25d09a0041d27487a5ff075b4911931829e4/thuthesis.dtx#L2275
的英文标题样式改为了Times new roman，但是学校又要求目录的字体为黑体，请问如何单独修改目录的英文字体呢？现在目录的英文字体是Times new roman，如图：
![image](https://user-images.githubusercontent.com/80686289/168325385-4232d007-8064-478d-b409-527abd7fe463.png)

**Comment by zepinglee** [comment]
> @zepinglee 又有一个新开发模板的问题，因为我们学校要求所有英文字体均为Times new roman，所以我把这里
> 
> https://github.com/tuna/thuthesis/blob/d1cc25d09a0041d27487a5ff075b4911931829e4/thuthesis.dtx#L2275
> 
> 的英文标题样式改为了Times new roman

不要这样改，`\setsansfont` 设置的是全文的无衬线字体。

英文标题如果需要用 Times 就把相应的 `\sffamily` 去掉恢复成默认的 `\rmfamily`，目录如果需要用无衬线字体再掉用 `\sffamily`。

**Comment by Gaviiin-W** [comment]
> > @zepinglee 又有一个新开发模板的问题，因为我们学校要求所有英文字体均为Times new roman，所以我把这里
> > https://github.com/tuna/thuthesis/blob/d1cc25d09a0041d27487a5ff075b4911931829e4/thuthesis.dtx#L2275
> > 
> > 的英文标题样式改为了Times new roman
> 
> 不要这样改，`\setsansfont` 设置的是全文的无衬线字体。
> 
> 英文标题如果需要用 Times 就把相应的 `\sffamily` 去掉恢复成默认的 `\rmfamily`，目录如果需要用无衬线字体再掉用 `\sffamily`。

明白啦，已解决！感谢！
