### ISSUE TITLE
thuthesis-example.tex:25: Missing number, treated as zero. <to be read again>                     = l.25 

### ISSUE THREAD

**Issue by jiegec** [tuna/thuthesis#779]
## 编译环境
编译的系统：macOS 12.3
TeX 发行版：MiKTeX
模板版本：commit e0b5751588fed96d8d3145ab2431dc008ced0d44
模板类型：master

## 描述问题

不进行任何修改，仓库中运行 `make`，报错如下：

```
(/Users/macbookair/Library/Application Support/MiKTeX/texmfs/install/tex/latex/
translations/dicts/translations-basic-dictionary-english.trsl)
(/Users/macbookair/Library/Application Support/MiKTeX/texmfs/install/tex/latex/
hyperref/nameref.sty
(/Users/macbookair/Library/Application Support/MiKTeX/texmfs/install/tex/latex/
refcount/refcount.sty)
(/Users/macbookair/Library/Application Support/MiKTeX/texmfs/install/tex/generi
c/gettitlestring/gettitlestring.sty)) (thuthesis-example.out)
(thuthesis-example.out) [1]
thuthesis-example.tex:25: Missing number, treated as zero.
<to be read again>
                   =
l.25

Output written on thuthesis-example.xdv (1 page, 4792 bytes).
SyncTeX written on thuthesis-example.synctex.gz.

Transcript written on thuthesis-example.log.
Latexmk: Getting log file 'thuthesis-example.log'
Latexmk: Examining 'thuthesis-example.fls'
Latexmk: Examining 'thuthesis-example.log'
Latexmk: Log file says output to 'thuthesis-example.xdv'
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  xelatex: Command for 'xelatex' gave return code 1
      Refer to 'thuthesis-example.log' for details
Latexmk: If appropriate, the -f option can be used to get latexmk
  to try to force complete processing.
make: *** [thuthesis-example.pdf] Error 12

```

完整日志：

[thuthesis-example.log](https://github.com/tuna/thuthesis/files/8645425/thuthesis-example.log)

**Comment by zepinglee** [comment]
`maoOS 12.3.1 TeX Live 2022` 无法复现你的问题，而且 Linux 的 TeX Live 也运行正常：<https://github.com/tuna/thuthesis/runs/6334227319?check_suite_focus=true>。

**Comment by jiegec** [comment]
我在Linux上也无法复现，但是macOS上依然是这个问题。

**Comment by zepinglee** [comment]
感觉是 macOS 的 MikTeX 的问题，不妨把全部宏包升级到最新再试试。

另外 `thuthesis-example.tex:25` 应该是封面 `\maketitle`。

**Comment by jiegec** [comment]
> 感觉是 macOS 的 MikTeX 的问题，不妨把全部宏包升级到最新再试试。

已经升级了。

> 
> 另外 `thuthesis-example.tex:25` 应该是封面 `\maketitle`。

是的，注释掉这一行，错误会到下面，所以我觉得也许是 \begin{document} 的问题。

**Comment by zepinglee** [comment]
那我装个 miktex 试一下。

**Comment by zepinglee** [comment]
@jiegec 下面的例子可以复现吗？

```tex
\documentclass{book}
\usepackage[perpage]{footmisc}
\begin{document}
Lorem ipsum.
\end{document}
```

**Comment by jiegec** [comment]
> 

可以：

! Missing number, treated as zero.
<to be read again>
                   =
l.5 \end{document}

?

**Comment by zepinglee** [comment]
大概是 miktex 错误地调用了 [`ednotes`](https://ctan.org/pkg/ednotes) 的旧版本 `perpage.sty 2006/07/15`，正确的应该是 [`bigfoot`](https://ctan.org/pkg/bigfoot) 的 `perpage.sty 2014/10/25`。我去给 miktex 反馈一下。

**Comment by zepinglee** [comment]
见 <https://github.com/MiKTeX/miktex/issues/1106>。

**Comment by jiegec** [comment]
试了一下，卸载 ednotes 后，下一次 make 会弹出窗口让我安装 ednotes，而不是 bigfoot，这里应该是推断包名的时候没有正确处理重名的问题。

**Comment by zepinglee** [comment]
对的。

可以拷贝一份 bigfoot 的 perpage.sty 到 cwd。

**Comment by jiegec** [comment]
> 可以拷贝一份 bigfoot 的 perpage.sty 到 cwd。

问题解决了。

**Comment by jiegec** [comment]
miktex 上游修复以后，卸载 bigfoot，删除复制的 perpage.sty，重新安装即可正常工作。
