### ISSUE TITLE
Tsinghua Overleaf上无法正常显示书面翻译部分的文献引用

### ISSUE THREAD

**Issue by nmrenyi** [tuna/thuthesis#780]
## 编译环境
编译的系统：Overleaf (Tsinghua Overleaf)
模板版本：v7.2.4
模板类型：bachelor

## 描述问题
从thuthesis的Github Release下载7.2.4版本的zip文件，上传至https://overleaf.tsinghua.edu.cn ，选择Compiler为XeLatex，发现模板中书面翻译部分的文献引用无法正常显示，也无法显示书面翻译对应的原文索引。

截图：
![屏幕截图 2022-05-08 102809](https://user-images.githubusercontent.com/46751328/167279184-56f80edb-f6a8-4e7c-aa14-06eae2b6cd35.png)

复现上述问题的代码：
```TeX
\section{文献引用}

文献引用示例\cite{abrahams99tex}。


\appendix

\section{附录}

附录的内容。


% 书面翻译的参考文献
\bibliographystyle{unsrtnat}
\bibliography{ref/appendix}

% 书面翻译对应的原文索引
\begin{translation-index}
  \nocite{salomon1995advanced}
  \bibliographystyle{unsrtnat}
  \bibliography{ref/appendix}
\end{translation-index}

```

**Comment by nmrenyi** [comment]
报错的Log，似乎是没找到引用

[output.log](https://github.com/tuna/thuthesis/files/8646250/output.log)

**Comment by zepinglee** [comment]
你试一下直接使用 https://www.overleaf.com/latex/templates/thuthesis-tsinghua-university-thesis-latex-template/wddqnwbyhtnk 有没有问题。

**Comment by nmrenyi** [comment]
> 你试一下直接使用 https://www.overleaf.com/latex/templates/thuthesis-tsinghua-university-thesis-latex-template/wddqnwbyhtnk 有没有问题。

直接用overleaf.com 里面的模板是没问题的，但是overleaf.com 里面没有Windows的字库，选择fontset=windows会编译超时，因此想在https://overleaf.tsinghua.edu.cn/ 上面做，不知道有没有合适的办法兼顾字体和翻译文献中的引用

**Comment by zepinglee** [comment]
> 直接用overleaf.com 里面的模板是没问题的，但是overleaf.com 里面没有Windows的字库，选择fontset=windows会编译超时，因此想在https://overleaf.tsinghua.edu.cn/ 上面做，不知道有没有合适的办法兼顾字体和翻译文献中的引用

参考 <https://github.com/tuna/thuthesis/discussions/747#discussioncomment-2428712>。

**Comment by nmrenyi** [comment]
> > 直接用overleaf.com 里面的模板是没问题的，但是overleaf.com 里面没有Windows的字库，选择fontset=windows会编译超时，因此想在https://overleaf.tsinghua.edu.cn/ 上面做，不知道有没有合适的办法兼顾字体和翻译文献中的引用
> 
> 参考 [#747 (reply in thread)](https://github.com/tuna/thuthesis/discussions/747#discussioncomment-2428712)。

好的我去试试，谢谢！
