### ISSUE TITLE
公式中\bm{}指令无法正确加粗sans serif字体

### ISSUE THREAD

**Issue by Xu1084** [tuna/thuthesis#781]
## 编译环境
编译的系统：Overleaf
模板版本：v7.2.4
模板类型：bachelor

## 描述问题
\bm加粗指令无法正确使用。说明文档thuthesis.pdf第16页指出“注意，unicode-math 宏包与amsfonts、amssymb、bm、mathrsfs、upgreek 等宏包不兼容。模板作了处理，用户可以直接使用这些宏包的命令，如\bm、\mathscr、\uppi”，所以想用\bm指令对公式中的sans serif字体进行加粗（需要以这种形式表示随机向量、随机矩阵），结果失败了。希望能有办法实现加粗的sans serif字体。

截图：
![image](https://user-images.githubusercontent.com/55276156/167829409-bddd2903-cff1-4025-840b-e0bfc46839f0.png)

复现上述问题的代码：
```TeX
\documentclass[degree=bachelor]{thuthesis}

\DeclareMathAlphabet{\mathsfbr}{OT1}{cmss}{m}{n}%for math sans serif (cmss)
\SetMathAlphabet{\mathsfbr}{bold}{OT1}{cmss}{bx}{n}%for math sans serif (cmss)
\DeclareRobustCommand{\msf}[1]{%
  \ifcat\noexpand#1\relax\msfgreek{#1}\else\mathsfbr{#1}\fi%for math sans serif (cmss)
}
\newcommand{\rv}[1]{\MakeLowercase{\msf{#1}}} %% random variable
\newcommand{\RV}[1]{\bm{\MakeLowercase{\msf{#1}}}}  %% random vector
\newcommand{\RM}[1]{\bm{\MakeUppercase{\msf{#1}}}}  %% random matrix
\newcommand{\RS}[1]{\MakeUppercase{\msf{#1}}} %% random set

\begin{document}
$\rv{x}$是细体的Sans Serif，$\RV{x}$本该是粗体的结果也是细体的； $\RM{X}$同理无法加粗；另外尝试直接用$\bm{\msf{x}}$同样也不行
\end{document}
```

**Comment by zepinglee** [comment]
使用 `unicode-math` 的命令。

```tex
\documentclass[degree=bachelor]{thuthesis}
\begin{document}
Random variable $\symsf{x}$, random vector $\symbfsf{x}$, random matrix $\symbfsf{X}$.\par
Random variable $\symsf{\alpha}$, random vector $\symbfsf{\alpha}$, random matrix $\symbfsf{\Sigma}$.
\end{document}
```
<img width="446" alt="Screen Shot 2022-05-12 at 13 04 53" src="https://user-images.githubusercontent.com/12290822/167995883-ea8782a9-1c40-442f-9f75-8da0c21be7e2.png">

**Comment by zepinglee** [comment]
`\thusetup{math-style = TeX}`

关于无衬线希腊字母，参考 `unicode-math` 文档：
<img width="576" alt="Screen Shot 2022-05-12 at 17 16 39" src="https://user-images.githubusercontent.com/12290822/168036960-8a74072a-109e-4876-bf35-d48009a93a3d.png">

大概就是，没有人会这么用，所以 Unicode 没有对应的编码。

**Comment by Xu1084** [comment]
感谢，问题解决了，可以做个折中，用\symup{\symsf{}}来表示细体随机变量（包含普通字母和希腊字母）
