### ISSUE TITLE
关于mac下 monofont 字体特别设定

### ISSUE THREAD

**Issue by liziwl** [tuna/thuthesis#782]
https://github.com/tuna/thuthesis/blob/e0b5751588fed96d8d3145ab2431dc008ced0d44/thuthesis.dtx#L2273-L2280

Mac 下采用了 Menlo 并没有采用和 Windows一致的 Courier New 字体，但是根据 Apple 官方文件是默认自带的，最新的12和和11都是包含 Courier New 字体的。这是什么原因要特别设定呢？

* https://en.wikipedia.org/wiki/List_of_typefaces_included_with_macOS
* [macOS 12](https://support.apple.com/en-us/HT212587)
* [macOS 11](https://support.apple.com/en-in/HT211240)

**Comment by Harry-Chen** [comment]
写作指南并未规定等宽字体，而 Courier New 并不好看…有需要可以自行修改

**Comment by jiguanglizipao** [comment]
我认为通过fontset来设置会比较统一。
可否将`\ifthu@system@mac`改为`\ifthu@fontset@mac`?

**Comment by zepinglee** [comment]
> 我认为通过fontset来设置会比较统一。 可否将`\ifthu@system@mac`改为`\ifthu@fontset@mac`?

感觉有道理，我稍后改一下。
