### ISSUE TITLE
本科生毕业论文外文资料的调研阅读报告参考文献编译出错

### ISSUE THREAD

**Issue by Carolyxwu** [tuna/thuthesis#783]
## 编译环境
编译的系统：Overleaf
TeX 发行版：TeX Live 2021
模板版本：v7.2.4
模板类型：bachelor

## 描述问题
在thuthesis-example.tex中添加了本科生外文资料的调研阅读报告之后，编译后无法正确显示附录中的参考文献编号及参考文献列表。

截图：
![image](https://user-images.githubusercontent.com/51412878/168536622-09698083-18e1-47b5-ae52-30e522b35918.png)

复现上述问题的代码：
\section{Citations}

Example citations in appendix.
\cite{abrahams99tex}
\cite{salomon1995advanced}
\cite{abrahams99tex,salomon1995advanced}

\bibliographystyle{unsrtnat}
\bibliography{ref/appendix}

**Comment by Harry-Chen** [comment]
是否使用 `latexmk` 编译？

**Comment by Carolyxwu** [comment]
不好意思，已经解决了，是模板类型使用的不对。
