### ISSUE TITLE
在mac环境下编译，\textsc无法实现小型大写

### ISSUE THREAD

**Issue by qinyuxian** [tuna/thuthesis#784]
目前使用的版本是7.2.3，在mac环境下编译，\textsc不起作用。在overleaf上没问题。
请问有什么方法可以解决？这个比较重要，涉及的符号要求比较严格。论文即将上传，非常着急。万分感谢。

**Comment by zepinglee** [comment]
macOS 的 Times New Roman 字体版本比较旧，没有 small caps 的 feature。你可以调用 windows 的字体。

**Comment by qinyuxian** [comment]
我手上没windows电脑。还进不了学校。

**Comment by zepinglee** [comment]
如果有 mac 版 Microsoft Word，可以把 `/Applications/Microsoft Word.app/Contents/Resources/DFonts/times*.ttf` 拷贝一份到 `~/Library/Fonts`；或者在 TeX 文档中设置 

```tex
\setmainfont{Times New Roman}[Path = /Applications/Microsoft Word.app/Contents/Resources/DFonts/]
\setsansfont{Arial}[Path = /Applications/Microsoft Word.app/Contents/Resources/DFonts/]
```

如果没有 Microsoft Word 就只能使用 Times 的克隆版 TeX Gyre Termes 了（`\thusetup{font = termes}`），也就是 Overleaf 上编译使用的字体。

**Comment by qinyuxian** [comment]
明明安装有word，但是报错。
Package fontspec Error: The font "Times New Roman" cannot be found. ...soft Word.app/Contents/Resources/DFonts/]

**Comment by stone-zeng** [comment]
先看看这个路径对不对，然后去这个路径下看看是不是有字体、字体名对不对（似乎此处应该填文件名？）

**Comment by qinyuxian** [comment]
ls /Applications/Microsoft\ Word.app/Contents/Resources/DFonts

有一堆的.ttf

**Comment by yzlnew** [comment]
> ls /Applications/Microsoft\ Word.app/Contents/Resources/DFonts
> 
> 有一堆的.ttf

参考[这个链接](https://stone-zeng.github.io/2019-07-06-use-opentype-fonts-ii/#%E5%AD%97%E4%BD%93%E5%90%8D%E8%B0%83%E7%94%A8-vs-%E6%96%87%E4%BB%B6%E5%90%8D%E8%B0%83%E7%94%A8)，可以试试文件名调用

**Comment by qinyuxian** [comment]
Package fontspec Error: The font "Times New Roman" cannot be found. }

**Comment by qinyuxian** [comment]
\setmainfont{Times}[Path = /Applications/Microsoft Word.app/Contents/Resources/DFonts/]
\setsansfont{Arial}[Path = /Applications/Microsoft Word.app/Contents/Resources/DFonts/]

改成这样，但是又出不了斜体了。

**Comment by zepinglee** [comment]
我的失误应该用字体文件名的。

```tex
\setmainfont{times}[
  Path           = /Applications/Microsoft Word.app/Contents/Resources/DFonts/,
  Extension      = .ttf,
  BoldFont       = *bd,
  ItalicFont     = *i,
  BoldItalicFont = *bi,
]
\setsansfont{arial}[
  Path           = /Applications/Microsoft Word.app/Contents/Resources/DFonts/,
  Extension      = .ttf,
  BoldFont       = *bd,
  ItalicFont     = *i,
  BoldItalicFont = *bi,
]
```
