### ISSUE TITLE
二学位论文格式修改

### ISSUE THREAD

**Issue by thuliu-yt16** [tuna/thuthesis#786]
请问如何修改模板能满足如下word模板的格式要求？
[管理学工商管理专业二学位综合论文格式模板.docx](https://github.com/tuna/thuthesis/files/8714887/default.docx)

目前显著不一样的地方包括
1. 题目下的`（清华大学管理学工商管理专业二学位综合论文）`
2. 学号
3. 正文一级标题的格式

十分感谢！

**Comment by zepinglee** [comment]
封面 https://github.com/tuna/thuthesis/blob/d42e3fbc15fdb2a856331646a613147e8d3ad910/thuthesis.dtx#L4781-L4864

一级标题格式https://github.com/tuna/thuthesis/blob/d42e3fbc15fdb2a856331646a613147e8d3ad910/thuthesis.dtx#L3703-L3709
