### ISSUE TITLE
mac编译后复制不了文字

### ISSUE THREAD

**Issue by qinyuxian** [tuna/thuthesis#787]
我用Mac编译之后，想从封面页复制文字，粘贴到word之后，中文显示为乱码。请问如何解决。谢谢。

**Comment by zepinglee** [comment]
能不能给个截图，是封面的黑体部分吗？

**Comment by qinyuxian** [comment]
封面的XXX教授的复制过来，中文显示为乱码。比如，培养单位 􂘠 􂰠 􃖠􁱶 􀀦

**Comment by zepinglee** [comment]
复现问题的示例：
```
\documentclass{article}
\usepackage{xeCJK}
\setCJKmainfont{Songti SC Light}
\setCJKsansfont{Heiti SC Light}
\setCJKfamilyfont{zhfs}{STFangsong}
\setCJKfamilyfont{zhkai}{Kaiti SC Regular}
\begin{document}
\textrm{劳伦衣普桑}\par
\textsf{劳伦衣普桑}\par
{\CJKfamily{zhfs}劳伦衣普桑\par}
{\CJKfamily{zhkai}劳伦衣普桑\par}
\end{document}
```
字体版本：
- Heiti SC Light; 17.0d1e2; 2021-06-23
- STKaiti; 17.0d1e2; 2021-06-23 

其中黑体和仿宋无法复制，似乎是 macOS 系统字体的问题。

请教一下 @Stone-Zeng，这是字体的 cmap 坏了吗？有没有渠道向苹果反馈？

**Comment by clerkma** [comment]
我来解决，需要改dvipdfmx。
预计周六日改，如果周六日没改完，就留到下周六日。

**Comment by qinyuxian** [comment]
希望能快些，学校要求25日之前将最终稿上传。谢谢。

**Comment by zepinglee** [comment]
> 我来解决，需要改dvipdfmx。 预计周六日改，如果周六日没改完，就留到下周六日。

感谢帮忙！

**Comment by zepinglee** [comment]
> 希望能快些，学校要求25日之前将最终稿上传。谢谢。

上传最终版应使用 Windows 的字体编译。

**Comment by qinyuxian** [comment]
\documentclass[degree=doctor,fontset=windows]{thuthesis}
在mac环境下报错，只好写成
\documentclass[degree=doctor,fontset=mac]{thuthesis}

**Comment by Harry-Chen** [comment]
> \documentclass[degree=doctor,fontset=windows]{thuthesis} 在mac环境下报错，只好写成 \documentclass[degree=doctor,fontset=mac]{thuthesis}

你需要手工安装字体，请见 #747

**Comment by zepinglee** [comment]
> \documentclass[degree=doctor,fontset=windows]{thuthesis} 在mac环境下报错，只好写成 \documentclass[degree=doctor,fontset=mac]{thuthesis}

在最新版的模板中，如果不填 fontset 选项，模板会尝试寻找 mac 版 microsoft word 的中易字体。也可以指定 `fontset = mac-word`。

**Comment by qinyuxian** [comment]
fontset = mac-word
报错。

**Comment by zepinglee** [comment]
> fontset = mac-word 报错。

如果你装了 mac 版 word，请给出具体的报错。

**Comment by qinyuxian** [comment]
```
\xeCJKsetup{EmboldenFactor=3}%
\setCJKmainfont{SimSun}[%
Path         = /Applications/Microsoft Word.app/Contents/Resources/DFonts/,
AutoFakeBold = true,
ItalicFont   = KaiTi,
]%
\setCJKsansfont{SimHei}[%
Path         = /Applications/Microsoft Word.app/Contents/Resources/DFonts/,
AutoFakeBold = true,
]%
\setCJKmonofont{FangSong}[Path=/Applications/Microsoft Word.app/Contents/Resources/DFonts/]%

\setCJKfamilyfont{zhsong}{SimSun}[%
Path         = /Applications/Microsoft Word.app/Contents/Resources/DFonts/,
AutoFakeBold = true,
]%
\setCJKfamilyfont{zhhei}{SimHei}[%
Path         = /Applications/Microsoft Word.app/Contents/Resources/DFonts/,
AutoFakeBold = true,
]%
\setCJKfamilyfont{zhkai}{KaiTi}[Path = /Applications/Microsoft Word.app/Contents/Resources/DFonts/]%
\setCJKfamilyfont{zhfs}{FangSong}[Path = /Applications/Microsoft Word.app/Contents/Resources/DFonts/]%
```

没办法，只好这样弄了。

**Comment by zepinglee** [comment]
> fontset = mac-word 报错。

我记错了，应该是 `cjk-font=mac-word`

**Comment by qinyuxian** [comment]
> > fontset = mac-word 报错。
> 
> 我记错了，应该是 `cjk-font = mac-word`

报错。

Class thuthesis Error: Invalid value "cjk-font = mac-word". \ProcessKeyvalOptions*

**Comment by zepinglee** [comment]
> > > fontset = mac-word 报错。
> > 
> > 
> > 我记错了，应该是 `cjk-font = mac-word`
> 
> 报错。
> 
> Class thuthesis Error: Invalid value "cjk-font = mac-word". \ProcessKeyvalOptions*

需要使用最新的模板。手动配置字体也行吧。

**Comment by qinyuxian** [comment]
既然要求最终稿是windows字体，建议以后的版本里对于mac系统把字体设置锁死。就算用mac的字体能够编译出来，但是又不符合规定，这样做出来没有意义。

**Comment by Harry-Chen** [comment]
> 既然要求最终稿是windows字体，建议以后的版本里对于mac系统把字体设置锁死。就算用mac的字体能够编译出来，但是又不符合规定，这样做出来没有意义。

使用者并不总是需要提交版本，如果这么做的话，会带来很多不便，比如 Overleaf 无法使用模板。

关于提交需要使用 Windows 字体这一事实，我们已经在文档中说明了。

**Comment by Harry-Chen** [comment]
此外，在本 issue 中和 #784 的交流中，您多次未能提供完整信息。我也认为您的态度并没有表现出对维护者足够的尊重。根据 [行为准则](https://github.com/tuna/issues/blob/master/CODE_OF_CONDUCT.md)，我作为 TUNA 组织管理员提出正式警告。
