### ISSUE TITLE
本科生公式和附录图片标号格式

### ISSUE THREAD

**Issue by ljy9912** [tuna/thuthesis#788]
## 编译环境
编译的系统：Manjaro
TeX 发行版：TeX Live 2021
模板版本：v7.3.0
模板类型：bachelor

## 描述问题
《本科生学位论文写作指南》第 3 页要求

> 公式的编号写在括号内，置于公式行末，其间不加虚线。如：（1-2）。

>附录A中图、表、公式的编号，应与正文中的编号区分开，即在阿拉伯数码前冠以附录的编号，如图A-1，表A-2，（A-3）等。

而模板编译的结果是

![image](https://user-images.githubusercontent.com/52590562/169525258-7362e0ed-bfd3-4257-bf06-7f8915cbd687.png)

![image](https://user-images.githubusercontent.com/52590562/169525295-dd908813-c33a-406d-b9bb-a5048c42d92e.png)

**Comment by zepinglee** [comment]
本科生《指南》并没有规定图、表、公式编号的分隔符，第 4 页还有句点的示例。
<img width="663" alt="Screen Shot 2022-05-20 at 20 26 38" src="https://user-images.githubusercontent.com/12290822/169527825-77a6c7d0-de95-46a3-81fb-d5a3de6d63fa.png">

可以理解为跟研究生的《指南》一样，分隔符使用“.”和“-”均可。而且按照习惯通常全文保持一致。模板选择默认“.”主要是因为“-”容易与表示数值范围的 en dash “–”混淆。

另外也可以使用 `\thusetup{number-separator = -}`设置分隔符。

**Comment by ljy9912** [comment]
好的明白了，感谢！
