### ISSUE TITLE
7.3.0设置language=english之后，摘要往后的部分无法编译

### ISSUE THREAD

**Issue by sxndqc** [tuna/thuthesis#790]
## 编译环境
编译的系统：Overleaf
TeX 发行版：TeX Live 2021
模板版本：v7.3.0
模板类型：master

## 描述问题
按照 http://ctan.math.utah.edu/ctan/tex-archive/macros/latex/contrib/thuthesis/thuthesis.pdf 第8页的描述，设置论文language为english之后，出现摘要之后的部分无法编译的情况（即输出总共只有10页），并报出下图所示错误；去掉language设置之后恢复正常。

截图：
![image](https://user-images.githubusercontent.com/20756531/169824435-08b15670-3715-4a67-a284-126349e17b35.png)

复现上述问题的代码：
```TeX
\thusetup{
    language = english,
}
```

**Comment by zepinglee** [comment]
原来是这里少了 “=”。

https://github.com/tuna/thuthesis/blob/6f59c86178e08cbc95146a3e5d987552fddfda9b/thuthesis.dtx#L2653
