### ISSUE TITLE
摘要页码为大写英文字母而非罗马数字

### ISSUE THREAD

**Issue by xiaoqyaoyao** [tuna/thuthesis#792]
在overleaf上采用模版编译后摘要到目录为止的页码均为大写英文字母而非罗马数字。

**Comment by zepinglee** [comment]
无法复现。

请按照 issue 模板填写必要的信息。

**Comment by xiaoqyaoyao** [comment]
姓名学院做了匿名处理，其他为thusetup配置内容：
% !TeX root = ./Main.tex

% 论文基本信息配置

\thusetup{
  %******************************
  % 注意：
  %   1. 配置里面不要出现空行
  %   2. 不需要的配置信息可以删除
  %   3. 建议先阅读文档中所有关于选项的说明
  %******************************
  %
  % 输出格式
  %   选择打印版（print）或用于提交的电子版（electronic），前者会插入空白页以便直接双面打印
  %
  output = electronic,
  %
  % 标题
  %   可使用“\\”命令手动控制换行
  %
  title  = {标题},
  title* = {Title},
  %
  % 学位
  %   1. 学术型
  %      - 中文
  %        需注明所属的学科门类，例如：
  %        哲学、经济学、法学、教育学、文学、历史学、理学、工学、农学、医学、
  %        军事学、管理学、艺术学
  %      - 英文
  %        博士：Doctor of Philosophy
  %        硕士：
  %          哲学、文学、历史学、法学、教育学、艺术学门类，公共管理学科
  %          填写“Master of Arts“，其它填写“Master of Science”
  %   2. 专业型
  %      直接填写专业学位的名称，例如：
  %      教育博士、工程硕士等
  %      Doctor of Education, Master of Engineering
  %   3. 本科生不需要填写
  %
  degree-name  = {博士},
  degree-name* = {Doctor of Philosophy},
  %
  % 培养单位
  %   填写所属院系的全名
  %
  department = {XX学院},
  %
  % 学科
  %   1. 学术型学位
  %      获得一级学科授权的学科填写一级学科名称，其他填写二级学科名称
  %   2. 工程硕士
  %      工程领域名称
  %   3. 其他专业型学位
  %      不填写此项
  %   4. 本科生填写专业名称，第二学位论文需标注“（第二学位）”
  %
  discipline  = {XX},
  discipline* = {XX},
  %
  % 姓名
  %
  author  = {},
  author* = {},
  %
  % 指导教师
  %   中文姓名和职称之间以英文逗号“,”分开，下同
  %
 supervisor  = {},
  supervisor* = {},
  %
  % 副指导教师
  %
  associate-supervisor  = {},
  associate-supervisor* = {},
  %
  % 联合指导教师
  %
  % co-supervisor  = {某某某, 教授},
  % co-supervisor* = {Professor Mou Moumou},
  %
  % 日期
  %   使用 ISO 格式；默认为当前时间
  %
  % date = {2019-07-07},
  %
  % 是否在中文封面后的空白页生成书脊（默认 false）
  %
  include-spine = true,
  %
  % 密级和年限
  %   秘密, 机密, 绝密
  %
  % secret-level = {秘密},
  % secret-year  = {10},
  %
  % 博士后专有部分
  %
  % clc                = {分类号},
  % udc                = {UDC},
  % id                 = {编号},
  % discipline-level-1 = {计算机科学与技术},  % 流动站（一级学科）名称
  % discipline-level-2 = {系统结构},          % 专业（二级学科）名称
  % start-date         = {2011-07-01},        % 研究工作起始时间
}



%\setCJKmainfont{SIMSUN.TTC}
% 载入所需的宏包

% 定理类环境宏包
\usepackage{amsthm}
% 也可以使用 ntheorem
% \usepackage[amsmath,thmmarks,hyperref]{ntheorem}

\thusetup{
  %
  % 数学字体
  % math-style = GB,  % GB | ISO | TeX
  math-font  = xits,  % sitx | xits | libertinus
}

% 可以使用 nomencl 生成符号和缩略语说明
% \usepackage{nomencl}
% \makenomenclature

% 表格加脚注
\usepackage{threeparttable}
\usepackage{threeparttablex}
% 表格中支持跨行
\usepackage{multirow}

% 固定宽度的表格。
% \usepackage{tabularx}

% 跨页表格和表格注释
\usepackage{longtable}
\usepackage{afterpage}
% outline
\usepackage{outlines}
% 算法
\usepackage{algorithm}
\usepackage{algorithmic}

% 量和单位
\usepackage{siunitx}

% 参考文献使用 BibTeX + natbib 宏包
% 顺序编码制
%\usepackage[sort]{natbib}
%\bibliographystyle{thuthesis-numeric}

% 著者-出版年制
 \usepackage{natbib}
 \bibliographystyle{thuthesis-author-year}

% 本科生参考文献的著录格式
% \usepackage[sort]{natbib}
% \bibliographystyle{thuthesis-bachelor}

% 参考文献使用 BibLaTeX 宏包
% \usepackage[backend=biber,style=thuthesis-numeric]{biblatex}
% \usepackage[backend=biber,style=thuthesis-author-year]{biblatex}
% \usepackage[backend=biber,style=apa]{biblatex}
% \usepackage[backend=biber,style=mla-new]{biblatex}
% 声明 BibLaTeX 的数据库
% \addbibresource{ref/refs.bib}

% 定义所有的图片文件在 figures 子目录下
\graphicspath{{figures/}}

% 数学命令
\makeatletter
\newcommand\dif{%  % 微分符号
  \mathop{}\!%
  \ifthu@math@style@TeX
    d%
  \else
    \mathrm{d}%
  \fi
}
\makeatother

% hyperref 宏包在最后调用
\usepackage{hyperref}

**Comment by zepinglee** [comment]
> 姓名学院做了匿名处理，其他为thusetup配置内容：

跟这部分无关，请给出主文档 `thuthesis-example.tex` 的示例。

> 顺便想问一下如果自定义了几个文件夹用input命令包含在Main.tex里面是不是会造成一些意想不到的后果，谢谢！

关键在于你的内容是怎么组织的。

**Comment by xiaoqyaoyao** [comment]
% !TeX encoding = UTF-8
% !TeX program = xelatex
% !TeX spellcheck = en_US

\documentclass[degree=doctor]{thuthesis}
  % 学位 degree:
  %   doctor | master | bachelor | postdoc
  % 学位类型 degree-type:
  %   academic（默认）| professional
  % 语言 language
  %   chinese（默认）| english
  % 字体库 fontset
  %   windows | mac | fandol | ubuntu
  % 建议终版使用 Windows 平台的字体编译


% 论文基本配置，加载宏包等全局配置
\input{thusetup}


\begin{document}

% 封面
\maketitle

% 学位论文指导小组、公开评阅人和答辩委员会名单
\input{chapters/other/committee}

% 使用授权的说明
\copyrightpage
% 将签字扫描后授权文件 scan-copyright.pdf 替换原始页面
% \copyrightpage[file=scan-copyright.pdf]

%\frontmatter
\input{chapters/other/abstract}

% 目录
\tableofcontents

% 插图和附表清单
% 本科生的插图索引和表格索引需要移至正文之后、参考文献前
\listoffiguresandtables  % 插图和附表清单
% \listoffigures           % 插图清单
% \listoftables            % 附表清单

% 符号对照表
%\input{data/other/denotation}


% 正文部分
\mainmatter
\input{chapters/chap01/chap01}
\input{chapters/chap02/chap02}
\input{chapters/chap03/chap03}
\input{chapters/chap04/chap04}
\input{chapters/chap05/chap05}
\input{chapters/chap06/chap06}
% 其他部分
\backmatter

% 参考文献
\bibliography{ref/refs}  % 参考文献使用 BibTeX 编译
% \printbibliography       % 参考文献使用 BibLaTeX 编译

% 附录
\appendix
% \input{chapters/appendix-survey}       % 本科生：外文资料的调研阅读报告
% \input{chapters/appendix-translation}  % 本科生：外文资料的书面翻译
\input{chapters/other/appendix}

% 致谢
\input{chapters/other/acknowledgements}

% 声明
\statement
% 将签字扫描后的声明文件 scan-statement.pdf 替换原始页面
% \statement[file=scan-statement.pdf]
% 本科生编译生成的声明页默认不加页脚，插入扫描版时再补上；
% 研究生编译生成时有页眉页脚，插入扫描版时不再重复。
% 也可以手动控制是否加页眉页脚
% \statement[page-style=empty]
% \statement[file=scan-statement.pdf, page-style=plain]

% 个人简历、在学期间完成的相关学术成果
\input{chapters/other/resume}

% 指导教师/指导小组学术评语
\input{chapters/other/comments}

% 答辩委员会决议书
\input{chapters/other/resolution}

% 本科生的综合论文训练记录表（扫描版）
% \record{file=scan-record.pdf}

\end{document}

**Comment by zepinglee** [comment]
摘要页码为大写英文字母是因为注释了 `\frontmatter`。

**Comment by xiaoqyaoyao** [comment]
感谢🙏
