### ISSUE TITLE
xelatex以外的编译方式？

### ISSUE THREAD

**Issue by Sam-Hou** [tuna/thuthesis#799]
## 描述问题
目前的最新版本是否支持xelatex以外的编译方式，例如latex, pdflatex？由于想直接把论文部分内容放到arxiv上，但arxiv对用tex写的文章必须上传原始的tex文件，arxiv本身又不支持xelatex，所以arxiv会报错Class thuthesis Error: XeLaTeX is required to compile this document.

**Comment by xkwxdyy** [comment]
arxiv 有自己的模版吗？

**Comment by Sam-Hou** [comment]
哦哦好的，谢谢！
