### ISSUE TITLE
一章中有超过十张插图时，插图清单的缩进

### ISSUE THREAD

**Issue by JackQian19** [tuna/thuthesis#801]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2019
模板版本：v7.3.0
模板类型：master

## 描述问题
当一章中有超过十张插图时，插图清单中会如下显示：
![image](https://user-images.githubusercontent.com/107017600/172289193-891b7636-2942-4da4-bbb7-b03c0642edcb.png)
学校的word模板中即为此格式，图编号和标题间为2个空格，理应没有问题，但审核格式的老师认为不美观，希望图的名字可以对齐，不知道应该如何对模板进行修改可以实现这点呢？

**Comment by zepinglee** [comment]
https://github.com/tuna/thuthesis/blob/4c44459f9bc5f6f5b733f7cb2cb4e43d00b56375/thuthesis.dtx#L5411-L5414

改成

```tex
\titlecontents{figure}
  [3em]{}
  {\contentslabel[\figurename~\thecontentslabel]{3em}}{\hspace{-3em}}
  {\nobreak\thu@leaders\nobreak\hfil\thecontentspage}
```

<img width="113" alt="Screen Shot 2022-06-15 at 19 55 34" src="https://user-images.githubusercontent.com/12290822/173821336-10006796-593a-445a-bbd7-0c74de66d77a.png">
