### ISSUE TITLE
模板使用示例文档中的“符号和缩略语说明”小节中存在bug

### ISSUE THREAD

**Issue by AlanruoyuLiu** [tuna/thuthesis#804]
## 编译环境
编译的系统：Windows 10 / Ubuntu 18.04 / Overleaf
TeX 发行版：TeX Live 2022
模板版本：v7.3.0
模板类型：master

## 描述问题
《研究生学位论文写作指南》第 8 页的第2.3.8小节中要求“符号和缩略语说明”中的英文采用Times New Roman 体。
而使用默认的模板编译得到thuthesis-example中的第 15 页的“符号和缩略语说明”中数学环境中的结果是斜体，并不是Times New Roman 体。

截图：
thuthesis-example的截图如：
![image](https://user-images.githubusercontent.com/31504274/186372008-1ddb4d41-90d9-41af-9933-7cb79c0aa1ec.png)

但是我用默认的 word 模板中的手打出来相应的数学符号时是Times New Roman 体，如下图：
![image](https://user-images.githubusercontent.com/31504274/186372619-ee7af441-c921-4c07-af9c-9648c4d76f21.png)

复现上述问题的代码：
```TeX
\documentclass[degree=master,degree-type=professional,fontset=windows]{thuthesis}
\begin{document}
$E_a$
\end{document}
```
在默认模板中的 denotation.tex 文件中
![image](https://user-images.githubusercontent.com/31504274/186373057-8c5b64ae-793c-43dd-85f2-e61dd7dca5d1.png)

# 实际上我遇到的问题
我使用该模板书写了英文符号，但是编译出来的结果符号不是《研究生学位论文写作指南》中所要求的 Times New Roman 体。
并且论文审稿人指出：**下标不是斜体。**
目前我的论文中有不少这样的英文符号，如下图：
![image](https://user-images.githubusercontent.com/31504274/186374127-b7c6f9ba-323a-4d00-a894-0b024b16aa98.png)

正好发现给的默认示例文档中就有类似的问题，所以就提出了这个bug。

# 希望找到的答案
请问应该如何通过全局的方式，统一改变文中的英文符号为 Times New Roman 体，尤其是这个下标的问题。
因为一个一个的修改，把$E_a$变成$\mathrm{E_a}$实在是有点费劲。

我也稍微懂一点VIM，我目前有打算用VIM去实现全局替换的想法，但是如何去实现还是有点不大清楚。
个人觉得最好的方法就是在Latex模板中通过全局设置实现相应的修改是最方便的。

谢谢您的帮助，期待您的回复 : )

**Comment by zepinglee** [comment]
1. 斜体和 Times New Roman 不是同一个维度的属性，Times New Roman 也有斜体。
2. 一般表示数学变量、物理量要用斜体字母，但表示描述性的短语应该使用正体，比如你 `$f_{rep}$` 中如果“rep”表示如“repeat”这样的描述性词语的缩写，应该写成 `$f_{\text{rep}}$`。如果表示 r, e, p 三个量的话就保持现有的样式。关于正斜体参考 GB 3100～3102 的国家标准或者咨询导师。

**Comment by zepinglee** [comment]
对。也可以用 VS Code 进行全局替换。
