### ISSUE TITLE
Overleaf中，fontset = windows后，所有中文都变成了框

### ISSUE THREAD

**Issue by LUKE-ZZ** [tuna/thuthesis#806]
## 编译环境
编译的系统：Overleaf
TeX 发行版：Overleaf
模板版本：v7.2.4
模板类型：doctor

## 描述问题
fontset = windows之后，模板编译的结果是所有中文都变成了框

截图：

复现上述问题的代码：
```TeX
\documentclass[degree = doctor, fontset = windows]{thuthesis}
```
![Untitled](https://user-images.githubusercontent.com/51853399/187626834-ca64c8e1-8280-495d-8f77-52d8041b6ba8.png)

如果是没有设定fontset，中文可以正常显示
\documentclass[degree = doctor]{thuthesis}

**Comment by zepinglee** [comment]
Overleaf 上没有 Windows 的字体，需要在 Windows 平台编译，或者，使用更为灵活的方式，将 Windows 字体传上去。
