### ISSUE TITLE
声明后面插入一个PDF文件出现空页

### ISSUE THREAD

**Issue by LUKE-ZZ** [tuna/thuthesis#807]
## 编译环境
编译的系统：Overleaf
TeX 发行版：Overleaf
模板版本：v7.2.4
模板类型：doctor

## 描述问题
我想在声明后面插入一个PDF文件

上传的PDF文件为A4大小的word文档转为的PDF文件，但是对Latex不是很熟悉，就想把自己的PDF文件重命名为record，通过    %\record{file=scan-record.pdf}插入在声明后面，则声明和新加的声明之间出现不明空页。如果删掉声明行(\statement[file=scan-statement.pdf])，就没有空页

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{thuthesis}
\begin{document}

\statement[file=scan-statement.pdf]
\record{file=scan-record.pdf}

\end{document}
```

另外如果认为将statement转变为PDF文档，和record合并成一个含有2页内容的文档，作为scan-statement上传，使用\statement[file=scan-statement.pdf]插入，则只显示PDF文档的第一页

希望能排查Bug，谢谢！

**Comment by zepinglee** [comment]
`\record` 命令专门用于本科生的“综合论文训练记录表”，所以包含其对应的格式设置，所以不适用于你的使用场景。

源码中可以看到，导致空白页是其中的 `\cleardoublepage`。

https://github.com/tuna/thuthesis/blob/a0d97d5bfe1d1e20761ddebfaf7392478680905a/thuthesis.dtx#L6326-L6343

建议使用 `pdfpage` 宏包原始的 `\includepdf` 命令，可以自由控制格式。模板中的 `\statement` 和 `\record` 也是通过屌哦用 `\includepdf` 实现的。
