### ISSUE TITLE
请问论文标题如何自行定义换行位置呢？

### ISSUE THREAD

**Issue by LUKE-ZZ** [tuna/thuthesis#808]
## 编译环境
编译的系统：Overleaf
TeX 发行版：Overleaf
模板版本：v7.2.4
模板类型：doctor

## 描述问题

比如我的论文标题是“甲甲甲甲甲甲甲甲甲甲甲甲甲甲甲甲甲甲乙乙乙乙乙乙”， 我想显示的效果为在甲和乙都是单独一行，也就是编译后显示为：

甲甲甲甲甲甲甲甲甲甲甲甲甲甲甲甲甲甲
                    乙乙乙乙乙乙

因为这样论文看上去不会分割语义。但是如果用\\或者直接两个回车都没能实现这样的功能。请问如何实现呢？

截图：
![Untitled](https://user-images.githubusercontent.com/51853399/187826361-cad27b73-ed91-4093-b186-57a11e2833a2.png)

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{thuthesis}
\begin{document}
title  = {甲甲甲甲甲甲甲甲甲甲甲甲甲甲甲甲甲甲乙乙乙乙乙乙},
\end{document}
```

**Comment by zhoulvyylj** [comment]
啊这个刚刚和别人讨论，知道怎么解决了，
用这个换行就可以了，建议在标题附近的注释那里更新一下
\protect\\

**Comment by zepinglee** [comment]
示例中就是使用 `\\` 换行的：

https://github.com/tuna/thuthesis/blob/d51530e91511f67d69c2890bb7fb2c7dfb3186c0/thusetup.tex#L21

**Comment by LUKE-ZZ** [comment]
> 示例中就是使用 `\\` 换行的：
> 
> https://github.com/tuna/thuthesis/blob/d51530e91511f67d69c2890bb7fb2c7dfb3186c0/thusetup.tex#L21

感谢解答，不过我在overleaf环境下，用两个\的确就会报错。。。
建议可以备注：可以考虑使用"\protect\\"强制手动换行，谢谢！

**Comment by Harry-Chen** [comment]
> > 示例中就是使用 `\\` 换行的：
> > https://github.com/tuna/thuthesis/blob/d51530e91511f67d69c2890bb7fb2c7dfb3186c0/thusetup.tex#L21
> 
> 感谢解答，不过我在overleaf环境下，用两个\的确就会报错。。。 建议可以备注：可以考虑使用"\protect\"强制手动换行，谢谢！

是否能给出具体的报错呢？

**Comment by LUKE-ZZ** [comment]
> > > 示例中就是使用 `\\` 换行的：
> > > https://github.com/tuna/thuthesis/blob/d51530e91511f67d69c2890bb7fb2c7dfb3186c0/thusetup.tex#L21
> > 
> > 
> > 感谢解答，不过我在overleaf环境下，用两个\的确就会报错。。。 建议可以备注：可以考虑使用"\protect"强制手动换行，谢谢！
> 
> 是否能给出具体的报错呢？

你好，非常吊诡的是，我刚刚想在overleaf中复现这个问题，发现又不报错了。。。不知道会不会是overleaf中使用的tex环境有更新？

**Comment by LUKE-ZZ** [comment]
> > 示例中就是使用 `\\` 换行的：
> > https://github.com/tuna/thuthesis/blob/d51530e91511f67d69c2890bb7fb2c7dfb3186c0/thusetup.tex#L21
> 
> 感谢解答，不过我在overleaf环境下，用两个\的确就会报错。。。 建议可以备注：可以考虑使用"\protect\"强制手动换行，谢谢！

抱歉之前因为没有使用代码的格式，导致显示有误，我使用强制手动换行的命令是`\protect\\`，可以考虑加到注释里，以免其他人可能在某些环境中出现换行报错

**Comment by Harry-Chen** [comment]
据我的理解，并没有必要在这里使用 `\protect`

**Comment by zepinglee** [comment]
> 你好，非常吊诡的是，我刚刚想在overleaf中复现这个问题，发现又不报错了。。。不知道会不会是overleaf中使用的tex环境有更新？

下次反馈问题时把报错内容贴上。
