### ISSUE TITLE
关于OverLeaf中无法使用标准字体的解决方法

### ISSUE THREAD

**Issue by LUKE-ZZ** [tuna/thuthesis#811]
OverLeaf中没有和学校标准中完全一致的标准的宋体黑体，答辩秘书老师看了我论文，说字体很奇怪

尝试上传字体发现总是有问题。也尝试了使用一些命令，但是效果都不理想。找到一个解决方法如下：

首先使用一个windows电脑安装liveTEX
http://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet/install-tl-windows.exe
时间可能会比较久，我花了3小时。

安装完成后abort按钮会变灰，有welcome界面

在OverLeaf网站上打开文档后，点击左上角的OverLeaf叶子图标，点击"Source"下载整个文档的压缩包，解压，找到tex主文件，会默认用texwork editor打开，点击绿色编译按钮即可得到非常标准字体的文件

**Comment by zepinglee** [comment]
不存在“标准字体”的概念。Word 模板中使用的是 Windows 默认的中易公司的宋黑楷字体。还有方正的、Adobe 的。

**Comment by LUKE-ZZ** [comment]
我没说清楚，抱歉哈，我指的是写作指南里要求的那些字体。。

**Comment by LUKE-ZZ** [comment]
而且我发现不知道为什么Overleaf下载下来的包在texworks editor里编译，需要XeLatex编译两次，BiTex编译一次，XeLatex编译一次，BiTex编译一次，XeLatex编译一次，这样吊诡的顺序之后，才会交叉引用和参考文献都显示正常

**Comment by zepinglee** [comment]
参考文档中关于编译方法的说明：
<img width="685" alt="Screen Shot 2022-09-27 at 08 51 47" src="https://user-images.githubusercontent.com/12290822/192406370-76657818-1fbe-47d0-bd6b-e59d6aeb94e2.png">

**Comment by LUKE-ZZ** [comment]
> 参考文档中关于编译方法的说明： <img alt="Screen Shot 2022-09-27 at 08 51 47" width="685" src="https://user-images.githubusercontent.com/12290822/192406370-76657818-1fbe-47d0-bd6b-e59d6aeb94e2.png">

谢谢~

**Comment by aliloke** [comment]
赞，我也遇到这个问题，试一试
