### ISSUE TITLE
表格中出现超长英文单词时，无法自动换行

### ISSUE THREAD

**Issue by LUKE-ZZ** [tuna/thuthesis#818]
## 编译环境
编译的系统：Overleaf
TeX 发行版：TeX Live 2022
模板版本：v7.2.4
模板类型：doctor

## 描述问题
生物相关的论文中，会出现由几十个英文字母构成的某些引物序列。这会被识别成一个长单词，从而在使用longtable编译的结果中，出现无法自动换行，顶到相邻单元格中的现象

截图：
![image](https://user-images.githubusercontent.com/51853399/199377421-ba9b9658-26aa-4c7c-a49c-fa3d79bb8785.png)

复现上述问题的代码：

```
\begin{longtable}{m{2.5cm}<{\centering}m{6.7cm}<{\centering}m{4.2cm}<{\centering}}
    \caption{本文中使用的引物} \\
    \toprule
      引物名称	&序列 &备注   \\
    \midrule
  \endfirsthead
    \caption*{续表~\thetable\quad 本文中使用的引物} \\
    \toprule
       引物名称	&序列 &备注 \\
    \midrule
  \endhead
    \bottomrule
  \endfoot
(0)Backbone\_ F &TGCGAGATCTCTAAGCCAGCGAGCTCCAATTCGCCCTATA &扩增供体质粒中质粒骨架的正向引物\\
(0)Backbone\_ R3 &AGGGAACTTAGAGGATGGGAGGTACCAGCTTTTGTTCCCT &扩增供体质粒中质粒骨架的反向引物\\

  \label{引物}
\end{longtable}
```

**Comment by Harry-Chen** [comment]
可以在过长的单词中插入 `\-` 标记断行点

**Comment by LUKE-ZZ** [comment]
> 可以在过长的单词中插入 `\-` 标记断行点

请问有没有什么方法可以自动在中间断行呢，因为有比较多这样的超长单词，如果不在中间断行，会显得格式很不整齐；如果手动给这些加断行，会有些费时。期待解答，谢谢！

**Comment by atxy-blip** [comment]
建议用 [`seqsplit`](http://mirrors.ctan.org/macros/latex/contrib/seqsplit/seqsplit.pdf) 宏包提供的 `\seqsplit` 命令：

```tex
\documentclass{thuthesis}
\usepackage{longtable,seqsplit}

\begin{document}

\begin{longtable}{m{2.5cm}<{\centering}m{6.7cm}<{\centering}m{4.2cm}<{\centering}}
    \caption{本文中使用的引物} \\
    \toprule
      引物名称	&序列 &备注   \\
    \midrule
  \endfirsthead
    \caption*{续表~\thetable\quad 本文中使用的引物} \\
    \toprule
       引物名称	&序列 &备注 \\
    \midrule
  \endhead
    \bottomrule
  \endfoot
(0)Backbone\_ F &\seqsplit{TGCGAGATCTCTAAGCCAGCGAGCTCCAATTCGCCCTATA} &扩增供体质粒中质粒骨架的正向引物\\
(0)Backbone\_ R3 &\seqsplit{AGGGAACTTAGAGGATGGGAGGTACCAGCTTTTGTTCCCT} &扩增供体质粒中质粒骨架的反向引物\\

  \label{引物}
\end{longtable}

\end{document}
```

<img width="377" alt="image" src="https://user-images.githubusercontent.com/63113546/205478878-a5eb5aeb-df29-49cd-bd2f-aa3711b7a1ce.png">

**Comment by LUKE-ZZ** [comment]
> 建议用 [`seqsplit`](http://mirrors.ctan.org/macros/latex/contrib/seqsplit/seqsplit.pdf) 宏包提供的 `\seqsplit` 命令。这个包是专门为 DNA 序列开发的，使得任意两个字母间都能断行。
> 
> 示例见：
> 
> ```
> \documentclass{thuthesis}
> \usepackage{longtable,seqsplit}
> 
> \begin{document}
> 
> \begin{longtable}{m{2.5cm}<{\centering}m{6.7cm}<{\centering}m{4.2cm}<{\centering}}
>     \caption{本文中使用的引物} \\
>     \toprule
>       引物名称	&序列 &备注   \\
>     \midrule
>   \endfirsthead
>     \caption*{续表~\thetable\quad 本文中使用的引物} \\
>     \toprule
>        引物名称	&序列 &备注 \\
>     \midrule
>   \endhead
>     \bottomrule
>   \endfoot
> (0)Backbone\_ F &\seqsplit{TGCGAGATCTCTAAGCCAGCGAGCTCCAATTCGCCCTATA} &扩增供体质粒中质粒骨架的正向引物\\
> (0)Backbone\_ R3 &\seqsplit{AGGGAACTTAGAGGATGGGAGGTACCAGCTTTTGTTCCCT} &扩增供体质粒中质粒骨架的反向引物\\
> 
>   \label{引物}
> \end{longtable}
> 
> \end{document}
> ```
> 
> <img alt="image" width="377" src="https://user-images.githubusercontent.com/63113546/205478878-a5eb5aeb-df29-49cd-bd2f-aa3711b7a1ce.png">

感谢解答！原谅我可能有点过于强迫症，看到上下两行不等长会很难受，请问这个包可以通过什么设置，让换行后的两行等长吗？谢谢！

**Comment by atxy-blip** [comment]
`seqsplit` 包能做的只是在每个字符中间插入断行点。自动对齐这种事情 corner case 太多，费力不讨好。倒是可以自行修改表格列宽或者拿 `\parbox` 套一层限制宽度，不过这就又回到了“手动加断行”的出发点了。
