### ISSUE TITLE
版本7.3.1的zip文件上传到overleaf后无法编译

### ISSUE THREAD

**Issue by Jiandang1995** [tuna/thuthesis#820]
## 编译环境
编译的系统：Overleaf
TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
模板版本：v7.3.1
模板类型：master

## 描述问题
最新发布的7.3.1的zip文件可以在本地的texstudio上运行，但上传至overleaf后无法编译，（貌似是因为书脊的问题）
截图：
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/118841033/203376209-18ea60b1-7aa1-4dce-9877-8d80ba730331.png">
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/118841033/203376529-8ecdcd9f-cebc-4843-84e0-324d597715d5.png">

复现上述问题的代码：
\documentclass[degree=master]{thuthesis}
\input{thusetup.tex}
% \thusetup{
%   spine-font   = {\zihao{3}},
%   spine-title  = {书脊的标题},
%   spine-author = {书脊的作者姓名},
% }
\begin{document}
\spine
\end{document}

**Comment by zepinglee** [comment]
> XeLaTeX or LuaLaTeX is required to compile this document.

**Comment by Jiandang1995** [comment]
Thanks a lot!
