### ISSUE TITLE
在学期间完成的相关学术成果应连续编号

### ISSUE THREAD

**Issue by tylovehhx** [tuna/thuthesis#825]
清华大学研究生院颁发的《研究生学位论文写作指南》第10页中说“在学期间完成的相关学术成果按照学术成果类型分列并连续编号”。

另外，研究生院所提供的Word模板中的学术成果也是连续编号，即专利成果的编号应从论文成果的最后一号开始，而不是从[1]开始。如下所示：
<img width="440" alt="截屏2023-01-13 17 23 58" src="https://user-images.githubusercontent.com/22938317/212284970-3f8802ab-3c97-4c78-b5e2-52ecdd4f7815.png">

目前的latex模板中，学术成果为每类从[1]开始编号，不是连续编号，可否进行修改？

谢谢！

**Comment by zepinglee** [comment]
嗯，确实是个 bug。

**Comment by AKIMaxwell** [comment]
然而自动化系的格式审查，要求每类从[1]重新开始编号，可以通过注释掉所有的`resume`实现，mark一下。
`% resume     = achievements,`

**Comment by RadetzkyLi** [comment]
除了在模板里注释掉`resume` ，还可以在想要重新编号的地方设置`start`选项：
```
\begin{achievements}[start=1]
  \item 成果1
  \item 成果2
\end{achievements}
```

**Comment by Harry-Chen** [comment]
> 除了在模板里注释掉`resume` ，还可以在想要重新编号的地方设置`start`选项：
> 
> ```
> \begin{achievements}[start=1]
>   \item 成果1
>   \item 成果2
> \end{achievements}
> ```

请在 #949 讨论相应内容。
