### ISSUE TITLE
如何自定义章节目录

### ISSUE THREAD

**Issue by yuyuexi** [tuna/thuthesis#831]
我想要在英文模版中设置不同层级章节目录的格式。

比如
1. `\section`对应格式为单词首字母大写，e.g.，`\section{first section of THU thesis}` 显示为First Section of THU Thesis
2. `\subsection`对应格式为首字母大写，e.g.，`\subsection{first subsection of THU thesis}` 显示为First section of THU thesis

但是目前没有找到合适的方法。

我尝试以下两种方式来实现\section对应格式：
1. `\renewcommand{\section}[1]{\section{\textsc{#1}}}`
2. `\renewcommand{\section}[1]{\section{\capitalisewords{#1}}}`

但是都不能编译（持续编译无结果）。

我使用的是
1. MacTeX-2021 Distribution
2. thuthesis-v7.3.1

请问我应该如何实现这个功能呢？

**Comment by zepinglee** [comment]
1. 建议使用 `\ctexset` 的接口，比如 <https://github.com/tuna/thuthesis/blob/9f934e108005bb2b119683abc017d5d153340965/thuthesis.dtx#L3816-L3836>。
2. 两种大小写方式分别称为 title case 和 sentence case，一般在标题的内容中按照对应的 case 填写，不需要使用转换命令吧？你是需要标题在正文和目录中使用不同的 case？

**Comment by yuyuexi** [comment]
> 1. 建议使用 `\ctexset` 的接口，比如 https://github.com/tuna/thuthesis/blob/9f934e108005bb2b119683abc017d5d153340965/thuthesis.dtx#L3816-L3836
>    。
> 2. 两种大小写方式分别称为 title case 和 sentence case，一般在标题的内容中按照对应的 case 填写，不需要使用转换命令吧？你是需要标题在正文和目录中使用不同的 case？

多谢回复！
我希望能有这样的转换命令，以防我自己修改时出错。

我检索了一些相关资料，发现要实现这样的功能不是非常容易，目前由于时间限制，只能先放下这个问题了。


再次感谢。
