### ISSUE TITLE
在论文的正文中引用某个文献中的定理，这个定理会显示成上标

### ISSUE THREAD

**Issue by yxliu23** [tuna/thuthesis#833]
## 编译环境
编译的系统：macOS 10.14 
TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
模板版本：v5.5.2
模板类型：doctor 

## 描述问题
在论文的正文中引用某个文献中的定理，这个定理会显示成上标。怎么取消上标？

截图：
![image](https://user-images.githubusercontent.com/126556904/221796453-3a1b8c86-c86d-46df-856d-9f0f3904acbf.png)

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{thuthesis}
\begin{document}


\cite[Theorem 1.2]{DL22}


\end{document}
```

**Comment by zepinglee** [comment]
上标主要是因为引文页码的格式。

<img width="650" alt="Screenshot 2023-02-28 at 17 59 19" src="https://user-images.githubusercontent.com/12290822/221819750-d7aaf22f-2473-44ac-985b-f2e7c16dc80f.png">
