### ISSUE TITLE
引用方式无法实现上标模式

### ISSUE THREAD

**Issue by lllyyq1121** [tuna/thuthesis#838]
## 编译环境
编译的系统：macOS 10.14 
TeX 发行版：Texifier Version 1.9.19 (741)   XeLaTeX
模板版本：v7.3.1
模板类型：doctor proposal

## 描述问题
《THUTHESIS:清华大学学位论文模板》第 17  页要求 4.6.5 引用方式，super是上标模式。
而模板编译的结果是著者-出版年份模式。

相同的代码在VScode 没有问题...

截图：
<img width="342" alt="截屏2023-03-23 22 28 54" src="https://user-images.githubusercontent.com/67221144/227235493-96e666bb-d9a7-47c6-a664-fd04601dd476.png">

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{thuthesis}
\thusetup{
      thesis-type = proposal,
      cite-style = super,
}
```

**Comment by zepinglee** [comment]
你是不是选择了 `author-year` 样式？`cite-style` 只对 `numeric` 有效。

**Comment by lllyyq1121** [comment]
没有选择author-year&nbsp;，感觉似乎代码没有问题，因为在vscode配置的环境下就是没问题，感觉是texifier下xelatex环境的问题，然后变成默认的了。。cite-style没有生效
&nbsp;


林依清
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zeping ***@***.***&gt;; 
发送时间: 2023年3月24日(星期五) 中午1:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tuna/thuthesis] 引用方式无法实现上标模式 (Issue #838)





 
你是不是选择了 author-year 样式？cite-style 只对 numeric 有效。

**Comment by note286** [comment]
建议你给一个能够复现问题的MWE，从`\documentclass`到`\end{document}`都要，并描述你的编译命令分别为什么。
