### ISSUE TITLE
tsinghua的overleaf无法使用cite和双击跳转的问题

### ISSUE THREAD

**Issue by Sinica1997** [tuna/thuthesis#846]
## 编译环境
编译的系统：macOS + Overleaf
TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
模板版本：v5.5.2
模板类型：/master 

## 描述问题
在官网的overleaf完成写作后，将zip文件上传到tsinghua的overleaf上，本想得到word模板的字体，发现字体变得和word模板一样了，但是使用cite无法自动跳出引用参考文献选项以及双击右侧pdf也无法跳转到对应到tex页面行处，请问这是tsinghua版本overleaf设置的问题吗

**Comment by Harry-Chen** [comment]
此问题与本项目没有关系，请咨询相应的维护者。

**Comment by zepinglee** [comment]
印象中是某个版本 overleaf 的问题，建议联系 tsinghua 的 overleaf 的维护者。
