### ISSUE TITLE
模板中的数学格式问题和提行问题

### ISSUE THREAD

**Issue by louieworth** [tuna/thuthesis#847]
1. 在指南里面有如下：
> 以上数学符号样式的差异可以在模板中统一设置。另外国标还有一些与 AMS，不同的符号使用习惯，需要用户在写作时进行处理。 
我想要更换为美国数学学会（AMS）的符号标准，请问我该如何设置？

```
%在thusetup位置我已更改成stix为了避免出现加粗的$\sum$格式。
\thusetup{
math-font  = stix, % stix | xits | libertinus,
}
```

但是我在进行输出$\mathbb{E}$的时候，文章中出现的极丑。根据 [link](https://blog.csdn.net/xovee/article/details/104873210)进行`\usepackage{amssymb}`，当前类定义宏包为`\usepackage{amsthm}` 更换在`thuthesis.cls`显示以下冲突：

```
\thu@package@conflict{unicode-math}{amscd}
\thu@package@conflict{unicode-math}{amsfonts}
\thu@package@conflict{unicode-math}{amssymb}
\thu@package@conflict{unicode-math}{bbm}
\thu@package@conflict{unicode-math}{bm}
\thu@package@conflict{unicode-math}{eucal}
\thu@package@conflict{unicode-math}{eufrak}
\thu@package@conflict{unicode-math}{mathrsfs}
\thu@package@conflict{unicode-math}{newtxmath}
\thu@package@conflict{unicode-math}{upgreek}
```

2.  如何更换文章换段落是提行模式（英文），不是中文的缩进模式？

**Comment by zepinglee** [comment]
> 我想要更换为美国数学学会（AMS）的符号标准，请问我该如何设置？

`math-style` 选择 `TeX`。

https://github.com/tuna/thuthesis/blob/900988bb93eae5395adc9a590132fb1262429222/thusetup.tex#L118

> 但是我在进行输出$\mathbb{E}$的时候，文章中出现的极丑。根据 [link](https://blog.csdn.net/xovee/article/details/104873210)进行`\usepackage{amssymb}`，当前类定义宏包为`\usepackage{amsthm}` 更换在`thuthesis.cls`显示以下冲突：
> 
> ```
> \thu@package@conflict{unicode-math}{amscd}
> \thu@package@conflict{unicode-math}{amsfonts}
> \thu@package@conflict{unicode-math}{amssymb}
> \thu@package@conflict{unicode-math}{bbm}
> \thu@package@conflict{unicode-math}{bm}
> \thu@package@conflict{unicode-math}{eucal}
> \thu@package@conflict{unicode-math}{eufrak}
> \thu@package@conflict{unicode-math}{mathrsfs}
> \thu@package@conflict{unicode-math}{newtxmath}
> \thu@package@conflict{unicode-math}{upgreek}
> ```

建议给出截图描述。你可以考虑将 `\mathbb` 设为 [newcm](https://www.ctan.org/pkg/newcomputermodern) 字体。
```
\thusetup{math-font  = xits}

\setmathfont{NewCMMath-Book}[
  Extension    = .otf,
  range        = {bb},
]%
```

模板中使用了 `unicode-math`，所以跟传统的 `amssymb` 不兼容。

> 2. 如何更换文章换段落是提行模式（英文），不是中文的缩进模式？

什么是“提行模式”？建议给个截图。

**Comment by louieworth** [comment]
> 1. 建议给出截图描述。你可以考虑将 \mathbb 设为 [newcm](https://www.ctan.org/pkg/newcomputermodern) 字体。
已解决，感谢。
> 2. 什么是“提行模式”？建议给个截图。
中文论文分段是通过，新的一行, 缩进两格。如下图：
<img width="142" alt="image" src="https://user-images.githubusercontent.com/37494792/229262159-0383755c-4ad1-45c0-afd2-d5cd4bc1bde9.png">
我想知道英文的分段模式如何设置？通过空一行体现新的段落，如下图：
<img width="213" alt="image" src="https://user-images.githubusercontent.com/37494792/229262234-11700907-bab2-4901-8ea6-acfdbf1e231f.png">

**Comment by note286** [comment]
可以设置`\parskip`和`\parindent`。

**Comment by zepinglee** [comment]
《撰写手册》规定了缩进和段前短后，如果你觉得格式审查没问题的话，可以修改

https://github.com/tuna/thuthesis/blob/900988bb93eae5395adc9a590132fb1262429222/thuthesis.dtx#L3257-L3267

以及设置`\setlength\parskip{6bp}`，后者当前为 LaTeX 默认的 `0\p@ \@plus \p@`。
