### ISSUE TITLE
个人简历、在学期间完成的相关学术成果-个人简历部分行间距过小

### ISSUE THREAD

**Issue by iznauy** [tuna/thuthesis#850]
查了下写作规范，这部分的行间距应该和正文保持一致？但是编译出来明显能感觉到这部分的行间距过小。

**Comment by Harry-Chen** [comment]
是有这个问题，

正文：

<img width="768" alt="image" src="https://user-images.githubusercontent.com/2819727/230317760-988fcec0-40ec-44f2-8948-715eb92523cb.png">


简历：

<img width="768" alt="image" src="https://user-images.githubusercontent.com/2819727/230317800-511d3688-7a3a-4a22-bb1d-d87f51e2f44f.png">

设置来自于

https://github.com/tuna/thuthesis/blob/900988bb93eae5395adc9a590132fb1262429222/thuthesis.dtx#L6207-L6209

是由 https://github.com/tuna/thuthesis/commit/8cb4ea1e4247767c7c658c6eafa3fe24a95f5451 引入的

**Comment by zepinglee** [comment]
我检查了一下，原来这里 `\fontsize{12bp}{16bp}` 只是设置“学术成果”列表的字号和行距，但是错误地设置到了整个简历部分。

在 bf93da1 中改为正确地设置“学术成果”列表。
