### ISSUE TITLE
arxiv的参考文献是不是特殊处理了？

### ISSUE THREAD

**Issue by sWildGold** [tuna/thuthesis#852]
@article{stadie2017third,
	title={Third-person imitation learning},
	author={Stadie, Bradly C and Abbeel, Pieter and Sutskever, Ilya},
	journal={arXiv preprint arXiv:1703.01703},
	year={2017}
}
我想要的效果是：
Stadie B C, Abbeel P, Sutskever I. Third-person imitation learning[J]. arXiv preprint arXiv:1703.01703, 2017.
但编译后的效果是：
Stadie B C, Abbeel P, Sutskever I. Third-person imitation learning[A].2017

**Comment by zepinglee** [comment]
1. arxiv 不是期刊，所以文献类型标识是 A 不是 J。
2. 国标没有规定预印本的格式，建议将 `arXiv:1703.01703` 填到 `numbers` 中。

**Comment by Xu-Shuhao** [comment]
是 number 不是 numbers

**Comment by aviczhl2** [comment]
填在numbers里面顺序上会有问题吧

**Comment by zepinglee** [comment]
> 填在number里面顺序上会有问题吧
> 
> 会生成这个 Stadie B C, Abbeel P, Sutskever I. Third-person imitation learning: arXiv preprint arXiv:1703.01703[A].2017

国标没有给出预印本的示例，怎么处理都可以。按照 arxiv 官方导出的 bibtex 格式也可以。

```bib
@misc{stadie2019thirdperson,
      title={Third-Person Imitation Learning}, 
      author={Bradly C. Stadie and Pieter Abbeel and Ilya Sutskever},
      year={2019},
      eprint={1703.01703},
      archivePrefix={arXiv},
      primaryClass={cs.LG}
}
```
