### ISSUE TITLE
参考文献中的note无效

### ISSUE THREAD

**Issue by ThuWangzw** [tuna/thuthesis#855]
## 编译环境
Overleaf

## 描述问题
使用的是Overleaf上的模板，bibtex中的note无效

截图：
![image](https://user-images.githubusercontent.com/26575579/230565441-b98da3cd-cc3d-462c-b498-d35e59199572.png)

复现上述问题的代码：
```TeX
 @misc{lacewell_2015, 
 title={Netscope {CNN} Analyzer}, 
 author={Lacewell, Chaunte  White}, 
 note={(2015-07-27)[2023-03-25]},
 howpublished={\url{https://dgschwend.github.io/netscope/}}
}
```

**Comment by zepinglee** [comment]
许多导出的 bibtex 数据库 `note` 字段会包含很多杂项，所以 bst 样式默认不显示。

另外 `(2015-07-27)[2023-03-25]` 应该分别填到 `date` 和 `urldate`。
