### ISSUE TITLE
本科生论文翻译部分无法正常编译显示参考文献

### ISSUE THREAD

**Issue by Photen** [tuna/thuthesis#857]
## 编译环境
编译的系统：Overleaf
TeX 发行版：TeX Live 2022
模板版本：7.2.2
模板类型：bachelor

## 描述问题
使用原模板进行编译后，在书面翻译部分的文献引用示例处显示[?]

复现上述问题的代码：
```TeX
% example.tex中：
\input{data/appendix-translation}  % 本科生：外文资料的书面翻译

% appendix_translation中：
\section{文献引用}
文献引用示例\cite{abrahams99tex}。
```

**Comment by Photen** [comment]
是在overleaf中使用xelatex直接编译的，我下载下来本地编译下试试

**Comment by zepinglee** [comment]
overleaf 是调用 latexmk 编译的。建议检查一下有没有报错。

**Comment by zepinglee** [comment]
<https://www.overleaf.com/latex/templates/thuthesis-tsinghua-university-thesis-latex-template/hrvjvrthtppg> 无法复现。

**Comment by yuxuan-z19** [comment]
@zepinglee 在[Tsinghua Overleaf](http://overleaf.tsinghua.edu.cn/)上会出现这些错误，在Overleaf上没问题

**Comment by zepinglee** [comment]
嗯，那还是联系一下该网站维护者吧。

**Comment by zepinglee** [comment]
@Harry-Chen <overleaf.tsinghua.edu.cn> 是哪边在维护呀？

**Comment by Harry-Chen** [comment]
> @Harry-Chen <overleaf.tsinghua.edu.cn> 是哪边在维护呀？

此前是由计算机系科协的 @sengxian 搭建的，目前的维护者我也不清楚，我去打听一下。
