### ISSUE TITLE
图文列表如何删去 (a)-(d)

### ISSUE THREAD

**Issue by SakurajimaMaiii** [tuna/thuthesis#858]
在图注中，可能会需要标注子图的内容。
比如
`XXXX. (a) XXXX (b) XXXX`
但是系里面格式审查的要求是：_图文列表中如果有(a)~(d)等，应删去，只保留主标题，因为这里只是索引目的，需要简洁_

想问一下这个应该如何设置，可以使得插图列表里面没有(a)(b)等内容，但是正文的图注里面有
（模板使用的\listoffigures会把正文插图图注的所有内容都放到插图列表里面）
（我使用的是 Windows11+v7.3.1版本，不知道这个是否有影响？）
比如在**正文中**的图注是这个样子：
![tempsnip](https://user-images.githubusercontent.com/83657651/231351824-787ef9bc-0dc9-46f7-9cba-1c2e20c5fea9.png)
我想在插图列表中只显示（a) 前面的内容

**Comment by note286** [comment]
`\caption[xxx]{yyy}`

**Comment by SakurajimaMaiii** [comment]
> `\caption[xxx]{yyy}`

这样是可以的，感谢！
（我直接关掉issue了）
