### ISSUE TITLE
模板使用文档西文主要字体Palatino在macOS下无法正常输出小型大写字母

### ISSUE THREAD

**Issue by MS-Windows** [tuna/thuthesis#859]
在 macOS（Ventura）下，配合 MacTeX2023 编译整个模板及其使用文档（make all-dev）时，产生的 thuthesis.pdf 文档里的小型大写字母未正确输出，而是使用了小写字母输出（非常显著的是文档标题 “ThuThesis” 中本应使用小型大写字母书写的小写字母，全文均存在此问题，对比使用 macOS 编译的结果和其他平台的结果即可发现）。
查看 [thuthesis](https://github.com/tuna/thuthesis/blob/c134870da625603740336b3fe86514476b3ddd36/thuthesis.dtx#L6791) 的 dtx 源代码可以看到该行中使用了 macOS 的内置系统字体 “Palatino”，是导致该问题出现的关键。如果将 Windows 平台的相应字体 “Palatino Linotype” 安装到 macOS 中并将此处改为使用 “Palatino Linotype” 字体，则该问题消失。
另一个可行的解决办法是把 [thuthesis](https://github.com/tuna/thuthesis/blob/c134870da625603740336b3fe86514476b3ddd36/thuthesis.dtx#L6795).dtx 所使用的 TeX Gyre Pagella 字体也应用到 macOS 环境下的字体配置和编译过程，如此即可实现与其他平台相同的效果。

不知文档作者缘何要单独针对 macOS 设置一套西文字体？
由于仅测试了 MacTeX 2023 版本，不知是否历史版本中会因使用 TeX Gyre 系列字体编译文档出现问题，但考虑到模板文档（thuthesis-example）中可以正常使用 TeX Gyre 字体编译，所以 macOS 系统字体在此处的使用原因有些令人费解，或许是更早的历史原因？（故而提出该问题）
但因为现在模板的编译需要 2017 及之后的版本了，所以向前兼容的必要性（此处推测可能的原因之一）或是凸显编译平台 macOS 的优越感（此处推测的另一种包含成见的原因，无意冒犯，仅供参考；若是因此，则 Windows 也同样可以搭配 Windows 所附字体进行编译而不是使用 TeX Gyre 字体）是否可以重新考虑？

总之，ThuThesis 一词（以及其他需要小型大写字母 ”\textsc“ 排版的场景）原本即应使用小型大写字母排版，而非普通小写字母，现在在 macOS 下的输出与预期存在偏差，望作者考虑改进。

**Comment by zepinglee** [comment]
大致是因为，有原版字体就尽量不用仿制版。没有针对 windows 设置是因为作者没有 windows 平台。

其实可以去掉 `\textsc`。

**Comment by MS-Windows** [comment]
感谢解读！
若 ThuThesis 一专有词本无意定义为 “全大写字母驼峰式”（暂且如此称呼，希望不要冒犯到原作者），那么此处事实上无伤大雅。
使用操作系统提供的字形确乎可以感到更尊重本源和亲切。
且类似 BibTeX 的 LOGO 皆是全形大写字母只不过进行了一些缩放和间距调整而实现的（就像经典的 LaTeX 里面的 “A”），是否可以在不支持小型大写字母的字形中也针对 ThuThesis 进行类似的定义呢？（谨在此提供一个建议，还是要尊重原作者的本意）
另外，依照此思路，P052 字体家族（也就是 URW Palladio）及相关联的系列字体是否也可以在特定平台上作类似调用？（通过是否可以通过程序 fontconfig 或宏包 fontspec 检索到对应的字体文件来判断，也是一个建议，仅供参考）

**Comment by MS-Windows** [comment]
同时，还注意到新版本中自动检测并使用了 Microsoft Word.app（若用户在自己的 OS 中安装了此应用）中的字体：
https://github.com/tuna/thuthesis/blob/c134870da625603740336b3fe86514476b3ddd36/thuthesis.dtx#L2240
在此目录中同样可以找到前文

> 如果将 Windows 平台的相应字体 “Palatino Linotype” 安装到 macOS 中并将此处改为使用 “Palatino Linotype” 字体，则该问题消失。

提到的 Microsoft 提供版 Palatino Linotype 字体，而不需要用户额外安装。若已检测到此字体，是否可以考虑用这个版本而不是 macOS 所附 Palatino 字体？（虽然这样说显然也已偏离 “利用原版字” 的初衷，或许可以在安装了 Microsoft Word（或 Office）应用的环境下得到与其他平台更加一致的输出效果？）

**Comment by MS-Windows** [comment]
多谢！
谨对本人带来的烦扰深表歉意

**Comment by MS-Windows** [comment]
题外话：
正文字体设置为 Palatino 的同时，数学字体使用了 XITS Math，虽然出现机会不多，但是否也可以用 刘海洋《LaTeX 入门》一书中 表 4.27 里面所列出的几种字体搭配（Asana Math、Neo Euler、TeX Gyre Pagella Math）或其他 Palatino 风格字体的搭配来优化说明文档的字体家族一致性？
从另一方面考虑，使用 XITS Math 可以和使用示例中保持一致，也是能做到呼应且无伤大雅。

总之，说明文档中的正文字与数学字的字形搭配不是严格必要的，保持现在的搭配即可，且能更好说明 ISO 格式/国标格式/AMS 格式 的实际效果差别。

再次感谢各位维护者的支持和指教！
