### ISSUE TITLE
模板示例文档中所使用示例图片”A“”B“在编译过程中使用了错误的路径

### ISSUE THREAD

**Issue by MS-Windows** [tuna/thuthesis#860]
https://github.com/tuna/thuthesis/blob/c134870da625603740336b3fe86514476b3ddd36/data/chap02.tex#L15
以及同文件的
https://github.com/tuna/thuthesis/blob/c134870da625603740336b3fe86514476b3ddd36/data/chap02.tex#L30 
和
https://github.com/tuna/thuthesis/blob/c134870da625603740336b3fe86514476b3ddd36/data/chap02.tex#L32
还有
https://github.com/tuna/thuthesis/blob/c134870da625603740336b3fe86514476b3ddd36/data/appendix.tex#L16
四处，所插入的图片可能在一定情况下找到 TeX 发行版中的同名文件而非用户所放置于 figures 目录下的 [example-image-a.pdf](https://github.com/tuna/thuthesis/blob/c134870da625603740336b3fe86514476b3ddd36/figures/example-image-a.pdf) 和 [example-image-b.pdf](https://github.com/tuna/thuthesis/blob/c134870da625603740336b3fe86514476b3ddd36/figures/example-image-b.pdf) 文件。

虽然大部分用户通常不会把自己的图片文件命名为 example-image-a.pdf 或 example-image-b.pdf，但难以排除会有此可能性。若确实有用户如此命名，则编译后的输出结果可能与预期不符，造成用户困扰。

解决办法是为图片指定相对路径，例如
 `\includegraphics[width=0.5\linewidth]{example-image-a.pdf}` 
可以写作
`\includegraphics[width=0.5\linewidth]{figures/example-image-a.pdf}`

如此，则编译程序会找到正确的图片并插入文档。

虽然实践过程中会使用多种机制在子目录下查找相应文件，但此处存在的同名文件或许会给新用户带来困扰，望模板维护者考虑改进此处图片文件定位的实现。

**Comment by note286** [comment]
就是为了调用TeX Live里的示例图片。一般不会有用户真的在学位论文里用这样的字样来命名图片的。

**Comment by zepinglee** [comment]
> 四处，所插入的图片可能在一定情况下找到 TeX 发行版中的同名文件而非用户所放置于 figures 目录下的 [example-image-a.pdf](https://github.com/tuna/thuthesis/blob/c134870da625603740336b3fe86514476b3ddd36/figures/example-image-a.pdf) 和 [example-image-b.pdf](https://github.com/tuna/thuthesis/blob/c134870da625603740336b3fe86514476b3ddd36/figures/example-image-b.pdf) 文件。

这里就是为了调用发行版中 [`mwe`](https://ctan.org/pkg/mwe) 宏包提供的示例图片。

**Comment by MS-Windows** [comment]
“有幸” 观摩到该模板的某用户确实如此命名了自己的图片（想要表达的意思是绘图示例 a 和示例 b ，但或许由于没有想到 sample 一词且冥冥之中有受到误导），结果也显而易见，输出的文档并未按照预期使用 figures 中的同名文件。（虽然该用户很快就意识到应该如何才能调用自己的图片了，如上所述，使用了相对路径）
此处则有另一问题：那么 figures 目录下的同名文件用意如何？若本意是使用 mwe 宏包所提供图片，此处是否显得存在些许冗余

**Comment by note286** [comment]
> 另外，或许也会给初次使用模板的用户作一个 “坏榜样”（教会他们不论把图片放在哪里都可以被检查到并调用，显然不利于文件资源的条理化管理），虽然本并无此意

这不是LaTeX教程，用户不应该在此学习基础知识。这放在其他领域，例如用户使用一个Java库，还需要教用户基础知识，是不敢想象的。

**Comment by MS-Windows** [comment]
> 这不是LaTeX教程，用户不应该在此学习基础知识。这放在其他领域，例如用户使用一个Java库，还需要教用户基础知识，是不敢想象的。

诚然。
当用户以不正确的使用方式编译并发现了问题时，应检视自己是否缺失一些基础知识甚至是常识。从另一方面讲，这或许也为用户提供了一条巩固知识和探索发现的新途径，能够在 “套模板” 的思路外延展并提升自己的技能水平，不失为一种行之有效的启示。

**Comment by Harry-Chen** [comment]
> > 四处，所插入的图片可能在一定情况下找到 TeX 发行版中的同名文件而非用户所放置于 figures 目录下的 [example-image-a.pdf](https://github.com/tuna/thuthesis/blob/c134870da625603740336b3fe86514476b3ddd36/figures/example-image-a.pdf) 和 [example-image-b.pdf](https://github.com/tuna/thuthesis/blob/c134870da625603740336b3fe86514476b3ddd36/figures/example-image-b.pdf) 文件。
> 
> 这里就是为了调用发行版中 [`mwe`](https://ctan.org/pkg/mwe) 宏包提供的示例图片。

目前 figures 目录下的确有这两个文件，可以考虑移除，这样可能不止于引起歧义

**Comment by zepinglee** [comment]
> “有幸” 观摩到该模板的某用户确实如此命名了自己的图片（想要表达的意思是绘图示例 a 和示例 b ，但或许由于没有想到 sample 一词且冥冥之中有受到误导），结果也显而易见，输出的文档并未按照预期使用 figures 中的同名文件。（虽然该用户很快就意识到应该如何才能调用自己的图片了，如上所述，使用了相对路径） 此处则有另一问题：那么 figures 目录下的同名文件用意如何？若本意是使用 mwe 宏包所提供图片，此处是否显得存在些许冗余

https://github.com/tuna/thuthesis/blob/c134870da625603740336b3fe86514476b3ddd36/thusetup.tex#L166-L167

这个配置很早以前就有，一直没有去掉是因为担心 break 掉已有的论文。

> > 这不是LaTeX教程，用户不应该在此学习基础知识。这放在其他领域，例如用户使用一个Java库，还需要教用户基础知识，是不敢想象的。
> 
> 诚然。 当用户以不正确的使用方式编译并发现了问题时，应检视自己是否缺失一些基础知识甚至是常识。从另一方面讲，这或许也为用户提供了一条巩固知识和探索发现的新途径，能够在 “套模板” 的思路外延展并提升自己的技能水平，不失为一种行之有效的启示。

少在这里阴阳怪气。

**Comment by zepinglee** [comment]
> > > 四处，所插入的图片可能在一定情况下找到 TeX 发行版中的同名文件而非用户所放置于 figures 目录下的 [example-image-a.pdf](https://github.com/tuna/thuthesis/blob/c134870da625603740336b3fe86514476b3ddd36/figures/example-image-a.pdf) 和 [example-image-b.pdf](https://github.com/tuna/thuthesis/blob/c134870da625603740336b3fe86514476b3ddd36/figures/example-image-b.pdf) 文件。
> > 
> > 
> > 这里就是为了调用发行版中 [`mwe`](https://ctan.org/pkg/mwe) 宏包提供的示例图片。
> 
> 目前 figures 目录下的确有这两个文件，可以考虑移除，这样可能不止于引起歧义

当时加这两个文件好像是简化 CI 的依赖。因为 `mwe` 需要 `lipsum`，可能还需要别的宏包。总之这个无关紧要。

**Comment by Harry-Chen** [comment]
> > > > 四处，所插入的图片可能在一定情况下找到 TeX 发行版中的同名文件而非用户所放置于 figures 目录下的 [example-image-a.pdf](https://github.com/tuna/thuthesis/blob/c134870da625603740336b3fe86514476b3ddd36/figures/example-image-a.pdf) 和 [example-image-b.pdf](https://github.com/tuna/thuthesis/blob/c134870da625603740336b3fe86514476b3ddd36/figures/example-image-b.pdf) 文件。
> > > 
> > > 
> > > 这里就是为了调用发行版中 [`mwe`](https://ctan.org/pkg/mwe) 宏包提供的示例图片。
> > 
> > 
> > 目前 figures 目录下的确有这两个文件，可以考虑移除，这样可能不止于引起歧义
> 
> 当时加这两个文件好像是简化 CI 的依赖。因为 `mwe` 需要 `lipsum`，可能还需要别的宏包。总之这个无关紧要。

明白了，我有空看一看。考虑到删掉的话也可以减少一点点发布体积，不过确实也不是很重要。

**Comment by MS-Windows** [comment]
> 少在这里阴阳怪气。

关于带来的不快在此表示非常抱歉，本人无意冒犯各位维护者。

> 这个配置很早以前就有，一直没有去掉是因为担心 break 掉已有的论文。

考虑历史兼容和实践中面临的未知挑战反映了各位的严谨态度，十分感谢各位耐心解答，现已深刻理解了这些文件的引入和保留缘由。
再次对于本人不当的表述表示万分抱歉
