### ISSUE TITLE
专业学位的封面与word模板不一致

### ISSUE THREAD

**Issue by Joshua1225** [tuna/thuthesis#861]
专业硕士学位的各种封面与word模板中的不一致。尤其是冒号与左侧问题的距离，是否有些过小了。

原代码thuthesis.cls/L2483，参数为：
\thu@titlepage@info@tabular{2.8cm}{2.8cm}{1.34cm}

我暂时调整了一下，可供参考：
\thu@titlepage@info@tabular{3cm}{2.75cm}{1.14cm}

**Comment by zepinglee** [comment]
具体哪个封面？

早期版本时，每个封面都跟 word 版进行像素级校对过的，见 [testfiles/01-cover](https://github.com/tuna/thuthesis/tree/master/testfiles/01-cover) 的一大堆测试。然而研究生院的 word 模板更新时会改动 layout。

**Comment by zepinglee** [comment]
我重新调了一下，效果如下（红色的是 Word 模板，青色的是 LaTeX 模板）。稍后推送上来。

<img width="903" alt="Screenshot 2023-04-23 at 23 03 28" src="https://user-images.githubusercontent.com/12290822/233847550-8b6323de-403b-44e5-94f4-29bede276432.png">

**Comment by zepinglee** [comment]
顺便吐槽一下，这些 word 封面每个布局都不一样。

**Comment by Joshua1225** [comment]
是的，如果你们有机会和负责的机构沟通的话，倒是可以交流一下这个问题

**Comment by zepinglee** [comment]
给研究生院反馈了。
