### ISSUE TITLE
LaTeX中hyperref对目录和参考文献超链接以及颜色的设定

### ISSUE THREAD

**Issue by louieworth** [tuna/thuthesis#863]
## 编译环境
follow [link](https://blog.csdn.net/weixin_39509073/article/details/113523302) 意图修改参考文献颜色，正文无变化。

## 描述问题
《研究生学位论文写作指南》第 xx 页要求……而模板编译的结果是……

截图：

<img width="455" alt="image" src="https://user-images.githubusercontent.com/37494792/232004885-5c5e0ce4-64e9-499f-82eb-02c0c099b795.png">

复现上述问题的代码：
```TeX
\usepackage[colorlinks,
            linkcolor=blue,       %%修改此处为你想要的颜色
            anchorcolor=blue,  %%修改此处为你想要的颜色
            citecolor=blue,        %%修改此处为你想要的颜色，例如修改blue为red
            ]{hyperref}
\usepackage{cleveref}
\usepackage{comment}
\usepackage{wrapfig}
```

**Comment by Harry-Chen** [comment]
模板中已经先期引入和配置了 hyperref，再次加载是无效的。可以使用 `\hypersetup` 来修改

**Comment by louieworth** [comment]
看起来比较困难，有instruction如何去修改所有的\ref{}为蓝色吗？

**Comment by zepinglee** [comment]
```tex
\usepackage{hyperref}
\hypersetup{
  colorlinks,
  linkcolor=blue,       %%修改此处为你想要的颜色
  anchorcolor=blue,  %%修改此处为你想要的颜色
  citecolor=blue,        %%修改此处为你想要的颜色，例如修改blue为red
}
```

目前模板是在载入 `hyperref` 后进行设置的，所以在 `\usepackage` 处的选项无效。

<https://github.com/tuna/thuthesis/blob/705f1dae5fd64693f5cb658d7e4fc5f186fa9200/thuthesis.dtx#L6355-L6369>

我觉得可以改成使用 `\PassOptionsToPackage` 进行配置，这样可以被用户传递的选项覆盖。

**Comment by zepinglee** [comment]
另外提醒一下，如果黑白打印，蓝色会变成灰色。
