### ISSUE TITLE
书脊题目和作者字体大小不一样

### ISSUE THREAD

**Issue by SakurajimaMaiii** [tuna/thuthesis#864]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2020
模板版本：v7.3.1
模板类型：master

**问题：书脊题目和作者字体大小不一样**

编译后的PDF是👇
[spine.pdf](https://github.com/tuna/thuthesis/files/11241415/spine.pdf)
下面的名字似乎看起来更大一点，截图👇
![image](https://user-images.githubusercontent.com/83657651/232277342-06cb211a-c15d-4d27-b18c-9ba4c14c7685.png)

复现上述问题的代码（`spine.tex`）：
```TeX
% !TeX encoding = UTF-8
% !TeX program = xelatex
% !TeX spellcheck = en_US

\documentclass[degree=master]{thuthesis}

\input{thusetup.tex}

\thusetup{
  spine-font   = {\zihao{-3}},
  spine-title  = {医学图像分析中的域泛化与自适应问题研究},
  spine-author = {王帅},
}
\begin{document}

\spine

\end{document}
```

**Comment by SakurajimaMaiii** [comment]
把代码改成
```TeX
% !TeX encoding = UTF-8
% !TeX program = xelatex
% !TeX spellcheck = en_US

\documentclass[degree=master]{thuthesis}

\input{thusetup.tex}

% \thusetup{
%   spine-font   = {\zihao{-3}},
%   spine-title  = {医学图像分析中的域泛化与自适应问题研究},
%   spine-author = {王帅},
% }
\thusetup{
  spine-font   = {\zihao{-3}},
  spine-title  = {医学图像分析中的域泛化与自适应问题研究医学图像分析中的域泛化与自适应问题研究},
  spine-author = {王帅},
}
\begin{document}

\spine

\end{document}
```
就一样大了？奇怪。。PDF👇
[spine.pdf](https://github.com/tuna/thuthesis/files/11241580/spine.pdf)

**Comment by SakurajimaMaiii** [comment]
在word模板中仔细确认了，应该是一样大的，按照这个代码没问题，只是视觉上的问题。
```
% !TeX encoding = UTF-8
% !TeX program = xelatex
% !TeX spellcheck = en_US

\documentclass[degree=master]{thuthesis}

\input{thusetup.tex}

\thusetup{
  spine-font   = {\zihao{-3}},
  spine-title  = {医学图像分析中的域泛化与自适应问题研究},
  spine-author = {王帅},
}
\begin{document}

\spine

\end{document}
```

**Comment by Harry-Chen** [comment]
https://github.com/tuna/thuthesis/blob/705f1dae5fd64693f5cb658d7e4fc5f186fa9200/thuthesis.dtx#L6681-L6693

确实是没有更改的。

**Comment by zepinglee** [comment]
使用 Acrobat：

<img width="507" alt="1" src="https://user-images.githubusercontent.com/12290822/233790583-1c1d6d54-7eab-475e-ae53-b9e4c60b9847.png">


<img width="438" alt="2" src="https://user-images.githubusercontent.com/12290822/233790579-d6249a29-8bc6-479b-a174-287524d2b495.png">
