### ISSUE TITLE
附录翻译里的摘要部分无法显示关键词

### ISSUE THREAD

**Issue by Wuuu-x** [tuna/thuthesis#865]
## 编译环境
编译的系统： Windows 10
TeX 发行版：TeX Live 2020
模板版本：v7.3.1
模板类型：bachelor

## 描述问题
附录翻译里的摘要部分无法显示关键词

截图：
![image](https://user-images.githubusercontent.com/59256821/233256365-4dd23dff-2870-4fe7-b2ff-c77f0f7a0c25.png)

复现上述问题的代码：
```TeX
\begin{abstract}
    12345
    \thusetup{
      keywords = {4,5,6},
    }
  \end{abstract}
```

**Comment by zepinglee** [comment]
因为原版 LaTeX 的 `abstract` 环境没有关键词相关的配置，所以这里也没有加。

不过我记得上次也有人提过这个需求，感觉可以加一下这个功能。
