### ISSUE TITLE
本科生书面调研编译不通过 Latexmk: fls file doesn't appear to have been made.

### ISSUE THREAD

**Issue by lucywang720** [tuna/thuthesis#866]
## 编译环境
编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
模板版本：v5.5.2
模板类型：doctor / master / bachelor

## 描述问题
《研究生学位论文写作指南》第 xx 页要求……而模板编译的结果是……

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{thuthesis}
\begin{document}
abc
\end{document}
```

**Comment by zepinglee** [comment]
可能是文档本身报错，也可能是 xelatex 没有打开 `-recorder`。总之建议给出详细报错。
