### ISSUE TITLE
英文冒号编译不出来

### ISSUE THREAD

**Issue by Martian9119** [tuna/thuthesis#870]
## 编译环境
编译的系统：Windows 11
TeX 发行版：TeX Live 2019
模板版本：v7.3.2
模板类型：bachelor

## 描述问题
我在输入数学公式的时候，英文的冒号编译后就消失了。比如我输入“函数f: X→I”，编译出来变成了“函数f X→I”。

截图：
![capture_20230428111614691](https://user-images.githubusercontent.com/67163009/235046310-0a072792-efed-42ff-a573-753b63191b40.jpg)

复现上述问题的代码：
```TeX
\documentclass[degree=bachelor]{thuthesis}
\begin{document}
函数$f: X_0\rightarrow\mathcal{I}$
\end{document}
```

**Comment by note286** [comment]
我测试了TeX Live 2018/2019/2023均无法复现你的问题，`thuthesis.cls`为`7.3.2`，Windows 10。

![image](https://user-images.githubusercontent.com/16207292/235292871-5b4ff47b-46da-4b20-8ab5-41b3d766d363.png)

**Comment by zepinglee** [comment]
同样无法复现。

另外这里的冒号要用 `\colon`。

**Comment by Martian9119** [comment]
> 同样无法复现。
> 
> 另外这里的冒号要用 `\colon`。

我尝试了\colon冒号也编译不出来

**Comment by Martian9119** [comment]
> 同样无法复现。
> 
> 另外这里的冒号要用 `\colon`。

啊我把commath宏包删去就编译出来了，这是为什么？以前没碰到过这种问题（不过现在用不了\dif了）

**Comment by note286** [comment]
```latex
\documentclass{thuthesis}
\usepackage{commath}
\begin{document}
$f:x$
$f\colon x$
\end{document}
```

![image](https://user-images.githubusercontent.com/16207292/236655719-f3e1cdb0-16f3-46f6-b414-65e06136ffea.png)

**Comment by zepinglee** [comment]
可能是别的什么冲突。

https://tex.stackexchange.com/questions/261265/angle-brackets-with-commath-and-asana-math-too-large-or-small

https://tex.stackexchange.com/questions/135944/commath-and-ifinner

> The commath package has many errors and I can't recommend using it.
