### ISSUE TITLE
请问怎么让奇数、偶数页的页边距保持一致？

### ISSUE THREAD

**Issue by Ziiiirem** [tuna/thuthesis#878]
我想让print打印稿的时候让奇数页的页边距为左3.67，右2.67；偶数页反过来，奇数页的页边距为左2.67，右3.67。然后在电子稿electric的时候，我想让所有页面都保持在页边距为左3.67，右2.67，在电子版的时候，我做不到这一点！！请问该如何实现？急急急

**Comment by zepinglee** [comment]
```tex
\geometry{
  left = 3.67cm,
  right = 267cm,
}
```

电子稿在 `\documentclass` 加参数 `oneside`。
