### ISSUE TITLE
windows系统编译环境如何修改所有章标题为宋体？

### ISSUE THREAD

**Issue by Ziiiirem** [tuna/thuthesis#880]
请问windows系统编译环境，请问如何修改所有章、节标题为宋体、英文标题用times new roman？急急急，十分感谢回复！！

**Comment by AlphaZTX** [comment]
提问应当具体、规范。你这么提问是很难收到满意的回答的。

**Comment by Harry-Chen** [comment]
自行修改章节格式将导致论文不符合写作指南的要求。

**Comment by Ziiiirem** [comment]
sorry不好意思。在master硕士的排版里，如何把章标题修改为宋体？我目前章标题是黑体，内容是宋体，我想把所有字体都改为宋体，感谢赐教！

**Comment by zepinglee** [comment]
至少说明一下，你是觉得模板不符合格式要求，还是出于个人使用的目的需要这么修改。

**Comment by Ziiiirem** [comment]
个人目的啦，实在抱歉，询问不妥，请见谅！

**Comment by Ziiiirem** [comment]
感谢！！
