### ISSUE TITLE
将document class内degree修改为bachelor后目录、插图索引和表格索引消失

### ISSUE THREAD

**Issue by AntonyMei** [tuna/thuthesis#881]
## 编译环境
编译的系统：Overleaf (Tsinghua)
TeX 编译器：XeLaTex
模板版本：v7.4.0
模板类型：bachelor

## 描述问题
将document class内degree修改为bachelor后目录，插图索引和表格索引会消失（无论是否将插图索引和表格索引移至正文后都会出现同样问题）

截图：（插图索引和表格索引情况与目录相同）
![image](https://github.com/tuna/thuthesis/assets/30572462/6f573358-9ccb-41af-b568-c6404cf492c4)

复现上述问题的代码：
```
\documentclass[degree=bachelor]{thuthesis}
```

**Comment by zepinglee** [comment]
overleaf.com 无法复现。可能是 Overleaf (Tsinghua) 的问题。

**Comment by weigerzan** [comment]
overleaf.com出现相同问题

**Comment by weigerzan** [comment]
![776FBD04-F101-4826-9E0F-52C8AE06F94A](https://github.com/tuna/thuthesis/assets/68595949/e8591679-47a8-4f5f-af97-2ef62f974120)
