### ISSUE TITLE
将document class内degree修改为bachelor后appendix附录编译报错，附录无法正确显示参考文献

### ISSUE THREAD

**Issue by shadowofgost** [tuna/thuthesis#882]
## 编译环境
编译的系统：Overleaf (Tsinghua)
TeX 编译器：XeLaTex
模板版本：v7.4.0
模板类型：bachelor

## 描述问题
将document class内degree修改为bachelor后appendix附录编译报错，附录无法正确显示参考文献
截图：
![image](https://github.com/tuna/thuthesis/assets/59472916/2483c02c-7b32-4449-9310-6ad17b42e965)

**Comment by zepinglee** [comment]
我能复现这个问题。大概是忘记实现本科生附录的 `\printbibliography` 接口了（见 #837 和 #875）。目前只是示例文档编译不过，但是不影响正常使用。

目前本科生的“调研阅读报告”和“书面翻译”这两个特殊章节的参考文献是单独编号的（不加“A-”这样的前缀），但《指南》其余位置并未提到附录中的参考文献。

> 附录 A 中图、表、公式的编号，应与正文中的编号区分开，即在阿拉伯数码前冠以附录 的编号，如图 A-1，表 A-2，(A-3)等。

那么其他附录中的参考文献需要单独编号吗？如果单独编号的话是否加附录号的前缀？

**Comment by Harry-Chen** [comment]
> 目前本科生的“调研阅读报告”和“书面翻译”这两个特殊章节的参考文献是单独编号的（不加“A-”这样的前缀），但《指南》其余位置并未提到附录中的参考文献。
> 
> > 附录 A 中图、表、公式的编号，应与正文中的编号区分开，即在阿拉伯数码前冠以附录 的编号，如图 A-1，表 A-2，(A-3)等。
> 
> 那么其他附录中的参考文献需要单独编号吗？如果单独编号的话是否加附录号的前缀？

我接触过的本科生的论文通常不涉及其他部分，如果有的话应该也是文章的一部分（而不像报告和翻译是独立的内容），要不就和研究生一样带前缀处理吧。

**Comment by zepinglee** [comment]
搞了两个晚上，总算在 https://github.com/tuna/thuthesis/commit/195aab5fc7b6fedc61446fd5716ffa412bfbb3e0 中解决了这个问题。

大致是，`bibunits` 开启了 `\bibliographyunit` 模式后的内部机制跟原来的 `bibunit` 环境完全不一样。
