### ISSUE TITLE
v7.4.0 若将thusetup中的副导师注释掉，生成的文件中英文封面的导师那一栏会不居中

### ISSUE THREAD

**Issue by wsh16** [tuna/thuthesis#883]
## 编译环境
编译的系统：Overleaf (Tsinghua)
compalier:     XeLaTeX
模板版本：v7.4.0
模板类型：master

## 描述问题
若将thusetup.tex中的
```TeX
associate-supervisor = {副导师姓名, 副教授},
associate-supervisor* = {Professor Assoc-Supervisor Name},
```
注释掉，仅保留导师，无副导师，生成的文件中英文封面的导师那一栏会不居中。

截图：
![image](https://github.com/tuna/thuthesis/assets/39235588/5ee9f671-bb61-4470-a063-64f73f98b9a8)
上图为将副导师注释掉的情况，导师不居中
![image](https://github.com/tuna/thuthesis/assets/39235588/6d811533-ead1-472b-bfcc-aeee9cdb7c7f)
上图为保留副导师情况，两个导师均正常居中

编译无报错。

复现上述问题的代码：
thusetup.tex 中

```TeX
  % 副指导教师
  %
%  associate-supervisor  = {陈文光, 教授},
%  associate-supervisor* = {Professor Chen Wenguang},
  %
```

**Comment by zepinglee** [comment]
确实，这部分的横向位置有问题。
