### ISSUE TITLE
将degree改为bachelor后目录、插图索引、表格索引无法正常显示

### ISSUE THREAD

**Issue by weigerzan** [tuna/thuthesis#885]
编译的系统：Overleaf（非Overleaf Tsinghua）
模板版本：v7.4.0
模板类型：bachelor

将degree改为bachelor后目录、插图索引、表格索引无法正常显示

![1684999097364_7D94902F-1CEA-49ad-8DB5-664136D6B339](https://github.com/tuna/thuthesis/assets/68595949/7f2e49f6-fde8-4f63-a57b-36800561cfcf)
![1684999109204_AD46DE78-31D7-48ff-8E20-8700B34F2D2E](https://github.com/tuna/thuthesis/assets/68595949/a314f993-7b57-4286-be30-6c777d236844)
![1684999118276_3F65665D-5D5B-4b74-BE0E-ABA1CF80CC43](https://github.com/tuna/thuthesis/assets/68595949/dd6ceb81-0c7c-4e35-8628-c781724b0b8d)

复现上述问题的代码：
\documentclass[degree=bachelor]{thuthesis}

**Comment by weigerzan** [comment]
实测7.3.2及之前版本不会出现此问题，应该与overleaf tsinghua无关

**Comment by weigerzan** [comment]
![1685016106093_89553DF7-D410-4279-8824-0772DD9950D1](https://github.com/tuna/thuthesis/assets/68595949/77e44c4f-cc51-4eff-a168-8ea6df2911b0)
报错如上

**Comment by zepinglee** [comment]
同 #882。

用本科生的附录可以暂时避免这个问题。

<img width="506" alt="Screenshot 2023-05-25 at 21 53 15" src="https://github.com/tuna/thuthesis/assets/12290822/c3a6b3be-a579-4a65-a3b3-5d2b66735232">
