### ISSUE TITLE
出于学校的要求，想修改下模板，请问如何修改章标题和节标题的内容、字体和字号？

### ISSUE THREAD

**Issue by Ziiiirem** [tuna/thuthesis#889]
我使用的是master选项。
1.如何将章标题的“第1章”，中间的阿拉伯数字改为汉字，变成“第一章”，宋体、不加粗、四号？并且页眉也需要改成“第一章 xx”，而非“第1章 xx”
2.如何将节标题“1.1”的字体和字号改为time new romans、不加粗、小四？
非常感谢您的回复，祝好！

**Comment by Harry-Chen** [comment]
你的上个 issue 中我已经回答过了。

duplicate with #880
