### ISSUE TITLE
插图索引图号超过两位数之后上下间距不对齐

### ISSUE THREAD

**Issue by 1358361259** [tuna/thuthesis#891]
## 编译环境
编译的系统：win11
TeX 发行版：TeX Live 2019 
模板版本：7.4.0
模板类型：bachelor

## 描述问题
插图索引图号超过两位数之后间距不对齐，感觉应该要对齐？

**Comment by 1358361259** [comment]
![image](https://github.com/tuna/thuthesis/assets/56356352/d4dc3600-7866-4b5d-8f03-0824561311af)

**Comment by zepinglee** [comment]
本科生《指南》没有规定空多少，所以使用了研究生的格式，既空一字宽。

**Comment by 1358361259** [comment]
谢谢



---原始邮件---
发件人: "Zeping ***@***.***&gt;
发送时间: 2023年6月6日(周二) 中午11:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tuna/thuthesis] 插图索引图号超过两位数之后上下间距不对齐 (Issue #891)




 
本科生《指南》没有规定空多少，所以使用了研究生的格式，既空一字宽。
