### ISSUE TITLE
正文中的参考文献的括号是英文括号

### ISSUE THREAD

**Issue by Ivy1012** [tuna/thuthesis#896]
正文中的参考文献的括号可以选择中文括号吗？

**Comment by zepinglee** [comment]
顺序编码还是著者-出版年？

如果是后者的话推荐使用 `biblatex`，然后设置 `biblatex-gb7714-2015` 的 `gbcitelabel` 参数。参考 `biblatex-gb7714-2015` 的文档。

bibtex 方案由于 `natbib` 宏包的限制，使用全角符号会有额外的空白，不推荐使用。
