### ISSUE TITLE
与vscode中的插件zotero-latex的协同

### ISSUE THREAD

**Issue by JIMMYGENN** [tuna/thuthesis#897]
开发者好，

我安装了zotero-latex的插件，可以在vscode中调用zotero来插入文献，按照以前的介绍需要在插入文献的地方加入
```
\bibliographstyle{unsrt}
\bibliographstyle{D:/Zotero/Bib_tex/MyLibray}
```

请问在这套模板中应该在哪里插入呢？谢谢！

**Comment by zepinglee** [comment]
> 我安装了zotero-latex的插件，可以在vscode中调用zotero来插入文献，按照以前的介绍需要在插入文献的地方加入

zotero-latex 是什么插件？有没有链接？

> ```
> \bibliographstyle{unsrt}
> \bibliographstyle{D:/Zotero/Bib_tex/MyLibray}
> ```
> 
> 请问在这套模板中应该在哪里插入呢？谢谢！

thuthesis 的示例文档中分在了连个地方：

https://github.com/tuna/thuthesis/blob/cdba5baf91752e0242c41a70f3b62192d3387fb4/thusetup.tex#L148-L151

https://github.com/tuna/thuthesis/blob/cdba5baf91752e0242c41a70f3b62192d3387fb4/thuthesis-example.tex#L62-L63

**Comment by JIMMYGENN** [comment]
@zepinglee 是vscode中的一个扩展插件，https://github.com/bnavetta/vscode-zotero-latex
