### ISSUE TITLE
封面中的字号bug

### ISSUE THREAD

**Issue by ILTShade** [tuna/thuthesis#899]
## 描述问题
《研究生学位论文写作指南》第 10 页（P5）要求学科门类采用三号宋体：
<img width="855" alt="image" src="https://github.com/tuna/thuthesis/assets/17716696/3c81bc0a-8719-4772-ab90-60e64ace8928">

模板中这部分采用的是小二：
<img width="534" alt="image" src="https://github.com/tuna/thuthesis/assets/17716696/78e02b9c-573c-402b-aacf-f1fc284af4f6">

**Comment by zepinglee** [comment]
你的《指南》是哪个版本的？我手上的 2023 年 3 月版《指南》第 5 页是“小二号”。

<img width="744" alt="Screenshot 2023-09-05 at 12 20 40" src="https://github.com/tuna/thuthesis/assets/12290822/908c8494-cfd2-4e5f-b7b3-b2107344aad1">

**Comment by ILTShade** [comment]
不对啊，我看的版本也是2023年3月份的啊。

**Comment by ILTShade** [comment]
我的访问链接是 http://yjsy.cic.tsinghua.edu.cn/docinfo/board/boarddetail.jsp？columnId=0010102&parentColumnId=00101&itemSeq=5365
pdf的链接是：http://yjsy.cic.tsinghua.edu.cn/download.jsp?attachSeq=11206
再确认一下？

**Comment by ILTShade** [comment]
我看的版本也是2023年3月版本的。我去看的链接是：http://yjsy.cic.tsinghua.edu.cn/docinfo/board/boarddetail.jsp?columnId=0010102&parentColumnId=001&itemSeq=5365
指南的链接是：http://yjsy.cic.tsinghua.edu.cn/download.jsp?attachSeq=11206

**Comment by ILTShade** [comment]
我发现这个问题是我对比了最新版本的cls文件生成的pdf，和word模板的对比，word模版中的三号字。
<img width="1087" alt="image" src="https://github.com/tuna/thuthesis/assets/17716696/4073e20a-37c2-4fdc-b280-a74e015910e7">
而这个文件是来自这里：
<img width="730" alt="image" src="https://github.com/tuna/thuthesis/assets/17716696/baaa0065-32b3-4542-b1f9-0d5de0aa2cef">

**Comment by zepinglee** [comment]
> 我看的版本也是2023年3月版本的。我去看的链接是：http://yjsy.cic.tsinghua.edu.cn/docinfo/board/boarddetail.jsp?columnId=0010102&parentColumnId=001&itemSeq=5365 指南的链接是：http://yjsy.cic.tsinghua.edu.cn/download.jsp?attachSeq=11206

可以将这个页面的快照以及全部附件发一份到 GitHub 吗？我在校外无法访问。

**Comment by ILTShade** [comment]
好的，内网的网页打包文件是 
[研究生院办公网内网.mht.zip](https://github.com/tuna/thuthesis/files/12531562/mht.zip)
指南的下载文件是：
[Çå»ª´óÑ§ÑÐ¾¿ÉúÑ§Î»ÂÛÎÄÐ´×÷Ö¸ÄÏ(202303).pdf](https://github.com/tuna/thuthesis/files/12531567/Ca.oN.ND.EuN.I.AUIAD.x.O.AI.202303.pdf)
word模板的压缩包文件是：（需要先解压zip，再解压rar，github不能直接上传rar）
[wordÄ£°å(202303).rar.zip](https://github.com/tuna/thuthesis/files/12531574/wordA.a.202303.rar.zip)

**Comment by ILTShade** [comment]
上述几个文件我都是重新下载的，名称也是用的默认的。可能存在一些编码上的问题导致显示不太正确

**Comment by zepinglee** [comment]
看来是研究生院悄悄修改了。我也更新一下。
