### ISSUE TITLE
附录参考文献永远显示？？？

### ISSUE THREAD

**Issue by Mirviy** [tuna/thuthesis#903]
## 编译环境
编译的系统：Windows 10
TeX 发行版：This is XeTeX, Version 3.141592653-2.6-0.999995 (MiKTeX 23.9)
模板版本：v7.4.0
模板类型：doctor / master / bachelor

## 描述问题
附录参考文献永远显示？？？

截图：

![屏幕截图 2023-09-22 211352](https://github.com/tuna/thuthesis/assets/24671039/45f24dee-5329-49d1-8d1b-685f5b42e5a8)

复现上述问题的代码：
```TeX

附录中的参考文献示例（\cite{carlson1981two} 和 \cite{carlson1981two,taylor1983scanning,taylor1981study}）。

\printbibliography

```

**Comment by note286** [comment]
无法复现

```latex
\documentclass{thuthesis}
\usepackage[style=thuthesis-author-year]{biblatex}
\addbibresource{ref.bib}
\begin{document}
\appendix
\chapter{title}
附录中的参考文献示例（\cite{carlson1981two} 和 \cite{carlson1981two,taylor1983scanning,taylor1981study}）。
\printbibliography
\end{document}
```

![image](https://github.com/tuna/thuthesis/assets/16207292/89087e9d-0f01-4293-b822-5ec2e4e35163)

**Comment by Mirviy** [comment]
你不需要写任何新的tex文档……
我直接下载模板编译，就能复现这个问题。

**Comment by note286** [comment]
你所指的模板具体是？

**Comment by Mirviy** [comment]
> 你所指的模板具体是？

https://github.com/tuna/thuthesis/archive/refs/heads/master.zip

**Comment by Harry-Chen** [comment]
通常是因为你的编译方式不正确，缺少了某些步骤，请仔细阅读文档，按照说明编译。

**Comment by Mirviy** [comment]
[thuthesis_see_appendix.zip](https://github.com/tuna/thuthesis/files/12701305/thuthesis_see_appendix.zip)

啊……

**Comment by note286** [comment]
注意`appendix.tex`文件中存在`\printbibliography`，因此需要使用`biblatex`编译。请修改`thusetup.tex`中关于参考文献的设置。

```latex
% \usepackage[sort]{natbib}
% \bibliographystyle{thuthesis-numeric}

\usepackage[style=thuthesis-numeric]{biblatex}
\addbibresource{ref/refs.bib}
```

![image](https://github.com/tuna/thuthesis/assets/16207292/b530b74a-f399-4466-8f06-2bf1ceecc6d1)

**Comment by Harry-Chen** [comment]
> 注意`appendix.tex`文件中存在`\printbibliography`，因此需要使用`biblatex`编译。请修改`thusetup.tex`中关于参考文献的设置。

其实不需要，我们统一了一些配置，是可以用 bibtex 工作的。

**Comment by note286** [comment]
> 你不需要写任何新的tex文档…… 我直接下载模板编译，就能复现这个问题。
> 
> 另外你给的代码在我的环境下直接编译会粗体打印出reference的key值，显然我们的环境不一样。

你提问的时候并没有给出完整的代码，仅给出了部分，也没有说直接编译模板。

**Comment by note286** [comment]
> > 注意`appendix.tex`文件中存在`\printbibliography`，因此需要使用`biblatex`编译。请修改`thusetup.tex`中关于参考文献的设置。
> 
> 其实不需要，我们统一了一些配置，是可以用 bibtex 工作的。

是重定义了`\printbibliography`吗？

抱歉，我没有仔细阅读过相关说明。

**Comment by note286** [comment]
使用如下命令编译

```
https://github.com/tuna/thuthesis/archive/refs/heads/master.zip
```

```
xelatex thuthesis-example
bibtex thuthesis-example
xelatex thuthesis-example
xelatex thuthesis-example
```

![image](https://github.com/tuna/thuthesis/assets/16207292/2ac3bfe8-35eb-4bc1-8483-d1d46ea086c3)


附录的参考文献确实有问题，部分日志如下：

```
) [9] (./thuthesis-example.bbl [10]) (./data/appendix.tex (./bu.aux) [11]
附录 A
[12] (./thuthesis-example-appendix-a.aux)

Package natbib Warning: Citation `dupont1974bone' on page 13 undefined on input line 57.


Package natbib Warning: Citation `zhengkaiqing1987' on page 13 undefined on input line 57.


Package natbib Warning: Citation `dupont1974bone' on page 13 undefined on input line 58.


Package natbib Warning: Citation `zhengkaiqing1987' on page 13 undefined on input line 58.

No file thuthesis-example-appendix-a.bbl.
) (./data/acknowledgements.tex (./bu.aux) [13]) (./bu.aux) [14] (./data/resume.tex (./bu.aux)
[15]) (./data/comments.tex (./bu.aux) [16] [17]) (./data/resolution.tex (./bu.aux) [18])

Package natbib Warning: There were undefined citations.

(./bu.aux) (./thuthesis-example.aux (./bu.aux)) )
(see the transcript file for additional information)
Output written on thuthesis-example.pdf (34 pages).
Transcript written on thuthesis-example.log.
```

不确定是不是我编译的问题。

**Comment by Mirviy** [comment]
> 注意`appendix.tex`文件中存在`\printbibliography`，因此需要使用`biblatex`编译。请修改`thusetup.tex`中关于参考文献的设置。

谢谢！

我用这个方法，编译三次之后参考文献正常了 : ) （第一次是粗体key，第二次序号从0开始，第三次正常。）

不太清楚里面有什么魔法，不过我的问题解决了。

**Comment by zepinglee** [comment]
学会阅读文档：

<img width="737" alt="Screenshot 2023-09-22 at 23 37 29" src="https://github.com/tuna/thuthesis/assets/12290822/0f419ad8-a20c-412f-8ff2-623088dc8c7d">

BibTeX 方法需要对附录的 `.aux` 单独处理。biblatex 不需要这一过程。

但是更推荐使用 `latexmk` 自动处理编译过程。

**Comment by note286** [comment]
非常感谢，是我的疏忽。
