### ISSUE TITLE
[Feature Request] 各类定理环境统一编号的选项

### ISSUE THREAD

**Issue by ekaradon-Alexander** [tuna/thuthesis#904]
一些专著中的各类定理是统一编号的，例如：

**引理 1.1** blah blah ...

**定理 1.2** blah blah ...

**推论 1.3** blah blah...

**例 1.4** blah blah...

作为对比，非统一编号的结果是：

**引理 1.1** blah blah ...

**定理 1.1** blah blah ...

**推论 1.1** blah blah...

**例 1.1** blah blah...

对于论文中命题、引理、定理等较多的情形，统一编号的形式可能更合适一些（不然如果答辩时口误把「定理」说成了「引理」，会引起误解，统一编号的形式下，至少编号的数字是能对应上的）；且研究生院的《写作指南》似乎并没有对各类定理环境是否应当统一编号作出规定。

是否可以考虑增加一个选项，用于决定各类定理环境是分别编号还是统一编号？

**Comment by zepinglee** [comment]
> 且研究生院的《写作指南》似乎并没有对各类定理环境是否应当统一编号作出规定。

确实没有规定。

> 是否可以考虑增加一个选项，用于决定各类定理环境是分别编号还是统一编号？

感觉这样还是不够灵活，建议自己仿照模板的代码重新定义一套。

我印象中有的书是“推论”、“公理”跟“定理”公用一套编号，但“示例”、“引理”分别单独编号。这样的格式不太方设置选项。

**Comment by ekaradon-Alexander** [comment]
> 我印象中有的书是“推论”、“公理”跟“定理”公用一套编号，但“示例”、“引理”分别单独编号。这样的格式不太方设置选项。

嗯，你说得对，毕竟关于哪些定理环境统一编号、哪些分别编号的需求是多样的。

**Comment by YijunYuan** [comment]
如果有人有这个需求，可以在导言区使用如下方法（意义应该不言自明）
```tex
\makeatletter
	\let\c@remark\c@theorem
	\let\c@proposition\c@theorem
	\let\c@corollary\c@theorem
	\let\c@lemma\c@theorem
	\let\c@definition\c@theorem
	\let\c@conjecture\c@theorem
	\let\c@question\c@theorem
	\let\c@example\c@theorem
\makeatother
```

参考了 [https://tex.stackexchange.com/a/425984/107173](https://tex.stackexchange.com/a/425984/107173)
