### ISSUE TITLE
请问Overleaf的版本不更新了吗？看了一下还是7.2.4

### ISSUE THREAD

**Issue by thulishuang** [tuna/thuthesis#905]

**Comment by zepinglee** [comment]
使用这个 <https://www.overleaf.com/latex/templates/thuthesis-tsinghua-university-thesis-latex-template/cfwgcxtvkbsx>

**Comment by zepinglee** [comment]
a32a0f5 更新了 README 中 Overleaf 的链接。我联系一下他们删除原来的。

Overleaf 的模板如果要直接更新必须使用原来的项目，否则只能创建新的模板，也就是新的链接。而之前我不小心删除了原项目（为了测试）。

**Comment by thulishuang** [comment]
好的~
