### ISSUE TITLE
正文部分数学公式中的部分希腊字母无法正常显示。

### ISSUE THREAD

**Issue by zhendonghou** [tuna/thuthesis#915]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2023
模板版本：v7.4.0
模板类型：master

## 描述问题
正文部分数学公式中的部分希腊字母无法正常显示。
似乎只要\mathbf命令作用在希腊字母上，就会显示一个方框
截图：
![Snipaste_2024-01-29_03-33-08](https://github.com/tuna/thuthesis/assets/93426718/1f6d571d-25b9-4214-88b9-864970033562)

复现上述问题的代码：
```TeX
\documentclass[degree=master]{thuthesis}
\begin{document}
$\mathbf{A}$
$\mathbf{\Sigma}$
$\Sigma$
\end{document}
```

**Comment by stone-zeng** [comment]
用 `\symbf`
