### ISSUE TITLE
参考文献无法识别 @masterthesis 类型

### ISSUE THREAD

**Issue by roastduck** [tuna/thuthesis#916]
## 编译环境
编译的系统：Overleaf
TeX 发行版：Overleaf 的 xelatex
模板版本：v7.4.0
模板类型：doctor

## 描述问题
在 `.bib` 文件中指定 `@masterthesis` 类型时，无法正确识别，会显示警告并识别为GBT7714-2015中的[Z]（其他）类型。`@phdthesis`可正常识别为[D]（学位论文）。按[Overleaf 的说明](https://www.overleaf.com/learn/latex/Bibliography_management_with_bibtex)， `@masterthesis` 应为合法类型。

下述代码应生成：
```
Lopez D A. Evolving gpu-accelerated capsule networks[D]. University of Nevada, Reno, 2018.
```

实际生成：
```
Lopez D A. Evolving gpu-accelerated capsule networks[Z]. University of Nevada, Reno, 2018
```

复现上述问题的代码：
```TeX
@masterthesis{lopez2018evolving,
  title={Evolving GPU-accelerated capsule networks},
  author={Lopez, Daniel Anthony},
  year={2018},
  school={University of Nevada, Reno}
}
```

**Comment by zepinglee** [comment]
<img width="590" alt="Screenshot 2024-01-31 at 18 47 54" src="https://github.com/tuna/thuthesis/assets/12290822/479df145-6ca5-456e-a6ce-e27669af8400">

**Comment by roastduck** [comment]
谢谢，请随时关闭此issue。
