### ISSUE TITLE
使用vscode-xelatex编译报错，Package kysetkeys: undefined key 'degree-category'

### ISSUE THREAD

**Issue by doraldoa** [tuna/thuthesis#919]
## 编译环境
编译的系统：Windows 11
模板版本：v7.2.1
模板类型：master

## 描述问题
xelatex直接编译模板thusetup报错

**Comment by note286** [comment]
请编译`thuthesis-example.tex`。

**Comment by doraldoa** [comment]
编译的是此文件

> 请编译`thuthesis-example.tex`。

**Comment by zepinglee** [comment]
需要在本地生成 .cls 文件在 2024年2月6日，22:13，doraldoa ***@***.***> 写道：﻿
编译环境
编译的系统：Windows 11
模板版本：v7.2.1
模板类型：master
描述问题
xelatex直接编译模板thusetup报错

**Comment by doraldoa** [comment]
> 需要在本地生成 .cls 文件在 2024年2月6日，22:13，doraldoa ***@***.***> 写道：﻿ 编译环境 编译的系统：Windows 11 模板版本：v7.2.1 模板类型：master 描述问题 xelatex直接编译模板thusetup报错 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

请问应该如何在本地生成该类型文件
