### ISSUE TITLE
生物学要求采用最新的Cell 格式给出参考文献列表

### ISSUE THREAD

**Issue by Xiaofeiff** [tuna/thuthesis#920]
[论文格式自检表.pdf](https://github.com/tuna/thuthesis/files/14219284/default.pdf)
说明会提到引用时仍要求使用author-date，但采用最新的Cell 格式给出参考文献列表。请问在之前使用overleaf的模板写完了之后怎么修改可以满足学院的要求呀？新年快乐，麻烦啦~

**Comment by zepinglee** [comment]
在 #921 中讨论，这个先关了。

其实只需发一个就好。
