### ISSUE TITLE
封面学科如何调整字体间距？

### ISSUE THREAD

**Issue by niyunsheng** [tuna/thuthesis#924]
求助各位大佬，学院要求封面学科“生物学”三个字之间也要有间隔，和姓名一样对齐，如何修改呢？

<img width="185" alt="176ec2ffd95d7f34ef6d88008a189fc" src="https://github.com/tuna/thuthesis/assets/62385270/98089ce7-f672-40f1-897f-c941b9108bb3">

**Comment by zepinglee** [comment]
有没有学院官方的模板文件？

研究生院给出的“01各类封面示例”格式不统一，博士、学硕、专硕的格式各不相同。我后来问了研究生院，答复是样式整体风格一致即可，一些细节（比如字距、对齐方式）等不必完全一致。所以目前的 LaTeX 模板基本是按照“`01-博-1-中文1学术学位封面（论文题目两行，无副导师）.doc`”的格式。

**Comment by Harry-Chen** [comment]
> 有没有学院官方的模板文件？
> 
> 研究生院给出的“01各类封面示例”格式不统一，博士、学硕、专硕的格式各不相同。我后来问了研究生院，答复是样式整体风格一致即可，一些细节（比如字距、对齐方式）等不必完全一致。所以目前的 LaTeX 模板基本是按照“`01-博-1-中文1学术学位封面（论文题目两行，无副导师）.doc`”的格式。

 我的理解是此类对齐并无必要，因为姓名和专业名称的长度并不是一定的，都可以很长或者很短，很难有确定的操作标准。
