### ISSUE TITLE
caption如何设置首行缩进两字符？

### ISSUE THREAD

**Issue by niyunsheng** [tuna/thuthesis#925]
在caption中我加入了`$\qquad$`，但是看到图注并不都是标准的缩进两字符，可以调整哪里设置图注首行缩进两字符呢？

```
\caption*{$\qquad$图注}
```

![image](https://github.com/tuna/thuthesis/assets/62385270/cd903a88-5807-4cdb-b19e-72f595e965d8)

**Comment by note286** [comment]
```latex
\captionsetup{margin={2em,0cm},indention=-2em}
```

**Comment by note286** [comment]
或者

```latex
\DeclareCaptionFormat{thu}{\qquad #1#2#3}
\captionsetup{format=thu}
```

**Comment by niyunsheng** [comment]
> 或者
> 
> ```
> \DeclareCaptionFormat{thu}{\qquad #1#2#3}
> \captionsetup{format=thu}
> ```

看起来没问题，非常感谢！

**Comment by niyunsheng** [comment]
> 或者
> 
> ```
> \DeclareCaptionFormat{thu}{\qquad #1#2#3}
> \captionsetup{format=thu}
> ```

@note286 你好呀，这样设置不仅会把`\caption*{$\qquad$图注}`空两行，也会把`\caption{}`缩进，但实际上我只想要把`\caption*`这里缩进，有解决办法吗？

**Comment by note286** [comment]
你可以在你需要的`\caption{}`上方使用`\captionsetup{format=thu}`，而不是在导言区全局配置。

**Comment by niyunsheng** [comment]
> 你可以在你需要的`\caption{}`上方使用`\captionsetup{format=thu}`，而不是在导言区全局配置。

谢谢，这样可以了
