### ISSUE TITLE
如何修改目录中章标题的行距

### ISSUE THREAD

**Issue by QWERT1104** [tuna/thuthesis#926]
学校给的论文写作指南中关于目录是这样规定的，章标题的间距为固定20磅，
![1](https://github.com/tuna/thuthesis/assets/161580957/a8f4546a-1fb1-4f05-921a-b364ed0915b3)
然而latex编译后的目录是这样的，行距明显更大（左侧为doc模板，右侧为latex），
![2](https://github.com/tuna/thuthesis/assets/161580957/35167bbb-3f69-439e-b70a-03b09fc40a05)
请问如何修改目录中章标题的行距。

**Comment by QWERT1104** [comment]
目前我自己尝试在cls文件中修改第2028行代码，可以让行距在视觉效果上变为和word模板基本一致
2027`\titlecontents{chapter}`
2028`        [\z@]{\addvspace{0.5bp}\sffamily}`
2029`        {\contentspush{\thecontentslabel\quad}}{}`
2030`        {\rmfamily\thu@leaders\thecontentspage}%`
cls文件为开发版，2024/2/28上午编译的
平台为Windows11，TeXstuidio 4.7.2
效果如下图所示
![3](https://github.com/tuna/thuthesis/assets/161580957/1e8aa4fa-d4ae-40b2-91d5-5c0716bba6ee)
从左到右依次是word模板，2023年毕业同学的论文，latex预览。还是有细微差别，期待其他同学可以彻底解决这一问题。

**Comment by QWERT1104** [comment]
修改了一下section和subsection，效果好了一些，2026到2038如下图，
![4](https://github.com/tuna/thuthesis/assets/161580957/8e99a21a-b33a-487a-af76-bc541194fdc8)
效果如下，从左到右依次是word模板，2023年毕业同学的论文，latex预览。
![5](https://github.com/tuna/thuthesis/assets/161580957/18df4d69-f8d8-4d34-b44e-6b246d85d7be)

**Comment by Harry-Chen** [comment]
> 你的 Word 模板是 2023 年 9 月版吧？

我没有在研究生院的官网上发现这个版本的模板，最新的看起来还是 3 月。

**Comment by zepinglee** [comment]
> 我没有在研究生院的官网上发现这个版本的模板，最新的看起来还是 3 月。

似乎是直上传了修改后的 Word 模板文件。

**Comment by QWERT1104** [comment]
word模板是从研究生院网站上下载的，链接如下：
https://info2021.tsinghua.edu.cn/f/info/xxfb_fg/xnzx/template/detail?xxid=fa880bdf60102a29fbe3c31f36b76c7e
上面标注的word版本是202303

**Comment by zepinglee** [comment]
已在 ff9f197 中修改。

**Comment by petronny** [comment]
请问是否有计划发布 7.4.1 版本以包括此修改？

**Comment by Harry-Chen** [comment]
> 请问是否有计划发布 7.4.1 版本以包括此修改？

我将发布 7.5.0 版本。
