### ISSUE TITLE
选择英文作为重要的语言，但中文封面会出现英文标题

### ISSUE THREAD

**Issue by huzizhan** [tuna/thuthesis#927]
## 编译环境
编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
模板版本：v5.5.2
模板类型：doctor / master / bachelor

## 描述问题
如题，按照要求键入中英文标题时，并选择英文作为主要语言时，中文封面仍然存在英文标题，最理想的情况应该是只有中文标题，即和主要语言设置为中文时一致

截图：
![Snipaste_2024-02-28_21-28-34](https://github.com/tuna/thuthesis/assets/48824060/080f23cf-8dc7-425d-ba5e-ea4055940638)

复现上述问题的代码：
```TeX
\thusetup{
  language = english,
}
......
\thusetup{
  % 选择英文作为主要语言
  title  = {一个新xxxxx},
  title* = {A New xxxxx},
```

**Comment by zepinglee** [comment]
学校研究生院 *GUIDE TO THESIS WRITING FOR GRADUATE STUDENTS (202303)* 要求的。

<img width="782" alt="Screenshot 2024-02-28 at 21 36 38" src="https://github.com/tuna/thuthesis/assets/12290822/dc62ad23-e896-405e-8637-a8025e158f8c">

**Comment by huzizhan** [comment]
感谢大佬指点！！！ @zepinglee 我还是准备了两套方案，怕系里的老师们答辩的时候问，还不好怼他们2333
