### ISSUE TITLE
开发版cls模板下公式中的字母间距各有不同

### ISSUE THREAD

**Issue by QWERT1104** [tuna/thuthesis#929]
## 编译环境
编译的系统：Windows 11@VS code & TeXstudio
TeX 发行版：TeX Live 2023 
模板版本：2024.3.3编译的开发版
模板类型：master 

## 描述问题
在模板中使用equation或者align命令输入公式，公式中的字母间距不同，字母A-Z顺序键入效果如下图，可以看到字母之间的间距有比较明显的不同。

截图：
![image](https://github.com/tuna/thuthesis/assets/161580957/0bf26932-d89d-4db3-bc8d-11293216149b)

复现上述问题的代码：
```TeX
\begin{equation}
	\textit{Sensitivity} = \textit{SNR}_{req} + \textit{N}_0 + \textit{NF} + 10 \text{log} \textit{BW}
\end{equation}
\begin{equation}
ABCDEFGHIJKLMNOPQRSTUVWXYZ
\end{equation}
\begin{equation}
	Sensitivity = SNR_{req} + N_0 + NF + 10 \text{log} BW
\end{equation}
```

麻烦作者排查一下问题，万分感谢！

**Comment by zepinglee** [comment]
这是 feature 不是 bug。LaTeX 数学模式直接输入 `SNR` 表示 `S`, `N`, `R` 三个变量，而 `\textit{SNR}` 表示 `SNR` 单词。两者使用的是不同 kerning。谁有合适介绍资料不妨评论一下。

另外单词 `\text{log}` 和算符 `\log` 前后的 kerning 也不同。

**Comment by QWERT1104** [comment]
明白了，感谢解答。
