### ISSUE TITLE
专著析出文献不能正确显示

### ISSUE THREAD

**Issue by SaYa-t** [tuna/thuthesis#930]
## 编译环境
编译的系统：Windows 10
TeX 发行版：MiKTeX 2.9.6753
模板版本：v7.4.0
模板类型：doctor

## 描述问题
《研究生学位论文写作指南》第 17 页要求
![image](https://github.com/tuna/thuthesis/assets/16526986/e66b9d1a-1798-491e-86b9-9e3902c10848)

而模板编译的结果未包含//专著主要责任者. 专著题名: 其他题名信息

截图：
![image](https://github.com/tuna/thuthesis/assets/16526986/60a492c3-c4e6-49f3-8b4d-a32ffbe08bea)
![image](https://github.com/tuna/thuthesis/assets/16526986/67202812-b01b-413e-bcd2-6eb8e42bd9c6)

复现上述问题的代码：
```TeX
@inbook{Baker2014,
	author="Baker, Ryan Shaun and Inventado, Paul Salvador",
	editor="Larusson, Johann Ari and White, Brandon",
	title="Educational Data Mining and Learning Analytics",
	bookTitle="Learning Analytics: From Research to Practice",
	year="2014",
	publisher="Springer New York",
	address="New York",
	pages="61--75"
}
```

**Comment by zepinglee** [comment]
感觉 `@inbook` 可以改成按照是否有 `booktitle` 选择是用 `book` 格式还是 `incollection` 格式。
