### ISSUE TITLE
目录行间距有问题，模板里要求行间距固定20磅，段前段后间距均为0磅，应该如何修改？

### ISSUE THREAD

**Issue by kaidi-g** [tuna/thuthesis#933]
<img width="289" alt="image" src="https://github.com/tuna/thuthesis/assets/53245442/77a8ed0d-467a-4a47-bace-1983b54e27e9">
各章标题之间的间距过宽

**Comment by zepinglee** [comment]
见 <https://github.com/tuna/thuthesis/issues/926> 和 <https://github.com/tuna/thuthesis/commit/ff9f1975f2ae13e76eeacd22b2262a3f56747410>。
