### ISSUE TITLE
参考文献中著者的缩写格式与标准有所不同

### ISSUE THREAD

**Issue by roastduck** [tuna/thuthesis#934]
## 编译环境
编译的系统：Overleaf
模板版本：master
模板类型：doctor

## 描述问题
《研究生学位论文写作指南》第 21 页要求“依据 GB/T 28039—2011 有关规定，用汉语拼音书写的人名，姓全写，其名可缩写，取**每个汉字**的拼音的首字母。欧美著者的名可用缩写字母，缩写名后省略缩写点；欧美著者的中译名只著录其姓；同姓不同名的欧美著者，其中译名不仅要著录其姓，还需著录其名的首字母。如用首字母无法识别该人名时，则用全名。”，而本模板一律只将名缩写为一个字母。

截图：

![image](https://github.com/tuna/thuthesis/assets/6522983/e681df62-4b21-414a-9ef5-4a8c97dfe623)

复现上述问题的代码：
```
@inproceedings{metaflow,
  author       = {Zhihao Jia and
                  James Thomas and
                  Todd Warszawski and
                  Mingyu Gao and
                  Matei Zaharia and
                  Alex Aiken},
  editor       = {Ameet Talwalkar and
                  Virginia Smith and
                  Matei Zaharia},
  title        = {Optimizing {DNN} Computation with Relaxed Graph Substitutions},
  booktitle    = {Proceedings of Machine Learning and Systems 2019, MLSys 2019, Stanford,
                  CA, USA, March 31 - April 2, 2019},
  publisher    = {mlsys.org},
  year         = {2019},
  url          = {https://proceedings.mlsys.org/book/276.pdf},
  timestamp    = {Mon, 10 Oct 2022 12:44:27 +0200},
  biburl       = {https://dblp.org/rec/conf/mlsys/JiaTWGZA19.bib},
  bibsource    = {dblp computer science bibliography, https://dblp.org}
}
```

既然写作指南中缩写规则如此复杂，但缩写本身又是可选的，是否可改为一律不缩写？

**Comment by roastduck** [comment]
注意到与 #442 重复，关闭本 issue。

**Comment by zepinglee** [comment]
> 既然写作指南中缩写规则如此复杂，但缩写本身又是可选的，是否可改为一律不缩写？

学校的示例、国标的示例都是缩写，所以采用了缩写。

如果你实在需要全名的话，可以将这一行改成 `{ t #1 "{vv~}{ll}{ ff}" format.name$`。

https://github.com/tuna/thuthesis/blob/44bd13b87816cfff72d0ac19762fecd5f360bffb/thuthesis-numeric.bst#L595

> 用汉语拼音书写的人名，姓全写，其名可缩写，取每个汉字的拼音的首字母

按规则确实是这样，但是在 BibTeX 不好判断是否“汉语拼音书写的人名”。一是有外籍华人的名字不应视为“汉语拼音书写的人名”，二是某些西方人的名字也符合汉语拼音规则，比如 Fatou、Fubini。

目前可行方案是手动在 `.bib` 中将名拆开，比如 `Zhihao Jia` => `Zhi Hao, Jia`，输出的就是 `Jia Z H`了。

实际中一般不会在意这个，缩写为“Jia Z”问题也不大。
