### ISSUE TITLE
\mathbb not available when using newcm as math-font

### ISSUE THREAD

**Issue by YijunYuan** [tuna/thuthesis#940]
### 提交前检查

- [X] 我已经充分阅读了模板文档。
- [X] 我的问题并非关于模板的用法（否则请前往 discussions 提出）。
- [X] 我已经搜索了已有的 issues 和 discussion，确认没有重复提交。

### 系统

Ubuntu 23.10 on Windows 10 x86_64, 5.15.146.1-microsoft-standard-WSL2

### TeX 发行版

TeXLive 2023

### TeX 编译器

XeLaTeX

### 版本

7.5.0

### 学位类型

doctor

### 问题描述

使用`newcm`作为`math-font`时，使用`\mathbb`字体显示`Undefined control sequence`.

### 复现代码

```TeX
\documentclass[math-font=newcm]{thuthesis}
\begin{document}
\maketitle
\frontmatter
\mainmatter
$\mathbb{R}$
\backmatter
\end{document}
```

### 编译日志

```Text
......

LaTeX Font Warning: Font shape `OMX/cmex/m/n' in size <16.06> not available
(Font)              size <17.28> substituted on input line 3.


LaTeX Font Warning: Font shape `OMX/cmex/m/n' in size <10.53937> not available
(Font)              size <10.95> substituted on input line 3.

[1] [2]

LaTeX Font Warning: Font shape `OMX/cmex/m/n' in size <15.05624> not available
(Font)              size <14.4> substituted on input line 3.

[3] [4]
! Undefined control sequence.
<recently read> \mathbb 
                        
l.6 $\mathbb
            {R}$
```

### 其他信息

将`newcm`换为`lm`有同样报错。

**Comment by YijunYuan** [comment]
临时解决方案：
在文件开头添加
```tex
\RequirePackage{amssymb}
```
强行使用`amssymb`。但这么干会有什么副作用很难说。

**Comment by Harry-Chen** [comment]
> ```
> \documentclass[math-font=newcm]{thuthesis}
> \begin{document}
> \maketitle
> \frontmatter
> \mainmatter
> $\mathbb{R}$
> \backmatter
> \end{document}
> ```

`\RequirePackage` 并非给文档作者使用的，直接 `\usepackage{amssymb}` 即可，这是预期的用法，也没有什么副作用。也可见 https://tex.stackexchange.com/questions/360607/unicode-math-but-ordinary-blackboard-bold

**Comment by YijunYuan** [comment]
> > ```
> > \documentclass[math-font=newcm]{thuthesis}
> > \begin{document}
> > \maketitle
> > \frontmatter
> > \mainmatter
> > $\mathbb{R}$
> > \backmatter
> > \end{document}
> > ```
> 
> `\RequirePackage` 并非给文档作者使用的，直接 `\usepackage{amssymb}` 即可，这是预期的用法，也没有什么副作用。也可见 [tex.stackexchange.com/questions/360607/unicode-math-but-ordinary-blackboard-bold](https://tex.stackexchange.com/questions/360607/unicode-math-but-ordinary-blackboard-bold)

我想说的是`thuthesis`的文档里已经明确说明`unicode-math`与`amssymb`不兼容
。所以您这里说的

> 直接 `\usepackage{amssymb}` 即可，这是预期的用法
与`thuthesis`的文档不是很一致。

**Comment by Harry-Chen** [comment]
> 我想说的是`thuthesis`的文档里已经明确说明`unicode-math`与`amssymb`不兼容

这里的“不兼容”要看具体情况，并不是说两个库同时使用就一定会导致严重的问题。据我所知，unicode-math 对于数学排版的处理会破坏 amssymb 的部分字体选择等功能。但如果只是用 \mathbb 引入一些用来集合标记的字体，并没有太大的问题。

此外，引用代码不需要一行一行引用，可以引用多行。

**Comment by zepinglee** [comment]
目前 `math-font` 只能用在导言区不能用在 `\documentclass` 的参数。下面的例子可以 work。

```tex
\documentclass{thuthesis}
\thusetup{math-font = newcm}
\begin{document}
$\mathbb{R}$
\end{document}
```
