### ISSUE TITLE
避免在非proposal型文档中显示学号

### ISSUE THREAD

**Issue by jjyyxx** [tuna/thuthesis#945]
### 提交前检查

- [X] 我已经充分阅读了模板文档。
- [X] 我的问题并非关于模板的用法（否则请前往 discussions 提出）。
- [X] 我已经搜索了已有的 issues 和 discussion，确认没有重复提交。

### 系统

Overleaf

### TeX 发行版

Tex Live 2024

### TeX 编译器

XeLaTeX

### 版本

7.5.0

### 学位类型

master

### 问题描述

如果在 `thusetup` 中设置了 `student-id`，封面将无条件显示学号，即使当前不是proposal型文档。建议加入判断，仅在proposal型文档下显示，或者为了灵活性考虑给出一个 warning。

PS: 虽然`thusetup.tex`的注释中提及`仅当书写开题报告时需要（同时设置 `thesis-type = proposal'）`，但我们这边还是有同学没注意到，也可能是没想到设置后会无条件显示，导致封面不符合要求。

### 复现代码

```TeX
-
```

**Comment by Harry-Chen** [comment]
感谢建议！
