### ISSUE TITLE
关于本科生综合论文训练封面个人信息没有居中的问题

### ISSUE THREAD

**Issue by zhangshi20** [tuna/thuthesis#958]
系统：Win11
环境：最新版Tex Live
模版：最新
学位：学士
我在2020年的FAQ中有看到相同的问题，是说和模版的绝对位置一致即可，因为时间问题，那个模版已经打不开了
不过我分别对比了师兄的博士论文和室友发的word模版，我发现和博士论文的绝对位置基本是一致的，而博士论文因为字间距比较大，所以比较美观，但学士论文的字间距小不少，远不如word模版的美观。我按照本科Latex 博士Latex 和 本科Word依次附上图片
![image](https://github.com/tuna/thuthesis/assets/72800758/4c54b721-cb6c-4bca-8624-6f1acc7dc4b8)
![image](https://github.com/tuna/thuthesis/assets/72800758/d72ddd47-c94a-491e-83e0-722da68286fc)
![image](https://github.com/tuna/thuthesis/assets/72800758/615e4495-eb6a-482a-b2f2-19cd605798b6)

**Comment by zepinglee** [comment]
> 室友发的word模版

有没有学校官方发的 Word 模板？

目前本科生的封面布局是按照“01综合论文训练-论文样例.pdf”这份文档制作的。

[综合论文训练-论文样例.pdf](https://github.com/tuna/thuthesis/files/15446134/-.pdf)

**Comment by zhangshi20** [comment]
谢谢您的回复，我看了一下室友的模版是在这里找的https://github.com/qbh16/ThuWordThesis，并非官方模版

此外想要请教，如果我不得不对此处的排版做出修改的话，是否会对其它位置产生不可逆的影响。（很抱歉问这么愚蠢的问题）

**Comment by zepinglee** [comment]
大概需要改这一段。

https://github.com/tuna/thuthesis/blob/fd35bde76fe21a49726068177af3bc992bc8f4b3/thuthesis.dtx#L4895-L4919

**Comment by zhangshi20** [comment]
谢谢您！！！
        
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Zeping ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年5月26日 21:08
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [tuna/thuthesis] 关于本科生综合论文训练封面个人信息没有居中的问题 (Issue #958)
        
      
    
  

大概需要改这一段。
https://github.com/tuna/thuthesis/blob/fd35bde76fe21a49726068177af3bc992bc8f4b3/thuthesis.dtx#L4895-L4919
