### ISSUE TITLE
附录中的中文文献可以正常引用，英文则显示为？

### ISSUE THREAD

**Issue by cbccbcc** [tuna/thuthesis#960]
### 提交前检查

- [X] 我已经充分阅读了模板文档。
- [X] 我的问题并非关于模板的用法（否则请前往 discussions 提出）。
- [X] 我已经搜索了已有的 issues 和 discussion，确认没有重复提交。

### 系统

macOS 14.4.1

### TeX 发行版

Tex Live 2023

### TeX 编译器

XeLaTeX

### 版本

7.5.0

### 学位类型

bachelor

### 问题描述

在新建附录中引用位于refs.bib的文献，如果文献为中文则引用成功，引用为英文则失败，显示为？，这个问题应该和之前的类似问题不一样，不涉及inline的格式问题，通过新建appendix.bib无法解决

### 复现代码

```TeX
% !TeX root = ../thuthesis-example.tex

\chapter{数据降维与聚类} % 附录，附录名为appendix A
\section{面板数据截取}
\citep{zhangj2021,wangy2024} %成功
\citep{allaoui_considerably_2020} %失败
```

**Comment by Harry-Chen** [comment]
请考虑重命名相关文献的 citekey，使用包含有下划线的 citekey 可能会产生某些兼容性问题： https://tex.stackexchange.com/questions/605564/problem-with-underscore-character-in-a-citation-key

**Comment by cbccbcc** [comment]
感谢！！

**Comment by Harry-Chen** [comment]
顺便提醒，“文献为中文则引用成功，引用为英文则失败”的归因是错误的，调试此类问题需要控制变量
