### ISSUE TITLE
本科生书面翻译的参考文献无法显示且使用正文的参考文献

### ISSUE THREAD

**Issue by csp2002** [tuna/thuthesis#961]
### 提交前检查

- [X] 我已经充分阅读了模板文档。
- [X] 我的问题并非关于模板的用法（否则请前往 discussions 提出）。
- [X] 我已经搜索了已有的 issues 和 discussion，确认没有重复提交。

### 系统

Windows10

### TeX 发行版

Tex Live 2024

### TeX 编译器

XeLaTeX

### 版本

7.4.0

### 学位类型

bachelor

### 问题描述

在写本科生的外文文献翻译时，我在ref文件夹下新建了一个appendix.bib，用于存放我翻译的那篇外文文献的参考文献，而在data/appendix-translation中，我使用\bibliography{ref/appendix}，但是编译后我发现：1.并未显示外文资料的参考文献列表。2.翻译内容中如果文献在正文的参考文献中出现过就会显示正文参考文献的序号，反之则是“？”。此外，书面翻译对应的原文索引也显示不了

### 复现代码

```TeX
\bibliography{ref/appendix}
```

**Comment by zepinglee** [comment]
按照文档的描述进行编译。

**Comment by Winston-Gu** [comment]
我也遇到了同样的问题)

**Comment by Harry-Chen** [comment]
正如上面另一位维护者所说的，请按照文档的描述进行编译。
