### ISSUE TITLE
当章节标题、图表标题长度刚好为一行时，页码未能顶格生成

### ISSUE THREAD

**Issue by SaYa-t** [tuna/thuthesis#963]
### 提交前检查

- [X] 我已经充分阅读了模板文档。
- [X] 我的问题并非关于模板的用法（否则请前往 discussions 提出）。
- [X] 我已经搜索了已有的 issues 和 discussion，确认没有重复提交。

### 系统

Windows11

### TeX 发行版

MikTex 

### TeX 编译器

XeLaTeX

### 版本

7.5.1

### 学位类型

doctor

### 问题描述

![image](https://github.com/tuna/thuthesis/assets/16526986/6b037d8d-d217-4f64-bef4-e6fade5d2ba3)
在生成目录时如果标题长度处于页码当行放不下的情况时会出现页码换行后未能贴右边生成的情况

### 复现代码

```TeX
\begin{document}
\chapter{找一个在目录里刚好顶格又不会自动换行的标题}
\end{document}
```

**Comment by Harry-Chen** [comment]
Fixed by #966.
