### ISSUE TITLE
打印版插入空白页后罗马数字页码不连续

### ISSUE THREAD

**Issue by saffahyjp** [tuna/thuthesis#964]
### 提交前检查

- [X] 我已经充分阅读了模板文档。
- [X] 我的问题并非关于模板的用法（否则请前往 discussions 提出）。
- [X] 我已经搜索了已有的 issues 和 discussion，确认没有重复提交。

### 系统

Ubuntu 24.04

### TeX 发行版

TeX Live 2024

### TeX 编译器

XeLaTeX

### 版本

7.5.1

### 学位类型

bachelor

### 问题描述

假设内容包含中文摘要、英文摘要、目录，则以打印版（print）输出的页码分别为 I、III、V。
期望现象应当为只插入空白页，但不影响页码，即与电子版（electronic）输出的页码一致（I、II、III）。

### 复现代码

```TeX
\documentclass[degree=bachelor]{thuthesis}
\thusetup{output = print}
\begin{document}
\maketitle
\frontmatter
\begin{abstract}
中文摘要
\end{abstract}
\begin{abstract*}
English abstract
\end{abstract*}
\tableofcontents
\end{document}
```

**Comment by Harry-Chen** [comment]
排版印刷的惯例中，通常会给插入的空白页编码。此外，打印版和电子版除了页码之外，还有别的区别（页边距，#684），并不是完全一致的。

**Comment by saffahyjp** [comment]
感谢解答！是预期现象就没事了……

（起因就是某老师要求页码需要是 I II III，我已通过编辑 PDF 的方式处理了，hhhhhh
