### ISSUE TITLE
v7.5.0 v7.5.1为什么把figures下的文件删掉了

### ISSUE THREAD

**Issue by liuyu5337** [tuna/thuthesis#965]
### 提交前检查

- [X] 我已经充分阅读了模板文档。
- [X] 我的问题并非关于模板的用法（否则请前往 discussions 提出）。
- [X] 我已经搜索了已有的 issues 和 discussion，确认没有重复提交。

### 系统

macOS

### TeX 发行版

TexLive 2024

### TeX 编译器

XeLaTeX

### 版本

7.5.0 7.5.1

### 学位类型

master

### 问题描述

为什么v7.5.0和v7.5.1 把figures下的示例文件删掉了，在make的时候会报错 缺少文件。Unable to load picture or PDF file 'example-image-a.pdf'. [...[width=0.5\linewidth]{example-image-a.pdf}]。

希望后续版本更新可以不要删掉示例文件，因为还需要从其他版本把文件复制到新的版本

### 复现代码

```TeX
\begin{figure}
  \centering
  \includegraphics[width=0.5\linewidth]{example-image-a.pdf}
  \caption*{国外的期刊习惯将图表的标题和说明文字写成一段，需要改写为标题只含图表的名称，其他说明文字以注释方式写在图表下方，或者写在正文中。}
  \caption{示例图片标题}
  \label{fig:example}
\end{figure}
```

### 编译日志

```Text
Unable to load picture or PDF file 'example-image-a.pdf'. [...[width=0.5\linewidth]{example-image-a.pdf}]
Package graphics Error: Division by 0. [...idth=0.35\linewidth]{example-image-a.pdf}}]
```

**Comment by liuyu5337** [comment]
希望后续版本更新可以不要删掉示例文件，因为还需要从其他版本把文件复制到新的版本

**Comment by Harry-Chen** [comment]
问题已经复现，看起来是打包脚本的错误导致的
