### ISSUE TITLE
参考文献人名显示问题

### ISSUE THREAD

**Issue by dhblues** [tuna/thuthesis#968]
### 提交前检查

- [X] 我已经充分阅读了模板文档。
- [X] 我的问题并非关于模板的用法（否则请前往 discussions 提出）。
- [X] 我已经搜索了已有的 issues 和 discussion，确认没有重复提交。

### 系统

Windows11

### TeX 发行版

TeXstudio

### TeX 编译器

XeLaTeX

### 版本

6.0.2

### 学位类型

doctor

### 问题描述

一个参考文献在正文中引用显示格式的问题，就是如果参考文献作者为两人（无论中文还是英文），在正文引用中，中文作者会显示为“”张三等“，而不是“张三和李四”，英文作者则会显示为“A et al.” 而不是“A and B”。

### 复现代码

```TeX
@article{xp2019,
	title={中国农村金融改革的回顾、反思与展望},
	author={谢平 and 刘海二},
	journal={南方金融},
	number={3},
	pages={3-11},
	year={2019},
	key={xie4ping2liu2hai3er2},
}
\begin{document}
\cite{xp2019}
\end{document}
```

### 其他信息

显示为“谢平等（2019）”而不是“谢平和刘海二（2019）”，若将代码改为 \citet*{xp2019}，则显示为“谢平 and 刘海二（2019）”

**Comment by Harry-Chen** [comment]
See #969.
