### ISSUE TITLE
CTAN上发布的模板文档有个别字符乱码

### ISSUE THREAD

**Issue by YDX-2147483647** [tuna/thuthesis#970]
### 提交前检查

- [X] 我已经充分阅读了模板文档。
- [X] 我的问题并非关于模板的用法（否则请前往 discussions 提出）。
- [X] 我已经搜索了已有的 issues 和 discussion，确认没有重复提交。

### 系统

N/A

### TeX 发行版

N/A

### TeX 编译器

N/A

### 版本

7.5.2

### 学位类型

bachelor

### 问题描述

在当前版本 http://mirrors.ctan.org/macros/latex/contrib/thuthesis/thuthesis.pdf 第59页，U+2025（‥）和 U+2E3A（⸺）两个字符未能正确显示。

![图片](https://github.com/user-attachments/assets/9218ed92-6960-4519-8d84-ef88850680c1)

### 复现代码

```TeX
N/A
```

### 其他信息

我尝试了两种阅读器，都是如此，大约是提交给CTAN的PDF有问题？

相应源代码：

https://github.com/tuna/thuthesis/blob/60661f7d140c192418cc9151b54a6c59a99fae23/thuthesis.dtx#L2126-L2140

**Comment by zepinglee** [comment]
这不是乱码，而且编译文档用的中文字体（没记错应该是 Fandol）缺这两个字形。不过这只是文档，问题不大。

**Comment by YDX-2147483647** [comment]
嗯，标题我为简洁才这么写，确实是码缺字形而非乱成别的码。

那我就直接关闭议题了，有需要再打开。
