### ISSUE TITLE
Windows下 make 错误

### ISSUE THREAD

**Issue by ProLet-1917** [tuna/thuthesis#973]
### 提交前检查

- [X] 我已经充分阅读了模板文档。
- [X] 我的问题并非关于模板的用法（否则请前往 discussions 提出）。
- [X] 我已经搜索了已有的 issues 和 discussion，确认没有重复提交。

### 系统

Windows 11

### TeX 发行版

make

### TeX 编译器

XeLaTeX

### 版本

7.5.2

### 学位类型

master

### 问题描述

在windows系统，powershell或cmd中进行 make（已安装）会产生错误。

### 复现代码

```TeX
make thesis
```

### 编译日志

```Text
xetex thuthesis.ins
process_begin: CreateProcess(NULL, xetex thuthesis.ins, ...) failed.
make (e=2): 系统找不到指定的文件。
make: *** [Makefile:31: dtx-style.sty] Error 2
```

**Comment by Harry-Chen** [comment]
PATH 中有 `xetex.exe` 吗？
