### ISSUE TITLE
Compile log not shown

### ISSUE THREAD

**Issue by Altantsooj** [tuna/thuthesis#980]
### 提交前检查

- [X] 我已经充分阅读了模板文档。
- [X] 我的问题并非关于模板的用法（否则请前往 discussions 提出）。
- [X] 我已经搜索了已有的 issues 和 discussion，确认没有重复提交。

### 系统

https://overleaf.tsinghua.edu.cn/

### TeX 发行版

Overleaf

### TeX 编译器

XeLaTeX

### 版本

7.5.0

### 学位类型

doctor

### 问题描述

If compilation has error it's not shown. If compilation hasn't error everything is fine. I want to show error log. 
![image](https://github.com/user-attachments/assets/54e307f9-ab82-4495-9d6e-ab6d04095b1f)

### 复现代码

```TeX
\documentclass[degree=doctor, degree-type=professional, language=english, fontset=windows]{thuthesis}
\begin{document}

\end{document}
```

### 编译日志

```Text
I want to see compilation log.
```

**Comment by Harry-Chen** [comment]
You might want to contact the administrator of overleaf.tsinghua.edu.cn (lnj at tsinghua dot edu dot cn). This is not a problem of thuthesis itself.
